import type { ActionContract } from "@/types/action-contract";

export const commonActions: ActionContract[] = [
  {
    key: "openModuleCenter",
    label: { zh: "打开模块中心", en: "Open Module Center" },
    description: { zh: "跳转到模块中心注册表页面。", en: "Navigate to the module center registry page." },
    tone: "neutral",
    intent: "navigate",
    status: "active",
    source: {
      sourceModule: "shell",
      sourcePage: "global",
      sourceComponent: "ShellNav",
      sourceEvent: "click",
    },
    target: {
      targetRoute: "/modules",
      targetAction: "navigate",
      targetPage: "ModuleCenter",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
    },
    isPlaceholder: false,
    isDestructive: false,
    analyticsKey: "nav.module-center",
  },
  {
    key: "openTemplates",
    label: { zh: "打开页面模板", en: "Open Page Templates" },
    description: { zh: "跳转到页面模板展示路由。", en: "Navigate to the page templates showcase route." },
    tone: "neutral",
    intent: "navigate",
    status: "active",
    source: {
      sourceModule: "shell",
      sourcePage: "global",
      sourceComponent: "ShellNav",
      sourceEvent: "click",
    },
    target: {
      targetRoute: "/templates",
      targetAction: "navigate",
      targetPage: "Templates",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
    },
    isPlaceholder: false,
    isDestructive: false,
    analyticsKey: "nav.templates",
  },
  {
    key: "openComponents",
    label: { zh: "打开核心组件", en: "Open Core Components" },
    description: { zh: "跳转到组件展示与规范页。", en: "Navigate to the component showcase and conventions." },
    tone: "neutral",
    intent: "navigate",
    status: "active",
    source: {
      sourceModule: "shell",
      sourcePage: "global",
      sourceComponent: "ShellNav",
      sourceEvent: "click",
    },
    target: {
      targetRoute: "/components",
      targetAction: "navigate",
      targetPage: "Components",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
    },
    isPlaceholder: false,
    isDestructive: false,
    analyticsKey: "nav.components",
  },
  {
    key: "openDemo",
    label: { zh: "打开 Demo Workspace", en: "Open Demo Workspace" },
    description: { zh: "跳转到本地 Demo Workspace。", en: "Navigate to the local demo workspace." },
    tone: "primary",
    intent: "navigate",
    status: "active",
    source: {
      sourceModule: "shell",
      sourcePage: "global",
      sourceComponent: "ShellNav",
      sourceEvent: "click",
    },
    target: {
      targetRoute: "/demo",
      targetAction: "navigate",
      targetPage: "DemoWorkspace",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
    },
    isPlaceholder: false,
    isDestructive: false,
    analyticsKey: "nav.demo",
  },
  {
    key: "openLayoutEngine",
    label: { zh: "打开布局引擎", en: "Open Layout Engine" },
    description: { zh: "跳转到布局引擎演示路由。", en: "Navigate to the layout engine foundation route." },
    tone: "neutral",
    intent: "navigate",
    status: "active",
    source: {
      sourceModule: "shell",
      sourcePage: "global",
      sourceComponent: "ShellNav",
      sourceEvent: "click",
    },
    target: {
      targetRoute: "/layout-engine",
      targetAction: "navigate",
      targetPage: "LayoutEngine",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
    },
    isPlaceholder: false,
    isDestructive: false,
    analyticsKey: "nav.layout-engine",
  },
  {
    key: "openTasks",
    label: { zh: "打开任务引擎", en: "Open Task Engine" },
    description: { zh: "跳转到 Task Engine MVP 路由。", en: "Navigate to the task engine MVP route." },
    tone: "neutral",
    intent: "navigate",
    status: "active",
    source: {
      sourceModule: "shell",
      sourcePage: "global",
      sourceComponent: "ShellNav",
      sourceEvent: "click",
    },
    target: {
      targetRoute: "/tasks",
      targetAction: "navigate",
      targetPage: "TaskEngine",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
    },
    isPlaceholder: false,
    isDestructive: false,
    analyticsKey: "nav.tasks",
  },
  {
    key: "exportPlaceholder",
    label: { zh: "导出（占位）", en: "Export (Placeholder)" },
    description: { zh: "导出动作占位，仅用于合同与映射。", en: "Export placeholder action for contract and mapping only." },
    tone: "info",
    intent: "export",
    status: "placeholder",
    source: {
      sourceModule: "shell",
      sourcePage: "global",
      sourceComponent: "ShellNav",
      sourceEvent: "click",
    },
    target: {
      targetAction: "export",
    },
    requirement: {
      auditRequired: true,
      confirmationRequired: false,
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "action.export.placeholder",
  },
  {
    key: "createPlaceholder",
    label: { zh: "新建（占位）", en: "Create (Placeholder)" },
    description: { zh: "新建动作占位，仅用于合同与映射。", en: "Create placeholder action for contract and mapping only." },
    tone: "primary",
    intent: "create",
    status: "placeholder",
    source: {
      sourceModule: "shell",
      sourcePage: "global",
      sourceComponent: "ShellNav",
      sourceEvent: "click",
    },
    target: {
      targetAction: "create",
    },
    requirement: {
      auditRequired: true,
      confirmationRequired: true,
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "action.create.placeholder",
  },
  {
    key: "configurePlaceholder",
    label: { zh: "配置（占位）", en: "Configure (Placeholder)" },
    description: { zh: "配置动作占位，仅用于合同与映射。", en: "Configure placeholder action for contract and mapping only." },
    tone: "neutral",
    intent: "configure",
    status: "placeholder",
    source: {
      sourceModule: "shell",
      sourcePage: "global",
      sourceComponent: "ShellNav",
      sourceEvent: "click",
    },
    target: {
      targetAction: "configure",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "action.configure.placeholder",
  },
];
