import type { ActionContract } from "@/types/action-contract";

export const demoActions: ActionContract[] = [
  {
    key: "openDemoWorkspace",
    label: { zh: "打开 Demo Workspace", en: "Open Demo Workspace" },
    description: { zh: "进入本地演示工作台。", en: "Enter the local demo workspace." },
    tone: "primary",
    intent: "navigate",
    status: "active",
    source: {
      sourceModule: "demo",
      sourcePage: "workspace",
      sourceComponent: "DemoWorkspace",
      sourceEvent: "click",
      sourceRoute: "/demo",
    },
    target: {
      targetRoute: "/demo",
      targetAction: "navigate",
      targetPage: "DemoWorkspace",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
    },
    isPlaceholder: false,
    isDestructive: false,
    analyticsKey: "demo.open.workspace",
  },
  {
    key: "openDemoModule",
    label: { zh: "打开 Demo 模块", en: "Open Demo Module" },
    description: { zh: "通过模块代码打开演示页面。", en: "Open a demo module page by module code." },
    tone: "neutral",
    intent: "navigate",
    status: "active",
    source: {
      sourceModule: "demo",
      sourcePage: "workspace",
      sourceComponent: "DemoModuleSwitcher",
      sourceEvent: "select",
      sourceRoute: "/demo",
    },
    target: {
      targetRoute: "/demo/:module",
      targetAction: "navigate",
      targetPage: "DemoModule",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
    },
    isPlaceholder: false,
    isDestructive: false,
    analyticsKey: "demo.open.module",
  },
  {
    key: "openDemoFlow",
    label: { zh: "打开 Demo Flow", en: "Open Demo Flow" },
    description: { zh: "流程演示占位入口。", en: "Placeholder entry point for demo flow." },
    tone: "info",
    intent: "open-drawer",
    status: "coming-soon",
    source: {
      sourceModule: "demo",
      sourcePage: "workspace",
      sourceComponent: "DemoFlow",
      sourceEvent: "click",
      sourceRoute: "/demo",
    },
    target: {
      targetAction: "openDemoFlow",
      targetComponent: "DemoFlowDrawer",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "demo.flow.placeholder",
  },
  {
    key: "openMockDataNotice",
    label: { zh: "查看 Mock Data 提示", en: "Open Mock Data Notice" },
    description: { zh: "Mock Data 提示卡片占位。", en: "Placeholder mock data notice card." },
    tone: "neutral",
    intent: "open-modal",
    status: "placeholder",
    source: {
      sourceModule: "demo",
      sourcePage: "workspace",
      sourceComponent: "MockDataNotice",
      sourceEvent: "click",
      sourceRoute: "/demo",
    },
    target: {
      targetAction: "openMockDataNotice",
      targetComponent: "MockDataNoticeModal",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "demo.mock-notice.placeholder",
  },
];
