import type { ActionContract } from "@/types/action-contract";

export const moduleActions: ActionContract[] = [
  {
    key: "createPurchaseRequest",
    label: { zh: "新建采购需求", en: "Create Purchase Request" },
    description: { zh: "采购模块的创建入口占位。", en: "Placeholder create entry point for procurement." },
    tone: "primary",
    intent: "create",
    status: "placeholder",
    source: {
      sourceModule: "procurement",
      sourcePage: "listing",
      sourceComponent: "ProcurementListing",
      sourceEvent: "click",
      sourceRoute: "/modules/procurement/listing",
    },
    target: {
      targetModule: "procurement",
      targetRoute: "/modules/procurement/form",
      targetAction: "createPurchaseRequest",
      targetPage: "form",
    },
    requirement: {
      permissionRequired: "procurement.create",
      auditRequired: true,
      confirmationRequired: true,
      roleRequired: "Store Operations Manager",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    futureWorkflowKey: "workflow.procurement.purchase-request",
    analyticsKey: "procurement.create.purchase-request",
  },
  {
    key: "approvePurchaseRequestPlaceholder",
    label: { zh: "审批采购需求（占位）", en: "Approve Purchase Request (Placeholder)" },
    description: { zh: "审批动作占位，仅用于合同与映射。", en: "Approval placeholder for contract and mapping only." },
    tone: "success",
    intent: "approve",
    status: "coming-soon",
    source: {
      sourceModule: "procurement",
      sourcePage: "detail",
      sourceComponent: "ProcurementDetail",
      sourceEvent: "click",
      sourceRoute: "/modules/procurement/detail",
    },
    target: {
      targetModule: "procurement",
      targetAction: "approvePurchaseRequest",
      targetPage: "detail",
    },
    requirement: {
      permissionRequired: "procurement.approve",
      auditRequired: true,
      confirmationRequired: true,
      roleRequired: "Procurement Lead",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    futureWorkflowKey: "workflow.procurement.approval",
    analyticsKey: "procurement.approve.placeholder",
  },
  {
    key: "exportProcurementPlaceholder",
    label: { zh: "导出采购数据（占位）", en: "Export Procurement (Placeholder)" },
    description: { zh: "导出采购数据占位。", en: "Placeholder export for procurement data." },
    tone: "info",
    intent: "export",
    status: "placeholder",
    source: {
      sourceModule: "procurement",
      sourcePage: "listing",
      sourceComponent: "ProcurementListing",
      sourceEvent: "click",
      sourceRoute: "/modules/procurement/listing",
    },
    target: {
      targetModule: "procurement",
      targetAction: "exportProcurement",
    },
    requirement: {
      permissionRequired: "procurement.export",
      auditRequired: true,
      confirmationRequired: false,
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "procurement.export.placeholder",
  },
  {
    key: "addSupplierPlaceholder",
    label: { zh: "新增供应商（占位）", en: "Add Supplier (Placeholder)" },
    description: { zh: "供应商新增入口占位。", en: "Placeholder add supplier entry point." },
    tone: "primary",
    intent: "create",
    status: "placeholder",
    source: {
      sourceModule: "supplier",
      sourcePage: "listing",
      sourceComponent: "SupplierListing",
      sourceEvent: "click",
      sourceRoute: "/modules/supplier/listing",
    },
    target: {
      targetModule: "supplier",
      targetRoute: "/modules/supplier/form",
      targetAction: "addSupplier",
      targetPage: "form",
    },
    requirement: {
      permissionRequired: "supplier.create",
      auditRequired: true,
      confirmationRequired: true,
      roleRequired: "Procurement Lead",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "supplier.add.placeholder",
  },
  {
    key: "reviewSupplierPlaceholder",
    label: { zh: "审核供应商（占位）", en: "Review Supplier (Placeholder)" },
    description: { zh: "供应商审核动作占位。", en: "Placeholder review action for supplier." },
    tone: "success",
    intent: "approve",
    status: "coming-soon",
    source: {
      sourceModule: "supplier",
      sourcePage: "detail",
      sourceComponent: "SupplierDetail",
      sourceEvent: "click",
      sourceRoute: "/modules/supplier/detail",
    },
    target: {
      targetModule: "supplier",
      targetAction: "reviewSupplier",
      targetPage: "detail",
    },
    requirement: {
      permissionRequired: "supplier.approve",
      auditRequired: true,
      confirmationRequired: true,
      roleRequired: "Procurement Lead",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "supplier.review.placeholder",
  },
  {
    key: "exportSupplierPlaceholder",
    label: { zh: "导出供应商（占位）", en: "Export Supplier (Placeholder)" },
    description: { zh: "供应商导出动作占位。", en: "Placeholder export action for supplier." },
    tone: "info",
    intent: "export",
    status: "placeholder",
    source: {
      sourceModule: "supplier",
      sourcePage: "listing",
      sourceComponent: "SupplierListing",
      sourceEvent: "click",
      sourceRoute: "/modules/supplier/listing",
    },
    target: {
      targetModule: "supplier",
      targetAction: "exportSupplier",
    },
    requirement: {
      permissionRequired: "supplier.export",
      auditRequired: true,
      confirmationRequired: false,
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "supplier.export.placeholder",
  },
  {
    key: "adjustStockPlaceholder",
    label: { zh: "库存调整（占位）", en: "Adjust Stock (Placeholder)" },
    description: { zh: "库存调整动作占位。", en: "Placeholder stock adjustment action." },
    tone: "warning",
    intent: "update",
    status: "coming-soon",
    source: {
      sourceModule: "inventory",
      sourcePage: "detail",
      sourceComponent: "InventoryDetail",
      sourceEvent: "click",
      sourceRoute: "/modules/inventory/detail",
    },
    target: {
      targetModule: "inventory",
      targetAction: "adjustStock",
      targetPage: "detail",
    },
    requirement: {
      permissionRequired: "inventory.edit",
      auditRequired: true,
      confirmationRequired: true,
      roleRequired: "Inventory Controller",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "inventory.adjust.placeholder",
  },
  {
    key: "transferStockPlaceholder",
    label: { zh: "库存调拨（占位）", en: "Transfer Stock (Placeholder)" },
    description: { zh: "库存调拨动作占位。", en: "Placeholder stock transfer action." },
    tone: "warning",
    intent: "update",
    status: "coming-soon",
    source: {
      sourceModule: "inventory",
      sourcePage: "listing",
      sourceComponent: "InventoryListing",
      sourceEvent: "click",
      sourceRoute: "/modules/inventory/listing",
    },
    target: {
      targetModule: "inventory",
      targetAction: "transferStock",
    },
    requirement: {
      permissionRequired: "inventory.edit",
      auditRequired: true,
      confirmationRequired: true,
      roleRequired: "Inventory Controller",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "inventory.transfer.placeholder",
  },
  {
    key: "exportInventoryPlaceholder",
    label: { zh: "导出库存（占位）", en: "Export Inventory (Placeholder)" },
    description: { zh: "库存导出动作占位。", en: "Placeholder export action for inventory." },
    tone: "info",
    intent: "export",
    status: "placeholder",
    source: {
      sourceModule: "inventory",
      sourcePage: "listing",
      sourceComponent: "InventoryListing",
      sourceEvent: "click",
      sourceRoute: "/modules/inventory/listing",
    },
    target: {
      targetModule: "inventory",
      targetAction: "exportInventory",
    },
    requirement: {
      permissionRequired: "inventory.export",
      auditRequired: true,
      confirmationRequired: false,
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "inventory.export.placeholder",
  },
  {
    key: "viewPosReportPlaceholder",
    label: { zh: "查看 POS 报表（占位）", en: "View POS Report (Placeholder)" },
    description: { zh: "POS 报表入口占位。", en: "Placeholder entry point for POS report." },
    tone: "neutral",
    intent: "navigate",
    status: "placeholder",
    source: {
      sourceModule: "pos-report",
      sourcePage: "dashboard",
      sourceComponent: "PosReportDashboard",
      sourceEvent: "click",
      sourceRoute: "/modules/pos-report/dashboard",
    },
    target: {
      targetModule: "pos-report",
      targetRoute: "/modules/pos-report/report",
      targetAction: "viewPosReport",
      targetPage: "report",
    },
    requirement: {
      permissionRequired: "pos-report.view",
      auditRequired: false,
      confirmationRequired: false,
      roleRequired: "Store Operations Manager",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "pos-report.view.placeholder",
  },
  {
    key: "auditRefundPlaceholder",
    label: { zh: "退款审核（占位）", en: "Audit Refund (Placeholder)" },
    description: { zh: "退款审核动作占位。", en: "Placeholder refund audit action." },
    tone: "warning",
    intent: "approve",
    status: "coming-soon",
    source: {
      sourceModule: "pos-report",
      sourcePage: "detail",
      sourceComponent: "PosReportDetail",
      sourceEvent: "click",
      sourceRoute: "/modules/pos-report/detail",
    },
    target: {
      targetModule: "pos-report",
      targetAction: "auditRefund",
      targetPage: "detail",
    },
    requirement: {
      permissionRequired: "pos-report.approve",
      auditRequired: true,
      confirmationRequired: true,
      roleRequired: "Store Operations Manager",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "pos-report.refund-audit.placeholder",
  },
  {
    key: "exportPosReportPlaceholder",
    label: { zh: "导出 POS 报表（占位）", en: "Export POS Report (Placeholder)" },
    description: { zh: "POS 报表导出动作占位。", en: "Placeholder export for POS report." },
    tone: "info",
    intent: "export",
    status: "placeholder",
    source: {
      sourceModule: "pos-report",
      sourcePage: "report",
      sourceComponent: "PosReportReport",
      sourceEvent: "click",
      sourceRoute: "/modules/pos-report/report",
    },
    target: {
      targetModule: "pos-report",
      targetAction: "exportPosReport",
    },
    requirement: {
      permissionRequired: "pos-report.export",
      auditRequired: true,
      confirmationRequired: false,
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "pos-report.export.placeholder",
  },
  {
    key: "assignCoursePlaceholder",
    label: { zh: "分派课程（占位）", en: "Assign Course (Placeholder)" },
    description: { zh: "教育模块课程分派占位。", en: "Placeholder course assignment action for education." },
    tone: "primary",
    intent: "assign",
    status: "coming-soon",
    source: {
      sourceModule: "education",
      sourcePage: "listing",
      sourceComponent: "EducationListing",
      sourceEvent: "click",
      sourceRoute: "/modules/education/listing",
    },
    target: {
      targetModule: "education",
      targetAction: "assignCourse",
    },
    requirement: {
      permissionRequired: "education.assign",
      auditRequired: true,
      confirmationRequired: true,
      roleRequired: "Store Operations Manager",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    futureWorkflowKey: "workflow.education.assignment",
    analyticsKey: "education.assign.placeholder",
  },
  {
    key: "reviewSopPlaceholder",
    label: { zh: "审核 SOP（占位）", en: "Review SOP (Placeholder)" },
    description: { zh: "SOP 审核动作占位。", en: "Placeholder SOP review action." },
    tone: "success",
    intent: "approve",
    status: "coming-soon",
    source: {
      sourceModule: "education",
      sourcePage: "detail",
      sourceComponent: "EducationDetail",
      sourceEvent: "click",
      sourceRoute: "/modules/education/detail",
    },
    target: {
      targetModule: "education",
      targetAction: "reviewSop",
    },
    requirement: {
      permissionRequired: "education.approve",
      auditRequired: true,
      confirmationRequired: true,
      roleRequired: "Store Operations Manager",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "education.review.placeholder",
  },
  {
    key: "exportEducationPlaceholder",
    label: { zh: "导出学习数据（占位）", en: "Export Education (Placeholder)" },
    description: { zh: "教育模块导出动作占位。", en: "Placeholder export action for education." },
    tone: "info",
    intent: "export",
    status: "placeholder",
    source: {
      sourceModule: "education",
      sourcePage: "report",
      sourceComponent: "EducationReport",
      sourceEvent: "click",
      sourceRoute: "/modules/education/report",
    },
    target: {
      targetModule: "education",
      targetAction: "exportEducation",
    },
    requirement: {
      permissionRequired: "education.export",
      auditRequired: true,
      confirmationRequired: false,
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "education.export.placeholder",
  },
  {
    key: "createTaskPlaceholder",
    label: { zh: "新建任务（占位）", en: "Create Task (Placeholder)" },
    description: { zh: "任务创建占位，仅用于合同与映射。", en: "Task create placeholder for contract and mapping only." },
    tone: "primary",
    intent: "create",
    status: "placeholder",
    source: {
      sourceModule: "task",
      sourcePage: "engine",
      sourceComponent: "TaskEngine",
      sourceEvent: "click",
      sourceRoute: "/tasks",
    },
    target: {
      targetModule: "task",
      targetAction: "createTask",
    },
    requirement: {
      permissionRequired: "task.create",
      auditRequired: true,
      confirmationRequired: true,
      roleRequired: "Store Operations Manager",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    futureWorkflowKey: "workflow.task.create",
    analyticsKey: "task.create.placeholder",
  },
  {
    key: "assignTaskPlaceholder",
    label: { zh: "分派任务（占位）", en: "Assign Task (Placeholder)" },
    description: { zh: "任务分派占位。", en: "Placeholder task assignment action." },
    tone: "neutral",
    intent: "assign",
    status: "coming-soon",
    source: {
      sourceModule: "task",
      sourcePage: "detail",
      sourceComponent: "TaskDetail",
      sourceEvent: "click",
      sourceRoute: "/tasks/:taskId",
    },
    target: {
      targetModule: "task",
      targetAction: "assignTask",
    },
    requirement: {
      permissionRequired: "task.assign",
      auditRequired: true,
      confirmationRequired: true,
      roleRequired: "Store Operations Manager",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    futureWorkflowKey: "workflow.task.assignment",
    analyticsKey: "task.assign.placeholder",
  },
  {
    key: "closeTaskPlaceholder",
    label: { zh: "关闭任务（占位）", en: "Close Task (Placeholder)" },
    description: { zh: "任务关闭占位。", en: "Placeholder task closure action." },
    tone: "danger",
    intent: "close",
    status: "coming-soon",
    source: {
      sourceModule: "task",
      sourcePage: "detail",
      sourceComponent: "TaskDetail",
      sourceEvent: "click",
      sourceRoute: "/tasks/:taskId",
    },
    target: {
      targetModule: "task",
      targetAction: "closeTask",
    },
    requirement: {
      permissionRequired: "task.close",
      auditRequired: true,
      confirmationRequired: true,
      roleRequired: "Store Operations Manager",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: true,
    futureWorkflowKey: "workflow.task.close",
    analyticsKey: "task.close.placeholder",
  },
];
