import type { ActionContract } from "@/types/action-contract";

export const taskActions: ActionContract[] = [
  {
    key: "openTaskEngine",
    label: { zh: "打开任务引擎", en: "Open Task Engine" },
    description: { zh: "进入 Task Engine MVP。", en: "Enter the task engine MVP." },
    tone: "neutral",
    intent: "navigate",
    status: "active",
    source: {
      sourceModule: "task",
      sourcePage: "engine",
      sourceComponent: "TaskEngine",
      sourceEvent: "click",
      sourceRoute: "/tasks",
    },
    target: {
      targetModule: "task",
      targetRoute: "/tasks",
      targetAction: "navigate",
      targetPage: "TaskEngine",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
    },
    isPlaceholder: false,
    isDestructive: false,
    analyticsKey: "task.open.engine",
  },
  {
    key: "openTaskDetail",
    label: { zh: "打开任务详情", en: "Open Task Detail" },
    description: { zh: "从任务列表打开任务详情页。", en: "Open task detail from the task list." },
    tone: "neutral",
    intent: "navigate",
    status: "active",
    source: {
      sourceModule: "task",
      sourcePage: "engine",
      sourceComponent: "TaskTable",
      sourceEvent: "click",
      sourceRoute: "/tasks",
    },
    target: {
      targetModule: "task",
      targetRoute: "/tasks/:taskId",
      targetAction: "navigate",
      targetPage: "TaskDetail",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
    },
    isPlaceholder: false,
    isDestructive: false,
    analyticsKey: "task.open.detail",
  },
  {
    key: "assignTask",
    label: { zh: "分派任务（元数据）", en: "Assign Task (Metadata)" },
    description: { zh: "仅提供合同元数据，不触发真实分派。", en: "Metadata only; does not trigger real assignment." },
    tone: "info",
    intent: "assign",
    status: "coming-soon",
    source: {
      sourceModule: "task",
      sourcePage: "detail",
      sourceComponent: "TaskDetail",
      sourceEvent: "click",
      sourceRoute: "/tasks/:taskId",
    },
    target: {
      targetModule: "task",
      targetAction: "assignTask",
    },
    requirement: {
      permissionRequired: "task.assign",
      auditRequired: true,
      confirmationRequired: true,
      roleRequired: "Store Operations Manager",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    futureWorkflowKey: "workflow.task.assignment",
    analyticsKey: "task.assign.metadata",
  },
  {
    key: "closeTask",
    label: { zh: "关闭任务（元数据）", en: "Close Task (Metadata)" },
    description: { zh: "仅提供合同元数据，不触发真实关闭。", en: "Metadata only; does not trigger real closure." },
    tone: "danger",
    intent: "close",
    status: "coming-soon",
    source: {
      sourceModule: "task",
      sourcePage: "detail",
      sourceComponent: "TaskDetail",
      sourceEvent: "click",
      sourceRoute: "/tasks/:taskId",
    },
    target: {
      targetModule: "task",
      targetAction: "closeTask",
    },
    requirement: {
      permissionRequired: "task.close",
      auditRequired: true,
      confirmationRequired: true,
      roleRequired: "Store Operations Manager",
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: true,
    futureWorkflowKey: "workflow.task.close",
    analyticsKey: "task.close.metadata",
  },
  {
    key: "exportTasksPlaceholder",
    label: { zh: "导出任务（占位）", en: "Export Tasks (Placeholder)" },
    description: { zh: "任务导出占位。", en: "Placeholder export action for tasks." },
    tone: "info",
    intent: "export",
    status: "placeholder",
    source: {
      sourceModule: "task",
      sourcePage: "engine",
      sourceComponent: "TaskEngine",
      sourceEvent: "click",
      sourceRoute: "/tasks",
    },
    target: {
      targetModule: "task",
      targetAction: "exportTasks",
    },
    requirement: {
      permissionRequired: "task.export",
      auditRequired: true,
      confirmationRequired: false,
      planRequired: "ops",
    },
    isPlaceholder: true,
    isDestructive: false,
    analyticsKey: "task.export.placeholder",
  },
];
