import type { RuleContract } from "@/types/rule";

const t = (zh: string, en: string) => ({ zh, en });

export const ruleContracts: RuleContract[] = [
  {
    key: "rule.inventory.lowStockRisk",
    title: t("库存低库存风险", "Inventory Low Stock Risk"),
    description: t("用于标记库存低于安全阈值的风险占位规则。", "Placeholder rule for stock-below-safety-threshold risk tagging."),
    ruleType: "risk",
    status: "active",
    severity: "high",
    source: {
      sourceModule: "inventory",
      sourcePage: "listing",
      sourceRoute: "/modules/inventory/listing",
      sourceComponent: "StockRiskCard",
      sourceService: "inventory.service",
      sourceRepository: "inventory.repository",
      sourceDataset: "inventory.stock-overview",
      accessRuleKey: "access.inventory.detail",
      auditEventKey: "audit.access.inventory.module",
      reportWidgetKey: "report.inventory.lowStockAlert",
    },
    inputs: [
      { key: "availableQty", label: t("可用数量", "Available Qty"), inputType: "count", sampleValue: 12, required: true },
      { key: "safetyStock", label: t("安全库存", "Safety Stock"), inputType: "count", sampleValue: 20, required: true },
    ],
    outputs: [
      { key: "riskStatus", label: t("风险状态", "Risk Status"), outputType: "status", sampleValue: "low-stock", severity: "high" },
      { key: "riskSeverity", label: t("风险级别", "Risk Severity"), outputType: "severity", sampleValue: "high", severity: "high" },
    ],
    conditions: [{ key: "available-lt-safety", label: t("可用数低于安全库存", "Available below safety"), operator: "lt", compareField: "safetyStock" }],
    requirement: {
      permissionRequired: "inventory.view",
      roleRequired: "warehouse-handler",
      auditRequired: true,
      humanReviewRequired: true,
      canTriggerWorkflow: true,
      canSendNotification: true,
      canCreateTask: true,
      isPlaceholder: false,
    },
    sampleExpression: "availableQty < safetyStock",
    sampleExplanation: t("当可用数量低于安全库存时，标记为低库存风险。", "Marks low stock risk when available quantity is below safety stock."),
    linkedRoute: "/reports",
    futureRuleEngineKey: "engine.rule.inventory.lowStockRisk",
    futureFormulaKey: "formula.inventory.lowStockRisk",
    futureAutomationKey: "automation.inventory.lowStockEscalation",
  },
  {
    key: "rule.inventory.stockValueEstimate",
    title: t("库存估值预估", "Inventory Stock Value Estimate"),
    ruleType: "formula",
    status: "active",
    severity: "medium",
    source: {
      sourceModule: "inventory",
      sourcePage: "dashboard",
      sourceRoute: "/reports",
      sourceComponent: "InventoryValueWidget",
      sourceService: "inventory.service",
      sourceRepository: "inventory.repository",
      sourceDataset: "inventory.stock-value",
      reportWidgetKey: "report.inventory.stockValue",
    },
    inputs: [
      { key: "unitCost", label: t("单位成本", "Unit Cost"), inputType: "amount", sampleValue: 15.5, required: true },
      { key: "onHandQty", label: t("在库数量", "On Hand Qty"), inputType: "count", sampleValue: 180, required: true },
    ],
    outputs: [{ key: "stockValue", label: t("库存估值", "Stock Value"), outputType: "currency", sampleValue: 2790 }],
    conditions: [{ key: "inputs-exist", label: t("输入存在", "Inputs exist"), operator: "exists", compareField: "unitCost" }],
    requirement: {
      permissionRequired: "inventory.view",
      auditRequired: false,
      humanReviewRequired: false,
      canTriggerWorkflow: false,
      canSendNotification: false,
      canCreateTask: false,
      isPlaceholder: false,
    },
    sampleExpression: "unitCost * onHandQty",
    sampleExplanation: t("示例公式仅用于元数据预览，不执行真实计算。", "Sample formula is metadata-only and performs no real calculation."),
    futureFormulaKey: "formula.inventory.stockValueEstimate",
  },
  {
    key: "rule.inventory.stockVarianceSeverity",
    title: t("库存差异严重性", "Inventory Stock Variance Severity"),
    ruleType: "threshold",
    status: "preview-only",
    severity: "medium",
    samplePreviewEnabled: true,
    source: {
      sourceModule: "inventory",
      sourcePage: "detail",
      sourceComponent: "VarianceSeverityPanel",
      sourceService: "inventory.service",
      sourceDataset: "inventory.variance",
      auditEventKey: "audit.action.inventory.adjustStock",
      reportWidgetKey: "report.inventory.stockVariance",
    },
    inputs: [{ key: "variancePct", label: t("差异百分比", "Variance Percent"), inputType: "percentage", sampleValue: 7.2, required: true }],
    outputs: [{ key: "severity", label: t("严重级别", "Severity"), outputType: "severity", sampleValue: "medium", severity: "medium" }],
    conditions: [
      { key: "variance-gte-5", label: t("差异大于等于 5%", "Variance >= 5%"), operator: "gte", thresholdValue: 5 },
      { key: "variance-lt-15", label: t("差异小于 15%", "Variance < 15%"), operator: "lt", thresholdValue: 15 },
    ],
    requirement: {
      permissionRequired: "inventory.edit",
      auditRequired: true,
      humanReviewRequired: true,
      canTriggerWorkflow: false,
      canSendNotification: false,
      canCreateTask: false,
      isPlaceholder: false,
    },
    sampleExpression: "variancePct >= 5 && variancePct < 15",
    sampleExplanation: t("仅展示样例阈值区间，未接入真实盘点流程。", "Shows sample threshold range only; no real cycle-count process is connected."),
    futureRuleEngineKey: "engine.rule.inventory.varianceSeverity",
  },
  {
    key: "rule.pos.refundAlert",
    title: t("POS 退款告警", "POS Refund Alert"),
    ruleType: "condition",
    status: "active",
    severity: "high",
    source: {
      sourceModule: "pos-report",
      sourcePage: "report",
      sourceRoute: "/modules/pos-report/report",
      sourceComponent: "RefundAlertWidget",
      sourceDataset: "pos.refund-summary",
      notificationKey: "notification.alert.refundRisk",
      reportWidgetKey: "report.pos.refundAlert",
    },
    inputs: [
      { key: "refundCount", label: t("退款笔数", "Refund Count"), inputType: "count", sampleValue: 16, required: true },
      { key: "salesCount", label: t("销售笔数", "Sales Count"), inputType: "count", sampleValue: 220, required: true },
    ],
    outputs: [{ key: "alertStatus", label: t("告警状态", "Alert Status"), outputType: "status", sampleValue: "warning", severity: "high" }],
    conditions: [{ key: "refund-rate-gte", label: t("退款比例过高", "Refund rate too high"), operator: "gte", thresholdValue: 0.05, compareField: "refundCount/salesCount" }],
    requirement: {
      permissionRequired: "pos-report.view",
      auditRequired: true,
      humanReviewRequired: true,
      canTriggerWorkflow: true,
      canSendNotification: true,
      canCreateTask: false,
      isPlaceholder: false,
    },
    sampleExpression: "refundCount / salesCount >= 0.05",
    sampleExplanation: t("达到阈值时显示退款风险提示，实际消息发送未实现。", "Shows refund risk warning at threshold; real delivery is not implemented."),
    linkedRoute: "/notifications",
    futureRuleEngineKey: "engine.rule.pos.refundAlert",
    futureAutomationKey: "automation.pos.refundReview",
  },
  {
    key: "rule.pos.salesDropWarning",
    title: t("POS 销售下滑预警", "POS Sales Drop Warning"),
    ruleType: "threshold",
    status: "coming-soon",
    severity: "medium",
    source: {
      sourceModule: "pos-report",
      sourcePage: "dashboard",
      sourceComponent: "SalesDropWidget",
      sourceDataset: "pos.sales-trend",
      reportWidgetKey: "report.pos.salesTrend",
    },
    inputs: [
      { key: "todaySales", label: t("今日销售", "Today Sales"), inputType: "amount", sampleValue: 12000, required: true },
      { key: "baselineSales", label: t("基线销售", "Baseline Sales"), inputType: "amount", sampleValue: 16000, required: true },
    ],
    outputs: [{ key: "dropPct", label: t("下滑比例", "Drop Percent"), outputType: "percentage", sampleValue: 0.25, severity: "medium" }],
    conditions: [{ key: "drop-gte-20", label: t("下滑超过 20%", "Drop over 20%"), operator: "gte", thresholdValue: 0.2, compareField: "(baselineSales-todaySales)/baselineSales" }],
    requirement: {
      permissionRequired: "pos-report.view",
      auditRequired: false,
      humanReviewRequired: true,
      canTriggerWorkflow: true,
      canSendNotification: true,
      canCreateTask: true,
      isPlaceholder: true,
    },
    sampleExpression: "(baselineSales - todaySales) / baselineSales >= 0.2",
    sampleExplanation: t("当前仅定义预警合同，等待未来引擎接入。", "Warning contract is defined only; waiting for future engine integration."),
    futureRuleEngineKey: "engine.rule.pos.salesDropWarning",
  },
  {
    key: "rule.procurement.overdueReceiving",
    title: t("采购逾期收货", "Procurement Overdue Receiving"),
    ruleType: "sla",
    status: "active",
    severity: "high",
    source: {
      sourceModule: "procurement",
      sourcePage: "listing",
      sourceRoute: "/modules/procurement/listing",
      sourceComponent: "ReceivingSlaCard",
      sourceService: "procurement.service",
      sourceRepository: "procurement.repository",
      workflowKey: "workflow.procurement.overdueReceiving",
      actionKey: "createPurchaseRequest",
    },
    inputs: [
      { key: "etaDate", label: t("预计到货日期", "ETA Date"), inputType: "date", sampleValue: "2026-05-02", required: true },
      { key: "today", label: t("当前日期", "Today"), inputType: "date", sampleValue: "2026-05-05", required: true },
    ],
    outputs: [{ key: "slaStatus", label: t("SLA 状态", "SLA Status"), outputType: "status", sampleValue: "overdue", severity: "high" }],
    conditions: [{ key: "today-gt-eta", label: t("当前日期晚于 ETA", "Today later than ETA"), operator: "gt", compareField: "etaDate" }],
    requirement: {
      permissionRequired: "procurement.view",
      roleRequired: "purchasing-manager",
      auditRequired: true,
      humanReviewRequired: true,
      canTriggerWorkflow: true,
      canSendNotification: true,
      canCreateTask: true,
      isPlaceholder: false,
    },
    sampleExpression: "today > etaDate",
    sampleExplanation: t("超过 ETA 触发逾期收货元数据提示。", "Metadata warning for overdue receiving when today is later than ETA."),
    linkedRoute: "/workflow",
    futureRuleEngineKey: "engine.rule.procurement.overdueReceiving",
    futureAutomationKey: "automation.procurement.overdueReceiving",
  },
  {
    key: "rule.procurement.approvalSla",
    title: t("采购审批 SLA", "Procurement Approval SLA"),
    ruleType: "sla",
    status: "active",
    severity: "medium",
    source: {
      sourceModule: "procurement",
      sourcePage: "detail",
      sourceComponent: "ApprovalSlaPanel",
      sourceDataset: "procurement.approval-cycle",
      workflowKey: "workflow.procurement.approvalReminder",
      notificationKey: "notification.procurement.approvalReminder",
    },
    inputs: [
      { key: "pendingHours", label: t("待审批小时", "Pending Hours"), inputType: "count", sampleValue: 30, required: true },
      { key: "slaHours", label: t("SLA 小时", "SLA Hours"), inputType: "count", sampleValue: 24, required: true },
    ],
    outputs: [{ key: "approvalSlaStatus", label: t("审批 SLA 状态", "Approval SLA Status"), outputType: "status", sampleValue: "breached", severity: "medium" }],
    conditions: [{ key: "pending-gte-sla", label: t("待审批超 SLA", "Pending exceeds SLA"), operator: "gte", compareField: "slaHours" }],
    requirement: {
      permissionRequired: "procurement.approve",
      auditRequired: true,
      humanReviewRequired: true,
      canTriggerWorkflow: true,
      canSendNotification: true,
      canCreateTask: false,
      isPlaceholder: false,
    },
    sampleExpression: "pendingHours >= slaHours",
    sampleExplanation: t("审批超时只做预览提示，不会发起真实催办。", "Approval timeout is preview-only and does not start real reminders."),
    futureFormulaKey: "formula.procurement.approvalSla",
  },
  {
    key: "rule.supplier.issueSeverity",
    title: t("供应商问题严重性", "Supplier Issue Severity"),
    ruleType: "score",
    status: "active",
    severity: "medium",
    source: {
      sourceModule: "supplier",
      sourcePage: "detail",
      sourceComponent: "SupplierIssueScoreCard",
      sourceDataset: "supplier.issue-score",
      accessRuleKey: "access.supplier.module",
      auditEventKey: "audit.access.supplier.module",
    },
    inputs: [
      { key: "delayRate", label: t("延迟率", "Delay Rate"), inputType: "percentage", sampleValue: 0.18, required: true },
      { key: "defectRate", label: t("缺陷率", "Defect Rate"), inputType: "percentage", sampleValue: 0.06, required: true },
    ],
    outputs: [{ key: "issueSeverity", label: t("问题严重级别", "Issue Severity"), outputType: "severity", sampleValue: "medium", severity: "medium" }],
    conditions: [{ key: "score-custom", label: t("综合评分规则", "Composite score rule"), operator: "custom", description: t("由未来评分引擎实现。", "Implemented by future scoring engine.") }],
    requirement: {
      permissionRequired: "supplier.view",
      auditRequired: true,
      humanReviewRequired: true,
      canTriggerWorkflow: true,
      canSendNotification: true,
      canCreateTask: true,
      isPlaceholder: false,
    },
    sampleExpression: "(delayRate * 0.6 + defectRate * 0.4) * 100",
    sampleExplanation: t("仅定义评分结构，不进行实时评分。", "Defines scoring structure only; no real-time scoring is performed."),
    futureRuleEngineKey: "engine.rule.supplier.issueSeverity",
  },
  {
    key: "rule.task.overdueSla",
    title: t("任务逾期 SLA", "Task Overdue SLA"),
    ruleType: "sla",
    status: "active",
    severity: "high",
    source: {
      sourceModule: "task",
      sourcePage: "listing",
      sourceRoute: "/tasks",
      sourceComponent: "TaskSlaCard",
      sourceDataset: "task.records",
      workflowKey: "workflow.task.overdueEscalation",
      notificationKey: "notification.task.overdueReminder",
      actionKey: "openTasks",
    },
    inputs: [
      { key: "dueDate", label: t("截止时间", "Due Date"), inputType: "date", sampleValue: "2026-05-01", required: true },
      { key: "taskStatus", label: t("任务状态", "Task Status"), inputType: "status", sampleValue: "open", required: true },
    ],
    outputs: [{ key: "taskSla", label: t("任务 SLA", "Task SLA"), outputType: "status", sampleValue: "overdue", severity: "high" }],
    conditions: [
      { key: "status-open", label: t("任务未关闭", "Task not closed"), operator: "neq", thresholdValue: "closed", compareField: "taskStatus" },
      { key: "due-past", label: t("超过截止日期", "Past due date"), operator: "custom", description: t("由未来时间规则引擎处理。", "Handled by future time rule engine.") },
    ],
    requirement: {
      permissionRequired: "task.view",
      auditRequired: true,
      humanReviewRequired: true,
      canTriggerWorkflow: true,
      canSendNotification: true,
      canCreateTask: true,
      isPlaceholder: false,
    },
    sampleExpression: "taskStatus != 'closed' && dueDate < today",
    sampleExplanation: t("仅展示任务 SLA 规则元数据，不会自动创建任务。", "Task SLA metadata preview only; no automatic task creation is performed."),
    futureRuleEngineKey: "engine.rule.task.overdueSla",
    futureAutomationKey: "automation.task.overdueSla",
  },
  {
    key: "rule.education.trainingCompletionRate",
    title: t("培训完成率", "Training Completion Rate"),
    ruleType: "formula",
    status: "preview-only",
    severity: "low",
    source: {
      sourceModule: "education",
      sourcePage: "dashboard",
      sourceComponent: "TrainingCompletionWidget",
      sourceDataset: "education.training-progress",
      reportWidgetKey: "report.education.trainingCompletion",
    },
    inputs: [
      { key: "completedCount", label: t("完成人数", "Completed Count"), inputType: "count", sampleValue: 42, required: true },
      { key: "assignedCount", label: t("分配人数", "Assigned Count"), inputType: "count", sampleValue: 56, required: true },
    ],
    outputs: [{ key: "completionRate", label: t("完成率", "Completion Rate"), outputType: "percentage", sampleValue: 0.75 }],
    conditions: [{ key: "assigned-exists", label: t("分配数存在", "Assigned count exists"), operator: "gt", thresholdValue: 0, compareField: "assignedCount" }],
    requirement: {
      permissionRequired: "education.view",
      auditRequired: false,
      humanReviewRequired: false,
      canTriggerWorkflow: false,
      canSendNotification: false,
      canCreateTask: false,
      isPlaceholder: false,
    },
    sampleExpression: "completedCount / assignedCount",
    sampleExplanation: t("当前仅预览完成率结构，不连接学习系统。", "Structure-only completion-rate preview; no learning system integration."),
    samplePreviewEnabled: false,
    futureFormulaKey: "formula.education.trainingCompletionRate",
  },
  {
    key: "rule.workflow.triggerPriority",
    title: t("工作流触发优先级", "Workflow Trigger Priority"),
    ruleType: "recommendation",
    status: "active",
    severity: "medium",
    source: {
      sourceModule: "workflow",
      sourcePage: "catalog",
      sourceRoute: "/workflow",
      sourceComponent: "WorkflowPriorityPreview",
      workflowKey: "workflow.action.createPurchaseRequest",
      notificationKey: "notification.workflow.approvalNotice",
    },
    inputs: [
      { key: "severity", label: t("严重级别", "Severity"), inputType: "status", sampleValue: "high", required: true },
      { key: "slaBreached", label: t("是否超时", "SLA Breached"), inputType: "boolean", sampleValue: true, required: true },
    ],
    outputs: [{ key: "priority", label: t("建议优先级", "Suggested Priority"), outputType: "recommendation", sampleValue: "P1", severity: "medium" }],
    conditions: [{ key: "priority-custom", label: t("优先级映射", "Priority mapping"), operator: "custom", description: t("由未来规则引擎消费。", "Consumed by future rule engine.") }],
    requirement: {
      auditRequired: true,
      humanReviewRequired: true,
      canTriggerWorkflow: true,
      canSendNotification: true,
      canCreateTask: false,
      isPlaceholder: false,
    },
    sampleExpression: "if severity=high and slaBreached then P1 else P2/P3",
    sampleExplanation: t("仅输出建议优先级，不触发真实流程。", "Outputs suggested priority only and does not trigger real flow."),
    futureRuleEngineKey: "engine.rule.workflow.triggerPriority",
  },
  {
    key: "rule.notification.escalationRequired",
    title: t("通知升级要求", "Notification Escalation Required"),
    ruleType: "escalation",
    status: "active",
    severity: "critical",
    source: {
      sourceModule: "message",
      sourcePage: "center",
      sourceRoute: "/notifications",
      sourceComponent: "EscalationPreviewCard",
      notificationKey: "notification.system.previewOnly",
      workflowKey: "workflow.alert.notificationEscalation",
    },
    inputs: [
      { key: "severity", label: t("通知级别", "Notification Severity"), inputType: "status", sampleValue: "critical", required: true },
      { key: "ackStatus", label: t("确认状态", "Ack Status"), inputType: "status", sampleValue: "unacknowledged", required: true },
    ],
    outputs: [{ key: "escalation", label: t("升级结果", "Escalation Result"), outputType: "notification-placeholder", sampleValue: "escalate", severity: "critical" }],
    conditions: [{ key: "need-escalation", label: t("未确认且高危", "Unacknowledged critical alert"), operator: "custom" }],
    requirement: {
      auditRequired: true,
      humanReviewRequired: true,
      canTriggerWorkflow: true,
      canSendNotification: true,
      canCreateTask: true,
      isPlaceholder: false,
    },
    sampleExpression: "severity == 'critical' && ackStatus == 'unacknowledged'",
    sampleExplanation: t("升级逻辑仅作元数据预览，不会发送真实通知。", "Escalation logic is metadata preview only and sends no real notification."),
    futureAutomationKey: "automation.notification.escalationRequired",
  },
  {
    key: "rule.report.ownerDashboardHealthScore",
    title: t("老板看板健康分", "Owner Dashboard Health Score"),
    ruleType: "score",
    status: "active",
    severity: "neutral",
    source: {
      sourceModule: "report-builder",
      sourcePage: "dashboard",
      sourceRoute: "/reports",
      sourceComponent: "OwnerHealthScoreCard",
      sourceDataset: "report.owner-health-score",
      reportWidgetKey: "report.owner.dashboardHealthScore",
    },
    inputs: [
      { key: "inventoryRiskScore", label: t("库存风险分", "Inventory Risk Score"), inputType: "metric", sampleValue: 72, required: true },
      { key: "taskSlaScore", label: t("任务 SLA 分", "Task SLA Score"), inputType: "metric", sampleValue: 85, required: true },
      { key: "supplierScore", label: t("供应商分", "Supplier Score"), inputType: "metric", sampleValue: 78, required: true },
    ],
    outputs: [{ key: "healthScore", label: t("健康分", "Health Score"), outputType: "number", sampleValue: 79 }],
    conditions: [{ key: "score-range", label: t("评分范围", "Score range"), operator: "between", thresholdValue: [0, 100] }],
    requirement: {
      permissionRequired: "report-builder.view",
      auditRequired: false,
      humanReviewRequired: false,
      canTriggerWorkflow: false,
      canSendNotification: false,
      canCreateTask: false,
      isPlaceholder: false,
    },
    sampleExpression: "(inventoryRiskScore * 0.4 + taskSlaScore * 0.3 + supplierScore * 0.3)",
    sampleExplanation: t("仅作为看板评分占位合同，不连接真实算分引擎。", "Dashboard score placeholder contract only; no real scoring engine is connected."),
    futureFormulaKey: "formula.report.ownerDashboardHealthScore",
  },
  {
    key: "rule.system.previewOnly",
    title: t("系统仅预览规则", "System Preview-Only Rule"),
    ruleType: "placeholder",
    status: "placeholder",
    severity: "neutral",
    source: {
      sourceModule: "system",
      sourcePage: "preview",
      sourceRoute: "/rules",
      sourceComponent: "SystemRulePreviewNotice",
    },
    inputs: [{ key: "previewFlag", label: t("预览标识", "Preview Flag"), inputType: "boolean", sampleValue: true, required: true }],
    outputs: [{ key: "previewStatus", label: t("预览状态", "Preview Status"), outputType: "status", sampleValue: "metadata-only" }],
    conditions: [{ key: "always-preview", label: t("始终预览", "Always preview"), operator: "eq", thresholdValue: true, compareField: "previewFlag" }],
    requirement: {
      auditRequired: false,
      humanReviewRequired: false,
      canTriggerWorkflow: false,
      canSendNotification: false,
      canCreateTask: false,
      isPlaceholder: true,
    },
    sampleExpression: "previewFlag == true",
    sampleExplanation: t("该规则用于声明规则系统当前为纯预览状态。", "This rule declares the current rule system is metadata preview only."),
    notes: t("不参与任何运行时计算。", "Not used for any runtime calculation."),
  },
];

export const ruleContractsByKey: Record<string, RuleContract> = Object.fromEntries(ruleContracts.map((item) => [item.key, item]));
