import type { AuditEventContract } from "@/types/audit"

export const auditEventRegistry: AuditEventContract[] = [
  {
    key: "audit.navigation.openModuleCenter",
    label: { zh: "导航到模块中心", en: "Navigate To Module Center" },
    description: {
      zh: "从首页导航打开模块中心页面的审计预览事件。",
      en: "Audit preview event for opening the module center from dashboard navigation.",
    },
    eventType: "navigation",
    severity: "info",
    status: "preview-only",
    actor: { actorType: "user", actorName: "Dashboard User" },
    source: {
      sourceModule: "shell",
      sourcePage: "dashboard",
      sourceComponent: "DashboardHome",
      sourceEvent: "click",
      sourceRoute: "/",
    },
    target: {
      targetModule: "shell",
      targetPage: "ModuleCenter",
      targetRoute: "/modules",
      targetAction: "openModuleCenter",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
      actionKey: "openModuleCenter",
    },
    timestampStrategy: "client-preview",
    isPlaceholder: false,
    futureEventKey: "event.navigation.open-module-center",
    retentionHint: "preview-only",
  },
  {
    key: "audit.navigation.openLayoutEngine",
    label: { zh: "导航到布局引擎", en: "Navigate To Layout Engine" },
    description: {
      zh: "从导航打开布局引擎路由的审计预览事件。",
      en: "Audit preview event for opening the layout engine route from navigation.",
    },
    eventType: "navigation",
    severity: "notice",
    status: "preview-only",
    actor: { actorType: "user", actorName: "Layout Operator" },
    source: {
      sourceModule: "shell",
      sourcePage: "global",
      sourceComponent: "ShellNav",
      sourceEvent: "click",
      sourceRoute: "/",
    },
    target: {
      targetModule: "layout-engine",
      targetPage: "LayoutEngine",
      targetRoute: "/layout-engine",
      targetAction: "openLayoutEngine",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
      actionKey: "openLayoutEngine",
      accessRuleKey: "access.layout-engine.preview",
    },
    timestampStrategy: "client-preview",
    isPlaceholder: false,
    futureEventKey: "event.navigation.open-layout-engine",
    retentionHint: "preview-only",
  },
  {
    key: "audit.action.createPurchaseRequest",
    label: { zh: "新建采购需求动作预览", en: "Create Purchase Request Action Preview" },
    description: {
      zh: "采购创建动作的审计合同预览，供未来事件日志接入。",
      en: "Audit contract preview for procurement creation action before future event logging integration.",
    },
    eventType: "create",
    severity: "notice",
    status: "pending",
    actor: { actorType: "role", role: "purchasing-manager" },
    source: {
      sourceModule: "procurement",
      sourcePage: "listing",
      sourceComponent: "ProcurementListing",
      sourceEvent: "click",
      sourceRoute: "/modules/procurement/listing",
    },
    target: {
      targetModule: "procurement",
      targetPage: "form",
      targetRoute: "/modules/procurement/form",
      targetAction: "createPurchaseRequest",
    },
    requirement: {
      auditRequired: true,
      permissionRequired: "procurement.create",
      roleRequired: "purchasing-manager",
      planRequired: "ops",
      confirmationRequired: true,
      actionKey: "createPurchaseRequest",
      accessRuleKey: "action.createPurchaseRequest",
    },
    timestampStrategy: "future",
    isPlaceholder: true,
    futureEventKey: "event.procurement.create-purchase-request",
    retentionHint: "operational",
  },
  {
    key: "audit.action.approvePurchaseRequestPlaceholder",
    label: { zh: "审批采购需求占位预览", en: "Approve Purchase Request Placeholder Preview" },
    description: {
      zh: "采购审批动作仍为占位阶段，当前仅输出审计元数据。",
      en: "Procurement approval remains placeholder and currently exposes audit metadata only.",
    },
    eventType: "approve",
    severity: "warning",
    status: "pending",
    actor: { actorType: "role", role: "purchasing-manager" },
    source: {
      sourceModule: "procurement",
      sourcePage: "detail",
      sourceComponent: "ProcurementDetail",
      sourceEvent: "click",
      sourceRoute: "/modules/procurement/detail",
    },
    target: {
      targetModule: "procurement",
      targetPage: "detail",
      targetAction: "approvePurchaseRequestPlaceholder",
    },
    requirement: {
      auditRequired: true,
      permissionRequired: "procurement.approve",
      roleRequired: "purchasing-manager",
      planRequired: "ops",
      confirmationRequired: true,
      actionKey: "approvePurchaseRequestPlaceholder",
      accessRuleKey: "action.approvePurchaseRequestPlaceholder",
    },
    timestampStrategy: "future",
    isPlaceholder: true,
    futureEventKey: "event.procurement.approve-purchase-request",
    retentionHint: "compliance",
  },
  {
    key: "audit.action.adjustStockPlaceholder",
    label: { zh: "库存调整占位预览", en: "Adjust Stock Placeholder Preview" },
    description: {
      zh: "库存调整动作的审计占位定义。",
      en: "Audit placeholder definition for stock adjustment action.",
    },
    eventType: "update",
    severity: "critical",
    status: "blocked",
    actor: { actorType: "role", role: "warehouse-handler" },
    source: {
      sourceModule: "inventory",
      sourcePage: "detail",
      sourceComponent: "InventoryDetail",
      sourceEvent: "click",
      sourceRoute: "/modules/inventory/detail",
    },
    target: {
      targetModule: "inventory",
      targetPage: "detail",
      targetAction: "adjustStockPlaceholder",
    },
    requirement: {
      auditRequired: true,
      permissionRequired: "inventory.edit",
      roleRequired: "warehouse-handler",
      planRequired: "ops",
      confirmationRequired: true,
      actionKey: "adjustStockPlaceholder",
      accessRuleKey: "action.adjustStockPlaceholder",
    },
    timestampStrategy: "future",
    isPlaceholder: true,
    futureEventKey: "event.inventory.adjust-stock",
    retentionHint: "compliance",
  },
  {
    key: "audit.action.assignTask",
    label: { zh: "任务分派审计预览", en: "Task Assignment Audit Preview" },
    description: {
      zh: "任务分派动作的未来审计事件合同。",
      en: "Future audit event contract for task assignment action.",
    },
    eventType: "assign",
    severity: "notice",
    status: "pending",
    actor: { actorType: "role", role: "store-manager" },
    source: {
      sourceModule: "task",
      sourcePage: "detail",
      sourceComponent: "TaskDetail",
      sourceEvent: "click",
      sourceRoute: "/tasks/:taskId",
    },
    target: {
      targetModule: "task",
      targetAction: "assignTask",
      targetPage: "detail",
    },
    requirement: {
      auditRequired: true,
      permissionRequired: "task.assign",
      roleRequired: "store-manager",
      planRequired: "ops",
      confirmationRequired: true,
      actionKey: "assignTask",
      accessRuleKey: "action.assignTask",
    },
    timestampStrategy: "server-generated",
    isPlaceholder: true,
    futureEventKey: "event.task.assign",
    retentionHint: "operational",
  },
  {
    key: "audit.action.closeTask",
    label: { zh: "任务关闭审计预览", en: "Task Closure Audit Preview" },
    description: {
      zh: "任务关闭属于破坏性动作，当前保留阻止状态合同。",
      en: "Task closure is destructive and currently remains a blocked contract preview.",
    },
    eventType: "close",
    severity: "critical",
    status: "blocked",
    actor: { actorType: "role", role: "store-manager" },
    source: {
      sourceModule: "task",
      sourcePage: "detail",
      sourceComponent: "TaskDetail",
      sourceEvent: "click",
      sourceRoute: "/tasks/:taskId",
    },
    target: {
      targetModule: "task",
      targetAction: "closeTask",
      targetPage: "detail",
    },
    requirement: {
      auditRequired: true,
      permissionRequired: "task.close",
      roleRequired: "store-manager",
      planRequired: "ops",
      confirmationRequired: true,
      actionKey: "closeTask",
      accessRuleKey: "action.closeTask",
    },
    timestampStrategy: "server-generated",
    isPlaceholder: true,
    futureEventKey: "event.task.close",
    retentionHint: "compliance",
  },
  {
    key: "audit.access.procurement.module",
    label: { zh: "采购模块访问检查", en: "Procurement Module Access Check" },
    description: {
      zh: "采购模块访问规则的审计检查预览。",
      en: "Audit check preview for procurement module access rule.",
    },
    eventType: "access-check",
    severity: "info",
    status: "captured",
    actor: { actorType: "role", role: "operations-manager" },
    source: {
      sourceModule: "access-control",
      sourcePage: "rule-list",
      sourceComponent: "AccessRuleCard",
      sourceEvent: "preview",
      sourceRoute: "/access-control",
    },
    target: {
      targetModule: "procurement",
      targetRoute: "/modules/procurement/listing",
      targetAction: "access-check",
    },
    requirement: {
      auditRequired: false,
      permissionRequired: "procurement.view",
      roleRequired: "operations-manager",
      planRequired: "ops",
      confirmationRequired: false,
      accessRuleKey: "access.procurement.module",
    },
    timestampStrategy: "client-preview",
    isPlaceholder: false,
    futureEventKey: "event.access.procurement-module",
    retentionHint: "preview-only",
  },
  {
    key: "audit.access.inventory.detail",
    label: { zh: "库存详情访问检查", en: "Inventory Detail Access Check" },
    description: {
      zh: "库存详情页访问规则涉及审计要求。",
      en: "Inventory detail access rule includes audit requirement metadata.",
    },
    eventType: "access-check",
    severity: "notice",
    status: "captured",
    actor: { actorType: "role", role: "warehouse-handler" },
    source: {
      sourceModule: "access-control",
      sourcePage: "rule-list",
      sourceComponent: "AccessRuleCard",
      sourceEvent: "preview",
      sourceRoute: "/access-control",
    },
    target: {
      targetModule: "inventory",
      targetRoute: "/modules/inventory/detail",
      targetAction: "access-check",
    },
    requirement: {
      auditRequired: true,
      permissionRequired: "inventory.view",
      roleRequired: "warehouse-handler",
      planRequired: "ops",
      confirmationRequired: false,
      accessRuleKey: "access.inventory.detail",
    },
    timestampStrategy: "server-generated",
    isPlaceholder: false,
    futureEventKey: "event.access.inventory-detail",
    retentionHint: "operational",
  },
  {
    key: "audit.access.task.board",
    label: { zh: "任务看板访问检查", en: "Task Board Access Check" },
    description: {
      zh: "任务看板访问规则预览事件。",
      en: "Task board access rule preview event.",
    },
    eventType: "permission-preview",
    severity: "info",
    status: "captured",
    actor: { actorType: "role", role: "staff" },
    source: {
      sourceModule: "access-control",
      sourcePage: "rule-list",
      sourceComponent: "AccessRuleCard",
      sourceEvent: "preview",
      sourceRoute: "/access-control",
    },
    target: {
      targetModule: "task",
      targetRoute: "/tasks",
      targetAction: "access-check",
    },
    requirement: {
      auditRequired: false,
      permissionRequired: "task.view",
      roleRequired: "staff",
      planRequired: "starter",
      confirmationRequired: false,
      accessRuleKey: "access.task.board",
    },
    timestampStrategy: "client-preview",
    isPlaceholder: false,
    futureEventKey: "event.access.task-board",
    retentionHint: "preview-only",
  },
  {
    key: "audit.export.tasksPlaceholder",
    label: { zh: "任务导出占位预览", en: "Task Export Placeholder Preview" },
    description: {
      zh: "任务导出能力尚未接入，仅保留审计合同预览。",
      en: "Task export is not integrated yet and remains an audit contract preview only.",
    },
    eventType: "export",
    severity: "warning",
    status: "skipped",
    actor: { actorType: "role", role: "operations-manager" },
    source: {
      sourceModule: "task",
      sourcePage: "engine",
      sourceComponent: "TaskActionBar",
      sourceEvent: "click",
      sourceRoute: "/tasks",
    },
    target: {
      targetModule: "task",
      targetAction: "exportTasksPlaceholder",
      targetRoute: "/tasks",
    },
    requirement: {
      auditRequired: true,
      permissionRequired: "task.export",
      roleRequired: "operations-manager",
      planRequired: "ops",
      confirmationRequired: false,
      actionKey: "exportTasksPlaceholder",
      accessRuleKey: "action.exportTasksPlaceholder",
    },
    timestampStrategy: "future",
    isPlaceholder: true,
    futureEventKey: "event.task.export",
    retentionHint: "compliance",
  },
  {
    key: "audit.system.previewOnly",
    label: { zh: "系统预览模式提示", en: "System Preview-Only Notice" },
    description: {
      zh: "统一说明当前审计链路仅为元数据预览，不做真实日志写入。",
      en: "Unified notice that the current audit chain is metadata preview only with no real event persistence.",
    },
    eventType: "system-preview",
    severity: "notice",
    status: "preview-only",
    actor: { actorType: "system", actorName: "ME Preview Engine" },
    source: {
      sourceModule: "audit-trail",
      sourcePage: "overview",
      sourceComponent: "AuditTrailPage",
      sourceEvent: "render",
      sourceRoute: "/audit-trail",
    },
    target: {
      targetModule: "audit-trail",
      targetRoute: "/audit-trail",
      targetAction: "preview",
    },
    requirement: {
      auditRequired: false,
      confirmationRequired: false,
    },
    timestampStrategy: "client-preview",
    isPlaceholder: false,
    futureEventKey: "event.system.preview-only",
    retentionHint: "system",
  },
]

export const auditEventRegistryByKey: Record<string, AuditEventContract> = Object.fromEntries(
  auditEventRegistry.map((event) => [event.key, event]),
)
