import type { PsiActionDraftContract } from "@/types/psi/actions";

const t = (zh: string, en: string) => ({ zh, en });
const submitLabel = t("提交（占位）", "Submit (Placeholder)");
const cancelLabel = t("取消", "Cancel");

const baseRequirement = {
  auditRequired: true,
  confirmationRequired: true,
  humanReviewRequired: true,
  createsTaskPlaceholder: false,
  triggersWorkflowPlaceholder: false,
  sendsNotificationPlaceholder: false,
  isPlaceholder: true,
} as const;

function makeDraft(input: PsiActionDraftContract): PsiActionDraftContract {
  return input;
}

export const psiActionDrafts: PsiActionDraftContract[] = [
  makeDraft({
    key: "psi.action.createPurchaseRequest",
    title: t("创建采购申请", "Create Purchase Request"),
    description: t("采购申请草稿表单占位预览。", "Placeholder preview for purchase request draft form."),
    category: "procurement",
    intent: "create",
    status: "draft",
    source: {
      moduleCode: "procurement",
      sourceRoute: "/psi/procurement",
      actionKey: "createPurchaseRequest",
      accessRuleKey: "access.procurement.request.create",
      auditEventKey: "audit.procurement.request.create",
      workflowKey: "workflow.procurement.request.submit",
      notificationKey: "notification.procurement.request.submit",
      packageKey: "package.pack.procurement",
    },
    sections: [
      {
        key: "request",
        title: t("申请信息", "Request Info"),
        fields: [
          { key: "storeId", label: t("门店", "Store"), fieldType: "store-select", required: true, isPlaceholder: true },
          { key: "supplierId", label: t("供应商", "Supplier"), fieldType: "supplier-select", required: false, isPlaceholder: true },
          { key: "requestedDate", label: t("申请日期", "Requested Date"), fieldType: "date", required: true, isPlaceholder: true },
        ],
      },
      {
        key: "line",
        title: t("明细", "Line"),
        fields: [
          { key: "skuId", label: t("SKU", "SKU"), fieldType: "sku-select", required: true, isPlaceholder: true },
          { key: "qty", label: t("数量", "Quantity"), fieldType: "quantity", required: true, isPlaceholder: true },
          { key: "reason", label: t("申请原因", "Reason"), fieldType: "textarea", required: false, isPlaceholder: true },
        ],
      },
    ],
    requirement: {
      ...baseRequirement,
      createsTaskPlaceholder: true,
      triggersWorkflowPlaceholder: true,
      sendsNotificationPlaceholder: true,
    },
    submitLabel,
    cancelLabel,
    linkedRoute: "/psi/procurement",
    futureServiceMethod: "createPurchaseRequestDraft",
    futureRepositoryMethod: "createPurchaseRequest",
    futureApiEndpoint: "POST /api/procurement/requests",
  }),
  makeDraft({
    key: "psi.action.createPurchaseOrder",
    title: t("创建采购订单", "Create Purchase Order"),
    category: "procurement",
    intent: "create",
    status: "placeholder",
    source: { moduleCode: "procurement", sourceRoute: "/psi/procurement" },
    sections: [{ key: "po", title: t("订单信息", "Order Info"), fields: [{ key: "requestId", label: t("申请单", "Request"), fieldType: "select", required: true, isPlaceholder: true }] }],
    requirement: { ...baseRequirement, triggersWorkflowPlaceholder: true, sendsNotificationPlaceholder: true },
    submitLabel,
    cancelLabel,
    futureServiceMethod: "createPurchaseOrderDraft",
    futureRepositoryMethod: "createPurchaseOrder",
    futureApiEndpoint: "POST /api/procurement/orders",
  }),
  makeDraft({
    key: "psi.action.recordReceiving",
    title: t("登记收货", "Record Receiving"),
    category: "receiving",
    intent: "receive",
    status: "placeholder",
    source: { moduleCode: "procurement", sourceRoute: "/psi/procurement", actionKey: "recordReceivingPlaceholder" },
    sections: [{ key: "receiving", title: t("收货信息", "Receiving Info"), fields: [{ key: "poId", label: t("采购订单", "Purchase Order"), fieldType: "select", required: true, isPlaceholder: true }] }],
    requirement: { ...baseRequirement },
    submitLabel,
    cancelLabel,
    futureServiceMethod: "recordReceivingDraft",
    futureRepositoryMethod: "recordReceiving",
    futureApiEndpoint: "POST /api/procurement/receiving",
  }),
  makeDraft({
    key: "psi.action.reportPurchaseIssue",
    title: t("报告采购问题", "Report Purchase Issue"),
    category: "issue",
    intent: "report-issue",
    status: "placeholder",
    source: { moduleCode: "procurement", sourceRoute: "/psi/procurement", actionKey: "reportPurchaseIssuePlaceholder" },
    sections: [{ key: "issue", title: t("问题信息", "Issue Info"), fields: [{ key: "description", label: t("问题描述", "Issue Description"), fieldType: "textarea", required: true, isPlaceholder: true }] }],
    requirement: { ...baseRequirement, createsTaskPlaceholder: true, triggersWorkflowPlaceholder: true, sendsNotificationPlaceholder: true },
    submitLabel,
    cancelLabel,
    futureServiceMethod: "reportPurchaseIssueDraft",
    futureRepositoryMethod: "createPurchaseIssue",
    futureApiEndpoint: "POST /api/procurement/issues",
  }),
  makeDraft({
    key: "psi.action.addSupplier",
    title: t("新增供应商", "Add Supplier"),
    category: "supplier",
    intent: "create",
    status: "placeholder",
    source: { moduleCode: "supplier", sourceRoute: "/psi/supplier", actionKey: "addSupplierPlaceholder" },
    sections: [{ key: "supplier", title: t("供应商信息", "Supplier Info"), fields: [{ key: "supplierName", label: t("供应商名称", "Supplier Name"), fieldType: "text", required: true, isPlaceholder: true }] }],
    requirement: { ...baseRequirement },
    submitLabel,
    cancelLabel,
    futureServiceMethod: "addSupplierDraft",
    futureRepositoryMethod: "createSupplier",
    futureApiEndpoint: "POST /api/suppliers",
  }),
  makeDraft({
    key: "psi.action.reviewSupplier",
    title: t("审核供应商", "Review Supplier"),
    category: "supplier",
    intent: "review",
    status: "preview-only",
    source: { moduleCode: "supplier", sourceRoute: "/psi/supplier", actionKey: "reviewSupplierPlaceholder" },
    sections: [{ key: "review", title: t("审核信息", "Review Info"), fields: [{ key: "reviewResult", label: t("审核结果", "Review Result"), fieldType: "select", required: true, isPlaceholder: true }] }],
    requirement: { ...baseRequirement, triggersWorkflowPlaceholder: true, sendsNotificationPlaceholder: true },
    submitLabel,
    cancelLabel,
    futureServiceMethod: "reviewSupplierDraft",
    futureRepositoryMethod: "reviewSupplier",
    futureApiEndpoint: "POST /api/suppliers/:id/review",
  }),
  makeDraft({
    key: "psi.action.reportSupplierIssue",
    title: t("报告供应商问题", "Report Supplier Issue"),
    category: "issue",
    intent: "report-issue",
    status: "placeholder",
    source: { moduleCode: "supplier", sourceRoute: "/psi/supplier", actionKey: "reportSupplierIssuePlaceholder" },
    sections: [{ key: "issue", title: t("问题信息", "Issue Info"), fields: [{ key: "issueDetail", label: t("问题详情", "Issue Detail"), fieldType: "textarea", required: true, isPlaceholder: true }] }],
    requirement: { ...baseRequirement, createsTaskPlaceholder: true, sendsNotificationPlaceholder: true, triggersWorkflowPlaceholder: true },
    submitLabel,
    cancelLabel,
    futureServiceMethod: "reportSupplierIssueDraft",
    futureRepositoryMethod: "createSupplierIssue",
    futureApiEndpoint: "POST /api/suppliers/issues",
  }),
  makeDraft({
    key: "psi.action.createSku",
    title: t("创建SKU", "Create SKU"),
    category: "inventory",
    intent: "create",
    status: "placeholder",
    source: { moduleCode: "inventory", sourceRoute: "/psi/inventory" },
    sections: [{ key: "sku", title: t("SKU信息", "SKU Info"), fields: [{ key: "skuCode", label: t("SKU编码", "SKU Code"), fieldType: "text", required: true, isPlaceholder: true }] }],
    requirement: { ...baseRequirement },
    submitLabel,
    cancelLabel,
    futureServiceMethod: "createSkuDraft",
    futureRepositoryMethod: "createSku",
    futureApiEndpoint: "POST /api/inventory/skus",
  }),
  makeDraft({
    key: "psi.action.adjustInventory",
    title: t("库存调整", "Adjust Inventory"),
    category: "stock",
    intent: "adjust",
    status: "coming-soon",
    source: { moduleCode: "inventory", sourceRoute: "/psi/inventory", actionKey: "adjustStockPlaceholder" },
    sections: [{ key: "adjust", title: t("调整信息", "Adjustment Info"), fields: [{ key: "deltaQty", label: t("调整数量", "Adjustment Qty"), fieldType: "quantity", required: true, isPlaceholder: true }] }],
    requirement: { ...baseRequirement },
    submitLabel,
    cancelLabel,
    futureServiceMethod: "adjustInventoryDraft",
    futureRepositoryMethod: "adjustInventory",
    futureApiEndpoint: "POST /api/inventory/adjustments",
  }),
  makeDraft({
    key: "psi.action.transferStock",
    title: t("库存调拨", "Transfer Stock"),
    category: "stock",
    intent: "transfer",
    status: "coming-soon",
    source: { moduleCode: "inventory", sourceRoute: "/psi/inventory", actionKey: "transferStockPlaceholder" },
    sections: [{ key: "transfer", title: t("调拨信息", "Transfer Info"), fields: [{ key: "transferQty", label: t("调拨数量", "Transfer Qty"), fieldType: "quantity", required: true, isPlaceholder: true }] }],
    requirement: { ...baseRequirement },
    submitLabel,
    cancelLabel,
    futureServiceMethod: "transferStockDraft",
    futureRepositoryMethod: "transferStock",
    futureApiEndpoint: "POST /api/inventory/transfers",
  }),
  makeDraft({
    key: "psi.action.reportInventoryIssue",
    title: t("报告库存问题", "Report Inventory Issue"),
    category: "issue",
    intent: "report-issue",
    status: "placeholder",
    source: { moduleCode: "inventory", sourceRoute: "/psi/inventory", actionKey: "reportInventoryIssuePlaceholder" },
    sections: [{ key: "issue", title: t("问题信息", "Issue Info"), fields: [{ key: "issueDetail", label: t("问题详情", "Issue Detail"), fieldType: "textarea", required: true, isPlaceholder: true }] }],
    requirement: { ...baseRequirement, createsTaskPlaceholder: true, sendsNotificationPlaceholder: true },
    submitLabel,
    cancelLabel,
    futureServiceMethod: "reportInventoryIssueDraft",
    futureRepositoryMethod: "createInventoryIssue",
    futureApiEndpoint: "POST /api/inventory/issues",
  }),
  makeDraft({
    key: "psi.action.createReplenishmentSuggestion",
    title: t("创建补货建议", "Create Replenishment Suggestion"),
    category: "inventory",
    intent: "suggest",
    status: "placeholder",
    source: { moduleCode: "inventory", sourceRoute: "/psi/inventory" },
    sections: [{ key: "replenishment", title: t("补货信息", "Replenishment Info"), fields: [{ key: "suggestQty", label: t("建议数量", "Suggested Qty"), fieldType: "quantity", required: true, isPlaceholder: true }] }],
    requirement: { ...baseRequirement, createsTaskPlaceholder: true },
    submitLabel,
    cancelLabel,
    futureServiceMethod: "createReplenishmentSuggestionDraft",
    futureRepositoryMethod: "createReplenishmentSuggestion",
    futureApiEndpoint: "POST /api/inventory/replenishments",
  }),
  makeDraft({
    key: "psi.action.previewOnly",
    title: t("系统预览动作", "System Preview Action"),
    description: t("仅用于系统占位预览。", "Used only as system placeholder preview."),
    category: "system",
    intent: "placeholder",
    status: "preview-only",
    source: { moduleCode: "system", sourceRoute: "/psi/actions" },
    sections: [{ key: "preview", title: t("预览信息", "Preview Info"), fields: [{ key: "notice", label: t("说明", "Notice"), fieldType: "text", required: false, isPlaceholder: true }] }],
    requirement: {
      ...baseRequirement,
      auditRequired: false,
      confirmationRequired: false,
      humanReviewRequired: false,
    },
    submitLabel,
    cancelLabel,
    notes: t("仅展示，不会提交。", "Display only; no submission."),
  }),
];

export const psiActionDraftsByKey: Record<string, PsiActionDraftContract> = Object.fromEntries(
  psiActionDrafts.map((item) => [item.key, item])
);
