import type { ReportWidgetContract } from "@/types/report-widget";

export const reportWidgetRegistry: ReportWidgetContract[] = [
  {
    key: "widget.pos.salesToday",
    title: { zh: "今日销售额", en: "Sales Today" },
    description: { zh: "POS 今日销售总览（元数据预览）", en: "POS sales overview for today (metadata preview)." },
    widgetType: "kpi",
    status: "active",
    severity: "low",
    size: "md",
    source: {
      sourceModule: "pos-report",
      sourcePage: "dashboard",
      sourceRoute: "/modules/pos-report/report",
      sourceComponent: "KpiCard",
      sourceService: "DemoService",
      sourceRepository: "DemoRepository",
      sourceDataset: "demo.pos.salesToday",
      dataSourceType: "mock",
      actionKey: "viewPosReportPlaceholder",
      accessRuleKey: "access.pos-report.module",
      auditEventKey: "audit.navigation.openModuleCenter",
      workflowKey: "workflow.system.previewOnly",
      notificationKey: "notification.system.previewOnly",
    },
    metrics: [
      { key: "grossSales", label: { zh: "销售额", en: "Gross Sales" }, format: "currency", sampleValue: 128520, trendDirection: "up", severity: "low" },
      { key: "transactionCount", label: { zh: "交易笔数", en: "Transactions" }, format: "count", sampleValue: 468, trendDirection: "up" },
    ],
    dimensions: [
      { key: "store", label: { zh: "门店", en: "Store" }, type: "store", sampleValue: "North Branch" },
      { key: "date", label: { zh: "日期", en: "Date" }, type: "date", sampleValue: "2026-05-05" },
    ],
    filters: [
      { key: "store", label: { zh: "门店", en: "Store" }, type: "store", required: false },
      { key: "dateRange", label: { zh: "日期范围", en: "Date Range" }, type: "date-range", required: true, defaultValue: "today" },
    ],
    requirement: {
      permissionRequired: "pos-report.view",
      roleRequired: "operations-manager",
      planRequired: "pro",
      auditRequired: true,
      exportable: false,
      refreshable: true,
      drillDownEnabled: true,
      isPlaceholder: false,
    },
    sampleData: { grossSales: 128520, transactionCount: 468, store: "North Branch" },
    linkedRoute: "/modules/pos-report/report",
    futureQueryKey: "query.pos.dailySales",
    futureDashboardKey: "dashboard.owner-overview",
    futureReportBuilderKey: "report-builder.pos.salesToday",
  },
  {
    key: "widget.pos.refundAlerts",
    title: { zh: "退款预警", en: "Refund Alerts" },
    description: { zh: "POS 退款风险预警汇总（占位）", en: "POS refund risk alerts summary (placeholder)." },
    widgetType: "alert",
    status: "coming-soon",
    severity: "high",
    size: "md",
    source: {
      sourceModule: "pos-report",
      sourcePage: "report",
      sourceRoute: "/modules/pos-report/report",
      sourceComponent: "ReportAlertList",
      sourceService: "DemoService",
      sourceRepository: "DemoRepository",
      sourceDataset: "demo.pos.refundAlerts",
      dataSourceType: "mock",
      actionKey: "auditRefundPlaceholder",
      accessRuleKey: "access.pos-report.module",
      auditEventKey: "audit.action.approvePurchaseRequestPlaceholder",
      workflowKey: "workflow.action.approvePurchaseRequestPlaceholder",
      notificationKey: "notification.workflow.purchaseApprovalNeeded",
    },
    metrics: [{ key: "refundRiskCount", label: { zh: "风险单数", en: "Risk Cases" }, format: "count", sampleValue: 6, trendDirection: "up", severity: "high" }],
    dimensions: [{ key: "status", label: { zh: "状态", en: "Status" }, type: "status", sampleValue: "warning" }],
    filters: [
      { key: "status", label: { zh: "状态", en: "Status" }, type: "status", required: false, defaultValue: "warning" },
      { key: "dateRange", label: { zh: "日期范围", en: "Date Range" }, type: "date-range", required: true, defaultValue: "7d" },
    ],
    requirement: {
      permissionRequired: "pos-report.view",
      roleRequired: "operations-manager",
      planRequired: "pro",
      auditRequired: true,
      exportable: false,
      refreshable: false,
      drillDownEnabled: true,
      isPlaceholder: true,
    },
    sampleData: [{ id: "rf-001", amount: 420, reason: "price override" }],
    futureQueryKey: "query.pos.refundRisk",
    futureDashboardKey: "dashboard.owner-overview",
    futureReportBuilderKey: "report-builder.pos.refundAlerts",
    notes: { zh: "仅预警元数据，未接入风险引擎。", en: "Alert metadata only; no risk engine integration." },
  },
  {
    key: "widget.inventory.lowStockRisk",
    title: { zh: "低库存风险", en: "Low Stock Risk" },
    description: { zh: "低库存 SKU 风险分布", en: "Low-stock SKU risk distribution." },
    widgetType: "distribution",
    status: "active",
    severity: "medium",
    size: "lg",
    source: {
      sourceModule: "inventory",
      sourcePage: "dashboard",
      sourceRoute: "/modules/inventory/dashboard",
      sourceComponent: "RiskDistribution",
      sourceService: "InventoryService",
      sourceRepository: "InventoryRepository",
      sourceDataset: "demo.inventory.lowStock",
      dataSourceType: "mock",
      actionKey: "adjustStockPlaceholder",
      accessRuleKey: "access.inventory.module",
      auditEventKey: "audit.action.adjustStockPlaceholder",
      workflowKey: "workflow.action.adjustStockPlaceholder",
      notificationKey: "notification.workflow.stockAdjustmentReview",
    },
    metrics: [
      { key: "highRiskSku", label: { zh: "高风险SKU", en: "High Risk SKU" }, format: "count", sampleValue: 18, trendDirection: "up", severity: "high" },
      { key: "coverageDays", label: { zh: "覆盖天数", en: "Coverage Days" }, format: "duration", sampleValue: 3, trendDirection: "down", severity: "medium" },
    ],
    dimensions: [
      { key: "sku", label: { zh: "SKU", en: "SKU" }, type: "sku", sampleValue: "SKU-1029" },
      { key: "store", label: { zh: "门店", en: "Store" }, type: "store", sampleValue: "South Branch" },
    ],
    filters: [
      { key: "store", label: { zh: "门店", en: "Store" }, type: "store", required: false },
      { key: "status", label: { zh: "风险状态", en: "Risk Status" }, type: "status", required: false, defaultValue: "high" },
    ],
    requirement: {
      permissionRequired: "inventory.view",
      roleRequired: "warehouse-handler",
      planRequired: "ops",
      auditRequired: true,
      exportable: false,
      refreshable: true,
      drillDownEnabled: true,
      isPlaceholder: false,
    },
    sampleData: [{ sku: "SKU-1029", coverageDays: 2, risk: "high" }],
    linkedRoute: "/modules/inventory/detail",
    futureQueryKey: "query.inventory.lowStockRisk",
    futureDashboardKey: "dashboard.inventory",
    futureReportBuilderKey: "report-builder.inventory.lowStockRisk",
  },
  {
    key: "widget.inventory.stockValue",
    title: { zh: "库存价值", en: "Stock Value" },
    description: { zh: "库存价值趋势（预览）", en: "Inventory value trend (preview)." },
    widgetType: "trend",
    status: "active",
    severity: "neutral",
    size: "lg",
    source: {
      sourceModule: "inventory",
      sourcePage: "report",
      sourceRoute: "/modules/inventory/report",
      sourceComponent: "TrendCard",
      sourceService: "InventoryService",
      sourceRepository: "InventoryRepository",
      sourceDataset: "demo.inventory.stockValue",
      dataSourceType: "mock",
      actionKey: "exportInventoryPlaceholder",
      accessRuleKey: "access.inventory.detail",
      auditEventKey: "audit.access.inventory.detail",
      workflowKey: "workflow.audit.inventoryDetailPreview",
      notificationKey: "notification.audit.inventoryDetailPreview",
    },
    metrics: [{ key: "inventoryValue", label: { zh: "库存价值", en: "Inventory Value" }, format: "currency", sampleValue: 892000, trendDirection: "up" }],
    dimensions: [{ key: "date", label: { zh: "日期", en: "Date" }, type: "date", sampleValue: "2026-05" }],
    filters: [
      { key: "dateRange", label: { zh: "日期范围", en: "Date Range" }, type: "date-range", required: true, defaultValue: "30d" },
      { key: "category", label: { zh: "品类", en: "Category" }, type: "select", required: false },
    ],
    requirement: {
      permissionRequired: "inventory.export",
      roleRequired: "warehouse-handler",
      planRequired: "ops",
      auditRequired: true,
      exportable: true,
      refreshable: true,
      drillDownEnabled: true,
      isPlaceholder: false,
    },
    sampleData: [
      { date: "2026-05-01", value: 870000 },
      { date: "2026-05-05", value: 892000 },
    ],
    linkedRoute: "/modules/inventory/report",
    futureQueryKey: "query.inventory.stockValueTrend",
    futureDashboardKey: "dashboard.inventory",
    futureReportBuilderKey: "report-builder.inventory.stockValue",
  },
  {
    key: "widget.procurement.pendingRequests",
    title: { zh: "待处理采购单", en: "Pending Requests" },
    description: { zh: "采购待处理数量与时长", en: "Pending procurement requests with aging." },
    widgetType: "table",
    status: "active",
    severity: "medium",
    size: "xl",
    source: {
      sourceModule: "procurement",
      sourcePage: "listing",
      sourceRoute: "/modules/procurement/listing",
      sourceComponent: "DataTable",
      sourceService: "ProcurementService",
      sourceRepository: "ProcurementRepository",
      sourceDataset: "demo.procurement.pendingRequests",
      dataSourceType: "mock",
      actionKey: "createPurchaseRequest",
      accessRuleKey: "access.procurement.listing",
      auditEventKey: "audit.action.createPurchaseRequest",
      workflowKey: "workflow.action.createPurchaseRequest",
      notificationKey: "notification.workflow.purchaseRequestCreated",
    },
    metrics: [
      { key: "pendingCount", label: { zh: "待处理数", en: "Pending Count" }, format: "count", sampleValue: 24, trendDirection: "flat" },
      { key: "avgAging", label: { zh: "平均等待", en: "Avg Aging" }, format: "duration", sampleValue: "18h", trendDirection: "up", severity: "medium" },
    ],
    dimensions: [
      { key: "supplier", label: { zh: "供应商", en: "Supplier" }, type: "supplier", sampleValue: "FreshNorth" },
      { key: "status", label: { zh: "状态", en: "Status" }, type: "status", sampleValue: "pending" },
    ],
    filters: [
      { key: "status", label: { zh: "状态", en: "Status" }, type: "status", required: false, defaultValue: "pending" },
      { key: "search", label: { zh: "搜索", en: "Search" }, type: "search", required: false },
    ],
    requirement: {
      permissionRequired: "procurement.view",
      roleRequired: "purchasing-manager",
      planRequired: "ops",
      auditRequired: true,
      exportable: true,
      refreshable: true,
      drillDownEnabled: true,
      isPlaceholder: false,
    },
    sampleData: [{ requestNo: "PR-2026-112", supplier: "FreshNorth", status: "pending", aging: "16h" }],
    linkedRoute: "/modules/procurement/listing",
    futureQueryKey: "query.procurement.pendingRequests",
    futureDashboardKey: "dashboard.procurement",
    futureReportBuilderKey: "report-builder.procurement.pendingRequests",
  },
  {
    key: "widget.procurement.receivingToday",
    title: { zh: "今日到货", en: "Receiving Today" },
    description: { zh: "今日到货进度摘要", en: "Daily receiving progress summary." },
    widgetType: "status-summary",
    status: "preview-only",
    severity: "low",
    size: "md",
    source: {
      sourceModule: "procurement",
      sourcePage: "dashboard",
      sourceRoute: "/modules/procurement/dashboard",
      sourceComponent: "StatusCard",
      sourceService: "ProcurementService",
      sourceRepository: "ProcurementRepository",
      sourceDataset: "demo.procurement.receivingToday",
      dataSourceType: "mock",
      actionKey: "approvePurchaseRequestPlaceholder",
      accessRuleKey: "access.procurement.module",
      auditEventKey: "audit.action.approvePurchaseRequestPlaceholder",
      workflowKey: "workflow.action.approvePurchaseRequestPlaceholder",
      notificationKey: "notification.workflow.purchaseApprovalNeeded",
    },
    metrics: [{ key: "receivedCount", label: { zh: "已到货", en: "Received" }, format: "count", sampleValue: 12, trendDirection: "up" }],
    dimensions: [{ key: "store", label: { zh: "门店", en: "Store" }, type: "store", sampleValue: "Central" }],
    filters: [{ key: "dateRange", label: { zh: "日期范围", en: "Date Range" }, type: "date-range", required: true, defaultValue: "today" }],
    requirement: {
      permissionRequired: "procurement.view",
      roleRequired: "purchasing-manager",
      planRequired: "ops",
      auditRequired: true,
      exportable: false,
      refreshable: false,
      drillDownEnabled: true,
      isPlaceholder: false,
    },
    sampleData: { receivedCount: 12, delayedCount: 3 },
    samplePreviewEnabled: true,
    futureQueryKey: "query.procurement.receivingToday",
    futureDashboardKey: "dashboard.procurement",
    futureReportBuilderKey: "report-builder.procurement.receivingToday",
    notes: { zh: "仅样例预览，不代表实时到货。", en: "Sample preview only; not real-time receiving data." },
  },
  {
    key: "widget.supplier.issueSummary",
    title: { zh: "供应商问题汇总", en: "Supplier Issue Summary" },
    description: { zh: "供应商异常与问题状态概览", en: "Supplier exceptions and issue status overview." },
    widgetType: "list",
    status: "active",
    severity: "medium",
    size: "lg",
    source: {
      sourceModule: "supplier",
      sourcePage: "issue",
      sourceRoute: "/modules/supplier/issue",
      sourceComponent: "IssueList",
      sourceService: "SupplierService",
      sourceRepository: "SupplierRepository",
      sourceDataset: "demo.supplier.issueSummary",
      dataSourceType: "mock",
      actionKey: "reviewSupplierPlaceholder",
      accessRuleKey: "access.supplier.module",
      auditEventKey: "audit.system.previewOnly",
      workflowKey: "workflow.manual.managerReview",
      notificationKey: "notification.manual.managerAlert",
    },
    metrics: [{ key: "openIssues", label: { zh: "待处理问题", en: "Open Issues" }, format: "count", sampleValue: 9, trendDirection: "flat", severity: "medium" }],
    dimensions: [{ key: "supplier", label: { zh: "供应商", en: "Supplier" }, type: "supplier", sampleValue: "BlueDelta" }],
    filters: [
      { key: "status", label: { zh: "状态", en: "Status" }, type: "status", required: false },
      { key: "supplier", label: { zh: "供应商", en: "Supplier" }, type: "select", required: false },
    ],
    requirement: {
      permissionRequired: "supplier.view",
      roleRequired: "supplier-coordinator",
      planRequired: "ops",
      auditRequired: true,
      exportable: false,
      refreshable: true,
      drillDownEnabled: true,
      isPlaceholder: false,
    },
    sampleData: [{ supplier: "BlueDelta", issue: "late delivery", status: "open" }],
    linkedRoute: "/modules/supplier/issue",
    futureQueryKey: "query.supplier.issueSummary",
    futureDashboardKey: "dashboard.procurement",
    futureReportBuilderKey: "report-builder.supplier.issueSummary",
  },
  {
    key: "widget.task.completionToday",
    title: { zh: "今日任务完成", en: "Task Completion Today" },
    description: { zh: "任务完成率摘要（元数据）", en: "Task completion ratio summary (metadata)." },
    widgetType: "task-summary",
    status: "active",
    severity: "low",
    size: "md",
    source: {
      sourceModule: "task",
      sourcePage: "dashboard",
      sourceRoute: "/tasks",
      sourceComponent: "TaskStatsRow",
      sourceService: "TaskService",
      sourceRepository: "TaskRepository",
      sourceDataset: "demo.task.completionToday",
      dataSourceType: "mock",
      actionKey: "assignTask",
      accessRuleKey: "access.task.board",
      auditEventKey: "audit.action.assignTask",
      workflowKey: "workflow.action.assignTask",
      notificationKey: "notification.workflow.taskAssigned",
    },
    metrics: [
      { key: "completionRate", label: { zh: "完成率", en: "Completion Rate" }, format: "percentage", sampleValue: 0.84, trendDirection: "up" },
      { key: "completedCount", label: { zh: "已完成", en: "Completed" }, format: "count", sampleValue: 126, trendDirection: "up" },
    ],
    dimensions: [{ key: "role", label: { zh: "角色", en: "Role" }, type: "role", sampleValue: "store-manager" }],
    filters: [
      { key: "role", label: { zh: "角色", en: "Role" }, type: "role", required: false },
      { key: "dateRange", label: { zh: "日期范围", en: "Date Range" }, type: "date-range", required: true, defaultValue: "today" },
    ],
    requirement: {
      permissionRequired: "task.view",
      roleRequired: "store-manager",
      planRequired: "starter",
      auditRequired: true,
      exportable: false,
      refreshable: true,
      drillDownEnabled: true,
      isPlaceholder: false,
    },
    sampleData: { completionRate: 0.84, completedCount: 126 },
    linkedRoute: "/tasks",
    futureQueryKey: "query.task.completionToday",
    futureDashboardKey: "dashboard.task-control",
    futureReportBuilderKey: "report-builder.task.completionToday",
  },
  {
    key: "widget.task.overdueTasks",
    title: { zh: "逾期任务", en: "Overdue Tasks" },
    description: { zh: "逾期任务清单（预览）", en: "Overdue task list (preview)." },
    widgetType: "table",
    status: "active",
    severity: "high",
    size: "lg",
    source: {
      sourceModule: "task",
      sourcePage: "listing",
      sourceRoute: "/tasks",
      sourceComponent: "TaskList",
      sourceService: "TaskService",
      sourceRepository: "TaskRepository",
      sourceDataset: "demo.task.overdue",
      dataSourceType: "mock",
      actionKey: "closeTask",
      accessRuleKey: "access.task.board",
      auditEventKey: "audit.action.closeTask",
      workflowKey: "workflow.action.closeTask",
      notificationKey: "notification.workflow.taskClosed",
    },
    metrics: [{ key: "overdueCount", label: { zh: "逾期数量", en: "Overdue Count" }, format: "count", sampleValue: 14, trendDirection: "up", severity: "high" }],
    dimensions: [{ key: "store", label: { zh: "门店", en: "Store" }, type: "store", sampleValue: "West Branch" }],
    filters: [
      { key: "status", label: { zh: "状态", en: "Status" }, type: "status", required: true, defaultValue: "overdue" },
      { key: "store", label: { zh: "门店", en: "Store" }, type: "store", required: false },
    ],
    requirement: {
      permissionRequired: "task.view",
      roleRequired: "store-manager",
      planRequired: "starter",
      auditRequired: true,
      exportable: true,
      refreshable: true,
      drillDownEnabled: true,
      isPlaceholder: false,
    },
    sampleData: [{ taskId: "TSK-2103", title: "Night checklist", overdueHours: 18 }],
    linkedRoute: "/tasks",
    futureQueryKey: "query.task.overdue",
    futureDashboardKey: "dashboard.task-control",
    futureReportBuilderKey: "report-builder.task.overdue",
  },
  {
    key: "widget.education.trainingCompletion",
    title: { zh: "培训完成进度", en: "Training Completion" },
    description: { zh: "培训课程完成进度占位", en: "Training completion placeholder." },
    widgetType: "trend",
    status: "placeholder",
    severity: "low",
    size: "md",
    source: {
      sourceModule: "education",
      sourcePage: "dashboard",
      sourceRoute: "/modules/education/dashboard",
      sourceComponent: "TrainingProgress",
      sourceService: "service.education.placeholder",
      sourceRepository: "repository.education.placeholder",
      sourceDataset: "education.progress.placeholder",
      dataSourceType: "service-placeholder",
      actionKey: "assignCoursePlaceholder",
      accessRuleKey: "access.education.module",
      workflowKey: "workflow.system.previewOnly",
      notificationKey: "notification.system.previewOnly",
    },
    metrics: [{ key: "completionRate", label: { zh: "完成率", en: "Completion Rate" }, format: "percentage", sampleValue: 0.62, trendDirection: "unknown" }],
    dimensions: [{ key: "role", label: { zh: "角色", en: "Role" }, type: "role", sampleValue: "staff" }],
    filters: [{ key: "module", label: { zh: "模块", en: "Module" }, type: "module", required: false, defaultValue: "education" }],
    requirement: {
      permissionRequired: "education.view",
      roleRequired: "store-manager",
      planRequired: "pro",
      auditRequired: false,
      exportable: false,
      refreshable: false,
      drillDownEnabled: false,
      isPlaceholder: true,
    },
    sampleData: [{ week: "W18", completionRate: 0.62 }],
    futureQueryKey: "query.education.trainingCompletion",
    futureDashboardKey: "dashboard.owner-overview",
    futureReportBuilderKey: "report-builder.education.trainingCompletion",
  },
  {
    key: "widget.workflow.triggerSummary",
    title: { zh: "工作流触发摘要", en: "Workflow Trigger Summary" },
    description: { zh: "工作流状态汇总", en: "Workflow status summary." },
    widgetType: "workflow-summary",
    status: "active",
    severity: "medium",
    size: "md",
    source: {
      sourceModule: "task",
      sourcePage: "workflow",
      sourceRoute: "/workflow",
      sourceComponent: "WorkflowPreviewCard",
      sourceService: "service.workflow.placeholder",
      sourceRepository: "repository.workflow.placeholder",
      sourceDataset: "workflow.contract.summary",
      dataSourceType: "service-placeholder",
      workflowKey: "workflow.action.assignTask",
      notificationKey: "notification.workflow.taskAssigned",
      auditEventKey: "audit.action.assignTask",
    },
    metrics: [
      { key: "activeWorkflowCount", label: { zh: "活跃工作流", en: "Active Workflows" }, format: "count", sampleValue: 4, trendDirection: "flat" },
      { key: "blockedWorkflowCount", label: { zh: "阻塞工作流", en: "Blocked Workflows" }, format: "count", sampleValue: 1, trendDirection: "down", severity: "medium" },
    ],
    dimensions: [{ key: "module", label: { zh: "模块", en: "Module" }, type: "module", sampleValue: "task" }],
    filters: [{ key: "status", label: { zh: "状态", en: "Status" }, type: "status", required: false }],
    requirement: {
      roleRequired: "operations-manager",
      planRequired: "ops",
      auditRequired: false,
      exportable: false,
      refreshable: true,
      drillDownEnabled: true,
      isPlaceholder: false,
    },
    sampleData: { activeWorkflowCount: 4, blockedWorkflowCount: 1 },
    linkedRoute: "/workflow",
    futureDashboardKey: "dashboard.owner-overview",
    futureReportBuilderKey: "report-builder.workflow.triggerSummary",
  },
  {
    key: "widget.notification.messageSummary",
    title: { zh: "消息汇总", en: "Message Summary" },
    description: { zh: "通知消息合同汇总", en: "Notification contract summary." },
    widgetType: "notification-summary",
    status: "active",
    severity: "low",
    size: "md",
    source: {
      sourceModule: "message",
      sourcePage: "notifications",
      sourceRoute: "/notifications",
      sourceComponent: "NotificationPreviewCard",
      sourceService: "service.notification.placeholder",
      sourceRepository: "repository.notification.placeholder",
      sourceDataset: "notification.contract.summary",
      dataSourceType: "service-placeholder",
      notificationKey: "notification.system.previewOnly",
      workflowKey: "workflow.system.previewOnly",
      auditEventKey: "audit.system.previewOnly",
    },
    metrics: [
      { key: "activeNotificationContracts", label: { zh: "启用合同", en: "Active Contracts" }, format: "count", sampleValue: 6 },
      { key: "placeholderNotificationContracts", label: { zh: "占位合同", en: "Placeholder Contracts" }, format: "count", sampleValue: 4 },
    ],
    dimensions: [{ key: "channel", label: { zh: "通道", en: "Channel" }, type: "custom", sampleValue: "in-app" }],
    filters: [{ key: "module", label: { zh: "模块", en: "Module" }, type: "module", required: false, defaultValue: "message" }],
    requirement: {
      roleRequired: "store-manager",
      planRequired: "starter",
      auditRequired: false,
      exportable: false,
      refreshable: true,
      drillDownEnabled: true,
      isPlaceholder: false,
    },
    sampleData: { active: 6, placeholder: 4 },
    linkedRoute: "/notifications",
    futureDashboardKey: "dashboard.owner-overview",
    futureReportBuilderKey: "report-builder.notification.messageSummary",
  },
  {
    key: "widget.audit.eventSummary",
    title: { zh: "审计事件汇总", en: "Audit Event Summary" },
    description: { zh: "审计事件合同统计", en: "Audit event contract statistics." },
    widgetType: "audit-summary",
    status: "active",
    severity: "medium",
    size: "md",
    source: {
      sourceModule: "task",
      sourcePage: "audit",
      sourceRoute: "/audit-trail",
      sourceComponent: "AuditPreviewCard",
      sourceService: "service.audit.placeholder",
      sourceRepository: "repository.audit.placeholder",
      sourceDataset: "audit.contract.summary",
      dataSourceType: "repository-placeholder",
      auditEventKey: "audit.system.previewOnly",
      workflowKey: "workflow.system.previewOnly",
      notificationKey: "notification.system.previewOnly",
    },
    metrics: [
      { key: "capturedLikeEvents", label: { zh: "可捕获预览事件", en: "Capturable Preview Events" }, format: "count", sampleValue: 8 },
      { key: "placeholderEvents", label: { zh: "占位事件", en: "Placeholder Events" }, format: "count", sampleValue: 4 },
    ],
    dimensions: [{ key: "severity", label: { zh: "严重级别", en: "Severity" }, type: "custom", sampleValue: "warning" }],
    filters: [{ key: "status", label: { zh: "状态", en: "Status" }, type: "status", required: false }],
    requirement: {
      roleRequired: "admin",
      planRequired: "ops",
      auditRequired: false,
      exportable: false,
      refreshable: true,
      drillDownEnabled: true,
      isPlaceholder: false,
    },
    sampleData: { capturedLikeEvents: 8, placeholderEvents: 4 },
    linkedRoute: "/audit-trail",
    futureDashboardKey: "dashboard.system-preview",
    futureReportBuilderKey: "report-builder.audit.eventSummary",
  },
  {
    key: "widget.system.previewOnly",
    title: { zh: "系统预览占位", en: "System Preview Placeholder" },
    description: {
      zh: "用于 dashboard/report builder 的占位组件，不连接真实数据或执行。",
      en: "Placeholder widget for dashboard/report builder without real data or execution.",
    },
    widgetType: "placeholder",
    status: "disabled",
    severity: "neutral",
    size: "sm",
    source: {
      sourceModule: "system",
      sourcePage: "reports",
      sourceRoute: "/reports",
      sourceComponent: "ReportWidgetPreviewCard",
      sourceService: "service.report.placeholder",
      sourceRepository: "repository.report.placeholder",
      sourceDataset: "system.preview.placeholder",
      dataSourceType: "external-placeholder",
      workflowKey: "workflow.system.previewOnly",
      notificationKey: "notification.system.previewOnly",
      auditEventKey: "audit.system.previewOnly",
    },
    metrics: [{ key: "placeholderMetric", label: { zh: "占位指标", en: "Placeholder Metric" }, format: "text", sampleValue: "N/A", trendDirection: "unknown" }],
    dimensions: [{ key: "module", label: { zh: "模块", en: "Module" }, type: "module", sampleValue: "system" }],
    filters: [{ key: "module", label: { zh: "模块", en: "Module" }, type: "module", required: false }],
    requirement: {
      auditRequired: false,
      exportable: false,
      refreshable: false,
      drillDownEnabled: false,
      isPlaceholder: true,
    },
    sampleData: { placeholder: true },
    futureDashboardKey: "dashboard.system-preview",
    futureReportBuilderKey: "report-builder.system.placeholder",
    notes: { zh: "仅用于元数据演示。", en: "For metadata demonstration only." },
  },
  {
    key: "widget.psi.procurementPendingRequests",
    title: { zh: "PSI 采购待处理请求", en: "PSI Procurement Pending Requests" },
    description: { zh: "PSI 采购待处理请求预览。", en: "PSI pending procurement request preview." },
    widgetType: "kpi",
    status: "preview-only",
    severity: "medium",
    size: "md",
    source: {
      sourceModule: "procurement",
      sourcePage: "psi-workspace",
      sourceRoute: "/psi/procurement",
      sourceComponent: "PsiReportWidgetCard",
      sourceService: "PsiProcurementService",
      sourceRepository: "PsiProcurementRepository",
      sourceDataset: "psi.procurement.pendingRequests",
      dataSourceType: "mock",
      accessRuleKey: "access.procurement.listing",
      auditEventKey: "audit.action.createPurchaseRequest",
      workflowKey: "workflow.action.createPurchaseRequest",
      notificationKey: "notification.workflow.purchaseRequestCreated",
    },
    metrics: [{ key: "pendingRequests", label: { zh: "待处理请求", en: "Pending Requests" }, format: "count", sampleValue: 12, trendDirection: "flat", severity: "medium" }],
    dimensions: [{ key: "status", label: { zh: "状态", en: "Status" }, type: "status", sampleValue: "pending" }],
    filters: [{ key: "status", label: { zh: "状态", en: "Status" }, type: "status", required: false, defaultValue: "pending" }],
    requirement: { permissionRequired: "procurement.view", roleRequired: "purchasing-manager", planRequired: "ops", auditRequired: true, exportable: false, refreshable: false, drillDownEnabled: true, isPlaceholder: false },
    sampleData: [{ requestNo: "PR-PSI-001", status: "pending" }],
    linkedRoute: "/psi/procurement",
    futureQueryKey: "query.psi.procurement.pendingRequests",
    futureDashboardKey: "dashboard.psi-overview",
    futureReportBuilderKey: "report-builder.psi.procurementPendingRequests",
    samplePreviewEnabled: true,
  },
  {
    key: "widget.psi.receivingToday",
    title: { zh: "PSI 到货状态", en: "PSI Receiving Today" },
    description: { zh: "PSI 采购到货状态预览。", en: "PSI receiving status preview." },
    widgetType: "status-summary",
    status: "preview-only",
    severity: "low",
    size: "md",
    source: {
      sourceModule: "procurement",
      sourcePage: "psi-workspace",
      sourceRoute: "/psi/procurement",
      sourceComponent: "PsiReportWidgetCard",
      sourceService: "PsiProcurementService",
      sourceRepository: "PsiProcurementRepository",
      sourceDataset: "psi.procurement.receivingToday",
      dataSourceType: "mock",
      accessRuleKey: "access.procurement.module",
      auditEventKey: "audit.action.approvePurchaseRequestPlaceholder",
      workflowKey: "workflow.action.approvePurchaseRequestPlaceholder",
      notificationKey: "notification.workflow.purchaseApprovalNeeded",
    },
    metrics: [{ key: "receivingToday", label: { zh: "今日到货", en: "Receiving Today" }, format: "count", sampleValue: 8, trendDirection: "up" }],
    dimensions: [{ key: "date", label: { zh: "日期", en: "Date" }, type: "date", sampleValue: "today" }],
    filters: [{ key: "dateRange", label: { zh: "日期范围", en: "Date Range" }, type: "date-range", required: true, defaultValue: "today" }],
    requirement: { permissionRequired: "procurement.view", roleRequired: "purchasing-manager", planRequired: "ops", auditRequired: true, exportable: false, refreshable: false, drillDownEnabled: true, isPlaceholder: false },
    sampleData: [{ receivingNo: "RCV-PSI-001", status: "pending" }],
    linkedRoute: "/psi/procurement",
    futureQueryKey: "query.psi.procurement.receivingToday",
    futureDashboardKey: "dashboard.psi-overview",
    futureReportBuilderKey: "report-builder.psi.receivingToday",
    samplePreviewEnabled: true,
  },
  {
    key: "widget.psi.supplierIssueSummary",
    title: { zh: "PSI 供应商问题汇总", en: "PSI Supplier Issue Summary" },
    description: { zh: "PSI 供应商问题汇总预览。", en: "PSI supplier issue summary preview." },
    widgetType: "list",
    status: "preview-only",
    severity: "medium",
    size: "md",
    source: {
      sourceModule: "supplier",
      sourcePage: "psi-workspace",
      sourceRoute: "/psi/supplier",
      sourceComponent: "PsiReportWidgetCard",
      sourceService: "PsiSupplierService",
      sourceRepository: "PsiSupplierRepository",
      sourceDataset: "psi.supplier.issueSummary",
      dataSourceType: "mock",
      accessRuleKey: "access.supplier.module",
      auditEventKey: "audit.system.previewOnly",
      workflowKey: "workflow.manual.managerReview",
      notificationKey: "notification.manual.managerAlert",
    },
    metrics: [{ key: "openIssues", label: { zh: "未关闭问题", en: "Open Issues" }, format: "count", sampleValue: 6, trendDirection: "flat", severity: "medium" }],
    dimensions: [{ key: "supplier", label: { zh: "供应商", en: "Supplier" }, type: "supplier", sampleValue: "SUP-001" }],
    filters: [{ key: "status", label: { zh: "状态", en: "Status" }, type: "status", required: false }],
    requirement: { permissionRequired: "supplier.view", roleRequired: "supplier-coordinator", planRequired: "ops", auditRequired: true, exportable: false, refreshable: false, drillDownEnabled: true, isPlaceholder: false },
    sampleData: [{ issueId: "SUP-ISS-001", status: "open" }],
    linkedRoute: "/psi/supplier",
    futureQueryKey: "query.psi.supplier.issueSummary",
    futureDashboardKey: "dashboard.psi-overview",
    futureReportBuilderKey: "report-builder.psi.supplierIssueSummary",
    samplePreviewEnabled: true,
  },
  {
    key: "widget.psi.supplierRatingPreview",
    title: { zh: "PSI 供应商评分预览", en: "PSI Supplier Rating Preview" },
    description: { zh: "PSI 供应商评分占位预览。", en: "PSI supplier rating placeholder preview." },
    widgetType: "kpi",
    status: "preview-only",
    severity: "low",
    size: "sm",
    source: {
      sourceModule: "supplier",
      sourcePage: "psi-workspace",
      sourceRoute: "/psi/supplier",
      sourceComponent: "PsiReportWidgetCard",
      sourceService: "PsiSupplierService",
      sourceRepository: "PsiSupplierRepository",
      sourceDataset: "psi.supplier.ratingPreview",
      dataSourceType: "mock",
      accessRuleKey: "access.supplier.module",
      auditEventKey: "audit.system.previewOnly",
      workflowKey: "workflow.manual.managerReview",
      notificationKey: "notification.manual.managerAlert",
    },
    metrics: [{ key: "averageScore", label: { zh: "平均评分", en: "Average Score" }, format: "number", sampleValue: 82, trendDirection: "flat", severity: "low" }],
    dimensions: [{ key: "period", label: { zh: "周期", en: "Period" }, type: "date", sampleValue: "2026-Q2" }],
    filters: [{ key: "dateRange", label: { zh: "周期", en: "Period" }, type: "date-range", required: false }],
    requirement: { permissionRequired: "supplier.view", roleRequired: "supplier-coordinator", planRequired: "ops", auditRequired: true, exportable: false, refreshable: false, drillDownEnabled: false, isPlaceholder: true },
    sampleData: [{ supplierId: "SUP-001", score: 86 }],
    linkedRoute: "/psi/supplier",
    futureQueryKey: "query.psi.supplier.ratingPreview",
    futureDashboardKey: "dashboard.psi-overview",
    futureReportBuilderKey: "report-builder.psi.supplierRatingPreview",
    samplePreviewEnabled: true,
  },
  {
    key: "widget.psi.inventoryLowStockRisk",
    title: { zh: "PSI 低库存风险", en: "PSI Inventory Low-Stock Risk" },
    description: { zh: "PSI 低库存风险预览。", en: "PSI low-stock risk preview." },
    widgetType: "distribution",
    status: "preview-only",
    severity: "high",
    size: "md",
    source: {
      sourceModule: "inventory",
      sourcePage: "psi-workspace",
      sourceRoute: "/psi/inventory",
      sourceComponent: "PsiReportWidgetCard",
      sourceService: "PsiInventoryService",
      sourceRepository: "PsiInventoryRepository",
      sourceDataset: "psi.inventory.lowStockRisk",
      dataSourceType: "mock",
      accessRuleKey: "access.inventory.detail",
      auditEventKey: "audit.access.inventory.detail",
      workflowKey: "workflow.audit.inventoryDetailPreview",
      notificationKey: "notification.audit.inventoryDetailPreview",
    },
    metrics: [{ key: "lowStockSkus", label: { zh: "低库存 SKU", en: "Low-Stock SKUs" }, format: "count", sampleValue: 10, trendDirection: "up", severity: "high" }],
    dimensions: [{ key: "sku", label: { zh: "SKU", en: "SKU" }, type: "sku", sampleValue: "SKU-001" }],
    filters: [{ key: "status", label: { zh: "风险状态", en: "Risk Status" }, type: "status", required: false }],
    requirement: { permissionRequired: "inventory.view", roleRequired: "warehouse-handler", planRequired: "ops", auditRequired: true, exportable: false, refreshable: false, drillDownEnabled: true, isPlaceholder: false },
    sampleData: [{ skuId: "SKU-001", risk: "high" }],
    linkedRoute: "/psi/inventory",
    futureQueryKey: "query.psi.inventory.lowStockRisk",
    futureDashboardKey: "dashboard.psi-overview",
    futureReportBuilderKey: "report-builder.psi.inventoryLowStockRisk",
    samplePreviewEnabled: true,
  },
  {
    key: "widget.psi.inventoryStockValue",
    title: { zh: "PSI 库存价值预览", en: "PSI Inventory Stock Value" },
    description: { zh: "PSI 库存价值预览占位。", en: "PSI stock value placeholder preview." },
    widgetType: "trend",
    status: "preview-only",
    severity: "neutral",
    size: "md",
    source: {
      sourceModule: "inventory",
      sourcePage: "psi-workspace",
      sourceRoute: "/psi/inventory",
      sourceComponent: "PsiReportWidgetCard",
      sourceService: "PsiInventoryService",
      sourceRepository: "PsiInventoryRepository",
      sourceDataset: "psi.inventory.stockValue",
      dataSourceType: "mock",
      accessRuleKey: "access.inventory.detail",
      auditEventKey: "audit.access.inventory.detail",
      workflowKey: "workflow.audit.inventoryDetailPreview",
      notificationKey: "notification.audit.inventoryDetailPreview",
    },
    metrics: [{ key: "estimatedStockValue", label: { zh: "库存价值", en: "Stock Value" }, format: "currency", sampleValue: 120000, trendDirection: "up" }],
    dimensions: [{ key: "warehouse", label: { zh: "仓库", en: "Warehouse" }, type: "store", sampleValue: "WH-01" }],
    filters: [{ key: "dateRange", label: { zh: "日期范围", en: "Date Range" }, type: "date-range", required: false }],
    requirement: { permissionRequired: "inventory.view", roleRequired: "warehouse-handler", planRequired: "ops", auditRequired: true, exportable: false, refreshable: false, drillDownEnabled: false, isPlaceholder: true },
    sampleData: [{ warehouseId: "WH-01", value: 120000 }],
    linkedRoute: "/psi/inventory",
    futureQueryKey: "query.psi.inventory.stockValue",
    futureDashboardKey: "dashboard.psi-overview",
    futureReportBuilderKey: "report-builder.psi.inventoryStockValue",
    samplePreviewEnabled: true,
  },
  {
    key: "widget.psi.replenishmentSuggestions",
    title: { zh: "PSI 补货建议汇总", en: "PSI Replenishment Suggestions" },
    description: { zh: "PSI 补货建议汇总预览。", en: "PSI replenishment suggestion summary preview." },
    widgetType: "table",
    status: "preview-only",
    severity: "medium",
    size: "md",
    source: {
      sourceModule: "inventory",
      sourcePage: "psi-workspace",
      sourceRoute: "/psi/inventory",
      sourceComponent: "PsiReportWidgetCard",
      sourceService: "PsiInventoryService",
      sourceRepository: "PsiInventoryRepository",
      sourceDataset: "psi.inventory.replenishmentSuggestions",
      dataSourceType: "mock",
      accessRuleKey: "access.inventory.detail",
      auditEventKey: "audit.access.inventory.detail",
      workflowKey: "workflow.audit.inventoryDetailPreview",
      notificationKey: "notification.audit.inventoryDetailPreview",
    },
    metrics: [{ key: "pendingSuggestions", label: { zh: "待处理建议", en: "Pending Suggestions" }, format: "count", sampleValue: 5, trendDirection: "flat", severity: "medium" }],
    dimensions: [{ key: "sku", label: { zh: "SKU", en: "SKU" }, type: "sku", sampleValue: "SKU-001" }],
    filters: [{ key: "status", label: { zh: "状态", en: "Status" }, type: "status", required: false }],
    requirement: { permissionRequired: "inventory.view", roleRequired: "warehouse-handler", planRequired: "ops", auditRequired: true, exportable: false, refreshable: false, drillDownEnabled: true, isPlaceholder: false },
    sampleData: [{ suggestionId: "RPL-001", status: "pending" }],
    linkedRoute: "/psi/inventory",
    futureQueryKey: "query.psi.inventory.replenishmentSuggestions",
    futureDashboardKey: "dashboard.psi-overview",
    futureReportBuilderKey: "report-builder.psi.replenishmentSuggestions",
    samplePreviewEnabled: true,
  },
  {
    key: "widget.psi.issueSummary",
    title: { zh: "PSI 问题总览", en: "PSI Issue Summary" },
    description: { zh: "PSI 跨模块问题汇总预览。", en: "PSI cross-module issue summary preview." },
    widgetType: "list",
    status: "preview-only",
    severity: "medium",
    size: "md",
    source: {
      sourceModule: "psi",
      sourcePage: "issues",
      sourceRoute: "/psi/issues",
      sourceComponent: "PsiReportWidgetCard",
      sourceService: "PsiIssuesPageData",
      sourceRepository: "PsiIssueRepositoryPlaceholder",
      sourceDataset: "psi.issues.summary",
      dataSourceType: "mock",
      accessRuleKey: "access.procurement.listing",
      auditEventKey: "audit.system.previewOnly",
      workflowKey: "workflow.system.previewOnly",
      notificationKey: "notification.system.previewOnly",
    },
    metrics: [{ key: "totalIssues", label: { zh: "问题总数", en: "Total Issues" }, format: "count", sampleValue: 14, trendDirection: "flat", severity: "medium" }],
    dimensions: [{ key: "module", label: { zh: "模块", en: "Module" }, type: "module", sampleValue: "psi" }],
    filters: [{ key: "module", label: { zh: "模块", en: "Module" }, type: "module", required: false }],
    requirement: { roleRequired: "operations-manager", planRequired: "ops", auditRequired: true, exportable: false, refreshable: false, drillDownEnabled: true, isPlaceholder: false },
    sampleData: [{ issueId: "PSI-ISS-001", moduleCode: "procurement" }],
    linkedRoute: "/psi/issues",
    futureQueryKey: "query.psi.issueSummary",
    futureDashboardKey: "dashboard.psi-overview",
    futureReportBuilderKey: "report-builder.psi.issueSummary",
    samplePreviewEnabled: true,
  },
  {
    key: "widget.psi.lifecycleSummary",
    title: { zh: "PSI 生命周期摘要", en: "PSI Lifecycle Summary" },
    description: { zh: "PSI 生命周期阶段分布预览。", en: "PSI lifecycle stage distribution preview." },
    widgetType: "status-summary",
    status: "preview-only",
    severity: "low",
    size: "md",
    source: {
      sourceModule: "psi",
      sourcePage: "issues",
      sourceRoute: "/psi/issues",
      sourceComponent: "PsiReportWidgetCard",
      sourceService: "PsiIssuesPageData",
      sourceRepository: "PsiIssueRepositoryPlaceholder",
      sourceDataset: "psi.issues.lifecycleSummary",
      dataSourceType: "mock",
      accessRuleKey: "access.procurement.listing",
      auditEventKey: "audit.system.previewOnly",
      workflowKey: "workflow.system.previewOnly",
      notificationKey: "notification.system.previewOnly",
    },
    metrics: [{ key: "lifecycleStages", label: { zh: "生命周期阶段", en: "Lifecycle Stages" }, format: "count", sampleValue: 4, trendDirection: "flat" }],
    dimensions: [{ key: "status", label: { zh: "阶段", en: "Stage" }, type: "status", sampleValue: "open" }],
    filters: [{ key: "status", label: { zh: "状态", en: "Status" }, type: "status", required: false }],
    requirement: { roleRequired: "operations-manager", planRequired: "ops", auditRequired: true, exportable: false, refreshable: false, drillDownEnabled: true, isPlaceholder: false },
    sampleData: [{ stage: "open", count: 3 }],
    linkedRoute: "/psi/issues",
    futureQueryKey: "query.psi.lifecycleSummary",
    futureDashboardKey: "dashboard.psi-overview",
    futureReportBuilderKey: "report-builder.psi.lifecycleSummary",
    samplePreviewEnabled: true,
  },
  {
    key: "widget.psi.healthScore",
    title: { zh: "PSI 健康评分占位", en: "PSI Health Score Placeholder" },
    description: { zh: "PSI 健康评分占位预览。", en: "PSI health score placeholder preview." },
    widgetType: "kpi",
    status: "preview-only",
    severity: "low",
    size: "sm",
    source: {
      sourceModule: "psi",
      sourcePage: "reports",
      sourceRoute: "/reports",
      sourceComponent: "PsiReportWidgetCard",
      sourceService: "PsiHealthScoreServicePlaceholder",
      sourceRepository: "PsiHealthScoreRepositoryPlaceholder",
      sourceDataset: "psi.healthScore.placeholder",
      dataSourceType: "service-placeholder",
      workflowKey: "workflow.system.previewOnly",
      notificationKey: "notification.system.previewOnly",
      auditEventKey: "audit.system.previewOnly",
    },
    metrics: [{ key: "healthScore", label: { zh: "健康评分", en: "Health Score" }, format: "number", sampleValue: 78, trendDirection: "unknown" }],
    dimensions: [{ key: "module", label: { zh: "模块", en: "Module" }, type: "module", sampleValue: "psi" }],
    filters: [{ key: "module", label: { zh: "模块", en: "Module" }, type: "module", required: false, defaultValue: "psi" }],
    requirement: { roleRequired: "operations-manager", planRequired: "ops", auditRequired: false, exportable: false, refreshable: false, drillDownEnabled: false, isPlaceholder: true },
    sampleData: [{ score: 78, source: "mock" }],
    linkedRoute: "/reports",
    futureQueryKey: "query.psi.healthScore",
    futureDashboardKey: "dashboard.psi-overview",
    futureReportBuilderKey: "report-builder.psi.healthScore",
    samplePreviewEnabled: true,
    notes: { zh: "仅为健康评分占位，不执行真实计算。", en: "Health score placeholder only; no real calculation is executed." },
  },
];

export const reportWidgetRegistryByKey: Record<string, ReportWidgetContract> = Object.fromEntries(
  reportWidgetRegistry.map((item) => [item.key, item]),
);
