import type { PackageContract } from "@/types/package";

const t = (zh: string, en: string) => ({ zh, en });

export const packageContracts: PackageContract[] = [
  {
    key: "package.plan.starter",
    name: t("ME 入门方案", "ME Starter Plan"),
    description: t("面向基础门店执行场景的起步方案。", "Starter package for baseline store execution scenarios."),
    category: "base-plan",
    tier: "starter",
    status: "active",
    billingMode: "monthly-placeholder",
    modules: ["task", "message"],
    features: [
      { featureType: "module", key: "task", label: t("任务模块", "Task Module"), required: true, status: "active" },
      { featureType: "action", key: "openTasks", label: t("任务入口动作", "Task Entry Action"), required: true, status: "active" },
      { featureType: "report-widget", key: "report.task.pendingSummary", label: t("任务看板组件", "Task Summary Widget"), required: false, status: "preview-only" },
    ],
    limits: [
      { key: "stores", label: t("门店数量", "Store Count"), value: 5, unit: t("家", "stores"), isPlaceholder: true },
      { key: "active-users", label: t("活跃用户", "Active Users"), value: 30, unit: t("人", "users"), isPlaceholder: true },
    ],
    requirement: {
      targetTier: "starter",
      targetPlan: "starter",
      targetRole: "store-manager",
      targetCustomer: t("单店与小型连锁", "Single-store and small chain operations"),
      requiredModules: ["task"],
      billingMode: "monthly-placeholder",
      auditRequired: false,
      isPlaceholder: true,
    },
    recommendedRoles: ["store-manager", "staff"],
    recommendedSkins: ["classic", "compact"],
    recommendedDashboards: ["layout.dashboard.owner.overview"],
    linkedRoute: "/tasks",
    futureBillingKey: "billing.plan.starter",
    futureSubscriptionKey: "subscription.plan.starter",
    futureProvisioningKey: "provisioning.plan.starter",
  },
  {
    key: "package.plan.ops",
    name: t("ME 运营方案", "ME Operations Plan"),
    description: t("覆盖采购、库存、供应商和任务协同的运营方案。", "Operations package across procurement, inventory, supplier, and task collaboration."),
    category: "base-plan",
    tier: "ops",
    status: "active",
    billingMode: "monthly-placeholder",
    modules: ["procurement", "inventory", "supplier", "task", "message"],
    features: [
      { featureType: "module", key: "procurement", label: t("采购模块", "Procurement Module"), required: true, status: "active" },
      { featureType: "module", key: "inventory", label: t("库存模块", "Inventory Module"), required: true, status: "active" },
      { featureType: "module", key: "supplier", label: t("供应商模块", "Supplier Module"), required: true, status: "active" },
      { featureType: "workflow", key: "workflow.procurement.overdueReceiving", label: t("采购逾期流程", "Procurement Overdue Workflow"), required: false, status: "active" },
      { featureType: "rule", key: "rule.inventory.lowStockRisk", label: t("低库存风险规则", "Low Stock Risk Rule"), required: false, status: "active" },
    ],
    limits: [
      { key: "stores", label: t("门店数量", "Store Count"), value: 20, unit: t("家", "stores"), isPlaceholder: true },
      { key: "tasks-per-month", label: t("每月任务量", "Tasks Per Month"), value: 5000, unit: t("条", "items"), isPlaceholder: true },
    ],
    requirement: {
      targetTier: "ops",
      targetPlan: "ops",
      targetRole: "operations-manager",
      targetCustomer: t("多门店运营团队", "Multi-store operations teams"),
      requiredModules: ["procurement", "inventory", "supplier"],
      requiredPermissions: ["procurement.view", "inventory.view", "supplier.view"],
      billingMode: "monthly-placeholder",
      auditRequired: true,
      isPlaceholder: true,
    },
    recommendedRoles: ["operations-manager", "warehouse-handler", "purchasing-manager"],
    recommendedSkins: ["classic", "dark"],
    recommendedDashboards: ["layout.dashboard.ops.overview"],
    linkedRoute: "/modules",
    futureBillingKey: "billing.plan.ops",
    futureSubscriptionKey: "subscription.plan.ops",
    futureProvisioningKey: "provisioning.plan.ops",
  },
  {
    key: "package.plan.pro",
    name: t("ME 专业方案", "ME Pro Plan"),
    description: t("增加报表、工作流与规则预览能力的专业方案。", "Professional package with reporting, workflow, and rule preview capabilities."),
    category: "base-plan",
    tier: "pro",
    status: "active",
    billingMode: "yearly-placeholder",
    modules: ["procurement", "inventory", "supplier", "task", "report-builder", "message", "pos-report", "education"],
    features: [
      { featureType: "report-widget", key: "report.owner.dashboardHealthScore", label: t("老板看板健康分", "Owner Dashboard Health Score"), required: false, status: "active" },
      { featureType: "workflow", key: "workflow.action.createPurchaseRequest", label: t("审批触发流程", "Approval Trigger Workflow"), required: false, status: "active" },
      { featureType: "notification", key: "notification.system.previewOnly", label: t("系统通知占位", "System Notification Placeholder"), required: false, status: "preview-only" },
      { featureType: "rule", key: "rule.report.ownerDashboardHealthScore", label: t("健康分规则", "Health Score Rule"), required: false, status: "active" },
    ],
    limits: [
      { key: "stores", label: t("门店数量", "Store Count"), value: 100, unit: t("家", "stores"), isPlaceholder: true },
      { key: "dashboards", label: t("可用看板数", "Dashboard Count"), value: 30, unit: t("个", "dashboards"), isPlaceholder: true },
    ],
    requirement: {
      targetTier: "pro",
      targetPlan: "pro",
      targetRole: "operations-manager",
      targetCustomer: t("成长型连锁企业", "Growing chain businesses"),
      requiredModules: ["report-builder", "workflow"],
      billingMode: "yearly-placeholder",
      auditRequired: true,
      isPlaceholder: true,
    },
    recommendedRoles: ["operations-manager", "owner", "regional-manager"],
    recommendedSkins: ["classic", "moon"],
    recommendedDashboards: ["layout.dashboard.owner.overview", "layout.dashboard.ops.overview"],
    linkedRoute: "/reports",
    futureBillingKey: "billing.plan.pro",
    futureSubscriptionKey: "subscription.plan.pro",
    futureProvisioningKey: "provisioning.plan.pro",
  },
  {
    key: "package.plan.enterprise",
    name: t("ME 企业方案", "ME Enterprise Plan"),
    description: t("面向大型组织的企业级占位方案，包含高级扩展映射。", "Enterprise placeholder plan for large organizations with advanced extension mapping."),
    category: "enterprise",
    tier: "enterprise",
    status: "active",
    billingMode: "custom-placeholder",
    modules: ["procurement", "inventory", "supplier", "task", "report-builder", "api-center", "automation-center", "rule-center", "formula-center"],
    features: [
      { featureType: "service", key: "service.enterprise.accountManager", label: t("企业客户经理", "Enterprise Account Manager"), required: false, status: "preview-only" },
      { featureType: "support", key: "support.enterprise.sla", label: t("企业支持 SLA", "Enterprise Support SLA"), required: false, status: "preview-only" },
      { featureType: "layout-skin", key: "moon", label: t("Moon 皮肤", "Moon Skin"), required: false, status: "active" },
      { featureType: "placeholder", key: "feature.enterprise.runtime-gating", label: t("运行时方案门禁占位", "Runtime Plan Guard Placeholder"), required: false, status: "placeholder" },
    ],
    limits: [
      { key: "stores", label: t("门店数量", "Store Count"), value: "unlimited-placeholder", isPlaceholder: true },
      { key: "integrations", label: t("集成数量", "Integration Count"), value: "custom-placeholder", isPlaceholder: true },
    ],
    requirement: {
      targetTier: "enterprise",
      targetPlan: "enterprise",
      targetRole: "admin",
      targetCustomer: t("大型集团与多区域组织", "Large groups and multi-region organizations"),
      billingMode: "custom-placeholder",
      auditRequired: true,
      isPlaceholder: true,
    },
    recommendedRoles: ["owner", "admin", "operations-manager"],
    recommendedSkins: ["moon", "dark"],
    recommendedDashboards: ["layout.dashboard.enterprise.command"],
    linkedRoute: "/modules",
    futureBillingKey: "billing.plan.enterprise",
    futureSubscriptionKey: "subscription.plan.enterprise",
    futureProvisioningKey: "provisioning.plan.enterprise",
  },
  {
    key: "package.pack.procurement",
    name: t("ME 采购扩展包", "ME Procurement Pack"),
    category: "module-pack",
    tier: "ops",
    status: "active",
    billingMode: "per-store-placeholder",
    modules: ["procurement", "approval"],
    features: [
      { featureType: "action", key: "createPurchaseRequest", label: t("创建采购申请", "Create Purchase Request"), required: true, status: "active" },
      { featureType: "workflow", key: "workflow.procurement.approvalReminder", label: t("采购审批提醒流程", "Procurement Approval Reminder"), required: false, status: "active" },
      { featureType: "notification", key: "notification.procurement.approvalReminder", label: t("采购审批提醒通知", "Procurement Approval Reminder Notification"), required: false, status: "active" },
    ],
    limits: [{ key: "approval-lanes", label: t("审批层级", "Approval Lanes"), value: 6, unit: t("层", "levels"), isPlaceholder: true }],
    requirement: {
      targetTier: "ops",
      targetRole: "purchasing-manager",
      requiredModules: ["procurement"],
      billingMode: "per-store-placeholder",
      auditRequired: true,
      isPlaceholder: true,
    },
    recommendedRoles: ["purchasing-manager", "operations-manager"],
    recommendedSkins: ["classic"],
    recommendedDashboards: ["layout.dashboard.procurement.overview"],
    linkedRoute: "/modules/procurement/listing",
    futureBillingKey: "billing.pack.procurement",
    futureSubscriptionKey: "subscription.pack.procurement",
  },
  {
    key: "package.pack.inventory",
    name: t("ME 库存扩展包", "ME Inventory Pack"),
    category: "module-pack",
    tier: "ops",
    status: "active",
    billingMode: "per-store-placeholder",
    modules: ["inventory"],
    features: [
      { featureType: "rule", key: "rule.inventory.lowStockRisk", label: t("低库存风险规则", "Low Stock Risk Rule"), required: false, status: "active" },
      { featureType: "report-widget", key: "report.inventory.lowStockAlert", label: t("低库存预警组件", "Low Stock Alert Widget"), required: false, status: "active" },
      { featureType: "audit-event", key: "audit.access.inventory.module", label: t("库存访问审计", "Inventory Access Audit"), required: false, status: "active" },
    ],
    limits: [{ key: "warehouses", label: t("仓库数量", "Warehouse Count"), value: 10, unit: t("个", "warehouses"), isPlaceholder: true }],
    requirement: {
      targetTier: "ops",
      targetRole: "warehouse-handler",
      requiredModules: ["inventory"],
      billingMode: "per-store-placeholder",
      auditRequired: true,
      isPlaceholder: true,
    },
    recommendedRoles: ["warehouse-handler", "operations-manager"],
    recommendedSkins: ["classic", "compact"],
    recommendedDashboards: ["layout.dashboard.inventory.control"],
    linkedRoute: "/modules/inventory/listing",
    futureBillingKey: "billing.pack.inventory",
    futureSubscriptionKey: "subscription.pack.inventory",
  },
  {
    key: "package.pack.supplier",
    name: t("ME 供应商扩展包", "ME Supplier Pack"),
    category: "module-pack",
    tier: "ops",
    status: "active",
    billingMode: "per-store-placeholder",
    modules: ["supplier"],
    features: [
      { featureType: "rule", key: "rule.supplier.issueSeverity", label: t("供应商问题严重性", "Supplier Issue Severity"), required: false, status: "active" },
      { featureType: "access-rule", key: "access.supplier.module", label: t("供应商模块权限", "Supplier Module Access Rule"), required: false, status: "active" },
      { featureType: "audit-event", key: "audit.access.supplier.module", label: t("供应商访问审计", "Supplier Access Audit"), required: false, status: "active" },
    ],
    limits: [{ key: "suppliers", label: t("供应商数量", "Supplier Count"), value: 300, unit: t("家", "suppliers"), isPlaceholder: true }],
    requirement: {
      targetTier: "ops",
      targetRole: "supplier-coordinator",
      requiredModules: ["supplier"],
      billingMode: "per-store-placeholder",
      auditRequired: true,
      isPlaceholder: true,
    },
    recommendedRoles: ["supplier-coordinator", "purchasing-manager"],
    recommendedSkins: ["classic"],
    recommendedDashboards: ["layout.dashboard.supplier.quality"],
    linkedRoute: "/modules/supplier/listing",
    futureBillingKey: "billing.pack.supplier",
    futureSubscriptionKey: "subscription.pack.supplier",
  },
  {
    key: "package.pack.task-control",
    name: t("ME 任务管控包", "ME Task Control Pack"),
    category: "module-pack",
    tier: "starter",
    status: "active",
    billingMode: "per-user-placeholder",
    modules: ["task", "message"],
    features: [
      { featureType: "rule", key: "rule.task.overdueSla", label: t("任务逾期 SLA", "Task Overdue SLA"), required: false, status: "active" },
      { featureType: "notification", key: "notification.task.overdueReminder", label: t("任务逾期提醒", "Task Overdue Reminder"), required: false, status: "active" },
      { featureType: "workflow", key: "workflow.task.overdueEscalation", label: t("任务逾期升级流程", "Task Overdue Escalation"), required: false, status: "active" },
    ],
    limits: [{ key: "tasks", label: t("任务上限", "Task Limit"), value: 10000, unit: t("条", "tasks"), isPlaceholder: true }],
    requirement: {
      targetTier: "starter",
      targetRole: "store-manager",
      requiredModules: ["task"],
      billingMode: "per-user-placeholder",
      auditRequired: true,
      isPlaceholder: true,
    },
    recommendedRoles: ["store-manager", "staff"],
    recommendedSkins: ["compact", "classic"],
    recommendedDashboards: ["layout.dashboard.task.control"],
    linkedRoute: "/tasks",
    futureBillingKey: "billing.pack.task-control",
    futureSubscriptionKey: "subscription.pack.task-control",
  },
  {
    key: "package.pack.education",
    name: t("ME 培训成长包", "ME Education Pack"),
    category: "industry-pack",
    tier: "pro",
    status: "preview-only",
    billingMode: "per-user-placeholder",
    modules: ["education"],
    features: [
      { featureType: "rule", key: "rule.education.trainingCompletionRate", label: t("培训完成率规则", "Training Completion Rate Rule"), required: false, status: "preview-only" },
      { featureType: "report-widget", key: "report.education.trainingCompletion", label: t("培训完成率组件", "Training Completion Widget"), required: false, status: "preview-only" },
    ],
    limits: [{ key: "learners", label: t("学员数量", "Learner Count"), value: 500, unit: t("人", "learners"), isPlaceholder: true }],
    requirement: {
      targetTier: "pro",
      targetRole: "training-manager",
      requiredModules: ["education"],
      billingMode: "per-user-placeholder",
      auditRequired: false,
      isPlaceholder: true,
    },
    recommendedRoles: ["training-manager", "store-manager"],
    recommendedSkins: ["classic"],
    recommendedDashboards: ["layout.dashboard.training.progress"],
    linkedRoute: "/modules/education/dashboard",
    futureBillingKey: "billing.pack.education",
    futureSubscriptionKey: "subscription.pack.education",
  },
  {
    key: "package.pack.pos-report",
    name: t("ME POS 报表包", "ME POS Report Pack"),
    category: "module-pack",
    tier: "pro",
    status: "coming-soon",
    billingMode: "per-store-placeholder",
    modules: ["pos-report", "report-builder"],
    features: [
      { featureType: "rule", key: "rule.pos.refundAlert", label: t("退款告警规则", "Refund Alert Rule"), required: false, status: "active" },
      { featureType: "rule", key: "rule.pos.salesDropWarning", label: t("销售下滑预警", "Sales Drop Warning"), required: false, status: "coming-soon" },
      { featureType: "report-widget", key: "report.pos.salesTrend", label: t("销售趋势组件", "Sales Trend Widget"), required: false, status: "coming-soon" },
    ],
    limits: [{ key: "history-months", label: t("历史月份", "History Months"), value: 24, unit: t("月", "months"), isPlaceholder: true }],
    requirement: {
      targetTier: "pro",
      targetRole: "operations-analyst",
      requiredModules: ["pos-report"],
      billingMode: "per-store-placeholder",
      auditRequired: false,
      isPlaceholder: true,
    },
    recommendedRoles: ["operations-analyst", "owner"],
    recommendedSkins: ["dark", "moon"],
    recommendedDashboards: ["layout.dashboard.pos.performance"],
    linkedRoute: "/modules/pos-report/report",
    futureBillingKey: "billing.pack.pos-report",
    futureSubscriptionKey: "subscription.pack.pos-report",
  },
  {
    key: "package.pack.manager-workspace",
    name: t("ME 管理者工作台包", "ME Manager Workspace Pack"),
    category: "role-pack",
    tier: "ops",
    status: "active",
    billingMode: "none",
    modules: ["task", "report-builder", "message"],
    features: [
      { featureType: "layout-skin", key: "dark", label: t("Dark 皮肤", "Dark Skin"), required: false, status: "active" },
      { featureType: "page-template", key: "dashboard-layout", label: t("看板模板", "Dashboard Template"), required: false, status: "active" },
      { featureType: "support", key: "support.workspace.manager-guide", label: t("管理者指南", "Manager Guide"), required: false, status: "preview-only" },
    ],
    limits: [{ key: "saved-views", label: t("保存视图数", "Saved Views"), value: 20, unit: t("个", "views"), isPlaceholder: true }],
    requirement: {
      targetTier: "ops",
      targetRole: "operations-manager",
      billingMode: "none",
      auditRequired: false,
      isPlaceholder: true,
    },
    recommendedRoles: ["operations-manager", "regional-manager"],
    recommendedSkins: ["dark", "moon"],
    recommendedDashboards: ["layout.dashboard.manager.workspace"],
    linkedRoute: "/layout-engine",
  },
  {
    key: "package.addon.layout-engine",
    name: t("ME 布局引擎附加包", "ME Layout Engine Add-on"),
    category: "add-on",
    tier: "pro",
    status: "active",
    billingMode: "yearly-placeholder",
    modules: ["report-builder"],
    features: [
      { featureType: "layout-skin", key: "classic", label: t("Classic 皮肤", "Classic Skin"), required: false, status: "active" },
      { featureType: "layout-skin", key: "moon", label: t("Moon 皮肤", "Moon Skin"), required: false, status: "active" },
      { featureType: "page-template", key: "report-layout", label: t("报表模板", "Report Template"), required: false, status: "active" },
    ],
    limits: [{ key: "custom-layouts", label: t("自定义布局数", "Custom Layouts"), value: 12, unit: t("个", "layouts"), isPlaceholder: true }],
    requirement: {
      targetTier: "pro",
      targetRole: "operations-analyst",
      billingMode: "yearly-placeholder",
      auditRequired: false,
      isPlaceholder: true,
    },
    recommendedRoles: ["operations-analyst"],
    recommendedSkins: ["classic", "moon"],
    recommendedDashboards: ["layout.dashboard.builder.preview"],
    linkedRoute: "/layout-engine",
    futureBillingKey: "billing.addon.layout-engine",
    futureSubscriptionKey: "subscription.addon.layout-engine",
  },
  {
    key: "package.addon.report-builder",
    name: t("ME 报表构建附加包", "ME Report Builder Add-on"),
    category: "add-on",
    tier: "pro",
    status: "preview-only",
    billingMode: "yearly-placeholder",
    modules: ["report-builder", "pos-report"],
    features: [
      { featureType: "report-widget", key: "report.owner.dashboardHealthScore", label: t("健康分组件", "Health Score Widget"), required: false, status: "active" },
      { featureType: "service", key: "service.report.builder.preview", label: t("报表构建服务占位", "Report Builder Service Placeholder"), required: false, status: "preview-only" },
    ],
    limits: [{ key: "widgets", label: t("组件数量", "Widget Count"), value: 100, unit: t("个", "widgets"), isPlaceholder: true }],
    requirement: {
      targetTier: "pro",
      targetRole: "operations-analyst",
      billingMode: "yearly-placeholder",
      auditRequired: false,
      isPlaceholder: true,
    },
    recommendedRoles: ["operations-analyst", "owner"],
    recommendedSkins: ["classic", "dark"],
    recommendedDashboards: ["layout.dashboard.reporting.builder"],
    linkedRoute: "/reports",
    samplePreviewEnabled: true,
    futureBillingKey: "billing.addon.report-builder",
    futureSubscriptionKey: "subscription.addon.report-builder",
  },
  {
    key: "package.addon.rules-preview",
    name: t("ME 规则预览附加包", "ME Rules Preview Add-on"),
    category: "add-on",
    tier: "pro",
    status: "active",
    billingMode: "none",
    modules: ["rule-center", "formula-center", "report-builder"],
    features: [
      { featureType: "rule", key: "rule.workflow.triggerPriority", label: t("流程优先级规则", "Workflow Priority Rule"), required: false, status: "active" },
      { featureType: "rule", key: "rule.notification.escalationRequired", label: t("通知升级规则", "Notification Escalation Rule"), required: false, status: "active" },
      { featureType: "placeholder", key: "feature.rules.engine-runtime", label: t("规则引擎运行时占位", "Rules Engine Runtime Placeholder"), required: false, status: "placeholder" },
    ],
    limits: [{ key: "rule-contracts", label: t("规则合同数量", "Rule Contract Count"), value: 200, unit: t("条", "rules"), isPlaceholder: true }],
    requirement: {
      targetTier: "pro",
      targetRole: "operations-manager",
      billingMode: "none",
      auditRequired: true,
      isPlaceholder: true,
    },
    recommendedRoles: ["operations-manager", "admin"],
    recommendedSkins: ["classic"],
    recommendedDashboards: ["layout.dashboard.rules.preview"],
    linkedRoute: "/rules",
  },
  {
    key: "package.addon.audit-compliance",
    name: t("ME 审计合规附加包", "ME Audit Compliance Add-on"),
    category: "add-on",
    tier: "enterprise",
    status: "active",
    billingMode: "custom-placeholder",
    modules: ["approval", "message", "report-builder"],
    features: [
      { featureType: "audit-event", key: "audit.access.procurement.module", label: t("采购访问审计", "Procurement Access Audit"), required: false, status: "active" },
      { featureType: "notification", key: "notification.alert.refundRisk", label: t("风险通知", "Risk Notification"), required: false, status: "active" },
      { featureType: "report-widget", key: "report.audit.eventSummary", label: t("审计摘要组件", "Audit Summary Widget"), required: false, status: "preview-only" },
    ],
    limits: [{ key: "retention-years", label: t("保留年限", "Retention Years"), value: 7, unit: t("年", "years"), isPlaceholder: true }],
    requirement: {
      targetTier: "enterprise",
      targetRole: "admin",
      billingMode: "custom-placeholder",
      auditRequired: true,
      isPlaceholder: true,
    },
    recommendedRoles: ["admin", "owner"],
    recommendedSkins: ["dark"],
    recommendedDashboards: ["layout.dashboard.compliance.command"],
    linkedRoute: "/audit-trail",
    futureBillingKey: "billing.addon.audit-compliance",
    futureSubscriptionKey: "subscription.addon.audit-compliance",
  },
  {
    key: "package.system.previewOnly",
    name: t("ME 系统预览包", "ME System Preview Package"),
    description: t("用于声明当前包与方案系统为元数据预览阶段。", "Declares package/plan system is currently metadata preview only."),
    category: "system",
    tier: "custom",
    status: "placeholder",
    billingMode: "none",
    modules: ["message"],
    features: [
      { featureType: "placeholder", key: "system.package.preview-only", label: t("系统预览声明", "System Preview Declaration"), required: true, status: "placeholder" },
    ],
    limits: [{ key: "runtime-guard", label: t("运行时门禁", "Runtime Guard"), value: "not-enabled", isPlaceholder: true }],
    requirement: {
      targetCustomer: t("内部演示与合同设计", "Internal demos and contract design"),
      billingMode: "none",
      auditRequired: false,
      isPlaceholder: true,
    },
    recommendedRoles: ["system"],
    recommendedSkins: ["classic"],
    recommendedDashboards: ["layout.dashboard.system.preview"],
    linkedRoute: "/packages",
    notes: t("仅用于合同与预览，不代表真实开通逻辑。", "Contract and preview only; does not represent real provisioning logic."),
  },
];

export const packageContractsByKey: Record<string, PackageContract> = Object.fromEntries(packageContracts.map((item) => [item.key, item]));
