export const erpBranchRows = [
  {
    id: "KCH-001",
    branchCode: "KCH-001",
    branchName: "KCH Central Kitchen",
    region: "Kuching",
    manager: "Chin Ling",
    status: "Operating",
    todaySales: "RM 28,750",
    openTasks: 5,
    stockAlerts: 2,
    inspection: "94%",
    lastUpdate: "10:15",
  },
  {
    id: "BTU-001",
    branchCode: "BTU-001",
    branchName: "BTU Outlet",
    region: "Bintulu",
    manager: "Morexson",
    status: "Operating",
    todaySales: "RM 18,420",
    openTasks: 4,
    stockAlerts: 1,
    inspection: "91%",
    lastUpdate: "09:45",
  },
  {
    id: "KCH-002",
    branchCode: "KCH-002",
    branchName: "KCH Pickup Point",
    region: "Kuching",
    manager: "Lydia",
    status: "Preparation",
    todaySales: "RM 6,880",
    openTasks: 2,
    stockAlerts: 1,
    inspection: "88%",
    lastUpdate: "08:30",
  },
];
