import type { WorkflowContract } from "@/types/workflow";

export const workflowRegistry: WorkflowContract[] = [
  {
    key: "workflow.action.createPurchaseRequest",
    label: { zh: "采购申请触发占位", en: "Create Purchase Request Trigger Placeholder" },
    description: { zh: "新建采购申请后，预留未来任务/审批编排入口。", en: "Reserves future task/approval orchestration when a purchase request is created." },
    triggerType: "action",
    target: {
      targetType: "approval",
      targetModule: "procurement",
      targetAction: "approval.purchase-request",
      targetRoute: "/modules/procurement/detail",
      targetOwnerRole: "purchasing-manager",
      targetDescription: { zh: "进入未来采购审批流。", en: "Enter the future procurement approval flow." },
    },
    status: "placeholder",
    severity: "high",
    source: {
      sourceModule: "procurement",
      sourcePage: "listing",
      sourceComponent: "ProcurementListing",
      sourceEvent: "click",
      sourceRoute: "/modules/procurement/listing",
      actionKey: "createPurchaseRequest",
    },
    requirement: {
      humanConfirmationRequired: true,
      auditRequired: true,
      permissionRequired: "procurement.create",
      roleRequired: "purchasing-manager",
      planRequired: "ops",
      actionKey: "createPurchaseRequest",
      accessRuleKey: "action.createPurchaseRequest",
      auditEventKey: "audit.action.createPurchaseRequest",
    },
    isPlaceholder: true,
    futureEngineKey: "engine.procurement.approval-v1",
    futureQueueKey: "queue.procurement.approval",
    notes: { zh: "仅做元数据占位，不触发真实审批。", en: "Metadata placeholder only; no real approval is triggered." },
  },
  {
    key: "workflow.action.approvePurchaseRequestPlaceholder",
    label: { zh: "采购审批触发占位", en: "Approve Purchase Request Trigger Placeholder" },
    description: { zh: "审批动作未来可触发通知和任务回写。", en: "Approval action can later trigger notifications and task updates." },
    triggerType: "action",
    target: {
      targetType: "notification",
      targetModule: "procurement",
      targetAction: "notification.manager-alert",
      targetDescription: { zh: "未来通知采购经理审批结果。", en: "Future manager alert for purchase approval result." },
    },
    status: "coming-soon",
    severity: "medium",
    source: {
      sourceModule: "procurement",
      sourcePage: "detail",
      sourceComponent: "ProcurementDetail",
      sourceEvent: "click",
      sourceRoute: "/modules/procurement/detail",
      actionKey: "approvePurchaseRequestPlaceholder",
    },
    requirement: {
      humanConfirmationRequired: true,
      auditRequired: true,
      permissionRequired: "procurement.approve",
      roleRequired: "purchasing-manager",
      planRequired: "ops",
      actionKey: "approvePurchaseRequestPlaceholder",
      accessRuleKey: "action.approvePurchaseRequestPlaceholder",
      auditEventKey: "audit.action.approvePurchaseRequestPlaceholder",
    },
    isPlaceholder: true,
    futureEngineKey: "engine.procurement.approval-v2",
    notes: { zh: "未来对接审批路由器。", en: "Will be wired to a future approval router." },
  },
  {
    key: "workflow.action.adjustStockPlaceholder",
    label: { zh: "库存调整触发占位", en: "Adjust Stock Trigger Placeholder" },
    description: { zh: "库存调整未来可触发人工复核与审计任务。", en: "Stock adjustment can later trigger human review and audit tasks." },
    triggerType: "action",
    target: {
      targetType: "human-review",
      targetModule: "inventory",
      targetAction: "human-review.stock-variance",
      targetOwnerRole: "warehouse-handler",
      targetDescription: { zh: "库存差异需人工复核。", en: "Stock variance requires human review." },
    },
    status: "blocked",
    severity: "critical",
    source: {
      sourceModule: "inventory",
      sourcePage: "detail",
      sourceComponent: "InventoryDetail",
      sourceEvent: "click",
      sourceRoute: "/modules/inventory/detail",
      actionKey: "adjustStockPlaceholder",
    },
    requirement: {
      humanConfirmationRequired: true,
      auditRequired: true,
      permissionRequired: "inventory.edit",
      roleRequired: "warehouse-handler",
      planRequired: "ops",
      actionKey: "adjustStockPlaceholder",
      accessRuleKey: "action.adjustStockPlaceholder",
      auditEventKey: "audit.action.adjustStockPlaceholder",
    },
    isPlaceholder: true,
    futureQueueKey: "queue.inventory.variance",
  },
  {
    key: "workflow.action.assignTask",
    label: { zh: "任务分派触发预览", en: "Task Assignment Trigger Preview" },
    description: { zh: "任务分派动作与未来工作流目标的预览映射。", en: "Preview mapping for task assignment action and future workflow targets." },
    triggerType: "action",
    target: {
      targetType: "task",
      targetModule: "task",
      targetAction: "task.supplier-review",
      targetRoute: "/tasks",
      targetDescription: { zh: "分派后可产生后续协作任务。", en: "May create downstream collaboration tasks in future." },
    },
    status: "preview-only",
    severity: "medium",
    source: {
      sourceModule: "task",
      sourcePage: "detail",
      sourceComponent: "TaskDetail",
      sourceEvent: "click",
      sourceRoute: "/tasks/:taskId",
      actionKey: "assignTask",
    },
    requirement: {
      humanConfirmationRequired: true,
      auditRequired: true,
      permissionRequired: "task.assign",
      roleRequired: "store-manager",
      planRequired: "ops",
      actionKey: "assignTask",
      accessRuleKey: "action.assignTask",
      auditEventKey: "audit.action.assignTask",
    },
    isPlaceholder: true,
    futureEngineKey: "engine.task.assign",
  },
  {
    key: "workflow.action.closeTask",
    label: { zh: "任务关闭触发占位", en: "Task Closure Trigger Placeholder" },
    description: { zh: "任务关闭后续流程仍禁用，仅保留合同。", en: "Post-closure flow is still disabled and only the contract is preserved." },
    triggerType: "action",
    target: {
      targetType: "report",
      targetModule: "task",
      targetAction: "report.daily-ops-summary",
      targetDescription: { zh: "未来进入日报摘要流水。", en: "Future flow into daily ops summary reporting." },
    },
    status: "disabled",
    severity: "high",
    source: {
      sourceModule: "task",
      sourcePage: "detail",
      sourceComponent: "TaskDetail",
      sourceEvent: "click",
      sourceRoute: "/tasks/:taskId",
      actionKey: "closeTask",
    },
    requirement: {
      humanConfirmationRequired: true,
      auditRequired: true,
      permissionRequired: "task.close",
      roleRequired: "store-manager",
      planRequired: "ops",
      actionKey: "closeTask",
      accessRuleKey: "action.closeTask",
      auditEventKey: "audit.action.closeTask",
    },
    isPlaceholder: true,
  },
  {
    key: "workflow.audit.accessProcurementModule",
    label: { zh: "采购访问审计触发", en: "Procurement Access Audit Trigger" },
    description: { zh: "访问审计事件可映射未来运营摘要。", en: "Access audit event can map to future operations summary processing." },
    triggerType: "audit-event",
    target: {
      targetType: "report",
      targetModule: "procurement",
      targetAction: "report.daily-ops-summary",
      targetDescription: { zh: "汇总采购访问态势。", en: "Aggregate procurement access activity." },
    },
    status: "active",
    severity: "low",
    source: {
      sourceModule: "access-control",
      sourcePage: "rule-list",
      sourceComponent: "AccessRuleCard",
      sourceEvent: "preview",
      sourceRoute: "/access-control",
      auditEventKey: "audit.access.procurement.module",
      accessRuleKey: "access.procurement.module",
    },
    requirement: {
      humanConfirmationRequired: false,
      auditRequired: false,
      accessRuleKey: "access.procurement.module",
      auditEventKey: "audit.access.procurement.module",
    },
    isPlaceholder: false,
    futureEngineKey: "engine.audit.aggregate",
  },
  {
    key: "workflow.audit.inventoryDetailPreview",
    label: { zh: "库存详情审计预览触发", en: "Inventory Detail Audit Preview Trigger" },
    description: { zh: "库存详情访问审计的自动化占位映射。", en: "Automation placeholder mapping for inventory detail access audit." },
    triggerType: "audit-event",
    target: {
      targetType: "automation-placeholder",
      targetModule: "inventory",
      targetAction: "automation-placeholder.external-connector",
      targetDescription: { zh: "未来可对接外部风控连接器。", en: "May connect to external risk connectors in future." },
    },
    status: "preview-only",
    severity: "medium",
    source: {
      sourceModule: "access-control",
      sourcePage: "rule-list",
      sourceComponent: "AccessRuleCard",
      sourceEvent: "preview",
      sourceRoute: "/access-control",
      auditEventKey: "audit.access.inventory.detail",
      accessRuleKey: "access.inventory.detail",
    },
    requirement: {
      humanConfirmationRequired: false,
      auditRequired: true,
      permissionRequired: "inventory.view",
      roleRequired: "warehouse-handler",
      planRequired: "ops",
      accessRuleKey: "access.inventory.detail",
      auditEventKey: "audit.access.inventory.detail",
    },
    isPlaceholder: true,
    futureQueueKey: "queue.audit.inventory-preview",
  },
  {
    key: "workflow.audit.taskBoardPreview",
    label: { zh: "任务看板审计预览触发", en: "Task Board Audit Preview Trigger" },
    description: { zh: "任务看板访问审计可关联未来告警通知。", en: "Task board access audit can be linked to future alert notifications." },
    triggerType: "audit-event",
    target: {
      targetType: "notification",
      targetModule: "task",
      targetAction: "notification.manager-alert",
      targetDescription: { zh: "未来任务看板异常通知。", en: "Future anomaly alerts for task board activity." },
    },
    status: "placeholder",
    severity: "low",
    source: {
      sourceModule: "access-control",
      sourcePage: "rule-list",
      sourceComponent: "AccessRuleCard",
      sourceEvent: "preview",
      sourceRoute: "/access-control",
      auditEventKey: "audit.access.task.board",
      accessRuleKey: "access.task.board",
    },
    requirement: {
      humanConfirmationRequired: false,
      auditRequired: false,
      permissionRequired: "task.view",
      roleRequired: "staff",
      planRequired: "starter",
      accessRuleKey: "access.task.board",
      auditEventKey: "audit.access.task.board",
    },
    isPlaceholder: true,
  },
  {
    key: "workflow.manual.managerReview",
    label: { zh: "经理人工复核触发", en: "Manager Manual Review Trigger" },
    description: { zh: "用于未来人工复核入口。", en: "Manual trigger placeholder for future manager review." },
    triggerType: "manual",
    target: {
      targetType: "human-review",
      targetModule: "inventory",
      targetAction: "human-review.stock-variance",
      targetOwnerRole: "operations-manager",
      targetDescription: { zh: "触发经理复核流程。", en: "Trigger manager-led review flow." },
    },
    status: "coming-soon",
    severity: "high",
    source: {
      sourceModule: "workflow",
      sourcePage: "overview",
      sourceComponent: "WorkflowPage",
      sourceEvent: "manual-click",
      sourceRoute: "/workflow",
    },
    requirement: {
      humanConfirmationRequired: true,
      auditRequired: true,
      roleRequired: "operations-manager",
      planRequired: "ops",
    },
    isPlaceholder: true,
  },
  {
    key: "workflow.system.previewOnly",
    label: { zh: "系统预览模式触发", en: "System Preview-Only Trigger" },
    description: { zh: "统一声明当前链路为元数据预览。", en: "Unified declaration that the current chain is metadata preview only." },
    triggerType: "system",
    target: {
      targetType: "none",
      targetModule: "workflow",
      targetAction: "preview-only",
      targetDescription: { zh: "不执行真实自动化。", en: "No real automation is executed." },
    },
    status: "preview-only",
    severity: "low",
    source: {
      sourceModule: "workflow",
      sourcePage: "overview",
      sourceComponent: "WorkflowPage",
      sourceEvent: "render",
      sourceRoute: "/workflow",
      auditEventKey: "audit.system.previewOnly",
    },
    requirement: {
      humanConfirmationRequired: false,
      auditRequired: false,
      auditEventKey: "audit.system.previewOnly",
    },
    isPlaceholder: false,
    notes: { zh: "用于统一展示预览模式声明。", en: "Used to display the unified preview-mode declaration." },
  },
];

export const workflowRegistryByKey: Record<string, WorkflowContract> = Object.fromEntries(
  workflowRegistry.map((workflow) => [workflow.key, workflow]),
);
