import type { NotificationContract } from "@/types/notification";

export const notificationRules: NotificationContract[] = [
  {
    key: "notification.workflow.purchaseRequestCreated",
    label: { zh: "采购申请创建通知占位", en: "Purchase Request Created Notification Placeholder" },
    description: { zh: "采购申请创建后的通知合同预览。", en: "Notification contract preview when purchase request is created." },
    channel: "in-app",
    category: "workflow",
    severity: "medium",
    status: "placeholder",
    source: {
      sourceModule: "procurement",
      sourcePage: "listing",
      sourceComponent: "ProcurementListing",
      sourceEvent: "click",
      sourceRoute: "/modules/procurement/listing",
      actionKey: "createPurchaseRequest",
      workflowKey: "workflow.action.createPurchaseRequest",
    },
    recipient: {
      recipientType: "role",
      role: "purchasing-manager",
      label: { zh: "采购经理", en: "Purchasing Manager" },
    },
    message: {
      title: { zh: "采购申请已创建", en: "Purchase Request Created" },
      body: { zh: "新采购申请已进入待审批列表。", en: "A new purchase request entered the pending approval list." },
      shortBody: { zh: "新采购申请待处理", en: "New purchase request pending" },
      ctaLabel: { zh: "查看详情", en: "View Detail" },
    },
    requirement: {
      humanReviewRequired: true,
      auditRequired: true,
      permissionRequired: "procurement.create",
      roleRequired: "purchasing-manager",
      planRequired: "ops",
      workflowKey: "workflow.action.createPurchaseRequest",
      actionKey: "createPurchaseRequest",
      auditEventKey: "audit.action.createPurchaseRequest",
      accessRuleKey: "action.createPurchaseRequest",
    },
    isPlaceholder: true,
    futureProviderKey: "provider.in-app.notification-center",
    futureTemplateKey: "approval.purchase-request",
    notes: { zh: "仅保留通知合同映射，不执行发送。", en: "Mapping-only notification contract; no real delivery is executed." },
  },
  {
    key: "notification.workflow.purchaseApprovalNeeded",
    label: { zh: "采购审批提醒", en: "Purchase Approval Needed" },
    description: { zh: "采购审批流程的提醒通知元数据。", en: "Reminder notification metadata for purchase approval workflow." },
    channel: "email-placeholder",
    category: "approval",
    severity: "high",
    status: "coming-soon",
    source: {
      sourceModule: "procurement",
      sourcePage: "detail",
      sourceComponent: "ProcurementDetail",
      sourceEvent: "click",
      sourceRoute: "/modules/procurement/detail",
      actionKey: "approvePurchaseRequestPlaceholder",
      workflowKey: "workflow.action.approvePurchaseRequestPlaceholder",
    },
    recipient: {
      recipientType: "role",
      role: "operations-manager",
      label: { zh: "运营经理", en: "Operations Manager" },
    },
    message: {
      title: { zh: "采购申请需要审批", en: "Purchase Request Requires Approval" },
      body: { zh: "请处理新的采购审批请求。", en: "Please process the new purchase approval request." },
      ctaLabel: { zh: "打开审批", en: "Open Approval" },
    },
    requirement: {
      humanReviewRequired: true,
      auditRequired: true,
      permissionRequired: "procurement.approve",
      roleRequired: "purchasing-manager",
      planRequired: "ops",
      workflowKey: "workflow.action.approvePurchaseRequestPlaceholder",
      actionKey: "approvePurchaseRequestPlaceholder",
      auditEventKey: "audit.action.approvePurchaseRequestPlaceholder",
      accessRuleKey: "action.approvePurchaseRequestPlaceholder",
    },
    isPlaceholder: true,
    futureProviderKey: "provider.email.connector",
    futureTemplateKey: "approval.purchase-request",
  },
  {
    key: "notification.workflow.stockAdjustmentReview",
    label: { zh: "库存调整复核提醒", en: "Stock Adjustment Review Reminder" },
    description: { zh: "库存差异复核流程的通知占位。", en: "Notification placeholder for stock variance review flow." },
    channel: "whatsapp-placeholder",
    category: "alert",
    severity: "critical",
    status: "blocked",
    source: {
      sourceModule: "inventory",
      sourcePage: "detail",
      sourceComponent: "InventoryDetail",
      sourceEvent: "click",
      sourceRoute: "/modules/inventory/detail",
      actionKey: "adjustStockPlaceholder",
      workflowKey: "workflow.action.adjustStockPlaceholder",
    },
    recipient: {
      recipientType: "module-owner",
      role: "warehouse-handler",
      label: { zh: "库存模块负责人", en: "Inventory Module Owner" },
    },
    message: {
      title: { zh: "库存差异待复核", en: "Stock Variance Needs Review" },
      body: { zh: "请先完成人工复核再处理后续动作。", en: "Please complete human review before further processing." },
      shortBody: { zh: "库存差异待复核", en: "Variance review required" },
    },
    requirement: {
      humanReviewRequired: true,
      auditRequired: true,
      permissionRequired: "inventory.edit",
      roleRequired: "warehouse-handler",
      workflowKey: "workflow.action.adjustStockPlaceholder",
      actionKey: "adjustStockPlaceholder",
      auditEventKey: "audit.action.adjustStockPlaceholder",
      accessRuleKey: "action.adjustStockPlaceholder",
    },
    isPlaceholder: true,
    futureProviderKey: "provider.whatsapp.business",
    futureTemplateKey: "alert.stock-variance",
  },
  {
    key: "notification.workflow.taskAssigned",
    label: { zh: "任务已分派通知", en: "Task Assigned Notification" },
    description: { zh: "任务分派动作对应的消息预览。", en: "Message preview mapping for task assignment action." },
    channel: "in-app",
    category: "task",
    severity: "medium",
    status: "preview-only",
    source: {
      sourceModule: "task",
      sourcePage: "detail",
      sourceComponent: "TaskDetail",
      sourceEvent: "click",
      sourceRoute: "/tasks/:taskId",
      actionKey: "assignTask",
      workflowKey: "workflow.action.assignTask",
    },
    recipient: {
      recipientType: "role",
      role: "staff",
      label: { zh: "执行人员", en: "Assignee Staff" },
    },
    message: {
      title: { zh: "你被分派了新任务", en: "A New Task Was Assigned To You" },
      body: { zh: "请查看任务详情并更新进度。", en: "Please check task details and update progress." },
      ctaLabel: { zh: "打开任务", en: "Open Task" },
    },
    requirement: {
      humanReviewRequired: true,
      auditRequired: true,
      permissionRequired: "task.assign",
      roleRequired: "store-manager",
      planRequired: "ops",
      workflowKey: "workflow.action.assignTask",
      actionKey: "assignTask",
      auditEventKey: "audit.action.assignTask",
      accessRuleKey: "action.assignTask",
    },
    isPlaceholder: true,
    futureProviderKey: "provider.in-app.notification-center",
    futureTemplateKey: "task.assigned",
  },
  {
    key: "notification.workflow.taskClosed",
    label: { zh: "任务关闭摘要提醒", en: "Task Closed Summary Reminder" },
    description: { zh: "任务关闭后的摘要通知占位。", en: "Placeholder summary notification after task closure." },
    channel: "system",
    category: "report",
    severity: "low",
    status: "disabled",
    source: {
      sourceModule: "task",
      sourcePage: "detail",
      sourceComponent: "TaskDetail",
      sourceEvent: "click",
      sourceRoute: "/tasks/:taskId",
      actionKey: "closeTask",
      workflowKey: "workflow.action.closeTask",
    },
    recipient: {
      recipientType: "role",
      role: "operations-manager",
      label: { zh: "运营经理", en: "Operations Manager" },
    },
    message: {
      title: { zh: "任务关闭摘要", en: "Task Closure Summary" },
      body: { zh: "任务关闭后将汇总到日报预览。", en: "Task closure will be summarized in daily report preview." },
    },
    requirement: {
      humanReviewRequired: false,
      auditRequired: true,
      permissionRequired: "task.close",
      roleRequired: "store-manager",
      planRequired: "ops",
      workflowKey: "workflow.action.closeTask",
      actionKey: "closeTask",
      auditEventKey: "audit.action.closeTask",
      accessRuleKey: "action.closeTask",
    },
    isPlaceholder: true,
    futureTemplateKey: "report.daily-ops-summary",
  },
  {
    key: "notification.audit.accessProcurementModule",
    label: { zh: "采购访问审计提示", en: "Procurement Access Audit Notice" },
    description: { zh: "采购访问审计事件的系统消息预览。", en: "System message preview for procurement access audit event." },
    channel: "system",
    category: "audit",
    severity: "low",
    status: "active",
    source: {
      sourceModule: "access-control",
      sourcePage: "rule-list",
      sourceComponent: "AccessRuleCard",
      sourceEvent: "preview",
      sourceRoute: "/access-control",
      accessRuleKey: "access.procurement.module",
      auditEventKey: "audit.access.procurement.module",
      workflowKey: "workflow.audit.accessProcurementModule",
    },
    recipient: {
      recipientType: "module-owner",
      role: "operations-manager",
      label: { zh: "采购模块负责人", en: "Procurement Module Owner" },
    },
    message: {
      title: { zh: "采购访问审计预览", en: "Procurement Access Audit Preview" },
      body: { zh: "访问事件仅用于审计预览映射。", en: "Access event is mapped for audit preview metadata only." },
    },
    requirement: {
      humanReviewRequired: false,
      auditRequired: false,
      accessRuleKey: "access.procurement.module",
      auditEventKey: "audit.access.procurement.module",
      workflowKey: "workflow.audit.accessProcurementModule",
    },
    isPlaceholder: false,
    futureTemplateKey: "audit.permission-preview",
  },
  {
    key: "notification.audit.inventoryDetailPreview",
    label: { zh: "库存详情审计预览提醒", en: "Inventory Detail Audit Preview Notice" },
    description: { zh: "库存详情访问与审计预览联动的通知占位。", en: "Notification placeholder for inventory-detail audit preview linkage." },
    channel: "webhook-placeholder",
    category: "audit",
    severity: "medium",
    status: "preview-only",
    source: {
      sourceModule: "access-control",
      sourcePage: "rule-list",
      sourceComponent: "AccessRuleCard",
      sourceEvent: "preview",
      sourceRoute: "/access-control",
      accessRuleKey: "access.inventory.detail",
      auditEventKey: "audit.access.inventory.detail",
      workflowKey: "workflow.audit.inventoryDetailPreview",
    },
    recipient: {
      recipientType: "system",
      label: { zh: "系统连接器占位", en: "System Connector Placeholder" },
    },
    message: {
      title: { zh: "库存详情审计预览", en: "Inventory Detail Audit Preview" },
      body: { zh: "未来可接入外部风控连接器。", en: "Can be connected to external risk connectors in future." },
    },
    requirement: {
      humanReviewRequired: false,
      auditRequired: true,
      permissionRequired: "inventory.view",
      roleRequired: "warehouse-handler",
      planRequired: "ops",
      accessRuleKey: "access.inventory.detail",
      auditEventKey: "audit.access.inventory.detail",
      workflowKey: "workflow.audit.inventoryDetailPreview",
    },
    isPlaceholder: true,
    futureProviderKey: "provider.webhook.audit-connector",
    futureTemplateKey: "external-connector.placeholder",
  },
  {
    key: "notification.audit.taskBoardPreview",
    label: { zh: "任务看板审计预览提示", en: "Task Board Audit Preview Notice" },
    description: { zh: "任务看板访问审计的消息占位。", en: "Message placeholder for task-board access audit preview." },
    channel: "push-placeholder",
    category: "audit",
    severity: "low",
    status: "placeholder",
    source: {
      sourceModule: "access-control",
      sourcePage: "rule-list",
      sourceComponent: "AccessRuleCard",
      sourceEvent: "preview",
      sourceRoute: "/access-control",
      accessRuleKey: "access.task.board",
      auditEventKey: "audit.access.task.board",
      workflowKey: "workflow.audit.taskBoardPreview",
    },
    recipient: {
      recipientType: "role",
      role: "staff",
      label: { zh: "任务看板用户", en: "Task Board User" },
    },
    message: {
      title: { zh: "任务看板访问预览", en: "Task Board Access Preview" },
      body: { zh: "当前仅展示审计与通知映射元数据。", en: "Only audit and notification mapping metadata is shown." },
    },
    requirement: {
      humanReviewRequired: false,
      auditRequired: false,
      permissionRequired: "task.view",
      roleRequired: "staff",
      planRequired: "starter",
      accessRuleKey: "access.task.board",
      auditEventKey: "audit.access.task.board",
      workflowKey: "workflow.audit.taskBoardPreview",
    },
    isPlaceholder: true,
    futureProviderKey: "provider.push.placeholder",
    futureTemplateKey: "audit.permission-preview",
  },
  {
    key: "notification.manual.managerAlert",
    label: { zh: "经理人工提醒", en: "Manual Manager Alert" },
    description: { zh: "手动触发的经理提醒消息合同。", en: "Manually-triggered manager alert message contract." },
    channel: "sms-placeholder",
    category: "alert",
    severity: "high",
    status: "coming-soon",
    source: {
      sourceModule: "workflow",
      sourcePage: "overview",
      sourceComponent: "WorkflowPage",
      sourceEvent: "manual-click",
      sourceRoute: "/workflow",
      workflowKey: "workflow.manual.managerReview",
    },
    recipient: {
      recipientType: "role",
      role: "operations-manager",
      label: { zh: "值班经理", en: "On-Duty Manager" },
    },
    message: {
      title: { zh: "经理复核提醒", en: "Manager Review Reminder" },
      body: { zh: "有新的人工复核请求等待处理。", en: "A new human-review request is waiting for handling." },
      ctaLabel: { zh: "查看复核项", en: "Open Review Item" },
    },
    requirement: {
      humanReviewRequired: true,
      auditRequired: true,
      roleRequired: "operations-manager",
      planRequired: "ops",
      workflowKey: "workflow.manual.managerReview",
    },
    isPlaceholder: true,
    futureProviderKey: "provider.sms.placeholder",
    futureTemplateKey: "workflow.manager-review",
  },
  {
    key: "notification.system.previewOnly",
    label: { zh: "系统预览模式提示", en: "System Preview-Only Notice" },
    description: { zh: "统一声明通知链路仍为预览模式。", en: "Unified declaration that notification chain remains preview-only." },
    channel: "system",
    category: "system",
    severity: "low",
    status: "active",
    source: {
      sourceModule: "notifications",
      sourcePage: "overview",
      sourceComponent: "NotificationsPage",
      sourceEvent: "render",
      sourceRoute: "/notifications",
      workflowKey: "workflow.system.previewOnly",
      auditEventKey: "audit.system.previewOnly",
    },
    recipient: {
      recipientType: "system",
      label: { zh: "系统预览层", en: "System Preview Layer" },
    },
    message: {
      title: { zh: "通知预览模式", en: "Notification Preview Mode" },
      body: { zh: "仅显示消息合同，不发送真实通知。", en: "Message contracts are displayed only. No real notification is sent." },
    },
    requirement: {
      humanReviewRequired: false,
      auditRequired: false,
      workflowKey: "workflow.system.previewOnly",
      auditEventKey: "audit.system.previewOnly",
    },
    isPlaceholder: false,
    futureTemplateKey: "system.preview-only",
  },
];

export const notificationRulesByKey: Record<string, NotificationContract> = Object.fromEntries(
  notificationRules.map((rule) => [rule.key, rule]),
);
