import type { NotificationTemplate } from "@/types/notification";

export const notificationTemplateCatalog: NotificationTemplate[] = [
  {
    code: "task.assigned",
    name: { zh: "任务分派消息", en: "Task Assigned Message" },
    description: { zh: "用于任务分派的站内通知模板。", en: "Template for in-app task assignment notification." },
    category: "task",
    defaultChannel: "in-app",
    status: "active",
    sampleTitle: { zh: "你有一个新任务", en: "You Have A New Task" },
    sampleBody: { zh: "任务已分派给你，请尽快处理。", en: "A task was assigned to you. Please review it soon." },
  },
  {
    code: "task.overdue",
    name: { zh: "任务逾期提醒", en: "Task Overdue Reminder" },
    description: { zh: "任务逾期提醒占位模板。", en: "Placeholder reminder template for overdue tasks." },
    category: "reminder",
    defaultChannel: "in-app",
    status: "preview-only",
    sampleTitle: { zh: "任务已逾期", en: "Task Is Overdue" },
    sampleBody: { zh: "请检查逾期任务并安排处理。", en: "Please review the overdue task and arrange follow-up." },
  },
  {
    code: "approval.purchase-request",
    name: { zh: "采购审批提醒", en: "Purchase Approval Reminder" },
    description: { zh: "采购申请审批消息模板。", en: "Notification template for purchase request approval." },
    category: "approval",
    defaultChannel: "in-app",
    status: "placeholder",
    sampleTitle: { zh: "采购申请待审批", en: "Purchase Request Needs Approval" },
    sampleBody: { zh: "有新的采购申请等待你审批。", en: "A new purchase request is waiting for your approval." },
  },
  {
    code: "alert.low-stock",
    name: { zh: "低库存告警", en: "Low Stock Alert" },
    description: { zh: "库存预警消息模板。", en: "Alert template for low stock warning." },
    category: "alert",
    defaultChannel: "in-app",
    status: "coming-soon",
    sampleTitle: { zh: "库存低于阈值", en: "Stock Is Below Threshold" },
    sampleBody: { zh: "请尽快检查补货计划。", en: "Please review replenishment planning soon." },
  },
  {
    code: "alert.stock-variance",
    name: { zh: "库存差异告警", en: "Stock Variance Alert" },
    description: { zh: "库存差异人工复核告警模板。", en: "Alert template for stock variance human review." },
    category: "alert",
    defaultChannel: "in-app",
    status: "blocked",
    sampleTitle: { zh: "库存差异需复核", en: "Stock Variance Needs Review" },
    sampleBody: { zh: "系统检测到库存差异，请经理复核。", en: "A stock variance was detected and needs manager review." },
  },
  {
    code: "report.daily-ops-summary",
    name: { zh: "每日运营摘要", en: "Daily Ops Summary" },
    description: { zh: "运营日报消息模板。", en: "Template for daily operations summary message." },
    category: "report",
    defaultChannel: "system",
    status: "preview-only",
    sampleTitle: { zh: "今日运营摘要", en: "Today Operations Summary" },
    sampleBody: { zh: "查看今日关键运营指标预览。", en: "Review today key operational metrics preview." },
  },
  {
    code: "audit.permission-preview",
    name: { zh: "权限审计预览提示", en: "Permission Audit Preview Notice" },
    description: { zh: "权限审计相关通知占位模板。", en: "Placeholder template for permission audit preview notifications." },
    category: "audit",
    defaultChannel: "system",
    status: "active",
    sampleTitle: { zh: "权限访问已记录为预览", en: "Permission Access Logged As Preview" },
    sampleBody: { zh: "当前仅记录元数据预览，不写入真实日志。", en: "Only metadata preview is recorded; no real audit write is performed." },
  },
  {
    code: "workflow.manager-review",
    name: { zh: "工作流经理复核", en: "Workflow Manager Review" },
    description: { zh: "经理人工复核工作流通知模板。", en: "Template for manager human-review workflow notifications." },
    category: "workflow",
    defaultChannel: "in-app",
    status: "coming-soon",
    sampleTitle: { zh: "经理复核任务已生成", en: "Manager Review Task Is Prepared" },
    sampleBody: { zh: "请确认复核条件后处理。", en: "Please confirm review conditions before processing." },
  },
  {
    code: "system.preview-only",
    name: { zh: "系统预览模式提示", en: "System Preview-Only Notice" },
    description: { zh: "统一提示当前仅为消息合同预览。", en: "Unified notice that current state is message-contract preview only." },
    category: "system",
    defaultChannel: "system",
    status: "active",
    sampleTitle: { zh: "通知预览模式", en: "Notification Preview Mode" },
    sampleBody: { zh: "当前不发送真实消息，仅展示元数据。", en: "No real messages are sent. Metadata preview only." },
  },
  {
    code: "external-connector.placeholder",
    name: { zh: "外部连接器占位", en: "External Connector Placeholder" },
    description: { zh: "未来 webhook / 第三方消息连接器占位模板。", en: "Placeholder template for future webhook or third-party connectors." },
    category: "placeholder",
    defaultChannel: "webhook-placeholder",
    status: "placeholder",
    sampleTitle: { zh: "外部连接器未接入", en: "External Connector Not Integrated" },
    sampleBody: { zh: "预留给未来 webhook / push / 短信接入。", en: "Reserved for future webhook, push, and SMS integration." },
  },
];

export const notificationTemplateCatalogByCode: Record<string, NotificationTemplate> = Object.fromEntries(
  notificationTemplateCatalog.map((template) => [template.code, template]),
);
