import type { AccessRule } from "@/types/access-control"

export const accessRules: AccessRule[] = [
  {
    key: "access.procurement.module",
    label: { zh: "采购模块访问", en: "Procurement Module Access" },
    scope: "module",
    targetModule: "procurement",
    condition: {
      requiredPermission: "procurement.view",
      requiredRole: "operations-manager",
      requiredPlan: "ops",
      requiredModule: "procurement",
      requiresAudit: false,
      requiresConfirmation: false,
      isPlaceholder: false,
    },
    status: "allowed",
    reason: { zh: "采购模块作为核心运营模块在 Ops 方案中开放。", en: "Procurement module is available in Ops plan as a core operations module." },
    futureEnforcementKey: "guard.module.procurement",
  },
  {
    key: "access.supplier.module",
    label: { zh: "供应商模块访问", en: "Supplier Module Access" },
    scope: "module",
    targetModule: "supplier",
    condition: {
      requiredPermission: "supplier.view",
      requiredRole: "supplier-coordinator",
      requiredPlan: "ops",
      requiredModule: "supplier",
      requiresAudit: false,
      requiresConfirmation: false,
      isPlaceholder: false,
    },
    status: "allowed",
    reason: { zh: "供应商模块在 Ops 方案下可预览。", en: "Supplier module is available for metadata preview under Ops plan." },
    futureEnforcementKey: "guard.module.supplier",
  },
  {
    key: "access.inventory.module",
    label: { zh: "库存模块访问", en: "Inventory Module Access" },
    scope: "module",
    targetModule: "inventory",
    condition: {
      requiredPermission: "inventory.view",
      requiredRole: "warehouse-handler",
      requiredPlan: "ops",
      requiredModule: "inventory",
      requiresAudit: false,
      requiresConfirmation: false,
      isPlaceholder: false,
    },
    status: "allowed",
    reason: { zh: "库存模块在 Ops 方案可访问。", en: "Inventory module is available for Ops customers." },
    futureEnforcementKey: "guard.module.inventory",
  },
  {
    key: "access.task.module",
    label: { zh: "任务模块访问", en: "Task Module Access" },
    scope: "module",
    targetModule: "task",
    condition: {
      requiredPermission: "task.view",
      requiredRole: "staff",
      requiredPlan: "starter",
      requiredModule: "task",
      requiresAudit: false,
      requiresConfirmation: false,
      isPlaceholder: false,
    },
    status: "allowed",
    reason: { zh: "任务模块在 Starter 即可使用。", en: "Task module is available from Starter plan." },
    futureEnforcementKey: "guard.module.task",
  },
  {
    key: "access.pos-report.module",
    label: { zh: "POS 报表模块访问", en: "POS Report Module Access" },
    scope: "module",
    targetModule: "pos-report",
    condition: {
      requiredPermission: "pos-report.view",
      requiredRole: "operations-manager",
      requiredPlan: "pro",
      requiredModule: "pos-report",
      requiresAudit: true,
      requiresConfirmation: false,
      isPlaceholder: true,
    },
    status: "coming-soon",
    reason: { zh: "POS 报表能力仍在占位阶段。", en: "POS reporting capability is still in placeholder stage." },
    futureEnforcementKey: "guard.module.pos-report",
  },
  {
    key: "access.education.module",
    label: { zh: "培训模块访问", en: "Education Module Access" },
    scope: "module",
    targetModule: "education",
    condition: {
      requiredPermission: "education.view",
      requiredRole: "store-manager",
      requiredPlan: "pro",
      requiredModule: "education",
      requiresAudit: false,
      requiresConfirmation: false,
      isPlaceholder: true,
    },
    status: "placeholder",
    reason: { zh: "培训模块仅提供元数据预览。", en: "Education module is metadata preview only." },
    futureEnforcementKey: "guard.module.education",
  },
  {
    key: "access.procurement.listing",
    label: { zh: "采购列表页访问", en: "Procurement Listing Access" },
    scope: "page",
    targetModule: "procurement",
    targetPage: "/modules/procurement/listing",
    condition: {
      requiredPermission: "procurement.view",
      requiredRole: "purchasing-manager",
      requiredPlan: "ops",
      requiredModule: "procurement",
      requiresAudit: false,
      requiresConfirmation: false,
      isPlaceholder: false,
    },
    status: "allowed",
    futureEnforcementKey: "guard.page.procurement.listing",
  },
  {
    key: "access.inventory.detail",
    label: { zh: "库存详情页访问", en: "Inventory Detail Access" },
    scope: "page",
    targetModule: "inventory",
    targetPage: "/modules/inventory/detail",
    condition: {
      requiredPermission: "inventory.view",
      requiredRole: "warehouse-handler",
      requiredPlan: "ops",
      requiredModule: "inventory",
      requiresAudit: true,
      requiresConfirmation: false,
      isPlaceholder: false,
    },
    status: "allowed",
    futureEnforcementKey: "guard.page.inventory.detail",
  },
  {
    key: "access.task.board",
    label: { zh: "任务看板页访问", en: "Task Board Access" },
    scope: "page",
    targetModule: "task",
    targetPage: "/tasks",
    condition: {
      requiredPermission: "task.view",
      requiredRole: "staff",
      requiredPlan: "starter",
      requiredModule: "task",
      requiresAudit: false,
      requiresConfirmation: false,
      isPlaceholder: false,
    },
    status: "allowed",
    futureEnforcementKey: "guard.page.task.board",
  },
  {
    key: "access.demo.workspace",
    label: { zh: "Demo 工作台访问", en: "Demo Workspace Access" },
    scope: "page",
    targetPage: "/demo",
    condition: {
      requiredRole: "staff",
      requiredPlan: "starter",
      requiresAudit: false,
      requiresConfirmation: false,
      isPlaceholder: true,
    },
    status: "placeholder",
    reason: { zh: "用于演示，不代表真实权限策略。", en: "For demo only, does not represent real production policy." },
  },
  {
    key: "access.layout-engine.preview",
    label: { zh: "布局引擎预览访问", en: "Layout Engine Preview Access" },
    scope: "page",
    targetPage: "/layout-engine",
    condition: {
      requiredRole: "admin",
      requiredPlan: "pro",
      requiresAudit: false,
      requiresConfirmation: false,
      isPlaceholder: false,
    },
    status: "allowed",
    futureEnforcementKey: "guard.page.layout-engine.preview",
  },
  {
    key: "access.action-contracts.preview",
    label: { zh: "动作合同预览访问", en: "Action Contracts Preview Access" },
    scope: "page",
    targetPage: "/action-contracts",
    condition: {
      requiredRole: "admin",
      requiredPlan: "ops",
      requiresAudit: false,
      requiresConfirmation: false,
      isPlaceholder: false,
    },
    status: "allowed",
    futureEnforcementKey: "guard.page.action-contracts.preview",
  },
  {
    key: "action.createPurchaseRequest",
    label: { zh: "新建采购需求动作", en: "Create Purchase Request Action" },
    scope: "action",
    targetModule: "procurement",
    targetAction: "createPurchaseRequest",
    condition: {
      requiredPermission: "procurement.create",
      requiredRole: "purchasing-manager",
      requiredPlan: "ops",
      requiredModule: "procurement",
      requiresAudit: true,
      requiresConfirmation: true,
      isPlaceholder: true,
    },
    status: "placeholder",
    reason: { zh: "当前仅展示动作合同，不执行真实创建。", en: "Currently metadata-only and does not execute a real create flow." },
    futureEnforcementKey: "guard.action.createPurchaseRequest",
  },
  {
    key: "action.approvePurchaseRequestPlaceholder",
    label: { zh: "审批采购需求动作", en: "Approve Purchase Request Action" },
    scope: "action",
    targetModule: "procurement",
    targetAction: "approvePurchaseRequestPlaceholder",
    condition: {
      requiredPermission: "procurement.approve",
      requiredRole: "purchasing-manager",
      requiredPlan: "ops",
      requiredModule: "procurement",
      requiresAudit: true,
      requiresConfirmation: true,
      isPlaceholder: true,
    },
    status: "coming-soon",
    reason: { zh: "审批流能力尚未接入，仅保留访问合同。", en: "Approval flow is not connected yet; only access metadata is defined." },
    futureEnforcementKey: "guard.action.approvePurchaseRequest",
  },
  {
    key: "action.adjustStockPlaceholder",
    label: { zh: "库存调整动作", en: "Adjust Stock Action" },
    scope: "action",
    targetModule: "inventory",
    targetAction: "adjustStockPlaceholder",
    condition: {
      requiredPermission: "inventory.edit",
      requiredRole: "warehouse-handler",
      requiredPlan: "ops",
      requiredModule: "inventory",
      requiresAudit: true,
      requiresConfirmation: true,
      isPlaceholder: true,
    },
    status: "coming-soon",
    reason: { zh: "库存调整仍是占位能力。", en: "Stock adjustment remains a placeholder capability." },
    futureEnforcementKey: "guard.action.adjustStock",
  },
  {
    key: "action.assignTask",
    label: { zh: "分派任务动作", en: "Assign Task Action" },
    scope: "action",
    targetModule: "task",
    targetAction: "assignTask",
    condition: {
      requiredPermission: "task.assign",
      requiredRole: "store-manager",
      requiredPlan: "ops",
      requiredModule: "task",
      requiresAudit: true,
      requiresConfirmation: true,
      isPlaceholder: true,
    },
    status: "coming-soon",
    reason: { zh: "任务分派在本里程碑仅做合同预览。", en: "Task assignment remains contract preview only in this milestone." },
    futureEnforcementKey: "guard.action.assignTask",
  },
  {
    key: "action.closeTask",
    label: { zh: "关闭任务动作", en: "Close Task Action" },
    scope: "action",
    targetModule: "task",
    targetAction: "closeTask",
    condition: {
      requiredPermission: "task.close",
      requiredRole: "store-manager",
      requiredPlan: "ops",
      requiredModule: "task",
      requiresAudit: true,
      requiresConfirmation: true,
      isPlaceholder: true,
    },
    status: "blocked",
    reason: { zh: "关闭任务属于破坏性操作，暂未开放。", en: "Task closure is destructive and remains blocked for now." },
    futureEnforcementKey: "guard.action.closeTask",
  },
  {
    key: "action.exportTasksPlaceholder",
    label: { zh: "导出任务动作", en: "Export Tasks Action" },
    scope: "action",
    targetModule: "task",
    targetAction: "exportTasksPlaceholder",
    condition: {
      requiredPermission: "task.export",
      requiredRole: "operations-manager",
      requiredPlan: "ops",
      requiredModule: "task",
      requiresAudit: true,
      requiresConfirmation: false,
      isPlaceholder: true,
    },
    status: "placeholder",
    reason: { zh: "导出能力仅提供权限合同占位。", en: "Export capability currently provides access metadata only." },
    futureEnforcementKey: "guard.action.exportTasks",
  },
]

export const accessRulesByKey: Record<string, AccessRule> = Object.fromEntries(accessRules.map((rule) => [rule.key, rule]))
