import type { SkinConfig } from "@/types/skin";

export const skinRegistry: SkinConfig[] = [
  {
    code: "classic",
    name: { zh: "经典皮肤", en: "Classic Skin" },
    description: { zh: "标准企业 SaaS 风格，适合大多数模块页面。", en: "Standard enterprise SaaS style for most module pages." },
    density: "comfortable",
    radius: "rounded",
    shadow: "subtle",
    navigation: "sidebar",
    preferredShell: "responsive",
    componentStyle: "default",
    supportedPageTypes: ["dashboard", "listing", "detail", "form", "report", "settings"],
    themeSupport: ["bright", "dark", "moon"],
    roleTargets: ["operator", "manager", "admin"],
  },
  {
    code: "premium",
    name: { zh: "高级皮肤", en: "Premium Skin" },
    description: { zh: "更强调品牌质感、层次感与演示表现。", en: "A brand-forward skin with stronger layering and presentation quality." },
    density: "comfortable",
    radius: "soft",
    shadow: "layered",
    navigation: "tabs",
    preferredShell: "desktop",
    componentStyle: "premium",
    supportedPageTypes: ["dashboard", "listing", "detail", "report"],
    themeSupport: ["bright", "dark", "moon"],
    roleTargets: ["sales", "manager", "admin"],
  },
  {
    code: "compact",
    name: { zh: "紧凑皮肤", en: "Compact Skin" },
    description: { zh: "提升信息密度，适合高频操作与列表扫描。", en: "Higher information density for frequent operations and table scanning." },
    density: "dense",
    radius: "sharp",
    shadow: "subtle",
    navigation: "sidebar",
    preferredShell: "desktop",
    componentStyle: "dense",
    supportedPageTypes: ["listing", "detail", "report", "settings"],
    themeSupport: ["bright", "dark"],
    roleTargets: ["operator", "admin"],
  },
  {
    code: "manager",
    name: { zh: "管理者皮肤", en: "Manager Skin" },
    description: { zh: "强调分栏、上下文抽屉与跟进视图的管理者皮肤。", en: "Manager-focused skin emphasizing split view, drawers, and follow-up context." },
    density: "comfortable",
    radius: "rounded",
    shadow: "elevated",
    navigation: "split-nav",
    preferredShell: "tablet",
    componentStyle: "soft",
    supportedPageTypes: ["dashboard", "listing", "detail", "issue", "report"],
    themeSupport: ["bright", "dark", "moon"],
    roleTargets: ["manager", "regional-ops"],
  },
  {
    code: "mobile-execution",
    name: { zh: "移动执行皮肤", en: "Mobile Execution Skin" },
    description: { zh: "适合门店执行与任务推进的移动优先皮肤。", en: "Mobile-first skin optimized for execution tasks and store follow-up." },
    density: "compact",
    radius: "rounded",
    shadow: "subtle",
    navigation: "bottom-nav",
    preferredShell: "mobile",
    componentStyle: "outlined",
    supportedPageTypes: ["dashboard", "listing", "detail", "issue", "form"],
    themeSupport: ["bright", "dark", "moon"],
    roleTargets: ["staff", "store-supervisor"],
  },
  {
    code: "desktop-admin",
    name: { zh: "后台桌面皮肤", en: "Desktop Admin Skin" },
    description: { zh: "适合后台配置、报表和设置中心的桌面管理皮肤。", en: "Desktop-focused admin skin for configuration, reporting, and settings centers." },
    density: "comfortable",
    radius: "sharp",
    shadow: "elevated",
    navigation: "sidebar",
    preferredShell: "desktop",
    componentStyle: "minimal",
    supportedPageTypes: ["dashboard", "listing", "detail", "report", "settings"],
    themeSupport: ["bright", "dark", "moon"],
    roleTargets: ["admin", "ops-owner"],
  },
];

export function getSkinConfig(code?: SkinConfig["code"]) {
  return skinRegistry.find((skin) => skin.code === (code ?? "classic")) ?? skinRegistry[0];
}
