import { ModulePageConfig } from "@/components/module/module-page-shell";

function rows(seed: string, entries: Array<[string, string, string, string, string?]>) {
  return entries.map((entry, idx) => ({
    id: `${seed}-${idx + 1}`,
    title: entry[0],
    subtitle: entry[1],
    status: entry[2],
    meta: entry[3],
    owner: entry[4],
  }));
}

export const modulePages: Record<string, ModulePageConfig> = {
  inspection: {
    title: "Inspection",
    description: "Daily branch checklist, hygiene audit, stock checks, and opening or closing reviews.",
    primaryAction: "New Inspection",
    kpis: [
      { label: "Today Inspections", value: "38" },
      { label: "Pending Review", value: "9" },
      { label: "Failed Items", value: "14" },
      { label: "Completion Rate", value: "92%" },
    ],
    chips: ["Today", "Pending", "Failed", "Completed"],
    searchPlaceholder: "Search branch or checklist",
    tableTitle: "Inspection",
    detailTitle: "Inspection Detail",
    rows: rows("inspection", [
      ["KLCC Opening Checklist", "KLCC Branch", "Pending Review", "12 min ago", "Nadia"],
      ["Kitchen Hygiene Audit", "Setia Alam", "Failed", "31 min ago", "Rafiq"],
      ["Closing Stock Verification", "Bangsar South", "Completed", "1 hour ago", "Irene"],
    ]).map((row, idx) => {
      const detailByRow = [
        {
          detailItems: [
            { label: "Checklist Name", value: "Opening Hygiene Checklist" },
            { label: "Branch", value: "KLCC Branch" },
            { label: "Score", value: "86%" },
            { label: "Failed Items", value: "2" },
            { label: "Inspector", value: "Nadia" },
            { label: "Review Status", value: "Pending Review" },
            { label: "Last Checked", value: "Today 09:12" },
          ],
          nextAction: "Submit Review",
          detailNote: "Next action: confirm corrective checks before lunch peak.",
        },
        {
          detailItems: [
            { label: "Checklist Name", value: "Kitchen Hygiene Audit" },
            { label: "Branch", value: "Setia Alam" },
            { label: "Score", value: "74%" },
            { label: "Failed Items", value: "4" },
            { label: "Inspector", value: "Rafiq" },
            { label: "Review Status", value: "Failed" },
            { label: "Last Checked", value: "Today 08:53" },
          ],
          nextAction: "Open Corrective Task",
          detailNote: "Next action: assign sanitation follow-up to shift supervisor.",
        },
        {
          detailItems: [
            { label: "Checklist Name", value: "Closing Stock Verification" },
            { label: "Branch", value: "Bangsar South" },
            { label: "Score", value: "95%" },
            { label: "Failed Items", value: "0" },
            { label: "Inspector", value: "Irene" },
            { label: "Review Status", value: "Completed" },
            { label: "Last Checked", value: "Yesterday 22:05" },
          ],
          nextAction: "Archive Record",
          detailNote: "Next action: archive and sync to daily branch report.",
        },
      ];
      return { ...row, ...detailByRow[idx] };
    }),
  },
  issues: {
    title: "Issue Center",
    description: "Operational issue queue across branches with severity tracking and follow-up ownership.",
    primaryAction: "Report Issue",
    kpis: [
      { label: "Open Issues", value: "27" },
      { label: "Critical", value: "4" },
      { label: "In Review", value: "8" },
      { label: "Resolved Today", value: "11" },
    ],
    chips: ["Critical", "Open", "My Branch", "Resolved"],
    searchPlaceholder: "Search issue",
    tableTitle: "Issue",
    detailTitle: "Issue Detail",
    rows: rows("issues", [
      ["Cold Storage Temperature Spike", "Johor Bahru Branch", "Critical", "8 min ago", "Ops Lead"],
      ["POS Printer Offline", "KL Sentral Branch", "In Review", "22 min ago", "IT Support"],
      ["Supplier Delivery Delay", "Petaling Jaya Branch", "Open", "45 min ago", "Branch Manager"],
    ]).map((row, idx) => {
      const detailByRow = [
        {
          detailItems: [
            { label: "Issue Title", value: "Cold Storage Temperature Spike" },
            { label: "Severity", value: "Critical" },
            { label: "Branch", value: "Johor Bahru Branch" },
            { label: "Owner", value: "Ops Lead" },
            { label: "Status", value: "Open" },
            { label: "Reported Time", value: "Today 10:08" },
          ],
          nextAction: "Escalate Incident",
          detailNote: "Timeline: alert triggered, technician dispatched, product isolation in progress.",
        },
        {
          detailItems: [
            { label: "Issue Title", value: "POS Printer Offline" },
            { label: "Severity", value: "High" },
            { label: "Branch", value: "KL Sentral Branch" },
            { label: "Owner", value: "IT Support" },
            { label: "Status", value: "In Review" },
            { label: "Reported Time", value: "Today 09:54" },
          ],
          nextAction: "Approve Temporary Workaround",
          detailNote: "Timeline: failover to backup counter, driver reinstall pending.",
        },
        {
          detailItems: [
            { label: "Issue Title", value: "Supplier Delivery Delay" },
            { label: "Severity", value: "Medium" },
            { label: "Branch", value: "Petaling Jaya Branch" },
            { label: "Owner", value: "Branch Manager" },
            { label: "Status", value: "Open" },
            { label: "Reported Time", value: "Today 09:31" },
          ],
          nextAction: "Confirm Revised ETA",
          detailNote: "Timeline: supplier acknowledged delay; fallback stock transfer suggested.",
        },
      ];
      return { ...row, ...detailByRow[idx] };
    }),
  },
  tasks: {
    title: "Tasks",
    description: "Task assignment and operational follow-up for store teams.",
    primaryAction: "New Task",
    kpis: [
      { label: "Open Tasks", value: "64" },
      { label: "Due Today", value: "19" },
      { label: "Overdue", value: "7" },
      { label: "Completed", value: "42" },
    ],
    chips: ["My Tasks", "Due Today", "Overdue", "Completed"],
    searchPlaceholder: "Search task",
    tableTitle: "Task",
    detailTitle: "Task Detail",
    rows: rows("tasks", [
      ["Check freezer gasket condition", "Subang Branch", "Due Today", "Today 16:30", "Amir"],
      ["Verify incoming produce batch", "Cheras Branch", "Open", "Today 17:00", "Farah"],
      ["Resolve handwash sink leak", "Damansara Branch", "Overdue", "Yesterday", "Maintenance"],
    ]).map((row, idx) => {
      const detailByRow = [
        {
          detailItems: [
            { label: "Task Title", value: "Check freezer gasket condition" },
            { label: "Branch", value: "Subang Branch" },
            { label: "Owner", value: "Amir" },
            { label: "Due Time", value: "Today 16:30" },
            { label: "Priority", value: "High" },
            { label: "Checklist / Progress", value: "6 of 8 checks done" },
            { label: "Completion Status", value: "In Progress" },
          ],
          nextAction: "Complete Remaining Checks",
          detailNote: "Next step: verify seal integrity and upload photo evidence.",
        },
        {
          detailItems: [
            { label: "Task Title", value: "Verify incoming produce batch" },
            { label: "Branch", value: "Cheras Branch" },
            { label: "Owner", value: "Farah" },
            { label: "Due Time", value: "Today 17:00" },
            { label: "Priority", value: "Medium" },
            { label: "Checklist / Progress", value: "2 of 5 checks done" },
            { label: "Completion Status", value: "Open" },
          ],
          nextAction: "Continue Batch Validation",
          detailNote: "Next step: complete quality sampling and sign receiving log.",
        },
        {
          detailItems: [
            { label: "Task Title", value: "Resolve handwash sink leak" },
            { label: "Branch", value: "Damansara Branch" },
            { label: "Owner", value: "Maintenance" },
            { label: "Due Time", value: "Yesterday 18:00" },
            { label: "Priority", value: "Critical" },
            { label: "Checklist / Progress", value: "1 of 4 checks done" },
            { label: "Completion Status", value: "Overdue" },
          ],
          nextAction: "Escalate Vendor Callout",
          detailNote: "Next step: submit emergency fix approval and update ETA.",
        },
      ];
      return { ...row, ...detailByRow[idx] };
    }),
  },
  expiry: {
    title: "Expiry Control",
    description: "Track expiring ingredients and product batches before loss.",
    primaryAction: "Add Expiry Item",
    kpis: [
      { label: "Expiring Today", value: "23" },
      { label: "Expiring Soon", value: "67" },
      { label: "Checked Today", value: "48" },
      { label: "Wasted / Disposed", value: "6" },
    ],
    chips: ["Today", "3 Days", "Expired", "Checked"],
    searchPlaceholder: "Search product or batch",
    tableTitle: "Expiry Item",
    detailTitle: "Expiry Detail",
    rows: rows("expiry", [
      ["Fresh Milk 2L", "Batch M23019 · Chiller A", "Expiring Today", "Today", "Storekeeper"],
      ["Chicken Fillet", "Batch C44102 · Freezer 2", "3 Days", "12 May", "Kitchen Lead"],
      ["Yogurt Cup", "Batch Y88310 · Front Cooler", "Expired", "10 May", "Supervisor"],
    ]).map((row, idx) => {
      const detailByRow = [
        {
          detailItems: [
            { label: "Product / Item", value: "Fresh Milk 2L" },
            { label: "Batch", value: "M23019" },
            { label: "Storage", value: "Chiller A" },
            { label: "Expiry Date", value: "May 11, 2026" },
            { label: "Remaining Days", value: "0 days" },
            { label: "Checked By", value: "Storekeeper" },
            { label: "Action Required", value: "Use or transfer by noon" },
            { label: "Disposal / Check Status", value: "Pending final check" },
          ],
          nextAction: "Confirm Disposition",
        },
        {
          detailItems: [
            { label: "Product / Item", value: "Chicken Fillet" },
            { label: "Batch", value: "C44102" },
            { label: "Storage", value: "Freezer 2" },
            { label: "Expiry Date", value: "May 12, 2026" },
            { label: "Remaining Days", value: "3 days" },
            { label: "Checked By", value: "Kitchen Lead" },
            { label: "Action Required", value: "Rotate into prep plan" },
            { label: "Disposal / Check Status", value: "Checked today" },
          ],
          nextAction: "Add To Prep Priority",
        },
        {
          detailItems: [
            { label: "Product / Item", value: "Yogurt Cup" },
            { label: "Batch", value: "Y88310" },
            { label: "Storage", value: "Front Cooler" },
            { label: "Expiry Date", value: "May 10, 2026" },
            { label: "Remaining Days", value: "-1 day" },
            { label: "Checked By", value: "Supervisor" },
            { label: "Action Required", value: "Dispose and record waste" },
            { label: "Disposal / Check Status", value: "Awaiting sign-off" },
          ],
          nextAction: "Complete Disposal Log",
        },
      ];
      return { ...row, ...detailByRow[idx] };
    }),
  },
  sop: {
    title: "SOP Library",
    description: "Standard operating procedure references for branch execution and training alignment.",
    primaryAction: "Add SOP",
    kpis: [
      { label: "Active SOPs", value: "86" },
      { label: "Need Review", value: "12" },
      { label: "Training Linked", value: "53" },
      { label: "Recently Updated", value: "9" },
    ],
    chips: ["Kitchen", "Service", "Safety", "HR"],
    searchPlaceholder: "Search SOP",
    tableTitle: "SOP",
    detailTitle: "SOP Detail",
    rows: rows("sop", [
      ["Daily Opening Procedure", "Kitchen · v3.2", "Active", "Updated 2 days ago", "Operations"],
      ["Food Allergy Handling", "Service · v1.9", "Need Review", "Updated 9 days ago", "QA"],
      ["Incident Escalation", "Safety · v2.1", "Active", "Updated 14 days ago", "Risk Team"],
    ]).map((row, idx) => {
      const detailByRow = [
        {
          detailItems: [
            { label: "SOP Title", value: "Daily Opening Procedure" },
            { label: "Category", value: "Kitchen" },
            { label: "Version", value: "v3.2" },
            { label: "Owner", value: "Operations" },
            { label: "Linked Training", value: "Opening Shift Basics" },
            { label: "Review Due", value: "June 15, 2026" },
            { label: "Last Updated", value: "2 days ago" },
          ],
          nextAction: "Open SOP",
        },
        {
          detailItems: [
            { label: "SOP Title", value: "Food Allergy Handling" },
            { label: "Category", value: "Service" },
            { label: "Version", value: "v1.9" },
            { label: "Owner", value: "QA" },
            { label: "Linked Training", value: "Allergen Response Training" },
            { label: "Review Due", value: "May 20, 2026" },
            { label: "Last Updated", value: "9 days ago" },
          ],
          nextAction: "Open SOP",
        },
        {
          detailItems: [
            { label: "SOP Title", value: "Incident Escalation" },
            { label: "Category", value: "Safety" },
            { label: "Version", value: "v2.1" },
            { label: "Owner", value: "Risk Team" },
            { label: "Linked Training", value: "Incident Escalation Drill" },
            { label: "Review Due", value: "July 1, 2026" },
            { label: "Last Updated", value: "14 days ago" },
          ],
          nextAction: "Open SOP",
        },
      ];
      return { ...row, ...detailByRow[idx] };
    }),
  },
  staff: {
    title: "Staff",
    description: "Staff directory, current workforce status, and profile review.",
    primaryAction: "Add Staff",
    kpis: [
      { label: "Active Staff", value: "1,204" },
      { label: "On Shift Today", value: "388" },
      { label: "Pending Docs", value: "15" },
      { label: "New Staff", value: "29" },
    ],
    chips: ["Branch", "Role", "Active", "New"],
    searchPlaceholder: "Search staff",
    tableTitle: "Staff",
    detailTitle: "Profile Preview",
    rows: rows("staff", [
      ["Aina Syahirah", "Shift Supervisor · KLCC", "Active", "Today 09:11", "HR Ops"],
      ["Daniel Kho", "Cashier · Mid Valley", "On Shift", "Today 10:02", "Branch Lead"],
      ["Magesh Kumar", "Kitchen Crew · SS2", "Pending Docs", "Yesterday", "HR Admin"],
    ]),
  },
  schedule: {
    title: "Schedule",
    description: "Weekly shift planning with branch and role coverage checks.",
    primaryAction: "Create Schedule",
    secondaryAction: "Publish",
    kpis: [
      { label: "Scheduled Today", value: "372" },
      { label: "Coverage Gaps", value: "5" },
      { label: "Pending Confirmation", value: "18" },
      { label: "Total Hours", value: "3,146" },
    ],
    chips: ["This Week", "Branch", "Shift", "Role"],
    searchPlaceholder: "Search shift or staff",
    tableTitle: "Shift Plan",
    detailTitle: "Schedule Preview",
    rows: rows("schedule", [
      ["Morning Shift · KLCC", "Mon 08:00-16:00", "Pending Confirmation", "Week 20", "Scheduling"],
      ["Night Shift · Sunway", "Mon 14:00-22:00", "Active", "Week 20", "Scheduling"],
      ["Weekend Support · Penang", "Sat 10:00-18:00", "Coverage Gap", "Week 20", "Workforce"],
    ]),
  },
  training: {
    title: "Training",
    description: "Course catalog and team training progress tracking.",
    primaryAction: "Add Course",
    kpis: [
      { label: "Active Courses", value: "24" },
      { label: "In Progress", value: "112" },
      { label: "Completed", value: "386" },
      { label: "Overdue Training", value: "13" },
    ],
    chips: ["Required", "In Progress", "Completed", "Overdue"],
    searchPlaceholder: "Search course or staff",
    tableTitle: "Course",
    detailTitle: "Training Progress",
    rows: rows("training", [
      ["Food Safety Level 1", "Required for kitchen crew", "In Progress", "Due 16 May", "L&D Team"],
      ["Service Recovery Basics", "Frontline team", "Completed", "Updated yesterday", "L&D Team"],
      ["Cash Handling Controls", "Cashier role", "Overdue", "Due 9 May", "Branch Managers"],
    ]),
  },
  roles: {
    title: "Roles",
    description: "Role assignments and permission overview for workforce operations.",
    primaryAction: "Add Role",
    kpis: [
      { label: "Total Roles", value: "18" },
      { label: "Assigned Staff", value: "1,204" },
      { label: "Permission Groups", value: "42" },
      { label: "Review Needed", value: "6" },
    ],
    chips: ["Store", "Manager", "Admin", "Custom"],
    searchPlaceholder: "Search role",
    tableTitle: "Role",
    detailTitle: "Permission Preview",
    rows: rows("roles", [
      ["Branch Manager", "Approvals, staffing, escalation", "Active", "Updated 4 days ago", "System Admin"],
      ["Shift Supervisor", "Task assignment, checklist sign-off", "Review Needed", "Updated 9 days ago", "HR Ops"],
      ["Kitchen Crew", "Operational execution only", "Active", "Updated 15 days ago", "System Admin"],
    ]),
  },
  reports: {
    title: "Reports",
    description: "Business reporting library for operations, sales, workforce, and finance insights.",
    primaryAction: "Create Report",
    kpis: [
      { label: "Available Reports", value: "57" },
      { label: "Scheduled Reports", value: "19" },
      { label: "Generated Today", value: "34" },
      { label: "Attention Needed", value: "5" },
    ],
    chips: ["Sales", "Stock", "Staff", "Finance"],
    searchPlaceholder: "Search report",
    tableTitle: "Report",
    detailTitle: "Report Preview",
    rows: rows("reports", [
      ["Daily Sales by Branch", "Category: Sales · Daily", "Active", "Generated 08:00", "BI Team"],
      ["Waste & Expiry Snapshot", "Category: Stock · Daily", "Attention Needed", "Generated 09:00", "Operations"],
      ["Labor Cost Ratio", "Category: Staff · Weekly", "Active", "Generated Mon", "Finance"],
    ]),
  },
  "reports-pos": {
    title: "POS Report",
    description: "Point-of-sale sales performance and refund variance analysis.",
    primaryAction: "Generate Report",
    secondaryAction: "Import POS Report",
    kpis: [
      { label: "Net Sales", value: "MYR 468,200" },
      { label: "Transactions", value: "9,412" },
      { label: "Average Ticket", value: "MYR 49.74" },
      { label: "Variance / Refunds", value: "MYR 6,190" },
    ],
    chips: ["Date Range", "Branch", "Sales", "Refund"],
    searchPlaceholder: "Search POS entry or receipt",
    tableTitle: "POS Entry",
    rows: rows("pos", [
      ["KLCC · Lunch Window", "12:00-14:00", "Sales", "Today", "POS Sync"],
      ["Mid Valley · Refund Batch", "Cashier Counter 3", "Refund", "Today", "Store Ops"],
      ["Penang · Card Settlement", "Day End", "Payment", "Yesterday", "Finance"],
    ]),
  },
  finance: {
    title: "Finance",
    description: "Revenue and expense records with review pipeline.",
    primaryAction: "Add Record",
    kpis: [
      { label: "Revenue", value: "MYR 2.31M" },
      { label: "Expenses", value: "MYR 1.44M" },
      { label: "Gross Margin", value: "37.7%" },
      { label: "Pending Review", value: "18" },
    ],
    chips: ["Revenue", "Expense", "Pending", "Approved"],
    searchPlaceholder: "Search financial record",
    tableTitle: "Record",
    detailTitle: "Finance Summary",
    rows: rows("finance", [
      ["Branch Utilities · April", "Expense · Operations", "Pending Review", "Today 10:15", "Finance Ops"],
      ["POS Settlement · Weekend", "Revenue · Retail", "Approved", "Today 08:40", "Accounts"],
      ["Maintenance Invoice", "Expense · Facility", "Approved", "Yesterday", "Finance Ops"],
    ]),
  },
  branches: {
    title: "Branches",
    description: "Branch directory with current operating status and management ownership.",
    primaryAction: "Add Branch",
    kpis: [
      { label: "Total Branches", value: "24" },
      { label: "Active Branches", value: "22" },
      { label: "Open Today", value: "21" },
      { label: "Need Attention", value: "3" },
    ],
    chips: ["Region", "Active", "Closed", "Attention"],
    searchPlaceholder: "Search branch",
    tableTitle: "Branch",
    detailTitle: "Branch Preview",
    rows: rows("branches", [
      ["KLCC", "Central Region", "Active", "Updated 12 min ago", "Nadia"],
      ["Penang Gurney", "North Region", "Need Attention", "Updated 34 min ago", "Azman"],
      ["Johor Bahru", "South Region", "Open", "Updated 1 hour ago", "Suresh"],
    ]).map((row, idx) => {
      const detailByRow = [
        {
          detailItems: [
            { label: "Branch Status", value: "Active" },
            { label: "Manager", value: "Nadia" },
            { label: "Today Sales", value: "MYR 28,750" },
            { label: "Open Tasks", value: "5" },
            { label: "Stock Alerts", value: "2" },
            { label: "Inspection Score", value: "94%" },
            { label: "Last Sync / Last Activity", value: "Synced 4 min ago" },
          ],
          nextAction: "Open Branch Detail",
        },
        {
          detailItems: [
            { label: "Branch Status", value: "Need Attention" },
            { label: "Manager", value: "Azman" },
            { label: "Today Sales", value: "MYR 19,320" },
            { label: "Open Tasks", value: "7" },
            { label: "Stock Alerts", value: "3" },
            { label: "Inspection Score", value: "87%" },
            { label: "Last Sync / Last Activity", value: "Synced 12 min ago" },
          ],
          nextAction: "Open Branch Detail",
        },
        {
          detailItems: [
            { label: "Branch Status", value: "Open" },
            { label: "Manager", value: "Suresh" },
            { label: "Today Sales", value: "MYR 24,610" },
            { label: "Open Tasks", value: "4" },
            { label: "Stock Alerts", value: "1" },
            { label: "Inspection Score", value: "91%" },
            { label: "Last Sync / Last Activity", value: "Synced 7 min ago" },
          ],
          nextAction: "Open Branch Detail",
        },
      ];
      return { ...row, ...detailByRow[idx] };
    }),
  },
  packages: {
    title: "Packages",
    description: "Subscription package and module bundle assignment across branches.",
    primaryAction: "Create Package",
    kpis: [
      { label: "Active Packages", value: "11" },
      { label: "Assigned Branches", value: "24" },
      { label: "Modules Included", value: "37" },
      { label: "Renewal Needed", value: "2" },
    ],
    chips: ["Active", "Draft", "Expiring", "Custom"],
    searchPlaceholder: "Search package",
    tableTitle: "Package",
    rows: rows("packages", [
      ["Enterprise Ops Suite", "Annual · 12 modules", "Active", "Renews Oct 2026", "Commercial"],
      ["Regional Growth Bundle", "Quarterly · 8 modules", "Expiring", "Renews Jun 2026", "Commercial"],
      ["Custom Analytics Add-on", "Monthly · 3 modules", "Draft", "Updated this week", "Product"],
    ]),
  },
  stakeholder: {
    title: "Stakeholder Summary",
    description: "Executive snapshot of business performance, risks, and decision backlog.",
    primaryAction: "Export Summary",
    kpis: [
      { label: "Business Health", value: "Strong" },
      { label: "Open Risks", value: "7" },
      { label: "Weekly Progress", value: "84%" },
      { label: "Pending Decisions", value: "5" },
    ],
    searchPlaceholder: "Search summary section",
    tableTitle: "Summary Section",
    rows: rows("stakeholder", [
      ["Revenue & Margin", "Week-over-week trend", "Active", "Updated 09:00", "Finance"],
      ["Operations Risk", "Critical incidents and mitigation", "Review Needed", "Updated 10:10", "Ops"],
      ["Expansion Readiness", "New branch onboarding", "Active", "Updated 11:25", "Executive PMO"],
    ]),
  },
  settings: {
    title: "Settings",
    description: "Workspace configuration for appearance, branch defaults, notifications, and security.",
    primaryAction: "Save Changes",
    kpis: [
      { label: "Workspace", value: "Configured" },
      { label: "Appearance", value: "Standard" },
      { label: "Branch Defaults", value: "22 Applied" },
      { label: "Security", value: "Policy Active" },
    ],
    searchPlaceholder: "Search setting",
    tableTitle: "Setting Section",
    rows: rows("settings", [
      ["Workspace Profile", "Name, timezone, locale", "Active", "Updated today", "Admin"],
      ["Notification Defaults", "Escalation and digest rules", "Active", "Updated yesterday", "Admin"],
      ["Security Policy", "Session and access guardrails", "Review Needed", "Updated this week", "Security"],
    ]),
  },
  access: {
    title: "Access Control",
    description: "User access, roles, and restricted area governance.",
    primaryAction: "Add Access Rule",
    kpis: [
      { label: "Active Users", value: "1,326" },
      { label: "Roles", value: "18" },
      { label: "Restricted Areas", value: "12" },
      { label: "Review Needed", value: "9" },
    ],
    chips: ["Admin", "Manager", "Staff", "Restricted"],
    searchPlaceholder: "Search user or role",
    tableTitle: "Access Rule",
    detailTitle: "Access Detail",
    rows: rows("access", [
      ["Manager Finance Approval", "Role: Branch Manager", "Active", "Updated 13:30", "Security"],
      ["Inventory Cost Visibility", "Role: Staff", "Restricted", "Updated 09:20", "System Admin"],
      ["System Settings Edit", "Role: Admin", "Review Needed", "Updated yesterday", "Security"],
    ]),
  },
  rules: {
    title: "Rules",
    description: "Business and automation rule management with execution status.",
    primaryAction: "Create Rule",
    kpis: [
      { label: "Active Rules", value: "63" },
      { label: "Draft Rules", value: "14" },
      { label: "Failed Runs", value: "3" },
      { label: "Last Updated", value: "11:25" },
    ],
    chips: ["Active", "Draft", "Error", "System"],
    searchPlaceholder: "Search rule",
    tableTitle: "Rule",
    rows: rows("rules", [
      ["Auto Escalate Critical Issues", "If unresolved > 30 min", "Active", "Run today", "Automation"],
      ["Stock Alert Threshold", "If stock < min level", "Draft", "Updated 2 days ago", "Operations"],
      ["Refund Variance Check", "If variance > 2%", "Failed", "Run 08:12", "Finance"],
    ]),
  },
  notifications: {
    title: "Notifications",
    description: "Notification center and channel rule control.",
    primaryAction: "Create Notification Rule",
    kpis: [
      { label: "Sent Today", value: "1,942" },
      { label: "Unread", value: "213" },
      { label: "Failed", value: "12" },
      { label: "Active Channels", value: "4" },
    ],
    chips: ["Unread", "Failed", "System", "Staff"],
    searchPlaceholder: "Search notification",
    tableTitle: "Notification",
    detailTitle: "Notification Detail",
    rows: rows("notifications", [
      ["Critical Issue Escalation", "Channel: App + Email", "Active", "Sent 10:11", "System"],
      ["Training Reminder", "Channel: App", "Unread", "Sent 09:22", "L&D"],
      ["Shift Confirmation", "Channel: App + SMS", "Failed", "Sent 08:49", "Workforce"],
    ]),
  },
  integration: {
    title: "Integrations",
    description: "Connector setup, sync health, and connection lifecycle management.",
    primaryAction: "Add Connector",
    kpis: [
      { label: "Connected", value: "9" },
      { label: "Needs Setup", value: "5" },
      { label: "Sync Issues", value: "2" },
      { label: "Last Sync", value: "3 min ago" },
    ],
    chips: ["Connected", "Setup Required", "Error", "Available"],
    searchPlaceholder: "Search connector",
    tableTitle: "Connector",
    rows: rows("integration", [
      ["POS Gateway", "Sales data ingest", "Connected", "Synced 3 min ago", "Platform"],
      ["Payroll Provider", "Workforce data sync", "Setup Required", "Updated today", "HR Tech"],
      ["Accounting API", "Finance posting", "Error", "Sync failed 08:32", "Finance Systems"],
    ]),
  },
  workflow: {
    title: "Workflow",
    description: "Operational workflow automation and approval routing.",
    primaryAction: "Create Workflow",
    kpis: [
      { label: "Active Workflows", value: "31" },
      { label: "Runs Today", value: "486" },
      { label: "Failed Runs", value: "6" },
      { label: "Pending Approval", value: "17" },
    ],
    chips: ["Active", "Draft", "Failed", "Approval"],
    searchPlaceholder: "Search workflow",
    tableTitle: "Workflow",
    rows: rows("workflow", [
      ["New Staff Onboarding", "HR to branch to system setup", "Active", "Ran 22 min ago", "HR Ops"],
      ["Issue Closure Approval", "Supervisor review chain", "Pending Approval", "Updated 11:03", "Store Ops"],
      ["Daily Branch Summary", "Automated report flow", "Failed", "Run 07:50", "BI Team"],
    ]),
  },
  templates: {
    title: "Templates",
    description: "Template library for SOP, report, form, and message standards.",
    primaryAction: "Create Template",
    kpis: [
      { label: "Active Templates", value: "73" },
      { label: "Used This Week", value: "214" },
      { label: "Need Review", value: "10" },
      { label: "Categories", value: "4" },
    ],
    chips: ["SOP", "Report", "Form", "Message"],
    searchPlaceholder: "Search template",
    tableTitle: "Template",
    rows: rows("templates", [
      ["Incident Report Form", "Category: Form", "Active", "Updated last week", "Risk Team"],
      ["Weekly Sales Digest", "Category: Report", "Need Review", "Updated 3 weeks ago", "BI Team"],
      ["New Hire Orientation", "Category: SOP", "Active", "Updated yesterday", "L&D"],
    ]),
  },
  audit: {
    title: "Audit Trail",
    description: "System activity logs for operational, user, and configuration events.",
    primaryAction: "Export Audit Log",
    kpis: [
      { label: "Events Today", value: "12,448" },
      { label: "Critical Events", value: "18" },
      { label: "User Changes", value: "241" },
      { label: "System Changes", value: "84" },
    ],
    chips: ["Today", "Critical", "User", "System"],
    searchPlaceholder: "Search event or user",
    tableTitle: "Event",
    rows: rows("audit", [
      ["Permission rule updated", "User: admin.sarah", "Critical", "11:18", "Security"],
      ["Branch settings saved", "User: manager.aina", "User", "10:42", "Operations"],
      ["Workflow deployment", "System job", "System", "09:15", "Automation"],
    ]),
  },
  "layout-engine": {
    title: "Layout Engine",
    description: "Internal layout schema and rendering policy controls.",
    primaryAction: "Update Layout Policy",
    kpis: [
      { label: "Active Layout Profiles", value: "6" },
      { label: "Recent Changes", value: "12" },
      { label: "Validation Errors", value: "0" },
      { label: "Published", value: "5" },
    ],
    searchPlaceholder: "Search layout profile",
    tableTitle: "Layout Profile",
    rows: rows("layout", [
      ["Manager Workspace", "Desktop + tablet shell", "Active", "Updated today", "Platform"],
      ["Quick Ops Mobile", "Mobile operation cards", "Published", "Updated yesterday", "Platform"],
      ["Detail Panel Rules", "Split layout behavior", "Draft", "Updated this week", "UX Systems"],
    ]),
  },
  navigation: {
    title: "Navigation",
    description: "Internal navigation map and route grouping governance.",
    primaryAction: "Update Navigation",
    kpis: [
      { label: "Module Groups", value: "4" },
      { label: "Active Routes", value: "31" },
      { label: "Pending Changes", value: "3" },
      { label: "Broken Links", value: "0" },
    ],
    searchPlaceholder: "Search route",
    tableTitle: "Route",
    rows: rows("nav", [
      ["Store Operations", "Inspection, Issues, Tasks, Expiry, SOP", "Active", "Updated today", "Platform"],
      ["Workforce", "Staff, Schedule, Training, Roles", "Active", "Updated today", "Platform"],
      ["System", "Settings and internal controls", "Review Needed", "Updated this week", "Architecture"],
    ]),
  },
  components: {
    title: "Components",
    description: "Internal component catalog status for ME product consistency.",
    primaryAction: "Review Component Set",
    kpis: [
      { label: "Registered Components", value: "48" },
      { label: "In Use", value: "41" },
      { label: "Deprecated", value: "3" },
      { label: "Needs Review", value: "4" },
    ],
    searchPlaceholder: "Search component",
    tableTitle: "Component",
    rows: rows("components", [
      ["Module Page Shell", "Header, KPI, toolbar rhythm", "Active", "Updated today", "UI Platform"],
      ["Data Table Shell", "Desktop listing layout", "Active", "Updated today", "UI Platform"],
      ["Detail Panel", "Contextual preview panel", "Review Needed", "Updated 4 days ago", "UX Team"],
    ]),
  },
  "display-settings": {
    title: "Display Settings",
    description: "Workspace display controls for readability and operational clarity.",
    primaryAction: "Save Display Settings",
    kpis: [
      { label: "Profiles", value: "3" },
      { label: "Default Theme", value: "Bright" },
      { label: "Density Mode", value: "Comfortable" },
      { label: "Last Changed", value: "Today" },
    ],
    searchPlaceholder: "Search display setting",
    tableTitle: "Display Policy",
    rows: rows("display", [
      ["Manager Default", "Desktop spacing and KPI emphasis", "Active", "Updated today", "Design Ops"],
      ["Store Floor Mobile", "Card-first compact layout", "Active", "Updated this week", "Product"],
      ["Accessibility Contrast", "High-contrast variant", "Draft", "Updated yesterday", "Design Ops"],
    ]),
  },
  "demo-mode": {
    title: "Presentation Mode",
    description: "Controlled presentation settings for guided product walkthrough sessions.",
    primaryAction: "Update Presentation Mode",
    kpis: [
      { label: "Active Presets", value: "4" },
      { label: "Locked Data Views", value: "7" },
      { label: "Session Templates", value: "5" },
      { label: "Last Session", value: "2 days ago" },
    ],
    searchPlaceholder: "Search presentation setting",
    tableTitle: "Presentation Preset",
    rows: rows("presentation", [
      ["Executive Walkthrough", "Summary-first sequence", "Active", "Updated this week", "Product"],
      ["Branch Operations Tour", "Store operations focus", "Active", "Updated today", "Solutions"],
      ["Finance Deep Dive", "Revenue and expense storyline", "Draft", "Updated yesterday", "Solutions"],
    ]),
  },
  "demo-readiness": {
    title: "Readiness Check",
    description: "Internal readiness checklist for presentations and guided demonstrations.",
    primaryAction: "Run Readiness Check",
    kpis: [
      { label: "Checklist Items", value: "36" },
      { label: "Passed", value: "31" },
      { label: "Needs Attention", value: "5" },
      { label: "Last Run", value: "Today" },
    ],
    searchPlaceholder: "Search readiness item",
    tableTitle: "Readiness Item",
    rows: rows("readiness", [
      ["Store Operations Flows", "Inspection to issue closure", "Passed", "Checked today", "QA"],
      ["Workforce Screens", "Schedule and training paths", "Needs Attention", "Checked today", "QA"],
      ["System Access Matrix", "Role permission validation", "Passed", "Checked yesterday", "Security"],
    ]),
  },
  "demo-story": {
    title: "Walkthrough Story",
    description: "Narrative sequence management for internal product walkthroughs.",
    primaryAction: "Update Walkthrough",
    kpis: [
      { label: "Story Sections", value: "12" },
      { label: "Published", value: "9" },
      { label: "In Review", value: "3" },
      { label: "Last Edit", value: "Today" },
    ],
    searchPlaceholder: "Search story step",
    tableTitle: "Story Step",
    rows: rows("story", [
      ["Operational Control", "Day-to-day branch management", "Published", "Updated today", "Product"],
      ["People & Staffing", "Workforce workflow", "In Review", "Updated today", "People Ops"],
      ["Executive Insights", "Business summary arc", "Published", "Updated yesterday", "BI Team"],
    ]),
  },
  "system-foundation": {
    title: "System Foundation",
    description: "Core platform policies and foundation-level governance for ME modules.",
    primaryAction: "Update Foundation",
    kpis: [
      { label: "Core Policies", value: "14" },
      { label: "Dependency Maps", value: "8" },
      { label: "Pending Reviews", value: "2" },
      { label: "Last Audit", value: "This week" },
    ],
    searchPlaceholder: "Search foundation policy",
    tableTitle: "Foundation Policy",
    rows: rows("foundation", [
      ["Module Contract Baseline", "Shared shell + data rules", "Active", "Audited this week", "Architecture"],
      ["Design Token Governance", "Spacing and typography rhythm", "Active", "Audited this week", "Design Ops"],
      ["Permission Boundary", "Cross-module access constraints", "Review Needed", "Audited last week", "Security"],
    ]),
  },
  "action-contracts": {
    title: "Action Contracts",
    description: "Action payload definitions and execution contract monitoring.",
    primaryAction: "Create Contract",
    kpis: [
      { label: "Active Contracts", value: "92" },
      { label: "Versioned", value: "84" },
      { label: "Breaking Changes", value: "1" },
      { label: "Pending Review", value: "6" },
    ],
    searchPlaceholder: "Search action contract",
    tableTitle: "Contract",
    rows: rows("contracts", [
      ["Issue Escalation Action", "Store Operations module", "Active", "Updated today", "Platform"],
      ["Schedule Publish Action", "Workforce module", "Versioned", "Updated yesterday", "Workforce Eng"],
      ["Finance Approval Action", "Business module", "Pending Review", "Updated this week", "Finance Systems"],
    ]),
  },
};
