export type BranchLocale = "en" | "zh";

export const branchLanguageCopy = {
  en: {
    page: {
      title: "Branch Management",
      subtitle: "Manage branch operating status, performance, staffing, tasks, and alerts across all stores.",
      breadcrumbs: ["ME", "Store Operations", "Branch Management"],
    },
    actions: {
      addBranch: "Add Branch",
      createBranch: "Create Branch",
      export: "Export",
      viewReports: "View Reports",
      openTasks: "Open Tasks",
      importBranches: "Import Branches",
      batchEdit: "Batch Edit",
      deleteArchive: "Delete Archive",
      createTask: "Create Task",
      more: "More",
      manage: "Manage",
    },
    kpis: {
      totalBranches: "Total Branches",
      openStores: "Open Stores",
      todaySales: "Today Sales",
      openTasks: "Open Tasks",
      stockAlerts: "Stock Alerts",
      staffOnDuty: "Staff On Duty",
      inspectionScore: "Inspection Score",
      criticalIssues: "Critical Issues",
    },
    filters: {
      allBranches: "All Branches",
      allRegions: "All Regions",
      allStatus: "All Status",
      moreFilters: "More Filters",
      searchPlaceholder: "Search branch, region, manager...",
    },
    fields: {
      branchName: "Branch Name",
      branchCode: "Branch Code",
      region: "Region",
      manager: "Manager",
      phone: "Phone",
      address: "Address",
      status: "Status",
    },
    detail: {
      currentShift: "Current Shift",
      recentActivity: "Recent Activity",
      regionSuffix: "Region",
      upcoming: "Content will be available soon.",
      salesInsightPrefix: "Sales for",
      salesInsightSuffix: "are up by 12% compared to last week. Productivity is high.",
      todayOperationSummary: "Today Operation Summary",
      staffOnDuty: "Staff on Duty",
      persons: "Persons",
      salesProgress: "Sales Progress",
      stockHealth: "Stock Health",
      staffCoverage: "Staff Coverage",
      inventoryAlerts: "Inventory Alerts",
      staffOnDutyTitle: "Staff On Duty",
      branchInsights: "Branch Insights",
      topAlerts: "Top Alerts",
      inventoryCritical: "Inventory Critical",
      scheduledTomorrow: "Scheduled for tomorrow",
      quickLinks: "Quick Links",
      viewAll: "View All",
      viewFullTimeline: "View Full Timeline",
      lastUpdate: "Last Update",
      inspection: "Inspection",
      targetSuffix: "of target",
      performanceUp: "Performance Up",
      itemsBelowThreshold: "items below threshold",
      inspectionDue: "Inspection Due",
      left: "left",
      good: "Good",
      warning: "Warning",
      high: "High",
      medium: "Medium",
      low: "Low",
      open: "Open",
      inProgress: "In Progress",
    },
    mobileCards: {
      todaySales: "Today Sales",
      openTasks: "Open Tasks",
      stockAlerts: "Stock Alerts",
    },
    quickLinks: {
      viewBranchReport: "View branch report",
      openTasks: "Open tasks",
      inventoryAlerts: "Inventory alerts",
      openInspection: "Open inspection",
      procurementRequest: "Procurement request",
    },
    tabs: {
      overview: "Overview",
      branchHealth: "Branch Health",
      todayOperations: "Today Operations",
      relatedRecords: "Related Records",
      tasks: "Tasks",
      activity: "Activity",
    },
    status: {
      operating: "Operating",
      attention: "Attention",
      preparation: "Preparation",
      inactive: "Inactive",
    },
  },
  zh: {
    page: {
      title: "门店管理",
      subtitle: "管理所有门店的营运状态、绩效、人手、任务与警报。",
      breadcrumbs: ["ME", "门店营运", "门店管理"],
    },
    actions: {
      addBranch: "新增门店",
      createBranch: "创建门店",
      export: "导出",
      viewReports: "查看报表",
      openTasks: "打开任务",
      importBranches: "导入门店",
      batchEdit: "批量编辑",
      deleteArchive: "归档门店",
      createTask: "创建任务",
      more: "更多",
      manage: "管理",
    },
    kpis: {
      totalBranches: "门店总数",
      openStores: "营业门店",
      todaySales: "今日销售",
      openTasks: "未完成任务",
      stockAlerts: "库存警报",
      staffOnDuty: "在岗员工",
      inspectionScore: "巡检评分",
      criticalIssues: "紧急问题",
    },
    filters: {
      allBranches: "全部门店",
      allRegions: "全部区域",
      allStatus: "全部状态",
      moreFilters: "更多筛选",
      searchPlaceholder: "搜索门店、区域、负责人...",
    },
    fields: {
      branchName: "门店名称",
      branchCode: "门店编号",
      region: "区域",
      manager: "负责人",
      phone: "电话",
      address: "地址",
      status: "状态",
    },
    detail: {
      currentShift: "当前班次",
      recentActivity: "最近动态",
      regionSuffix: "区域",
      upcoming: "内容即将开放。",
      salesInsightPrefix: "",
      salesInsightSuffix: "较上周提升 12%。当前生产效率良好。",
      todayOperationSummary: "今日营运摘要",
      staffOnDuty: "在岗员工",
      persons: "人",
      salesProgress: "销售进度",
      stockHealth: "库存健康",
      staffCoverage: "人手覆盖",
      inventoryAlerts: "库存警报",
      staffOnDutyTitle: "在岗员工",
      branchInsights: "门店洞察",
      topAlerts: "重点警报",
      inventoryCritical: "库存紧急",
      scheduledTomorrow: "已安排明天处理",
      quickLinks: "快捷入口",
      viewAll: "查看全部",
      viewFullTimeline: "查看完整时间线",
      lastUpdate: "最后更新",
      inspection: "巡检",
      targetSuffix: "目标",
      performanceUp: "表现上升",
      itemsBelowThreshold: "项低于安全线",
      inspectionDue: "巡检到期",
      left: "剩余",
      good: "良好",
      warning: "警告",
      high: "高",
      medium: "中",
      low: "低",
      open: "待处理",
      inProgress: "处理中",
    },
    mobileCards: {
      todaySales: "今日销售",
      openTasks: "未完成任务",
      stockAlerts: "库存警报",
    },
    quickLinks: {
      viewBranchReport: "查看门店报表",
      openTasks: "打开任务",
      inventoryAlerts: "库存警报",
      openInspection: "打开巡检",
      procurementRequest: "采购申请",
    },
    tabs: {
      overview: "概览",
      branchHealth: "门店健康",
      todayOperations: "今日营运",
      relatedRecords: "关联记录",
      tasks: "任务",
      activity: "动态",
    },
    status: {
      operating: "营运中",
      attention: "需关注",
      preparation: "准备中",
      inactive: "未启用",
    },
  },
} as const;

export function getBranchCopy(locale: BranchLocale) {
  return branchLanguageCopy[locale] ?? branchLanguageCopy.en;
}
