import type { MeControlRegistryItem } from "@/types/control-registry";

export const controlRegistry: MeControlRegistryItem[] = [
  {
    key: "global.search",
    label: "Global Search",
    module: "system",
    route: "*",
    layer: "UI_ONLY",
    behavior: "update_search_input",
    status: "active_preview",
    allowedNow: true,
    executionBoundary: "client_ui_state_only",
    uiFeedback: "updates search text field only",
    futureConnection: "global_search_api",
  },
  {
    key: "global.branch_selector",
    label: "Branch Selector",
    module: "system",
    route: "*",
    layer: "UI_ONLY",
    behavior: "open_branch_selector",
    status: "active_preview",
    allowedNow: true,
    executionBoundary: "client_ui_state_only",
    uiFeedback: "opens branch selection dropdown",
    futureConnection: "branch_context_service",
  },
  {
    key: "global.date_selector",
    label: "Date Selector",
    module: "system",
    route: "*",
    layer: "UI_ONLY",
    behavior: "open_date_selector",
    status: "active_preview",
    allowedNow: true,
    executionBoundary: "client_ui_state_only",
    uiFeedback: "opens date range dropdown",
    futureConnection: "reporting_date_service",
  },
  {
    key: "global.sidebar_collapse",
    label: "Sidebar Collapse",
    module: "system",
    route: "*",
    layer: "UI_ONLY",
    behavior: "toggle_sidebar_visibility",
    status: "active_preview",
    allowedNow: true,
    executionBoundary: "client_ui_state_only",
    uiFeedback: "show or hide desktop sidebar",
    futureConnection: null,
  },
  {
    key: "global.sidebar_group_collapse",
    label: "Sidebar Group Collapse",
    module: "system",
    route: "*",
    layer: "UI_ONLY",
    behavior: "toggle_sidebar_group",
    status: "active_preview",
    allowedNow: true,
    executionBoundary: "client_ui_state_only",
    uiFeedback: "expand or collapse a navigation group",
    futureConnection: null,
  },
  {
    key: "global.mobile_module_launcher",
    label: "Mobile Module Launcher",
    module: "system",
    route: "*",
    layer: "UI_ONLY",
    behavior: "open_mobile_module_sheet",
    status: "active_preview",
    allowedNow: true,
    executionBoundary: "client_ui_state_only",
    uiFeedback: "opens mobile all-modules launcher sheet",
    futureConnection: null,
  },

  {
    key: "table.saved_views",
    label: "Saved Views",
    module: "operations",
    route: "/psi/*",
    layer: "UI_ONLY",
    behavior: "switch_saved_view_tab",
    status: "active_preview",
    allowedNow: true,
    executionBoundary: "client_ui_state_only",
    uiFeedback: "switches local table view tab",
    futureConnection: "saved_views_service",
  },
  {
    key: "table.filters",
    label: "Filters",
    module: "operations",
    route: "/psi/*",
    layer: "UI_ONLY",
    behavior: "open_filter_chips",
    status: "active_preview",
    allowedNow: true,
    executionBoundary: "client_ui_state_only",
    uiFeedback: "shows filter chips and local filter UI",
    futureConnection: "filter_query_service",
  },
  {
    key: "table.columns",
    label: "Columns",
    module: "operations",
    route: "/psi/*",
    layer: "UI_ONLY",
    behavior: "open_columns_panel",
    status: "active_preview",
    allowedNow: true,
    executionBoundary: "client_ui_state_only",
    uiFeedback: "opens column visibility panel",
    futureConnection: null,
  },
  {
    key: "table.density",
    label: "Density",
    module: "operations",
    route: "/psi/*",
    layer: "UI_ONLY",
    behavior: "toggle_density_preview",
    status: "active_preview",
    allowedNow: true,
    executionBoundary: "client_ui_state_only",
    uiFeedback: "shows density switch preview",
    futureConnection: null,
  },
  {
    key: "table.sort",
    label: "Sort",
    module: "operations",
    route: "/psi/*",
    layer: "UI_ONLY",
    behavior: "open_sort_preview",
    status: "active_preview",
    allowedNow: true,
    executionBoundary: "client_ui_state_only",
    uiFeedback: "opens sort options preview",
    futureConnection: "table_sort_query",
  },
  {
    key: "table.export",
    label: "Export Preview",
    module: "operations",
    route: "/psi/*",
    layer: "PREVIEW_ACTION",
    behavior: "show_export_preview",
    status: "preview_only",
    allowedNow: true,
    executionBoundary: "no_file_generation_execution",
    uiFeedback: "shows export preview action",
    futureConnection: "export_service",
  },
  {
    key: "table.more_filters",
    label: "More Filters",
    module: "operations",
    route: "/psi/*",
    layer: "UI_ONLY",
    behavior: "open_more_filters_drawer",
    status: "active_preview",
    allowedNow: true,
    executionBoundary: "client_ui_state_only",
    uiFeedback: "opens advanced filter drawer",
    futureConnection: "advanced_filter_service",
  },
  {
    key: "table.row_selection",
    label: "Row Selection",
    module: "operations",
    route: "/psi/*",
    layer: "UI_ONLY",
    behavior: "select_table_row",
    status: "active_preview",
    allowedNow: true,
    executionBoundary: "client_ui_state_only",
    uiFeedback: "marks rows as selected",
    futureConnection: null,
  },
  {
    key: "table.clear_selection",
    label: "Clear Selection",
    module: "operations",
    route: "/psi/*",
    layer: "UI_ONLY",
    behavior: "clear_selected_rows",
    status: "active_preview",
    allowedNow: true,
    executionBoundary: "client_ui_state_only",
    uiFeedback: "clears selected rows in current table",
    futureConnection: null,
  },

  {
    key: "procurement.approve_preview",
    label: "Approve Preview",
    module: "procurement",
    route: "/psi/procurement",
    layer: "PREVIEW_ACTION",
    behavior: "show_approve_preview",
    status: "preview_only",
    allowedNow: true,
    executionBoundary: "no_approval_execution",
    uiFeedback: "opens approve preview panel",
    futureConnection: "procurement_approve_api",
  },
  {
    key: "procurement.reject_preview",
    label: "Reject Preview",
    module: "procurement",
    route: "/psi/procurement",
    layer: "PREVIEW_ACTION",
    behavior: "show_reject_preview",
    status: "preview_only",
    allowedNow: true,
    executionBoundary: "no_approval_execution",
    uiFeedback: "opens reject preview panel",
    futureConnection: "procurement_reject_api",
  },
  {
    key: "procurement.link_receiving_preview",
    label: "Link Receiving Preview",
    module: "procurement",
    route: "/psi/procurement",
    layer: "PREVIEW_ACTION",
    behavior: "show_link_receiving_preview",
    status: "preview_only",
    allowedNow: true,
    executionBoundary: "no_database_write",
    uiFeedback: "opens link receiving preview",
    futureConnection: "receiving_link_api",
  },

  {
    key: "supplier.create_pr_preview",
    label: "Create PR Preview",
    module: "supplier",
    route: "/psi/supplier",
    layer: "PREVIEW_ACTION",
    behavior: "show_create_pr_preview",
    status: "preview_only",
    allowedNow: true,
    executionBoundary: "no_database_write",
    uiFeedback: "opens create PR preview from supplier",
    futureConnection: "procurement_request_create_api",
  },
  {
    key: "supplier.add_note_preview",
    label: "Add Note Preview",
    module: "supplier",
    route: "/psi/supplier",
    layer: "PREVIEW_ACTION",
    behavior: "show_add_note_preview",
    status: "preview_only",
    allowedNow: true,
    executionBoundary: "no_database_write",
    uiFeedback: "opens add-note preview dialog",
    futureConnection: "notes_write_api",
  },

  {
    key: "inventory.create_pr_preview",
    label: "Create PR Preview",
    module: "inventory",
    route: "/psi/inventory",
    layer: "PREVIEW_ACTION",
    behavior: "show_create_pr_preview",
    status: "preview_only",
    allowedNow: true,
    executionBoundary: "no_database_write",
    uiFeedback: "opens create PR preview from inventory",
    futureConnection: "procurement_request_create_api",
  },
  {
    key: "inventory.count_stock_preview",
    label: "Count Stock Preview",
    module: "inventory",
    route: "/psi/inventory",
    layer: "PREVIEW_ACTION",
    behavior: "show_count_stock_preview",
    status: "preview_only",
    allowedNow: true,
    executionBoundary: "no_stock_posting_execution",
    uiFeedback: "opens stock count preview",
    futureConnection: "stock_count_write_api",
  },

  {
    key: "receiving.review_variance_preview",
    label: "Review Variance Preview",
    module: "receiving",
    route: "/psi/receiving",
    layer: "PREVIEW_ACTION",
    behavior: "show_variance_review_preview",
    status: "preview_only",
    allowedNow: true,
    executionBoundary: "no_write_execution",
    uiFeedback: "opens variance review preview",
    futureConnection: "variance_review_api",
  },
  {
    key: "receiving.post_stock_preview",
    label: "Post Stock Preview",
    module: "receiving",
    route: "/psi/receiving",
    layer: "PREVIEW_ACTION",
    behavior: "show_post_stock_preview",
    status: "preview_only",
    allowedNow: true,
    executionBoundary: "no_stock_posting_execution",
    uiFeedback: "opens post stock preview",
    futureConnection: "stock_post_api",
  },

  {
    key: "formula.coverage_days",
    label: "Coverage Days",
    module: "inventory",
    route: "/psi/inventory",
    layer: "FORMULA_METADATA",
    behavior: "display_formula_metadata",
    status: "metadata_only",
    allowedNow: true,
    executionBoundary: "no_formula_engine_execution",
    uiFeedback: "shows formula name and metadata block",
    futureConnection: "formula_engine",
  },
  {
    key: "formula.stock_risk",
    label: "Stock Risk",
    module: "inventory",
    route: "/psi/inventory",
    layer: "FORMULA_METADATA",
    behavior: "display_formula_metadata",
    status: "metadata_only",
    allowedNow: true,
    executionBoundary: "no_formula_engine_execution",
    uiFeedback: "shows stock risk metadata",
    futureConnection: "formula_engine",
  },
  {
    key: "formula.reorder_suggestion",
    label: "Reorder Suggestion",
    module: "inventory",
    route: "/psi/inventory",
    layer: "FORMULA_METADATA",
    behavior: "display_formula_metadata",
    status: "metadata_only",
    allowedNow: true,
    executionBoundary: "no_formula_engine_execution",
    uiFeedback: "shows reorder formula metadata",
    futureConnection: "formula_engine",
  },
  {
    key: "formula.cost_variance",
    label: "Cost Variance",
    module: "finance",
    route: "/finance",
    layer: "FORMULA_METADATA",
    behavior: "display_formula_metadata",
    status: "metadata_only",
    allowedNow: true,
    executionBoundary: "no_formula_engine_execution",
    uiFeedback: "shows cost variance formula metadata",
    futureConnection: "formula_engine",
  },
  {
    key: "formula.margin_preview",
    label: "Margin Preview",
    module: "finance",
    route: "/finance",
    layer: "FORMULA_METADATA",
    behavior: "display_formula_metadata",
    status: "metadata_only",
    allowedNow: true,
    executionBoundary: "no_formula_engine_execution",
    uiFeedback: "shows margin formula metadata",
    futureConnection: "formula_engine",
  },

  {
    key: "brain.suggested_reorder_reason",
    label: "Suggested Reorder Reason",
    module: "inventory",
    route: "/psi/inventory",
    layer: "BRAIN_METADATA",
    behavior: "display_brain_metadata",
    status: "metadata_only",
    allowedNow: true,
    executionBoundary: "no_brain_execution",
    uiFeedback: "shows static reorder reason metadata",
    futureConnection: "brain_suggestion_service",
  },
  {
    key: "brain.supplier_risk_reason",
    label: "Supplier Risk Reason",
    module: "supplier",
    route: "/psi/supplier",
    layer: "BRAIN_METADATA",
    behavior: "display_brain_metadata",
    status: "metadata_only",
    allowedNow: true,
    executionBoundary: "no_brain_execution",
    uiFeedback: "shows static supplier risk reason",
    futureConnection: "brain_suggestion_service",
  },
  {
    key: "brain.variance_reason",
    label: "Variance Reason",
    module: "receiving",
    route: "/psi/receiving",
    layer: "BRAIN_METADATA",
    behavior: "display_brain_metadata",
    status: "metadata_only",
    allowedNow: true,
    executionBoundary: "no_brain_execution",
    uiFeedback: "shows static receiving variance reason",
    futureConnection: "brain_suggestion_service",
  },
  {
    key: "brain.task_priority_reason",
    label: "Task Priority Reason",
    module: "tasks",
    route: "/tasks",
    layer: "BRAIN_METADATA",
    behavior: "display_brain_metadata",
    status: "metadata_only",
    allowedNow: true,
    executionBoundary: "no_brain_execution",
    uiFeedback: "shows static task priority reason",
    futureConnection: "brain_suggestion_service",
  },

  {
    key: "future.create_pr",
    label: "Create PR",
    module: "procurement",
    route: "/psi/procurement",
    layer: "FUTURE_WRITE",
    behavior: "create_procurement_request",
    status: "future_write_disabled",
    allowedNow: false,
    executionBoundary: "no_database_write",
    uiFeedback: "disabled pending write API",
    futureConnection: "procurement_request_create_api",
  },
  {
    key: "future.approve_pr",
    label: "Approve PR",
    module: "procurement",
    route: "/psi/procurement",
    layer: "FUTURE_WRITE",
    behavior: "approve_procurement_request",
    status: "future_write_disabled",
    allowedNow: false,
    executionBoundary: "no_approval_execution",
    uiFeedback: "disabled pending approval workflow",
    futureConnection: "procurement_approve_api",
  },
  {
    key: "future.post_stock",
    label: "Post Stock",
    module: "receiving",
    route: "/psi/receiving",
    layer: "FUTURE_WRITE",
    behavior: "post_stock_movement",
    status: "future_write_disabled",
    allowedNow: false,
    executionBoundary: "no_stock_posting_execution",
    uiFeedback: "disabled pending inventory write layer",
    futureConnection: "stock_post_api",
  },
  {
    key: "future.create_task",
    label: "Create Task",
    module: "tasks",
    route: "/tasks",
    layer: "FUTURE_WRITE",
    behavior: "create_task",
    status: "future_write_disabled",
    allowedNow: false,
    executionBoundary: "no_database_write",
    uiFeedback: "disabled pending task write API",
    futureConnection: "task_create_api",
  },
  {
    key: "future.update_supplier",
    label: "Update Supplier",
    module: "supplier",
    route: "/psi/supplier",
    layer: "FUTURE_WRITE",
    behavior: "update_supplier",
    status: "future_write_disabled",
    allowedNow: false,
    executionBoundary: "no_database_write",
    uiFeedback: "disabled pending supplier write API",
    futureConnection: "supplier_update_api",
  },
  {
    key: "future.update_inventory",
    label: "Update Inventory",
    module: "inventory",
    route: "/psi/inventory",
    layer: "FUTURE_WRITE",
    behavior: "update_inventory_record",
    status: "future_write_disabled",
    allowedNow: false,
    executionBoundary: "no_database_write",
    uiFeedback: "disabled pending inventory write API",
    futureConnection: "inventory_update_api",
  },

  {
    key: "integration.pos",
    label: "POS Integration",
    module: "integration",
    route: "/integration",
    layer: "EXTERNAL_INTEGRATION",
    behavior: "show_integration_status",
    status: "integration_not_connected",
    allowedNow: false,
    executionBoundary: "no_external_connection",
    uiFeedback: "shows Not Connected",
    futureConnection: "pos_connector",
  },
  {
    key: "integration.google_sheets",
    label: "Google Sheets Integration",
    module: "integration",
    route: "/integration",
    layer: "EXTERNAL_INTEGRATION",
    behavior: "show_integration_status",
    status: "integration_not_connected",
    allowedNow: false,
    executionBoundary: "no_external_connection",
    uiFeedback: "shows Pending Setup",
    futureConnection: "google_sheets_connector",
  },
  {
    key: "integration.supabase",
    label: "Supabase Integration",
    module: "integration",
    route: "/integration",
    layer: "EXTERNAL_INTEGRATION",
    behavior: "show_integration_status",
    status: "integration_not_connected",
    allowedNow: false,
    executionBoundary: "no_external_connection",
    uiFeedback: "shows Pending Setup",
    futureConnection: "supabase_connector",
  },
  {
    key: "integration.wms",
    label: "WMS Integration",
    module: "integration",
    route: "/integration",
    layer: "EXTERNAL_INTEGRATION",
    behavior: "show_integration_status",
    status: "integration_not_connected",
    allowedNow: false,
    executionBoundary: "no_external_connection",
    uiFeedback: "shows Not Connected",
    futureConnection: "wms_connector",
  },
  {
    key: "integration.accounting",
    label: "Accounting Integration",
    module: "integration",
    route: "/integration",
    layer: "EXTERNAL_INTEGRATION",
    behavior: "show_integration_status",
    status: "integration_not_connected",
    allowedNow: false,
    executionBoundary: "no_external_connection",
    uiFeedback: "shows Pending Setup",
    futureConnection: "accounting_connector",
  },
  {
    key: "integration.whatsapp",
    label: "WhatsApp Integration",
    module: "integration",
    route: "/integration",
    layer: "EXTERNAL_INTEGRATION",
    behavior: "show_integration_status",
    status: "integration_not_connected",
    allowedNow: false,
    executionBoundary: "no_external_connection",
    uiFeedback: "shows Pending Setup",
    futureConnection: "whatsapp_connector",
  },
  {
    key: "integration.printer",
    label: "Printer Integration",
    module: "integration",
    route: "/integration",
    layer: "EXTERNAL_INTEGRATION",
    behavior: "show_integration_status",
    status: "integration_not_connected",
    allowedNow: false,
    executionBoundary: "no_external_connection",
    uiFeedback: "shows Not Connected",
    futureConnection: "printer_connector",
  },
];
