import type {
  MeDemoReadinessChecklistItem,
  MeDemoReadinessLocalizedText,
  MeDemoReadinessSection,
} from "@/types/demo-readiness";

function localized(zh: string, en: string): MeDemoReadinessLocalizedText {
  return { zh, en };
}

function createItem(item: MeDemoReadinessChecklistItem): MeDemoReadinessChecklistItem {
  return item;
}

function createSection(section: MeDemoReadinessSection): MeDemoReadinessSection {
  return section;
}

export const meDemoReadinessGeneratedAt = "2026-05-06T00:00:00.000Z";

export const meDemoReadinessNotice = localized(
  "静态 QA 占位层，仅用于演示准备检查；不包含监控、分析、追踪、浏览器自动化、运行时爬取或 CI 变更。",
  "Static QA placeholder for presentation readiness only. No monitoring, analytics, tracking, browser automation, runtime crawling, or CI changes are included.",
);

const routeCompletenessItems: MeDemoReadinessChecklistItem[] = [
  createItem({
    key: "route-homepage",
    title: localized("首页 / 业务工作台", "Homepage / Business Workspace"),
    description: localized(
      "确认首页继续作为 ME Business Workspace，并保留业务优先的演示开场。",
      "Confirms the homepage remains ME Business Workspace and keeps a business-first presentation opener.",
    ),
    category: "route-completeness",
    status: "pass",
    tone: "success",
    route: "/",
    relatedRoutes: ["/demo-story", "/demo-mode", "/stakeholder-summary"],
    evidence: [
      localized("首页继续是业务工作台，而不是链接中心。", "The homepage stays business-first instead of becoming a link hub."),
      localized("保留 Demo、Stakeholder 与基础层入口。", "Demo, stakeholder, and foundation entry points remain visible."),
    ],
    notes: localized("仅做展示 QA，不添加运行时校验。", "Presentation QA only with no runtime validation added."),
    isPlaceholder: false,
  }),
  createItem({
    key: "route-navigation",
    title: localized("导航 IA", "Navigation IA"),
    description: localized(
      "确认 `/navigation` 继续展示业务导航、运营导航与系统基础层结构。",
      "Confirms `/navigation` continues to expose business, operations, and system-foundation IA.",
    ),
    category: "route-completeness",
    status: "pass",
    tone: "success",
    route: "/navigation",
    relatedRoutes: ["/", "/system-foundation", "/demo-readiness"],
    evidence: [
      localized("共享导航配置继续作为单一事实来源。", "Shared navigation config remains the single source of truth."),
      localized("次级链接区可容纳 Demo Readiness。", "The secondary-link area can host Demo Readiness safely."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "route-roles",
    title: localized("角色工作区", "Roles"),
    description: localized(
      "确认角色总览与详情路由仍可作为只读讲解入口。",
      "Confirms role overview and detail routes remain available as read-only presentation surfaces.",
    ),
    category: "route-completeness",
    status: "pass",
    tone: "success",
    route: "/roles",
    relatedRoutes: ["/roles/owner", "/roles/store-manager", "/navigation"],
    evidence: [
      localized("角色路由继续存在并复用共享导航。", "Role routes still exist and reuse the shared navigation layer."),
      localized("未引入真实权限执行。", "No live permission enforcement is introduced."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "route-branches",
    title: localized("门店上下文", "Branches"),
    description: localized(
      "确认门店总览与详情路由仍可作为门店叙事入口。",
      "Confirms branch overview and detail routes remain available for branch-context storytelling.",
    ),
    category: "route-completeness",
    status: "pass",
    tone: "success",
    route: "/branches",
    relatedRoutes: ["/branches/all-stores", "/branches/kch", "/reports"],
    evidence: [
      localized("All Stores、KCH、BTU 与 Future Branch 继续可访问。", "All Stores, KCH, BTU, and Future Branch remain available."),
      localized("未引入真实租户数据库或持久化切换。", "No live tenant database or persisted switching is introduced."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "route-demo-story",
    title: localized("Demo Story", "Demo Story"),
    description: localized(
      "确认 `/demo-story` 继续作为路由叙事编排层。",
      "Confirms `/demo-story` remains the route-orchestration layer for the presentation narrative.",
    ),
    category: "route-completeness",
    status: "pass",
    tone: "success",
    route: "/demo-story",
    relatedRoutes: ["/demo-story/business-overview", "/demo-mode", "/demo-readiness"],
    evidence: [
      localized("步骤数据继续来自静态配置。", "Step data continues to come from static config."),
      localized("现可把 Demo Readiness 作为 walkthrough QA 下一步。", "Demo Readiness can now follow the walkthrough as the QA next step."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "route-demo-mode",
    title: localized("Demo Mode", "Demo Mode"),
    description: localized(
      "确认 `/demo-mode` 继续作为截图与展示 framing 层。",
      "Confirms `/demo-mode` remains the screenshot-ready framing layer.",
    ),
    category: "route-completeness",
    status: "pass",
    tone: "success",
    route: "/demo-mode",
    relatedRoutes: ["/demo-story", "/stakeholder-summary", "/demo-readiness"],
    evidence: [
      localized("展示徽标、截图清单与路线顺序继续保持静态。", "Presentation badges, screenshot guidance, and route order remain static."),
      localized("新增最终 QA 跳转，而不是引入真实开关。", "Adds a final QA jump instead of a real toggle or engine."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "route-stakeholder-summary",
    title: localized("Stakeholder Summary", "Stakeholder Summary"),
    description: localized(
      "确认 `/stakeholder-summary` 继续作为 ME 的一页式提案总结层。",
      "Confirms `/stakeholder-summary` remains the one-page ME presentation summary.",
    ),
    category: "route-completeness",
    status: "pass",
    tone: "success",
    route: "/stakeholder-summary",
    relatedRoutes: ["/demo-story", "/demo-mode", "/demo-readiness"],
    evidence: [
      localized("产品层、路线图与演示路由地图继续保持可讲解。", "Product layers, roadmap, and demo route map remain presentation-ready."),
      localized("新增演示 QA 收尾链接。", "Adds a closing QA link for presentation readiness."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "route-psi-workspace",
    title: localized("PSI 工作区", "PSI Workspace"),
    description: localized(
      "确认 `/psi`、`/psi/actions`、`/psi/issues` 仍是只读运营占位层。",
      "Confirms `/psi`, `/psi/actions`, and `/psi/issues` remain read-only operations placeholders.",
    ),
    category: "route-completeness",
    status: "pass",
    tone: "success",
    route: "/psi",
    relatedRoutes: ["/psi/actions", "/psi/issues", "/reports"],
    evidence: [
      localized("PSI 仍可从首页、导航和演示路线进入。", "PSI remains reachable from the homepage, navigation, and demo flow."),
      localized("没有审批、过账或供应商门户。", "There is no approval, posting, or supplier portal flow."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "route-reports",
    title: localized("报表预览", "Reports"),
    description: localized(
      "确认 `/reports` 继续提供 PSI 预览与总结语境。",
      "Confirms `/reports` continues to provide PSI preview and recap context.",
    ),
    category: "route-completeness",
    status: "pass",
    tone: "success",
    route: "/reports",
    relatedRoutes: ["/psi", "/stakeholder-summary", "/demo-readiness"],
    evidence: [
      localized("报表仍是只读汇总层。", "Reports remain a read-only recap layer."),
      localized("无 BI 引擎、导出或调度。", "No BI engine, export flow, or scheduling is connected."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "route-tasks",
    title: localized("任务工作区", "Tasks"),
    description: localized(
      "确认 `/tasks` 继续提供任务队列、来源映射与闭环占位。",
      "Confirms `/tasks` continues to provide task queue, source mapping, and close-loop placeholders.",
    ),
    category: "route-completeness",
    status: "pass",
    tone: "success",
    route: "/tasks",
    relatedRoutes: ["/tasks/TASK-1001", "/psi", "/reports"],
    evidence: [
      localized("任务仍是 mock/read-only preview。", "Tasks remain mock/read-only previews."),
      localized("没有真实任务写入或通知发送。", "No real task write or notification sending is connected."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "route-settings-integration",
    title: localized("设置 / 集成", "Settings / Integration"),
    description: localized(
      "确认 `/settings`、`/integration` 与 connector detail 路由已经进入 preview-safe 管理中心。",
      "Confirms `/settings`, `/integration`, and connector detail routes are preview-safe admin-center surfaces.",
    ),
    category: "route-completeness",
    status: "pass",
    tone: "success",
    route: "/settings",
    relatedRoutes: ["/integration", "/integration/POS-KCH-PRIMARY", "/display-settings"],
    evidence: [
      localized("动作文案已改为 Preview Changes、Preview Sync、Preview Disable。", "Action wording now uses Preview Changes, Preview Sync, and Preview Disable."),
      localized("没有真实 POS、Printer、API、Webhook 或 DB 连接。", "No real POS, printer, API, webhook, or DB connection is added."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "route-access-packages",
    title: localized("访问控制 / 套餐", "Access Control / Packages"),
    description: localized(
      "确认 `/access-control` 与 `/packages` 已经以 contract / catalog preview 方式收口。",
      "Confirms `/access-control` and `/packages` are framed as contract/catalog previews.",
    ),
    category: "route-completeness",
    status: "pass",
    tone: "success",
    route: "/access-control",
    relatedRoutes: ["/roles", "/packages", "/audit-trail"],
    evidence: [
      localized("Role / Access 已移除真实 assign/grant/revoke 语气。", "Role / Access no longer uses real assign/grant/revoke-style UI wording."),
      localized("Package / Plan 使用 Catalog Active、Preview Usable 与 Future Ref 文案。", "Package / Plan uses Catalog Active, Preview Usable, and Future Ref wording."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "route-pos-report",
    title: localized("POS 报表", "POS Reports"),
    description: localized(
      "确认 `/reports/pos` 仍是 POS 销售日报与门店销量的只读预览。",
      "Confirms `/reports/pos` remains a read-only preview for POS daily sales and branch sales.",
    ),
    category: "route-completeness",
    status: "pass",
    tone: "success",
    route: "/reports/pos",
    relatedRoutes: ["/reports", "/integration", "/packages"],
    evidence: [
      localized("POS 报表仍声明无真实 POS integration、payment feed 或 export engine。", "POS reports still state no real POS integration, payment feed, or export engine."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "route-system-foundation",
    title: localized("系统基础层", "System Foundation"),
    description: localized(
      "确认 `/system-foundation` 仍保持次级但可访问的基础层总览。",
      "Confirms `/system-foundation` stays secondary but reachable as the platform-foundation overview.",
    ),
    category: "route-completeness",
    status: "pass",
    tone: "success",
    route: "/system-foundation",
    relatedRoutes: ["/layout-engine", "/action-contracts", "/packages"],
    evidence: [
      localized("基础层链接仍保持完整。", "Foundation links remain intact."),
      localized("新增 QA 审计入口，不改变其次级定位。", "Adds a QA audit link without changing its secondary positioning."),
    ],
    isPlaceholder: false,
  }),
];

const navigationReachabilityItems: MeDemoReadinessChecklistItem[] = [
  createItem({
    key: "nav-topbar-entry-points",
    title: localized("顶栏入口点", "Topbar Entry Points"),
    description: localized(
      "检查顶栏保留 Demo、Stakeholder、Navigation、Foundation 与 Branch 入口，并加入低干扰 QA 链接。",
      "Checks the topbar retains demo, stakeholder, navigation, foundation, and branch links while adding a low-noise QA entry.",
    ),
    category: "navigation-reachability",
    status: "review",
    tone: "info",
    relatedRoutes: ["/demo-story", "/demo-mode", "/stakeholder-summary", "/demo-readiness"],
    evidence: [
      localized("顶栏继续承担跨页面快速切换。", "The topbar continues to serve as a cross-page shortcut surface."),
      localized("Demo Readiness 以次级文字入口接入。", "Demo Readiness is added as a secondary text-level entry."),
    ],
    notes: localized("以展示可达性为主，而不是导航埋点。", "Focused on reachability only, not click instrumentation."),
    isPlaceholder: false,
  }),
  createItem({
    key: "nav-sidebar-footer-links",
    title: localized("侧栏 / Footer 次级链接", "Sidebar / Footer Links"),
    description: localized(
      "检查共享导航的 Footer / Secondary 分组可稳定暴露 Demo Readiness。",
      "Checks the shared navigation footer/secondary group exposes Demo Readiness reliably.",
    ),
    category: "navigation-reachability",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/navigation", "/demo-readiness", "/stakeholder-summary"],
    evidence: [
      localized("共享导航继续复用于侧栏与移动导航。", "Shared navigation continues to drive sidebar and mobile navigation."),
      localized("未删除现有任一路由入口。", "No existing route entry is removed."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "nav-demo-story-cross-links",
    title: localized("Demo Story 交叉链接", "Demo Story Cross-links"),
    description: localized(
      "检查导览页可把讲解流程自然引到最终 QA 页面。",
      "Checks the guided-story flow can hand off naturally into the final QA page.",
    ),
    category: "navigation-reachability",
    status: "review",
    tone: "info",
    relatedRoutes: ["/demo-story", "/demo-readiness", "/stakeholder-summary"],
    evidence: [
      localized("导览页继续引向现有页面而不是生成新流程。", "The story page still links into existing routes instead of creating a new engine."),
      localized("最终 QA 页面补齐 walkthrough 审查层。", "The final QA page adds a walkthrough-review layer."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "nav-demo-mode-cross-links",
    title: localized("Demo Mode 交叉链接", "Demo Mode Cross-links"),
    description: localized(
      "检查截图准备层可把演示者引到最终 QA。",
      "Checks the screenshot-ready layer can route presenters into the final QA surface.",
    ),
    category: "navigation-reachability",
    status: "review",
    tone: "info",
    relatedRoutes: ["/demo-mode", "/demo-readiness", "/stakeholder-summary"],
    evidence: [
      localized("保留截图清单与路线顺序说明。", "Retains screenshot checklist and route-sequence guidance."),
      localized("最终 QA 链接用于收尾检查而不是状态切换。", "The final QA link is for closing checks rather than state changes."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "nav-stakeholder-cross-links",
    title: localized("Stakeholder Summary 交叉链接", "Stakeholder Summary Cross-links"),
    description: localized(
      "检查总结页可回链到 Demo Readiness 作为演示收尾 QA。",
      "Checks the stakeholder summary can link back to Demo Readiness as the closing presentation QA step.",
    ),
    category: "navigation-reachability",
    status: "review",
    tone: "info",
    relatedRoutes: ["/stakeholder-summary", "/demo-readiness", "/demo-story"],
    evidence: [
      localized("总结页继续作为单页提案，而非分享门户。", "The summary remains a one-page presentation surface rather than a sharing portal."),
      localized("加入 QA 回链后仍保持静态。", "It stays static even with the QA back-link added."),
    ],
    isPlaceholder: false,
  }),
];

const presentationConsistencyItems: MeDemoReadinessChecklistItem[] = [
  createItem({
    key: "presentation-screenshot-labels",
    title: localized("截图就绪标签", "Screenshot-ready Labels"),
    description: localized(
      "检查 Demo surfaces 的标签、徽章与说明是否继续支持截图与评审语境。",
      "Checks that demo-surface labels, badges, and notes still support screenshot and review framing.",
    ),
    category: "screenshot-readiness",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/", "/demo-mode", "/stakeholder-summary"],
    evidence: [
      localized("首页与 Demo Mode 保留截图就绪表达。", "The homepage and Demo Mode retain screenshot-ready framing."),
      localized("标签继续是静态文案，不是运行时模式。", "Labels remain static presentation copy rather than a runtime mode."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "presentation-notices",
    title: localized("展示声明一致性", "Presentation Notices"),
    description: localized(
      "检查页面提示继续明确 mock/read-only 与无运行时能力的边界。",
      "Checks that page notices continue to clarify the mock/read-only and non-runtime boundaries.",
    ),
    category: "presentation-consistency",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/demo-story", "/demo-mode", "/stakeholder-summary", "/demo-readiness"],
    evidence: [
      localized("各展示页都保留静态说明。", "Each presentation surface keeps an explicit static notice."),
      localized("Demo Readiness 新增统一 QA 声明。", "Demo Readiness adds a unified QA notice."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "presentation-cta-consistency",
    title: localized("CTA 一致性", "CTA Consistency"),
    description: localized(
      "检查导览、截图、总结与 QA 路由之间的 CTA 保持自然顺序。",
      "Checks CTA flow remains coherent across story, screenshot, summary, and QA routes.",
    ),
    category: "presentation-consistency",
    status: "review",
    tone: "info",
    relatedRoutes: ["/", "/demo-story", "/demo-mode", "/stakeholder-summary", "/demo-readiness"],
    evidence: [
      localized("业务工作台继续是主入口。", "The business workspace remains the primary entry point."),
      localized("Demo Readiness 作为次级 QA CTA 插入。", "Demo Readiness is inserted as a secondary QA CTA."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "presentation-b2b-tone",
    title: localized("B2B SaaS 语气", "Premium B2B Tone"),
    description: localized(
      "检查新页面延续专业、现代、企业级展示语气。",
      "Checks the new page keeps a professional, modern, premium B2B SaaS tone.",
    ),
    category: "presentation-consistency",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/", "/demo-mode", "/demo-readiness"],
    evidence: [
      localized("页面使用指标卡、清单卡与说明文案组合。", "The page uses metric cards, checklist cards, and concise explanatory copy."),
      localized("不引入开发者调试 UI 风格。", "It avoids a developer-debug visual tone."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "presentation-bilingual-layout",
    title: localized("双语友好布局", "Bilingual-friendly Layout"),
    description: localized(
      "检查 zh/en 内容结构保持 UI-safe，并可继续扩展双语展示。",
      "Checks the zh/en content structure remains UI-safe and ready for bilingual presentation.",
    ),
    category: "presentation-consistency",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/demo-readiness", "/stakeholder-summary", "/navigation"],
    evidence: [
      localized("所有 QA 条目、指标与说明均提供 zh/en。", "All QA items, metrics, and notices provide zh/en copy."),
      localized("布局继续沿用现有卡片系统。", "The layout continues to reuse the existing card system."),
    ],
    isPlaceholder: false,
  }),
];

const scopeGuardrailItems: MeDemoReadinessChecklistItem[] = [
  createItem({
    key: "guardrail-no-database",
    title: localized("无真实数据库", "No Real Database"),
    description: localized("确认最终 QA 层没有引入数据库连接或持久化模型。", "Confirms the final QA layer adds no database connection or persistence model."),
    category: "scope-guardrail",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/demo-readiness"],
    evidence: [localized("仅使用静态配置与 helper。", "Uses static config and helper functions only.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "guardrail-no-api",
    title: localized("无 API", "No API"),
    description: localized("确认最终 QA 层没有引入 fetch、axios 或新的服务调用。", "Confirms the final QA layer introduces no fetch, axios, or new service calls."),
    category: "scope-guardrail",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/demo-readiness"],
    evidence: [localized("helper 仅返回静态数据。", "The helper returns static data only.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "guardrail-no-writes",
    title: localized("无真实写操作", "No Real Writes"),
    description: localized("确认最终 QA 层不创建任务、不提交表单、不写入业务状态。", "Confirms the final QA layer creates no tasks, submits no forms, and writes no business state."),
    category: "scope-guardrail",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/demo-readiness", "/psi", "/stakeholder-summary"],
    evidence: [localized("清单只做展示，不执行动作。", "Checklist data is descriptive only and executes nothing.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "guardrail-no-auth-session",
    title: localized("无认证 / Session", "No Auth / Session"),
    description: localized("确认最终 QA 层没有登录、会话、middleware 或运行时权限门控。", "Confirms the final QA layer adds no login, session, middleware, or runtime access gating."),
    category: "scope-guardrail",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/roles", "/system-foundation", "/demo-readiness"],
    evidence: [localized("仍是展示语义，不做权限执行。", "It stays descriptive and does not enforce permissions.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "guardrail-no-analytics-tracking",
    title: localized("无分析 / 追踪", "No Analytics / Tracking"),
    description: localized("确认最终 QA 层不接入 analytics、tracking 或点击记录。", "Confirms the final QA layer does not add analytics, tracking, or click instrumentation."),
    category: "scope-guardrail",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/demo-readiness", "/demo-mode", "/stakeholder-summary"],
    evidence: [localized("仅展示说明性文案。", "Only explanatory copy is displayed.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "guardrail-no-storage",
    title: localized("无 localStorage / sessionStorage", "No localStorage / sessionStorage"),
    description: localized("确认最终 QA 层不引入浏览器存储。", "Confirms the final QA layer introduces no browser storage usage."),
    category: "scope-guardrail",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/demo-readiness", "/demo-story", "/demo-mode"],
    evidence: [localized("状态完全来自配置，不保存在客户端。", "State comes entirely from config and is not stored client-side.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "guardrail-no-permission-enforcement",
    title: localized("无权限执行", "No Permission Enforcement"),
    description: localized("确认 QA 层不会触发真实角色、租户或套餐权限。", "Confirms the QA layer does not trigger real role, tenant, or package enforcement."),
    category: "scope-guardrail",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/roles", "/packages", "/demo-readiness"],
    evidence: [localized("仅审视展示边界，不改变访问规则。", "It audits presentation boundaries only and does not change access rules.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "guardrail-no-workflow",
    title: localized("无工作流执行", "No Workflow Execution"),
    description: localized("确认 QA 层不会触发 workflow、notification 或自动化。", "Confirms the QA layer triggers no workflow, notification, or automation execution."),
    category: "scope-guardrail",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/workflow", "/notifications", "/demo-readiness"],
    evidence: [localized("只读 QA 层不连接后台执行器。", "The read-only QA layer does not connect to any backend executor.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "guardrail-no-monitoring-browser-ci",
    title: localized("无监控 / 浏览器自动化 / CI", "No Monitoring / Browser Automation / CI"),
    description: localized(
      "确认最终 QA 层不引入监控 SDK、自动化浏览器测试或 CI 管线改动。",
      "Confirms the final QA layer introduces no monitoring SDKs, browser automation, or CI pipeline changes.",
    ),
    category: "scope-guardrail",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/demo-readiness"],
    evidence: [localized("审计可视化仅存在于页面与文档。", "The audit is visualized only in page/UI copy and docs.")],
    notes: localized("允许说明性文案提及这些排除项，但不实现任何相关逻辑。", "Explanatory copy may mention these exclusions, but no such logic is implemented."),
    isPlaceholder: false,
  }),
];

const docsConsistencyItems: MeDemoReadinessChecklistItem[] = [
  createItem({
    key: "docs-demo-story-flow",
    title: localized("ME_DEMO_STORY_FLOW", "ME_DEMO_STORY_FLOW"),
    description: localized("检查 Demo Story 文档已声明 `/demo-readiness` 为 walkthrough QA 下一步。", "Checks the Demo Story doc records `/demo-readiness` as the walkthrough QA next step."),
    category: "docs-consistency",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/demo-story", "/demo-readiness"],
    evidence: [localized("文档继续强调静态导览定位。", "The doc continues to frame the story layer as static only.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "docs-demo-mode-screen-ready",
    title: localized("ME_DEMO_MODE_SCREENSHOT_READY", "ME_DEMO_MODE_SCREENSHOT_READY"),
    description: localized("检查 Demo Mode 文档已声明最终 QA 层与无浏览器自动化 / 无 CI。", "Checks the Demo Mode doc records the final QA layer and the no-browser-automation / no-CI boundary."),
    category: "docs-consistency",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/demo-mode", "/demo-readiness"],
    evidence: [localized("文档继续保留截图准备语境。", "The doc keeps the screenshot-ready framing context.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "docs-stakeholder-summary",
    title: localized("ME_STAKEHOLDER_SUMMARY", "ME_STAKEHOLDER_SUMMARY"),
    description: localized("检查 Stakeholder Summary 文档已加入最终 QA 收尾说明。", "Checks the Stakeholder Summary doc includes the final QA closing step."),
    category: "docs-consistency",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/stakeholder-summary", "/demo-readiness"],
    evidence: [localized("文档仍然明确无 CRM、分析与分享权限。", "The doc still clearly excludes CRM, analytics, and sharing permissions.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "docs-demo-readiness",
    title: localized("ME_DEMO_READINESS", "ME_DEMO_READINESS"),
    description: localized("检查主 Readiness 文档与 Final Audit 文档同步 v0.8.7 范围。", "Checks the primary readiness doc and the final-audit doc both reflect the v0.8.7 scope."),
    category: "docs-consistency",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/demo-readiness"],
    evidence: [localized("包含 QA 分类、架构与未来迁移说明。", "Includes QA categories, architecture, and future migration notes.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "docs-master-project-scope",
    title: localized("ME_MASTER_PROJECT_SCOPE", "ME_MASTER_PROJECT_SCOPE"),
    description: localized("检查主项目范围文档已更新当前 milestone 与 `/demo-readiness`。", "Checks the master project scope doc is updated with the current milestone and `/demo-readiness`."),
    category: "docs-consistency",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/demo-readiness", "/packages", "/psi"],
    evidence: [localized("范围文档继续明确 UI-only、mock/read-only 边界。", "The scope doc continues to state the UI-only, mock/read-only boundary.")],
    isPlaceholder: false,
  }),
];

const demoWalkthroughItems: MeDemoReadinessChecklistItem[] = [
  createItem({
    key: "walkthrough-start-homepage",
    title: localized("从首页开始", "Start at Homepage"),
    description: localized("确认讲解从业务工作台开始，而不是从系统配置页开始。", "Confirms the walkthrough starts at the business workspace rather than a system-config page."),
    category: "demo-walkthrough",
    status: "pass",
    tone: "success",
    route: "/",
    relatedRoutes: ["/demo-story", "/demo-mode"],
    evidence: [localized("首页仍是 ME Business Workspace。", "The homepage remains ME Business Workspace.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "walkthrough-continue-demo-story",
    title: localized("继续到 Demo Story", "Continue to Demo Story"),
    description: localized("确认讲解序列继续通过 Demo Story 编排现有路由。", "Confirms the walkthrough sequence continues through Demo Story orchestration."),
    category: "demo-walkthrough",
    status: "pass",
    tone: "success",
    route: "/demo-story",
    relatedRoutes: ["/navigation", "/roles", "/branches"],
    evidence: [localized("Demo Story 仍是现有路由的讲解层。", "Demo Story remains an orchestration layer over existing routes.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "walkthrough-show-roles",
    title: localized("展示角色", "Show Roles"),
    description: localized("确认角色页仍适合作为多视角叙事站点。", "Confirms role pages still work as a multi-perspective storytelling stop."),
    category: "demo-walkthrough",
    status: "review",
    tone: "info",
    route: "/roles",
    relatedRoutes: ["/roles/owner", "/navigation"],
    evidence: [localized("角色页继续呈现未来 role-aware 方向。", "Role pages continue to frame future role-aware direction.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "walkthrough-show-branches",
    title: localized("展示门店", "Show Branches"),
    description: localized("确认门店页仍适合作为多门店经营语境讲解。", "Confirms branch pages still work for multi-branch operating context."),
    category: "demo-walkthrough",
    status: "review",
    tone: "info",
    route: "/branches",
    relatedRoutes: ["/branches/all-stores", "/reports"],
    evidence: [localized("门店上下文继续复用共享业务语言。", "Branch context continues to reuse the shared business narrative.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "walkthrough-show-psi",
    title: localized("展示 PSI", "Show PSI"),
    description: localized("确认 PSI 仍是运营闭环讲解节点。", "Confirms PSI remains an operations-loop presentation stop."),
    category: "demo-walkthrough",
    status: "pass",
    tone: "success",
    route: "/psi",
    relatedRoutes: ["/psi/issues", "/reports"],
    evidence: [localized("PSI 继续连接采购、供应商、库存与问题视角。", "PSI continues to connect procurement, supplier, inventory, and issue views.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "walkthrough-show-reports",
    title: localized("展示报表", "Show Reports"),
    description: localized("确认报表页继续作为读数总结与收束页。", "Confirms the reports page still works as the recap and summary stop."),
    category: "demo-walkthrough",
    status: "pass",
    tone: "success",
    route: "/reports",
    relatedRoutes: ["/psi", "/stakeholder-summary"],
    evidence: [localized("PSI 预览继续在报表页形成呼应。", "PSI preview continues to reinforce the report narrative.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "walkthrough-show-system-foundation",
    title: localized("展示系统基础层", "Show System Foundation"),
    description: localized("确认系统基础层仍作为次级说明页存在。", "Confirms System Foundation remains a secondary explanation surface."),
    category: "demo-walkthrough",
    status: "pass",
    tone: "success",
    route: "/system-foundation",
    relatedRoutes: ["/layout-engine", "/packages", "/demo-readiness"],
    evidence: [localized("Foundation routes 继续保持可见但次级。", "Foundation routes remain visible but secondary.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "walkthrough-admin-polish",
    title: localized("检查后台治理与套餐", "Review Admin Governance and Packages"),
    description: localized("确认 Settings、Integration、Access Control 与 Packages 都已经适合进入 UI 走查。", "Confirms Settings, Integration, Access Control, and Packages are ready for UI walkthrough testing."),
    category: "demo-walkthrough",
    status: "review",
    tone: "info",
    route: "/settings",
    relatedRoutes: ["/integration", "/access-control", "/packages"],
    evidence: [
      localized("这些页面已完成 preview-safe wording。", "These pages have completed preview-safe wording polish."),
      localized("仍不包含真实 billing、sync、auth、permission enforcement 或 API。", "They still include no real billing, sync, auth, permission enforcement, or API."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "walkthrough-end-stakeholder-summary",
    title: localized("以 Stakeholder Summary 结束", "End at Stakeholder Summary"),
    description: localized("确认讲解可在 Stakeholder Summary 收尾，并由 Demo Readiness 补充最终 QA。", "Confirms the walkthrough can close at Stakeholder Summary, with Demo Readiness adding the final QA layer."),
    category: "demo-walkthrough",
    status: "review",
    tone: "info",
    route: "/stakeholder-summary",
    relatedRoutes: ["/demo-readiness", "/demo-mode"],
    evidence: [localized("总结页继续服务于 owner、investor、partner 与内部评审。", "The summary still serves owners, investors, partners, and internal reviewers.")],
    isPlaceholder: false,
  }),
];

const stakeholderSummaryItems: MeDemoReadinessChecklistItem[] = [
  createItem({
    key: "stakeholder-what-me-is",
    title: localized("ME 是什么", "What ME Is"),
    description: localized("检查总结页继续明确 ME 是模块化门店运营平台。", "Checks the summary continues to define ME as a modular store operations platform."),
    category: "stakeholder-summary",
    status: "pass",
    tone: "success",
    route: "/stakeholder-summary",
    relatedRoutes: ["/"],
    evidence: [localized("首页与总结页命名继续一致。", "Homepage and summary naming remain aligned.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "stakeholder-problem-opportunity",
    title: localized("问题 / 机会", "Problem / Opportunity"),
    description: localized("检查总结页仍能解释多门店经营、PSI 与平台化机会。", "Checks the summary still explains the multi-branch operating challenge and platform opportunity."),
    category: "stakeholder-summary",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/stakeholder-summary", "/psi", "/reports"],
    evidence: [localized("问题与产品层叙事继续闭环。", "Problem framing and product-layer narrative still connect cleanly.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "stakeholder-product-layers",
    title: localized("产品层", "Product Layers"),
    description: localized("检查业务层、运营层、展示层与基础层仍可在同一页解释。", "Checks business, operations, presentation, and foundation layers still ladder up on one page."),
    category: "stakeholder-summary",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/stakeholder-summary", "/system-foundation", "/demo-mode"],
    evidence: [localized("Stakeholder Summary 继续复用已有 metadata。", "Stakeholder Summary continues to reuse existing metadata surfaces.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "stakeholder-admin-recap",
    title: localized("后台治理与套餐 recap", "Admin Governance and Package Recap"),
    description: localized("检查总结页是否已经覆盖 Settings / Integration、Role / Access 与 Package / Plan 抛光成果。", "Checks whether the summary now covers Settings / Integration, Role / Access, and Package / Plan polish."),
    category: "stakeholder-summary",
    status: "review",
    tone: "info",
    route: "/stakeholder-summary",
    relatedRoutes: ["/settings", "/integration", "/access-control", "/packages"],
    evidence: [
      localized("recap 需要反映 UI walkthrough 前最后的后台治理抛光。", "The recap should reflect the final admin-governance polish before UI walkthrough testing."),
    ],
    isPlaceholder: false,
  }),
  createItem({
    key: "stakeholder-roadmap",
    title: localized("路线图", "Roadmap"),
    description: localized("检查路线图已反映 v0.8.7 Final Audit milestone。", "Checks the roadmap reflects v0.8.7 final audit, v0.8.8 governance/package polish, and v0.8.9 UI walkthrough testing prep."),
    category: "stakeholder-summary",
    status: "review",
    tone: "info",
    relatedRoutes: ["/stakeholder-summary", "/demo-readiness"],
    evidence: [localized("路线图继续区分完成、进行中与未来阶段。", "The roadmap still distinguishes completed, in-progress, and future phases.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "stakeholder-demo-route-map",
    title: localized("演示路由地图", "Demo Route Map"),
    description: localized("检查演示路由地图继续覆盖业务、演示、PSI、报表与基础层。", "Checks the demo route map still covers business, demo, PSI, reports, settings, integration, access, packages, and foundation routes."),
    category: "stakeholder-summary",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/stakeholder-summary", "/demo-story", "/demo-mode", "/demo-readiness"],
    evidence: [localized("可在总结页和 QA 页之间互相回链。", "The summary page and QA page can now link to each other.")],
    isPlaceholder: false,
  }),
  createItem({
    key: "stakeholder-guardrail-notice",
    title: localized("范围边界声明", "Guardrail Notice"),
    description: localized("检查总结页继续明确当前是静态、只读、非生产集成原型。", "Checks the summary continues to state the product is a static, read-only, non-production-integrated prototype."),
    category: "stakeholder-summary",
    status: "pass",
    tone: "success",
    relatedRoutes: ["/stakeholder-summary", "/demo-readiness"],
    evidence: [localized("继续排除 CRM、analytics、tracking、API 与数据库。", "It continues to exclude CRM, analytics, tracking, API, and database integrations.")],
    isPlaceholder: false,
  }),
];

const futureReadinessItems: MeDemoReadinessChecklistItem[] = [
  createItem({
    key: "future-api-database",
    title: localized("真实 API / 数据库准备", "Real API / Database Preparation"),
    description: localized("未来可将静态 QA 迁移为真实 route inventory 与 data-backed readiness。", "Future work can migrate the static QA layer toward real route inventory and data-backed readiness."),
    category: "future-readiness",
    status: "future",
    tone: "muted",
    relatedRoutes: ["/demo-readiness", "/psi", "/reports"],
    evidence: [localized("当前仅停留在文档化与 UI 可视化层。", "Current scope stays at documentation and UI visualization only.")],
    notes: localized("未来方向，不代表当前启用。", "Future direction only and not enabled now."),
    isPlaceholder: true,
  }),
  createItem({
    key: "future-auth-tenant-role",
    title: localized("认证 / 租户 / 角色权限未来", "Auth / Tenant / Role Permissions Future"),
    description: localized("未来可把展示型角色与门店语义迁移到真实权限体系。", "Future work can migrate descriptive role and branch semantics into a real permission system."),
    category: "future-readiness",
    status: "future",
    tone: "muted",
    relatedRoutes: ["/roles", "/branches", "/access-control"],
    evidence: [localized("当前阶段仅保留语义层说明。", "Current scope preserves descriptive semantics only.")],
    notes: localized("当前不启用 auth、session 或 middleware。", "Auth, session, and middleware remain out of scope today."),
    isPlaceholder: true,
  }),
  createItem({
    key: "future-report-builder",
    title: localized("报表构建器未来", "Report Builder Future"),
    description: localized("未来可引入更真实的报表构建、导出与 QA 清单。", "Future work can add more real report-builder, export, and QA capabilities."),
    category: "future-readiness",
    status: "future",
    tone: "muted",
    relatedRoutes: ["/reports", "/demo-readiness"],
    evidence: [localized("当前报表仍是 metadata-first 预览。", "Reports remain metadata-first previews today.")],
    isPlaceholder: true,
  }),
  createItem({
    key: "future-workflow-engine",
    title: localized("工作流引擎未来", "Workflow Engine Future"),
    description: localized("未来可把基础层 workflow contracts 迁移到真实执行与 QA。", "Future work can move workflow contracts toward real execution and QA."),
    category: "future-readiness",
    status: "future",
    tone: "muted",
    relatedRoutes: ["/workflow", "/notifications", "/demo-readiness"],
    evidence: [localized("当前没有后台执行器、队列或通知服务。", "There is no backend executor, queue, or notification service today.")],
    isPlaceholder: true,
  }),
  createItem({
    key: "future-export-deck",
    title: localized("导出 / Deck 未来", "Export / Deck Future"),
    description: localized("未来可增加演示导出、截图库与 presentation deck QA。", "Future work can add presentation export, screenshot libraries, and deck QA."),
    category: "future-readiness",
    status: "future",
    tone: "muted",
    relatedRoutes: ["/demo-mode", "/stakeholder-summary", "/demo-readiness"],
    evidence: [localized("当前最终 QA 仍是页面内静态清单。", "The final QA currently remains an in-app static checklist.")],
    isPlaceholder: true,
  }),
];

export const meDemoReadinessSections: MeDemoReadinessSection[] = [
  createSection({
    key: "route-completeness",
    title: localized("路由完整性", "Route Completeness"),
    description: localized("确认 ME 现有关键展示路由继续完整、可访问且不被破坏。", "Confirms the key presentation routes remain intact, reachable, and undisturbed."),
    category: "route-completeness",
    items: routeCompletenessItems,
    tone: "success",
  }),
  createSection({
    key: "navigation-reachability",
    title: localized("导航可达性", "Navigation Reachability"),
    description: localized("检查主要入口、次级入口与跨页回链是否便于演示切换。", "Checks whether primary, secondary, and cross-page links support smooth presentation switching."),
    category: "navigation-reachability",
    items: navigationReachabilityItems,
    tone: "info",
  }),
  createSection({
    key: "presentation-consistency",
    title: localized("展示一致性", "Presentation Consistency"),
    description: localized("检查截图、文案、CTA 与展示气质是否保持统一。", "Checks screenshot framing, copy, CTA flow, and presentation tone for consistency."),
    category: "presentation-consistency",
    items: [...presentationConsistencyItems],
    tone: "info",
  }),
  createSection({
    key: "screenshot-readiness",
    title: localized("截图就绪", "Screenshot Readiness"),
    description: localized("把与截图、标签和展示 framing 相关的 QA 显式列出。", "Makes screenshot-ready labeling and presentation framing checks explicit."),
    category: "screenshot-readiness",
    items: presentationConsistencyItems.filter((item) => item.category === "screenshot-readiness"),
    tone: "success",
  }),
  createSection({
    key: "scope-guardrail",
    title: localized("范围边界", "Scope Guardrails"),
    description: localized("明确本次只做静态 QA 可视化，不引入真实运行能力。", "Makes the current milestone explicit: static QA visualization only with no live runtime capability."),
    category: "scope-guardrail",
    items: scopeGuardrailItems,
    tone: "success",
  }),
  createSection({
    key: "docs-consistency",
    title: localized("文档一致性", "Docs Consistency"),
    description: localized("检查 Demo / Stakeholder / Scope 文档是否与新路线一致。", "Checks that Demo, Stakeholder, and Scope docs stay aligned with the new route."),
    category: "docs-consistency",
    items: docsConsistencyItems,
    tone: "success",
  }),
  createSection({
    key: "demo-walkthrough",
    title: localized("演示走查 QA", "Demo Walkthrough QA"),
    description: localized("按讲解顺序检查关键站点是否仍适合现场演示。", "Checks the core stops in the live walkthrough sequence."),
    category: "demo-walkthrough",
    items: demoWalkthroughItems,
    tone: "info",
  }),
  createSection({
    key: "stakeholder-summary",
    title: localized("Stakeholder Summary QA", "Stakeholder Summary QA"),
    description: localized("确认最终提案总结页仍然可用于 owner、partner 与 investor 沟通。", "Confirms the final summary page remains usable for owner, partner, and investor conversations."),
    category: "stakeholder-summary",
    items: stakeholderSummaryItems,
    tone: "info",
  }),
  createSection({
    key: "future-readiness",
    title: localized("未来准备", "Future Readiness"),
    description: localized("保留未来迁移方向，但明确不在当前范围内启用。", "Keeps future migration directions visible while making them clearly out of scope today."),
    category: "future-readiness",
    items: futureReadinessItems,
    tone: "muted",
  }),
];

export const meDemoReadinessItems = meDemoReadinessSections.flatMap((section) => section.items);
