import type { ModuleDefinition, ModuleRoutes } from "@/types/module";

const allThemes = ["bright", "dark", "moon"] as const;
const allLanguages = ["zh", "en"] as const;

function createRoutes(code: string): ModuleRoutes {
  const basePath = `/modules/${code}`;

  return {
    home: basePath,
    dashboard: `${basePath}/dashboard`,
    listing: `${basePath}/listing`,
    detail: `${basePath}/detail`,
    issue: `${basePath}/issue`,
    form: `${basePath}/form`,
    report: `${basePath}/report`,
    settings: `${basePath}/settings`,
  };
}

export const moduleRegistry: ModuleDefinition[] = [
  {
    code: "procurement",
    name: { zh: "采购", en: "Procurement" },
    shortName: { zh: "采购", en: "Procure" },
    description: {
      zh: "采购需求、审批节奏与执行入口的模块骨架。",
      en: "Foundation for purchase requests, approval pacing, and procurement execution entry points.",
    },
    category: "core",
    priority: 10,
    icon: "ShoppingCart",
    status: "enabled",
    plan: "ops",
    routes: createRoutes("procurement"),
    permissions: [
      "procurement.view",
      "procurement.create",
      "procurement.edit",
      "procurement.approve",
      "procurement.export",
    ],
    apiScope: ["procurement.read", "procurement.write", "procurement.approval"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["purchase-request", "approval-lane", "supplier-link"],
    ownerRole: "Store Operations Manager",
    sourceMapping: {
      moduleKey: "procurement",
      routeNamespace: "/modules/procurement",
      permissionNamespace: "procurement",
      apiNamespace: "me.procurement",
      analyticsKey: "module.procurement",
    },
  },
  {
    code: "supplier",
    name: { zh: "供应商", en: "Supplier" },
    shortName: { zh: "供方", en: "Supplier" },
    description: {
      zh: "供应商档案、协作状态与绩效概览的模块骨架。",
      en: "Foundation for supplier profiles, collaboration status, and performance overview surfaces.",
    },
    category: "control",
    priority: 20,
    icon: "Truck",
    status: "enabled",
    plan: "ops",
    routes: createRoutes("supplier"),
    permissions: [
      "supplier.view",
      "supplier.create",
      "supplier.edit",
      "supplier.approve",
      "supplier.export",
    ],
    apiScope: ["supplier.read", "supplier.directory", "supplier.performance"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["supplier-directory", "vendor-scorecard", "cooperation-health"],
    ownerRole: "Procurement Lead",
    sourceMapping: {
      moduleKey: "supplier",
      routeNamespace: "/modules/supplier",
      permissionNamespace: "supplier",
      apiNamespace: "me.supplier",
      analyticsKey: "module.supplier",
    },
  },
  {
    code: "inventory",
    name: { zh: "库存", en: "Inventory" },
    shortName: { zh: "库存", en: "Stock" },
    description: {
      zh: "库存状态、移动轨迹与门店补货判断的模块骨架。",
      en: "Foundation for stock visibility, inventory movement, and replenishment-oriented operational views.",
    },
    category: "core",
    priority: 30,
    icon: "Boxes",
    status: "enabled",
    plan: "ops",
    routes: createRoutes("inventory"),
    permissions: [
      "inventory.view",
      "inventory.create",
      "inventory.edit",
      "inventory.approve",
      "inventory.export",
    ],
    apiScope: ["inventory.read", "inventory.adjustment", "inventory.audit"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["stock-overview", "movement-timeline", "replenishment-signal"],
    ownerRole: "Inventory Controller",
    sourceMapping: {
      moduleKey: "inventory",
      routeNamespace: "/modules/inventory",
      permissionNamespace: "inventory",
      apiNamespace: "me.inventory",
      analyticsKey: "module.inventory",
    },
  },
  {
    code: "pos-report",
    name: { zh: "POS 报表", en: "POS Report" },
    shortName: { zh: "报表", en: "POS" },
    description: {
      zh: "POS 表现、报表拆解与门店经营信号的模块骨架。",
      en: "Foundation for POS reporting, operational drill-down, and store performance trend views.",
    },
    category: "control",
    priority: 40,
    icon: "ChartColumn",
    status: "coming-soon",
    plan: "pro",
    routes: createRoutes("pos-report"),
    permissions: [
      "pos-report.view",
      "pos-report.create",
      "pos-report.edit",
      "pos-report.export",
      "pos-report.configure",
    ],
    apiScope: ["pos.read", "reporting.query", "reporting.export"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["daily-sales", "trend-overview", "drill-down-reporting"],
    ownerRole: "Operations Analyst",
    sourceMapping: {
      moduleKey: "pos-report",
      routeNamespace: "/modules/pos-report",
      permissionNamespace: "pos-report",
      apiNamespace: "me.pos-report",
      analyticsKey: "module.pos-report",
    },
  },
  {
    code: "education",
    name: { zh: "培训", en: "Education" },
    shortName: { zh: "培训", en: "Learning" },
    description: {
      zh: "SOP 学习、培训任务与知识触达的模块骨架。",
      en: "Foundation for SOP learning, training tasks, and knowledge enablement workflows.",
    },
    category: "future",
    priority: 50,
    icon: "GraduationCap",
    status: "coming-soon",
    plan: "pro",
    routes: createRoutes("education"),
    permissions: [
      "education.view",
      "education.create",
      "education.edit",
      "education.approve",
      "education.configure",
    ],
    apiScope: ["education.read", "education.assignment", "education.progress"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["sop-library", "training-assignment", "completion-tracking"],
    ownerRole: "Training Manager",
    sourceMapping: {
      moduleKey: "education",
      routeNamespace: "/modules/education",
      permissionNamespace: "education",
      apiNamespace: "me.education",
      analyticsKey: "module.education",
    },
  },
  {
    code: "task",
    name: { zh: "任务", en: "Task" },
    shortName: { zh: "任务", en: "Task" },
    description: {
      zh: "门店执行任务、协同跟进与责任归属的模块骨架。",
      en: "Foundation for store execution tasks, collaboration follow-up, and accountability workflows.",
    },
    category: "core",
    priority: 60,
    icon: "ListTodo",
    status: "enabled",
    plan: "starter",
    routes: createRoutes("task"),
    permissions: [
      "task.view",
      "task.create",
      "task.edit",
      "task.approve",
      "task.export",
    ],
    apiScope: ["task.read", "task.assignment", "task.timeline"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["task-queue", "execution-checklist", "follow-up-log"],
    ownerRole: "Store Supervisor",
    sourceMapping: {
      moduleKey: "task",
      routeNamespace: "/modules/task",
      permissionNamespace: "task",
      apiNamespace: "me.task",
      analyticsKey: "module.task",
    },
  },
  {
    code: "approval",
    name: { zh: "审批中心", en: "Approval Center" },
    shortName: { zh: "审批", en: "Approval" },
    description: {
      zh: "跨模块审批流入口与待办汇总中心。",
      en: "Cross-module approval inbox and approval orchestration foundation.",
    },
    category: "control",
    priority: 70,
    icon: "BadgeCheck",
    status: "coming-soon",
    plan: "pro",
    routes: createRoutes("approval"),
    permissions: ["approval.view", "approval.approve", "approval.export", "approval.configure"],
    apiScope: ["approval.read", "approval.queue"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["approval-inbox", "approval-routing"],
    ownerRole: "Regional Manager",
    sourceMapping: {
      moduleKey: "approval",
      routeNamespace: "/modules/approval",
      permissionNamespace: "approval",
      apiNamespace: "me.approval",
      analyticsKey: "module.approval",
    },
  },
  {
    code: "message",
    name: { zh: "消息中心", en: "Message Center" },
    shortName: { zh: "消息", en: "Messages" },
    description: {
      zh: "消息通知、提醒订阅与广播入口的模块骨架。",
      en: "Foundation for notifications, subscriptions, and operational broadcast flows.",
    },
    category: "control",
    priority: 80,
    icon: "Bell",
    status: "coming-soon",
    plan: "starter",
    routes: createRoutes("message"),
    permissions: ["message.view", "message.create", "message.edit", "message.configure"],
    apiScope: ["message.read", "message.subscription"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["notification-center", "alert-subscription"],
    ownerRole: "Store Supervisor",
    sourceMapping: {
      moduleKey: "message",
      routeNamespace: "/modules/message",
      permissionNamespace: "message",
      apiNamespace: "me.message",
      analyticsKey: "module.message",
    },
  },
  {
    code: "api-center",
    name: { zh: "API 中心", en: "API Center" },
    shortName: { zh: "API", en: "API" },
    description: {
      zh: "接口配置、同步状态与连接能力的占位注册项。",
      en: "Placeholder registry entry for API configuration, sync status, and connector visibility.",
    },
    category: "admin",
    priority: 90,
    icon: "PlugZap",
    status: "disabled",
    plan: "enterprise",
    routes: createRoutes("api-center"),
    permissions: ["api-center.view", "api-center.create", "api-center.edit", "api-center.configure"],
    apiScope: ["api.registry", "api.health"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["connector-registry", "health-check-panel"],
    ownerRole: "Platform Admin",
    sourceMapping: {
      moduleKey: "api-center",
      routeNamespace: "/modules/api-center",
      permissionNamespace: "api-center",
      apiNamespace: "me.api-center",
      analyticsKey: "module.api-center",
    },
  },
  {
    code: "automation-center",
    name: { zh: "自动化中心", en: "Automation Center" },
    shortName: { zh: "自动化", en: "Automation" },
    description: {
      zh: "自动化编排与事件规则的占位注册项。",
      en: "Placeholder registry entry for automation orchestration and event-driven flows.",
    },
    category: "admin",
    priority: 100,
    icon: "Workflow",
    status: "disabled",
    plan: "enterprise",
    routes: createRoutes("automation-center"),
    permissions: ["automation-center.view", "automation-center.create", "automation-center.edit", "automation-center.configure"],
    apiScope: ["automation.registry", "automation.audit"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["flow-catalog", "trigger-placeholder"],
    ownerRole: "Platform Admin",
    sourceMapping: {
      moduleKey: "automation-center",
      routeNamespace: "/modules/automation-center",
      permissionNamespace: "automation-center",
      apiNamespace: "me.automation-center",
      analyticsKey: "module.automation-center",
    },
  },
  {
    code: "rule-center",
    name: { zh: "规则中心", en: "Rule Center" },
    shortName: { zh: "规则", en: "Rules" },
    description: {
      zh: "规则配置与治理能力的占位注册项。",
      en: "Placeholder registry entry for rule configuration and operational governance.",
    },
    category: "admin",
    priority: 110,
    icon: "ShieldCheck",
    status: "disabled",
    plan: "enterprise",
    routes: createRoutes("rule-center"),
    permissions: ["rule-center.view", "rule-center.create", "rule-center.edit", "rule-center.configure"],
    apiScope: ["rule.registry", "rule.audit"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["rule-catalog", "governance-trace"],
    ownerRole: "Operations Architect",
    sourceMapping: {
      moduleKey: "rule-center",
      routeNamespace: "/modules/rule-center",
      permissionNamespace: "rule-center",
      apiNamespace: "me.rule-center",
      analyticsKey: "module.rule-center",
    },
  },
  {
    code: "formula-center",
    name: { zh: "公式中心", en: "Formula Center" },
    shortName: { zh: "公式", en: "Formula" },
    description: {
      zh: "公式配置与计算规则的占位注册项。",
      en: "Placeholder registry entry for formula management and operational calculation patterns.",
    },
    category: "admin",
    priority: 120,
    icon: "Calculator",
    status: "disabled",
    plan: "enterprise",
    routes: createRoutes("formula-center"),
    permissions: ["formula-center.view", "formula-center.create", "formula-center.edit", "formula-center.configure"],
    apiScope: ["formula.registry", "formula.validation"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["formula-library", "calculation-template"],
    ownerRole: "Operations Architect",
    sourceMapping: {
      moduleKey: "formula-center",
      routeNamespace: "/modules/formula-center",
      permissionNamespace: "formula-center",
      apiNamespace: "me.formula-center",
      analyticsKey: "module.formula-center",
    },
  },
  {
    code: "report-builder",
    name: { zh: "报表构建器", en: "Report Builder" },
    shortName: { zh: "构建器", en: "Builder" },
    description: {
      zh: "报表搭建与可视化配置的占位注册项。",
      en: "Placeholder registry entry for report composition and visualization configuration.",
    },
    category: "admin",
    priority: 130,
    icon: "BarChart3",
    status: "beta",
    plan: "pro",
    routes: createRoutes("report-builder"),
    permissions: ["report-builder.view", "report-builder.create", "report-builder.edit", "report-builder.export", "report-builder.configure"],
    apiScope: ["report-builder.read", "report-builder.export"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["visual-builder", "widget-layouts"],
    ownerRole: "Operations Analyst",
    sourceMapping: {
      moduleKey: "report-builder",
      routeNamespace: "/modules/report-builder",
      permissionNamespace: "report-builder",
      apiNamespace: "me.report-builder",
      analyticsKey: "module.report-builder",
    },
  },
  {
    code: "ai-assistant",
    name: { zh: "AI 助手", en: "AI Assistant" },
    shortName: { zh: "助手", en: "Assistant" },
    description: {
      zh: "智能辅助入口的注册占位，不包含任何 AI 实现。",
      en: "Registry placeholder for future assistant entry points without any AI implementation.",
    },
    category: "future",
    priority: 140,
    icon: "Bot",
    status: "disabled",
    plan: "enterprise",
    routes: createRoutes("ai-assistant"),
    permissions: ["ai-assistant.view", "ai-assistant.configure"],
    apiScope: ["assistant.registry"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["assistant-entry", "conversation-placeholder"],
    ownerRole: "Platform Strategy Lead",
    sourceMapping: {
      moduleKey: "ai-assistant",
      routeNamespace: "/modules/ai-assistant",
      permissionNamespace: "ai-assistant",
      apiNamespace: "me.ai-assistant",
      analyticsKey: "module.ai-assistant",
    },
  },
  {
    code: "branch-overview",
    name: { zh: "门店总览", en: "Branch Overview" },
    shortName: { zh: "总览", en: "Branch" },
    description: {
      zh: "多门店状态与经营概览的占位注册项。",
      en: "Placeholder registry entry for multi-branch visibility and performance overview.",
    },
    category: "control",
    priority: 150,
    icon: "GitBranch",
    status: "coming-soon",
    plan: "pro",
    routes: createRoutes("branch-overview"),
    permissions: ["branch-overview.view", "branch-overview.export", "branch-overview.configure"],
    apiScope: ["branch.read", "branch.analytics"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["branch-map", "branch-portfolio"],
    ownerRole: "Regional Manager",
    sourceMapping: {
      moduleKey: "branch-overview",
      routeNamespace: "/modules/branch-overview",
      permissionNamespace: "branch-overview",
      apiNamespace: "me.branch-overview",
      analyticsKey: "module.branch-overview",
    },
  },
  {
    code: "inspection",
    name: { zh: "巡检", en: "Inspection" },
    shortName: { zh: "巡检", en: "Inspect" },
    description: {
      zh: "门店巡检、问题复核与检查任务的占位注册项。",
      en: "Placeholder registry entry for inspection rounds, issue review, and compliance checks.",
    },
    category: "control",
    priority: 160,
    icon: "ClipboardCheck",
    status: "beta",
    plan: "ops",
    routes: createRoutes("inspection"),
    permissions: ["inspection.view", "inspection.create", "inspection.edit", "inspection.approve", "inspection.export"],
    apiScope: ["inspection.read", "inspection.audit"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["inspection-rounds", "compliance-notes"],
    ownerRole: "Area Supervisor",
    sourceMapping: {
      moduleKey: "inspection",
      routeNamespace: "/modules/inspection",
      permissionNamespace: "inspection",
      apiNamespace: "me.inspection",
      analyticsKey: "module.inspection",
    },
  },
  {
    code: "scheduling",
    name: { zh: "排班", en: "Scheduling" },
    shortName: { zh: "排班", en: "Schedule" },
    description: {
      zh: "班表编排与人力节奏的占位注册项。",
      en: "Placeholder registry entry for workforce scheduling and shift planning.",
    },
    category: "control",
    priority: 170,
    icon: "CalendarClock",
    status: "coming-soon",
    plan: "pro",
    routes: createRoutes("scheduling"),
    permissions: ["scheduling.view", "scheduling.create", "scheduling.edit", "scheduling.approve", "scheduling.export"],
    apiScope: ["scheduling.read", "scheduling.assignment"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["shift-board", "coverage-overview"],
    ownerRole: "Store Manager",
    sourceMapping: {
      moduleKey: "scheduling",
      routeNamespace: "/modules/scheduling",
      permissionNamespace: "scheduling",
      apiNamespace: "me.scheduling",
      analyticsKey: "module.scheduling",
    },
  },
  {
    code: "staff",
    name: { zh: "员工", en: "Staff" },
    shortName: { zh: "员工", en: "Staff" },
    description: {
      zh: "人员台账与岗位视图的占位注册项。",
      en: "Placeholder registry entry for staff rosters and role visibility.",
    },
    category: "control",
    priority: 180,
    icon: "Users",
    status: "coming-soon",
    plan: "ops",
    routes: createRoutes("staff"),
    permissions: ["staff.view", "staff.create", "staff.edit", "staff.export", "staff.configure"],
    apiScope: ["staff.read", "staff.profile"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["staff-directory", "role-roster"],
    ownerRole: "Store Manager",
    sourceMapping: {
      moduleKey: "staff",
      routeNamespace: "/modules/staff",
      permissionNamespace: "staff",
      apiNamespace: "me.staff",
      analyticsKey: "module.staff",
    },
  },
  {
    code: "crm",
    name: { zh: "客户关系", en: "CRM" },
    shortName: { zh: "客户", en: "CRM" },
    description: {
      zh: "客户运营与门店关系管理的占位注册项。",
      en: "Placeholder registry entry for customer relationship and retention workflows.",
    },
    category: "future",
    priority: 190,
    icon: "Handshake",
    status: "coming-soon",
    plan: "enterprise",
    routes: createRoutes("crm"),
    permissions: ["crm.view", "crm.create", "crm.edit", "crm.export", "crm.configure"],
    apiScope: ["crm.read", "crm.analytics"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["customer-journey", "relationship-overview"],
    ownerRole: "Customer Operations Lead",
    sourceMapping: {
      moduleKey: "crm",
      routeNamespace: "/modules/crm",
      permissionNamespace: "crm",
      apiNamespace: "me.crm",
      analyticsKey: "module.crm",
    },
  },
  {
    code: "erp-integration",
    name: { zh: "ERP 集成", en: "ERP Integration" },
    shortName: { zh: "ERP", en: "ERP" },
    description: {
      zh: "ERP 对接能力的注册占位，不包含真实连接器。",
      en: "Registry placeholder for ERP connectivity without any real connector implementation.",
    },
    category: "admin",
    priority: 200,
    icon: "Waypoints",
    status: "disabled",
    plan: "enterprise",
    routes: createRoutes("erp-integration"),
    permissions: ["erp-integration.view", "erp-integration.create", "erp-integration.edit", "erp-integration.configure"],
    apiScope: ["integration.registry", "integration.audit"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["erp-registry", "sync-health"],
    ownerRole: "Platform Admin",
    sourceMapping: {
      moduleKey: "erp-integration",
      routeNamespace: "/modules/erp-integration",
      permissionNamespace: "erp-integration",
      apiNamespace: "me.erp-integration",
      analyticsKey: "module.erp-integration",
    },
  },
  {
    code: "advanced-wms",
    name: { zh: "高级仓储", en: "Advanced WMS" },
    shortName: { zh: "WMS", en: "WMS" },
    description: {
      zh: "高级仓储与库位策略的占位注册项。",
      en: "Placeholder registry entry for advanced warehousing and location strategy capabilities.",
    },
    category: "future",
    priority: 210,
    icon: "Warehouse",
    status: "disabled",
    plan: "enterprise",
    routes: createRoutes("advanced-wms"),
    permissions: ["advanced-wms.view", "advanced-wms.create", "advanced-wms.edit", "advanced-wms.configure"],
    apiScope: ["wms.read", "wms.strategy"],
    themeSupport: [...allThemes],
    languageSupport: [...allLanguages],
    featureFlags: ["warehouse-map", "slotting-placeholder"],
    ownerRole: "Supply Chain Lead",
    sourceMapping: {
      moduleKey: "advanced-wms",
      routeNamespace: "/modules/advanced-wms",
      permissionNamespace: "advanced-wms",
      apiNamespace: "me.advanced-wms",
      analyticsKey: "module.advanced-wms",
    },
  },
];
