import type { MeNavigationItem, MeNavigationMap, MeSidebarNavigationGroup, MeSidebarNavigationItem } from "@/types/navigation";

function createItem(item: MeNavigationItem): MeNavigationItem {
  return item;
}

function createSidebarItem(item: MeSidebarNavigationItem): MeSidebarNavigationItem {
  return item;
}

const dashboard = createItem({
  key: "dashboard",
  label: { zh: "仪表盘", en: "Dashboard" },
  description: { zh: "ME 业务工作台首页。", en: "The main business workspace entry for ME." },
  href: "/",
  group: "business",
  status: "active",
  tone: "success",
  badge: { zh: "主入口", en: "Primary" },
  isPrimary: true,
  isFoundation: false,
  notes: "Business-first homepage route.",
});

const businessWorkspace = createItem({
  key: "business-workspace",
  label: { zh: "业务工作台", en: "Business Workspace" },
  description: { zh: "以业务运营为主的 B2B SaaS 首页。", en: "Business-first B2B SaaS workspace home." },
  href: "/",
  group: "business",
  status: "active",
  tone: "info",
  badge: { zh: "工作台", en: "Workspace" },
  isPrimary: true,
  isFoundation: false,
  notes: "Shares the homepage route with Dashboard for IA clarity.",
});

const psiWorkspace = createItem({
  key: "psi-workspace",
  label: { zh: "PSI 工作台", en: "PSI Workspace" },
  description: { zh: "采购、供应商与库存读写隔离的只读工作区。", en: "Read-only procurement, supplier, and inventory workspace." },
  href: "/psi",
  group: "business",
  status: "active",
  tone: "success",
  badge: { zh: "PSI", en: "PSI" },
  isPrimary: true,
  isFoundation: false,
  relatedModule: "procurement",
});

const procurement = createItem({
  key: "procurement",
  label: { zh: "采购", en: "Procurement" },
  description: { zh: "采购工作台只读预览。", en: "Read-only procurement workspace preview." },
  href: "/psi/procurement",
  group: "operations",
  status: "active",
  tone: "neutral",
  isPrimary: false,
  isFoundation: false,
  relatedModule: "procurement",
});

const supplier = createItem({
  key: "supplier",
  label: { zh: "供应商", en: "Supplier" },
  description: { zh: "供应商目录与协作状态只读预览。", en: "Read-only supplier directory and collaboration preview." },
  href: "/psi/supplier",
  group: "operations",
  status: "active",
  tone: "neutral",
  isPrimary: false,
  isFoundation: false,
  relatedModule: "supplier",
});

const inventory = createItem({
  key: "inventory",
  label: { zh: "库存", en: "Inventory" },
  description: { zh: "库存可见性与风险状态只读预览。", en: "Read-only inventory visibility and risk preview." },
  href: "/psi/inventory",
  group: "operations",
  status: "active",
  tone: "warning",
  isPrimary: false,
  isFoundation: false,
  relatedModule: "inventory",
});

const psiActions = createItem({
  key: "psi-actions",
  label: { zh: "PSI 动作", en: "PSI Actions" },
  description: { zh: "PSI 动作草稿与表单占位预览。", en: "PSI action draft and form placeholder preview." },
  href: "/psi/actions",
  group: "operations",
  status: "preview-only",
  tone: "info",
  badge: { zh: "预览", en: "Preview" },
  isPrimary: false,
  isFoundation: false,
  relatedModule: "procurement",
});

const psiIssues = createItem({
  key: "psi-issues",
  label: { zh: "PSI 问题", en: "PSI Issues" },
  description: { zh: "PSI 问题占位页与闭环预览。", en: "PSI issue placeholder and close-loop preview." },
  href: "/psi/issues",
  group: "operations",
  status: "preview-only",
  tone: "warning",
  badge: { zh: "预览", en: "Preview" },
  isPrimary: false,
  isFoundation: false,
  relatedModule: "inventory",
});

const reports = createItem({
  key: "reports",
  label: { zh: "报表", en: "Reports" },
  description: { zh: "ME 报表与 PSI 报表预览入口。", en: "ME reports and PSI preview entry point." },
  href: "/reports",
  group: "reports",
  status: "active",
  tone: "info",
  badge: { zh: "分析", en: "Analytics" },
  isPrimary: true,
  isFoundation: false,
  relatedModule: "pos-report",
});

const tasks = createItem({
  key: "tasks",
  label: { zh: "任务", en: "Tasks" },
  description: { zh: "任务引擎只读列表与详情预览。", en: "Read-only task engine list and detail preview." },
  href: "/tasks",
  group: "reports",
  status: "preview-only",
  tone: "neutral",
  isPrimary: false,
  isFoundation: false,
  relatedModule: "task",
});

const education = createItem({
  key: "education",
  label: { zh: "培训", en: "Education" },
  description: { zh: "培训模块 Demo 路由占位。", en: "Education module demo route placeholder." },
  href: "/demo/education",
  group: "reports",
  status: "preview-only",
  tone: "muted",
  badge: { zh: "占位", en: "Placeholder" },
  isPrimary: false,
  isFoundation: false,
  relatedModule: "education",
});

const posReports = createItem({
  key: "pos-reports",
  label: { zh: "POS 报表", en: "POS Reports" },
  description: { zh: "POS 报表 Demo 路由占位。", en: "POS report demo route placeholder." },
  href: "/demo/pos-report",
  group: "reports",
  status: "preview-only",
  tone: "muted",
  badge: { zh: "占位", en: "Placeholder" },
  isPrimary: false,
  isFoundation: false,
  relatedModule: "pos-report",
});

const branches = createItem({
  key: "branches",
  label: { zh: "门店上下文", en: "Branches" },
  description: {
    zh: "门店 / 分店上下文占位与未来选择器预览。",
    en: "Store and branch context placeholder with future selector preview.",
  },
  href: "/branches",
  group: "business",
  status: "preview-only",
  tone: "info",
  badge: { zh: "预览", en: "Preview" },
  isPrimary: false,
  isFoundation: false,
  relatedModule: "branch-overview",
  notes: "Preview-only route. No tenant switching, branch database, or permission enforcement is connected.",
});

const systemFoundation = createItem({
  key: "system-foundation",
  label: { zh: "系统基础层", en: "System Foundation" },
  description: { zh: "平台契约、元数据与基础能力总览。", en: "Platform contracts, metadata, and foundation overview." },
  href: "/system-foundation",
  group: "system-foundation",
  status: "active",
  tone: "muted",
  badge: { zh: "次级", en: "Secondary" },
  isPrimary: true,
  isFoundation: true,
});

const layoutEngine = createItem({
  key: "layout-engine",
  label: { zh: "布局引擎", en: "Layout Engine" },
  description: { zh: "布局与皮肤基础预览。", en: "Layout and skin foundation preview." },
  href: "/layout-engine",
  group: "system-foundation",
  status: "active",
  tone: "muted",
  isPrimary: false,
  isFoundation: true,
});

const actionContracts = createItem({
  key: "action-contracts",
  label: { zh: "动作契约", en: "Action Contracts" },
  description: { zh: "动作元数据与来源映射。", en: "Action metadata and source mapping." },
  href: "/action-contracts",
  group: "system-foundation",
  status: "active",
  tone: "muted",
  isPrimary: false,
  isFoundation: true,
});

const accessControl = createItem({
  key: "access-control",
  label: { zh: "访问控制", en: "Access Control" },
  description: { zh: "权限与角色契约预览。", en: "Permission and role contract preview." },
  href: "/access-control",
  group: "system-foundation",
  status: "active",
  tone: "muted",
  isPrimary: false,
  isFoundation: true,
});

const auditTrail = createItem({
  key: "audit-trail",
  label: { zh: "审计轨迹", en: "Audit Trail" },
  description: { zh: "审计契约与事件来源预览。", en: "Audit contract and event source preview." },
  href: "/audit-trail",
  group: "system-foundation",
  status: "active",
  tone: "muted",
  isPrimary: false,
  isFoundation: true,
});

const roles = createItem({
  key: "roles",
  label: { zh: "角色工作区", en: "Roles" },
  description: {
    zh: "角色工作区占位与未来权限映射预览。",
    en: "Role workspace placeholder and future permission mapping preview.",
  },
  href: "/roles",
  group: "system-foundation",
  status: "preview-only",
  tone: "info",
  badge: { zh: "预览", en: "Preview" },
  isPrimary: false,
  isFoundation: true,
  notes: "Preview-only route. No auth or permission enforcement is connected.",
});

const workflow = createItem({
  key: "workflow",
  label: { zh: "工作流", en: "Workflow" },
  description: { zh: "工作流触发与自动化契约占位。", en: "Workflow trigger and automation contract placeholder." },
  href: "/workflow",
  group: "system-foundation",
  status: "active",
  tone: "muted",
  isPrimary: false,
  isFoundation: true,
});

const notifications = createItem({
  key: "notifications",
  label: { zh: "通知", en: "Notifications" },
  description: { zh: "通知契约与模板占位预览。", en: "Notification contract and template placeholder preview." },
  href: "/notifications",
  group: "system-foundation",
  status: "active",
  tone: "muted",
  isPrimary: false,
  isFoundation: true,
});

const reportsFoundation = createItem({
  key: "reports-foundation",
  label: { zh: "报表基础", en: "Reports" },
  description: { zh: "报表契约与小部件基础仍保持可访问。", en: "Report contract and widget foundations remain accessible." },
  href: "/reports",
  group: "system-foundation",
  status: "active",
  tone: "muted",
  isPrimary: false,
  isFoundation: true,
  notes: "Secondary foundation link to the same /reports route.",
});

const rules = createItem({
  key: "rules",
  label: { zh: "规则", en: "Rules" },
  description: { zh: "规则与公式基础契约。", en: "Rule and formula foundation contracts." },
  href: "/rules",
  group: "system-foundation",
  status: "active",
  tone: "muted",
  isPrimary: false,
  isFoundation: true,
});

const packages = createItem({
  key: "packages",
  label: { zh: "套餐", en: "Packages" },
  description: { zh: "SaaS 套餐与模块包契约预览。", en: "SaaS plan and module package contract preview." },
  href: "/packages",
  group: "system-foundation",
  status: "active",
  tone: "muted",
  isPrimary: false,
  isFoundation: true,
});

const components = createItem({
  key: "components",
  label: { zh: "组件", en: "Components" },
  description: { zh: "核心 UI 组件与表单组件展示。", en: "Core UI and form component showcase." },
  href: "/components",
  group: "system-foundation",
  status: "active",
  tone: "muted",
  isPrimary: false,
  isFoundation: true,
});

const realDataMapping = createItem({
  key: "real-data-mapping",
  label: { zh: "真实数据映射", en: "Real Data Mapping" },
  description: {
    zh: "Mock 到真实数据的实体、接口与迁移规划。",
    en: "Mock-to-real data entities, API boundaries, and migration planning.",
  },
  href: "/real-data-mapping",
  group: "system-foundation",
  status: "active",
  tone: "muted",
  isPrimary: false,
  isFoundation: true,
});

const navigationIa = createItem({
  key: "navigation-ia",
  label: { zh: "导航 IA", en: "Navigation IA" },
  description: { zh: "ME 业务导航与系统基础层映射预览。", en: "ME business navigation and system foundation map preview." },
  href: "/navigation",
  group: "footer",
  status: "preview-only",
  tone: "info",
  badge: { zh: "IA", en: "IA" },
  isPrimary: true,
  isFoundation: false,
});

const demoStory = createItem({
  key: "demo-story",
  label: { zh: "Demo Story", en: "Demo Story" },
  description: {
    zh: "ME 引导演示故事流占位入口。",
    en: "Guided ME product narrative placeholder entry.",
  },
  href: "/demo-story",
  group: "footer",
  status: "preview-only",
  tone: "info",
  badge: { zh: "导览", en: "Tour" },
  isPrimary: false,
  isFoundation: false,
  notes: "Static guided demo story placeholder. No onboarding state, analytics, tracking, or personalization is connected.",
});

const demoMode = createItem({
  key: "demo-mode",
  label: { zh: "Demo Mode", en: "Demo Mode" },
  description: {
    zh: "ME 截图就绪展示层占位入口。",
    en: "Screenshot-ready ME presentation layer placeholder entry.",
  },
  href: "/demo-mode",
  group: "footer",
  status: "preview-only",
  tone: "muted",
  badge: { zh: "展示", en: "Preview" },
  isPrimary: false,
  isFoundation: false,
  notes: "Static demo presentation placeholder. No real demo mode state, persistence, analytics, tracking, or personalization is connected.",
});

const stakeholderSummary = createItem({
  key: "stakeholder-summary",
  label: { zh: "Stakeholder Summary", en: "Stakeholder Summary" },
  description: {
    zh: "ME 面向 owner、investor、partner 的静态总结页。",
    en: "Static ME summary for owners, investors, partners, and internal stakeholders.",
  },
  href: "/stakeholder-summary",
  group: "footer",
  status: "preview-only",
  tone: "muted",
  badge: { zh: "提案", en: "Review" },
  isPrimary: false,
  isFoundation: false,
  notes: "Static stakeholder summary placeholder. No investor portal, CRM, analytics, tracking, or sharing permissions are connected.",
});

const demoReadiness = createItem({
  key: "demo-readiness",
  label: { zh: "Demo Readiness", en: "Demo Readiness" },
  description: {
    zh: "ME 最终演示就绪审计占位入口。",
    en: "Final ME presentation QA audit placeholder entry.",
  },
  href: "/demo-readiness",
  group: "footer",
  status: "preview-only",
  tone: "muted",
  badge: { zh: "QA", en: "QA" },
  isPrimary: false,
  isFoundation: false,
  notes: "Static presentation QA placeholder. No monitoring, analytics, tracking, browser automation, runtime crawling, or CI changes are connected.",
});

const modules = createItem({
  key: "modules",
  label: { zh: "模块中心", en: "Modules" },
  description: { zh: "模块注册表与中心入口。", en: "Module registry and module center entry." },
  href: "/modules",
  group: "footer",
  status: "preview-only",
  tone: "neutral",
  isPrimary: false,
  isFoundation: false,
});

const demo = createItem({
  key: "demo",
  label: { zh: "演示", en: "Demo" },
  description: { zh: "跨模块 Demo 工作区。", en: "Cross-module demo workspace." },
  href: "/demo",
  group: "footer",
  status: "preview-only",
  tone: "neutral",
  isPrimary: false,
  isFoundation: false,
});

const templates = createItem({
  key: "templates",
  label: { zh: "模板", en: "Templates" },
  description: { zh: "页面模板与布局参考。", en: "Page templates and layout reference." },
  href: "/templates",
  group: "footer",
  status: "preview-only",
  tone: "neutral",
  isPrimary: false,
  isFoundation: false,
});

const sidebarGroups: MeSidebarNavigationGroup[] = [
  {
    key: "sidebar-dashboard",
    title: { zh: "仪表盘", en: "Dashboard" },
    description: { zh: "业务总览与主工作台。", en: "Business overview and primary workspace." },
    icon: "LayoutDashboard",
    collapsedByDefault: false,
    items: [
      createSidebarItem({
        key: "sidebar-business-workspace",
        routeKey: businessWorkspace.key,
        label: businessWorkspace.label,
        description: businessWorkspace.description,
        href: businessWorkspace.href,
        status: businessWorkspace.status,
        tone: businessWorkspace.tone,
        badge: businessWorkspace.badge,
        matchPaths: ["/"],
      }),
    ],
  },
  {
    key: "sidebar-psi",
    title: { zh: "PSI 工作区", en: "PSI Workspace" },
    description: { zh: "采购、供应商、库存与问题预览。", en: "Procurement, supplier, inventory, and issue previews." },
    icon: "PackageSearch",
    collapsedByDefault: false,
    items: [
      createSidebarItem({
        key: "sidebar-psi-overview",
        routeKey: psiWorkspace.key,
        label: { zh: "总览", en: "Overview" },
        description: psiWorkspace.description,
        href: psiWorkspace.href,
        status: psiWorkspace.status,
        tone: psiWorkspace.tone,
        badge: psiWorkspace.badge,
        matchPaths: ["/psi"],
      }),
      createSidebarItem({
        key: "sidebar-procurement",
        routeKey: procurement.key,
        label: procurement.label,
        description: procurement.description,
        href: procurement.href,
        status: procurement.status,
        tone: procurement.tone,
        matchPaths: ["/psi/procurement"],
      }),
      createSidebarItem({
        key: "sidebar-supplier",
        routeKey: supplier.key,
        label: supplier.label,
        description: supplier.description,
        href: supplier.href,
        status: supplier.status,
        tone: supplier.tone,
        matchPaths: ["/psi/supplier"],
      }),
      createSidebarItem({
        key: "sidebar-inventory",
        routeKey: inventory.key,
        label: inventory.label,
        description: inventory.description,
        href: inventory.href,
        status: inventory.status,
        tone: inventory.tone,
        matchPaths: ["/psi/inventory"],
      }),
      createSidebarItem({
        key: "sidebar-psi-issues",
        routeKey: psiIssues.key,
        label: { zh: "问题", en: "Issues" },
        description: psiIssues.description,
        href: psiIssues.href,
        status: psiIssues.status,
        tone: psiIssues.tone,
        badge: { zh: "预览", en: "Preview" },
        matchPaths: ["/psi/issues"],
      }),
      createSidebarItem({
        key: "sidebar-psi-actions",
        routeKey: psiActions.key,
        label: { zh: "动作草稿", en: "Action Drafts" },
        description: psiActions.description,
        href: psiActions.href,
        status: psiActions.status,
        tone: psiActions.tone,
        badge: { zh: "预览", en: "Preview" },
        matchPaths: ["/psi/actions"],
      }),
      createSidebarItem({
        key: "sidebar-psi-reports",
        routeKey: reports.key,
        label: { zh: "PSI 报表", en: "PSI Reports" },
        description: reports.description,
        href: reports.href,
        status: reports.status,
        tone: reports.tone,
        badge: { zh: "分析", en: "Analytics" },
        matchPaths: ["/reports"],
      }),
    ],
  },
  {
    key: "sidebar-reports",
    title: { zh: "报表", en: "Reports" },
    description: { zh: "报表工作区与导出准备。", en: "Report workspace and export readiness." },
    icon: "BarChart3",
    collapsedByDefault: false,
    items: [
      createSidebarItem({
        key: "sidebar-reports-overview",
        routeKey: reports.key,
        label: { zh: "总览", en: "Overview" },
        description: reports.description,
        href: reports.href,
        status: reports.status,
        tone: reports.tone,
        matchPaths: ["/reports"],
      }),
      createSidebarItem({
        key: "sidebar-pos-reports",
        routeKey: posReports.key,
        label: posReports.label,
        description: posReports.description,
        status: "coming-soon",
        tone: "muted",
        badge: { zh: "Soon", en: "Soon" },
      }),
      createSidebarItem({
        key: "sidebar-sales-analytics",
        label: { zh: "销售分析", en: "Sales Analytics" },
        description: { zh: "销售分析占位。", en: "Sales analytics placeholder." },
        status: "coming-soon",
        tone: "muted",
        badge: { zh: "Soon", en: "Soon" },
      }),
      createSidebarItem({
        key: "sidebar-branch-performance",
        label: { zh: "门店表现", en: "Branch Performance" },
        description: { zh: "门店表现占位。", en: "Branch performance placeholder." },
        status: "coming-soon",
        tone: "muted",
        badge: { zh: "Soon", en: "Soon" },
      }),
      createSidebarItem({
        key: "sidebar-export-center",
        label: { zh: "导出中心", en: "Export Center" },
        description: { zh: "导出中心占位。", en: "Export center placeholder." },
        status: "coming-soon",
        tone: "muted",
        badge: { zh: "Soon", en: "Soon" },
      }),
    ],
  },
  {
    key: "sidebar-branches",
    title: { zh: "门店", en: "Branches" },
    description: { zh: "门店上下文与运行状态。", en: "Branch context and operating status." },
    icon: "Building2",
    collapsedByDefault: false,
    items: [
      createSidebarItem({
        key: "sidebar-all-branches",
        routeKey: branches.key,
        label: { zh: "全部门店", en: "All Branches" },
        description: branches.description,
        href: branches.href,
        status: "active",
        tone: "info",
        matchPaths: ["/branches"],
      }),
      createSidebarItem({
        key: "sidebar-branch-context",
        routeKey: branches.key,
        label: { zh: "门店上下文", en: "Branch Context" },
        description: branches.description,
        href: branches.href,
        status: "active",
        tone: "info",
        matchPaths: ["/branches"],
      }),
      createSidebarItem({
        key: "sidebar-branch-operations-status",
        label: { zh: "运营状态", en: "Operations Status" },
        description: { zh: "运营状态占位。", en: "Operations status placeholder." },
        status: "coming-soon",
        tone: "muted",
        badge: { zh: "Soon", en: "Soon" },
      }),
      createSidebarItem({
        key: "sidebar-branch-inspection",
        label: { zh: "检查", en: "Inspection" },
        description: { zh: "检查占位。", en: "Inspection placeholder." },
        status: "coming-soon",
        tone: "muted",
        badge: { zh: "Soon", en: "Soon" },
      }),
    ],
  },
  {
    key: "sidebar-roles",
    title: { zh: "角色与员工", en: "Roles & Staff" },
    description: { zh: "角色、员工与权限预览。", en: "Roles, staff, and permission previews." },
    icon: "Users2",
    collapsedByDefault: false,
    items: [
      createSidebarItem({
        key: "sidebar-roles-main",
        routeKey: roles.key,
        label: { zh: "角色", en: "Roles" },
        description: roles.description,
        href: roles.href,
        status: "active",
        tone: "info",
        matchPaths: ["/roles"],
      }),
      createSidebarItem({
        key: "sidebar-staff-profiles",
        label: { zh: "员工档案", en: "Staff Profiles" },
        description: { zh: "员工档案占位。", en: "Staff profile placeholder." },
        status: "coming-soon",
        tone: "muted",
        badge: { zh: "Soon", en: "Soon" },
      }),
      createSidebarItem({
        key: "sidebar-permissions",
        label: { zh: "权限", en: "Permissions" },
        description: { zh: "权限占位。", en: "Permissions placeholder." },
        status: "coming-soon",
        tone: "muted",
        badge: { zh: "Soon", en: "Soon" },
      }),
      createSidebarItem({
        key: "sidebar-training",
        label: { zh: "培训", en: "Training" },
        description: { zh: "培训占位。", en: "Training placeholder." },
        status: "coming-soon",
        tone: "muted",
        badge: { zh: "Soon", en: "Soon" },
      }),
    ],
  },
  {
    key: "sidebar-tasks",
    title: { zh: "任务与教育", en: "Tasks & Education" },
    description: { zh: "任务、培训与模板占位。", en: "Tasks, training, and template placeholders." },
    icon: "ListTodo",
    collapsedByDefault: true,
    items: [
      createSidebarItem({
        key: "sidebar-tasks-main",
        routeKey: tasks.key,
        label: tasks.label,
        description: tasks.description,
        href: tasks.href,
        status: "preview-only",
        tone: "neutral",
        badge: { zh: "预览", en: "Preview" },
        matchPaths: ["/tasks"],
      }),
      createSidebarItem({
        key: "sidebar-education",
        routeKey: education.key,
        label: education.label,
        description: education.description,
        status: "coming-soon",
        tone: "muted",
        badge: { zh: "Soon", en: "Soon" },
      }),
      createSidebarItem({
        key: "sidebar-training-records",
        label: { zh: "培训记录", en: "Training Records" },
        description: { zh: "培训记录占位。", en: "Training records placeholder." },
        status: "coming-soon",
        tone: "muted",
        badge: { zh: "Soon", en: "Soon" },
      }),
      createSidebarItem({
        key: "sidebar-task-templates",
        label: { zh: "任务模板", en: "Task Templates" },
        description: { zh: "任务模板占位。", en: "Task templates placeholder." },
        status: "coming-soon",
        tone: "muted",
        badge: { zh: "Soon", en: "Soon" },
      }),
    ],
  },
  {
    key: "sidebar-demo",
    title: { zh: "演示与提案", en: "Demo & Presentation" },
    description: { zh: "展示、总结与演示 QA。", en: "Presentation surfaces, summaries, and QA." },
    icon: "Presentation",
    collapsedByDefault: false,
    items: [
      createSidebarItem({
        key: "sidebar-demo-story",
        routeKey: demoStory.key,
        label: { zh: "Demo Story", en: "Demo Story" },
        description: demoStory.description,
        href: demoStory.href,
        status: "preview-only",
        tone: "info",
        badge: demoStory.badge,
        matchPaths: ["/demo-story"],
      }),
      createSidebarItem({
        key: "sidebar-demo-mode",
        routeKey: demoMode.key,
        label: demoMode.label,
        description: demoMode.description,
        href: demoMode.href,
        status: "preview-only",
        tone: "muted",
        badge: demoMode.badge,
        matchPaths: ["/demo-mode"],
      }),
      createSidebarItem({
        key: "sidebar-stakeholder-summary",
        routeKey: stakeholderSummary.key,
        label: stakeholderSummary.label,
        description: stakeholderSummary.description,
        href: stakeholderSummary.href,
        status: "preview-only",
        tone: "muted",
        badge: stakeholderSummary.badge,
        matchPaths: ["/stakeholder-summary"],
      }),
      createSidebarItem({
        key: "sidebar-demo-readiness",
        routeKey: demoReadiness.key,
        label: demoReadiness.label,
        description: demoReadiness.description,
        href: demoReadiness.href,
        status: "preview-only",
        tone: "muted",
        badge: demoReadiness.badge,
        matchPaths: ["/demo-readiness"],
      }),
    ],
  },
  {
    key: "sidebar-system",
    title: { zh: "系统", en: "System" },
    description: { zh: "布局、契约与平台治理。", en: "Layouts, contracts, and platform governance." },
    icon: "ShieldEllipsis",
    collapsedByDefault: true,
    items: [
      createSidebarItem({
        key: "sidebar-navigation-ia",
        routeKey: navigationIa.key,
        label: { zh: "导航 IA", en: "Navigation IA" },
        description: navigationIa.description,
        href: navigationIa.href,
        status: "active",
        tone: "info",
        badge: navigationIa.badge,
        matchPaths: ["/navigation"],
      }),
      createSidebarItem({
        key: "sidebar-system-foundation",
        routeKey: systemFoundation.key,
        label: systemFoundation.label,
        description: systemFoundation.description,
        href: systemFoundation.href,
        status: systemFoundation.status,
        tone: systemFoundation.tone,
        badge: systemFoundation.badge,
        matchPaths: ["/system-foundation"],
      }),
      createSidebarItem({
        key: "sidebar-layout-engine",
        routeKey: layoutEngine.key,
        label: layoutEngine.label,
        description: layoutEngine.description,
        href: layoutEngine.href,
        status: layoutEngine.status,
        tone: layoutEngine.tone,
        matchPaths: ["/layout-engine"],
      }),
      createSidebarItem({
        key: "sidebar-real-data-mapping",
        routeKey: realDataMapping.key,
        label: realDataMapping.label,
        description: realDataMapping.description,
        href: realDataMapping.href,
        status: realDataMapping.status,
        tone: realDataMapping.tone,
        matchPaths: ["/real-data-mapping"],
      }),
      createSidebarItem({
        key: "sidebar-packages",
        routeKey: packages.key,
        label: packages.label,
        description: packages.description,
        href: packages.href,
        status: packages.status,
        tone: packages.tone,
        matchPaths: ["/packages"],
      }),
      createSidebarItem({
        key: "sidebar-rules",
        routeKey: rules.key,
        label: rules.label,
        description: rules.description,
        href: rules.href,
        status: rules.status,
        tone: rules.tone,
        matchPaths: ["/rules"],
      }),
      createSidebarItem({
        key: "sidebar-workflow",
        routeKey: workflow.key,
        label: workflow.label,
        description: workflow.description,
        href: workflow.href,
        status: workflow.status,
        tone: workflow.tone,
        matchPaths: ["/workflow"],
      }),
      createSidebarItem({
        key: "sidebar-notifications",
        routeKey: notifications.key,
        label: notifications.label,
        description: notifications.description,
        href: notifications.href,
        status: notifications.status,
        tone: notifications.tone,
        matchPaths: ["/notifications"],
      }),
      createSidebarItem({
        key: "sidebar-audit-trail",
        routeKey: auditTrail.key,
        label: auditTrail.label,
        description: auditTrail.description,
        href: auditTrail.href,
        status: auditTrail.status,
        tone: auditTrail.tone,
        matchPaths: ["/audit-trail"],
      }),
      createSidebarItem({
        key: "sidebar-access-control",
        routeKey: accessControl.key,
        label: accessControl.label,
        description: accessControl.description,
        href: accessControl.href,
        status: accessControl.status,
        tone: accessControl.tone,
        matchPaths: ["/access-control"],
      }),
    ],
  },
];

export const navigationMap: MeNavigationMap = {
  primaryItems: [dashboard, psiWorkspace, reports, systemFoundation, navigationIa],
  groups: [
    {
      key: "business",
      title: { zh: "业务", en: "Business" },
      description: { zh: "面向业务运营的主导航。", en: "Primary navigation for business operations." },
      groupType: "business",
      items: [dashboard, businessWorkspace, psiWorkspace, branches],
      collapsedByDefault: false,
      isFoundationGroup: false,
    },
    {
      key: "operations",
      title: { zh: "运营", en: "Operations" },
      description: { zh: "围绕 PSI 的日常运营导航。", en: "Daily operational navigation around PSI." },
      groupType: "operations",
      items: [procurement, supplier, inventory, psiActions, psiIssues],
      collapsedByDefault: false,
      isFoundationGroup: false,
    },
    {
      key: "reports",
      title: { zh: "报表", en: "Reports" },
      description: { zh: "报表、任务与演示分析入口。", en: "Reporting, task, and demo analytics entry points." },
      groupType: "reports",
      items: [reports, tasks, education, posReports],
      collapsedByDefault: false,
      isFoundationGroup: false,
    },
    {
      key: "system-foundation",
      title: { zh: "系统基础层", en: "System Foundation" },
      description: { zh: "平台契约与系统基础能力，保持可访问但降级展示。", en: "Platform contracts and system foundations remain accessible but secondary." },
      groupType: "system",
      items: [
        systemFoundation,
        layoutEngine,
        realDataMapping,
        actionContracts,
        accessControl,
        roles,
        auditTrail,
        workflow,
        notifications,
        reportsFoundation,
        rules,
        packages,
        components,
      ],
      collapsedByDefault: true,
      isFoundationGroup: true,
    },
  ],
  sidebarGroups,
  footerItems: [demoStory, demoMode, stakeholderSummary, demoReadiness, modules, demo, templates],
  generatedAt: "2026-05-06T00:00:00.000Z",
  notice: {
    zh: "当前导航 IA 仅用于 UI/导航演示，不包含认证、权限、数据库、API 或真实写操作。",
    en: "This navigation IA is UI-only and navigation-only. No auth, permission enforcement, database, API, or real writes are connected.",
  },
};
