export type PsiLocale = "en" | "zh";

export const psiLanguageCopy = {
  en: {
    shared: {
      psi: "PSI",
      procurement: "Procurement",
      supplier: "Supplier",
      inventory: "Inventory",
      receiving: "Receiving",
      issues: "Issues",
      actions: "Actions",
      reports: "Reports",
      overview: "Overview",
      activity: "Activity",
      attachments: "Attachments",
      linkedRecords: "Linked Records",
      lifecycle: "Lifecycle",
      source: "Source",
      status: "Status",
      priority: "Priority",
      detail: "Detail",
      module: "Module",
      record: "Record",
      action: "Action",
      relatedActions: "Related actions",
      relatedRecords: "Related Records",
      mockSource: "Mock source",
      serviceNoticePrefix: "PSI service notice:",
    },
    overview: {
      eyebrow: "PSI Workspace",
      title: "Procurement, supplier, and inventory operations",
      description:
        "Operational PSI shell with review queues, detail preview, and related context panels.",
      notice:
        "Use the PSI workspace to coordinate procurement requests, supplier follow-up, inventory risks, and branch receiving readiness.",
      operationModules: "PSI Operation Modules",
      operationModulesDescription: "Primary entry points for daily PSI work.",
      procurementDescription: "Request queues, supplier handoff, and receiving checkpoints.",
      supplierDescription: "Supplier readiness, issue context, and communication status.",
      inventoryDescription: "Low stock, coverage visibility, and replenishment context.",
      procurementMetric: "12 pending review",
      supplierMetric: "4 vendor issues",
      inventoryMetric: "8 watch items",
      openProcurement: "Open Procurement",
      openSupplier: "Open Supplier",
      openInventory: "Open Inventory",
      openPsiReports: "Open PSI Reports",
      openIssues: "Open Issues",
      createRequest: "Create Request",
      reviewSupplier: "Review Supplier",
      linkInventory: "Link Inventory",
      currentFocus: "Current Focus",
      procurementRequest: "Procurement request",
      requestType: "Request type",
      procurementNote: "Procurement Note",
      items: "Items",
      itemsDescription: "Line items under the current procurement request.",
      supplierAndReceiving: "Supplier and Receiving",
      supplierAndReceivingDescription:
        "Operational context tied to vendor and branch receiving readiness.",
      linkedInventoryStatus: "Linked Inventory Status",
      inventoryImpact: "Inventory Impact",
      relatedContext: "Related Context",
      serviceScope: "Service Scope",
      workspaceNote: "Workspace Note",
      workspaceNoteDescription:
        "PSI follows the shared ERP detail pattern with request header, action bar, line items, activity, and branch context.",
    },
    rightRail: {
      psiStatus: "PSI Status",
      procurementQueueVisible: "Procurement queue visible",
      supplierRisksSurfaced: "Supplier risks surfaced",
      inventoryFollowUpCoordinated:
        "Inventory follow-up remains coordinated through the workspace",
      todayFocus: "Today Focus",
      workCoverage: "Work Coverage",
      procurementCoordination: "Procurement coordination",
      supplierReview: "Supplier review",
      inventoryWatch: "Inventory watch",
      operationalFollowUp: "Operational follow-up",
      workspaceContext: "Workspace Context",
      serviceLayer: "Service Layer",
      issueWatch: "Issue Watch",
      issueContext: "Issue Context",
      currentQueue: "Current Queue",
      procurementFollowUp: "Procurement follow-up",
      supplierCoordination: "Supplier coordination",
      inventoryRiskReview: "Inventory risk review",
      activeIssuesSuffix: "active issues",
      currentRelease: "Current release",
      queueSize: "Queue size",
      openBranches: "Open Branches",
      openDetail: "Open detail",
      currentWorkspace: "Current workspace",
      lifecycle: "Lifecycle",
      queue: "Queue",
      queueReview: "Queue review",
      linkedIssueContext: "Linked issue context",
      branchCoordination: "Branch coordination",
      catalogLayer: "Published through the shared catalog layer",
      connectedService: "Published through the connected service layer",
      visibleRecordsSuffix: "active records in scope",
      linkedIssueRecordsSuffix: "linked issue records",
      escalationReview: "Escalation review",
      timelineFollowUp: "Timeline follow-up",
      operationalQueue: "Operational queue",
      currentServiceScope: "Current service scope",
      visibleRecords: "Visible records",
      issueWatchMeta: "Issue watch",
      deliveryMode: "Delivery mode",
      catalogLayerShort: "Catalog layer",
      connectedServiceShort: "Connected service",
    },
    workspace: {
      eyebrow: "PSI Workspace",
      procurementTitle: "ME PSI Procurement",
      procurementSubtitle: "Procurement requests, purchase activity, and issue review workspace",
      supplierTitle: "ME PSI Supplier",
      supplierSubtitle: "Supplier readiness, vendor issue, and follow-up workspace",
      inventoryTitle: "ME PSI Inventory",
      inventorySubtitle: "Inventory risk, replenishment, and stock watch workspace",
      mainRecords: "Main Records",
      mainRecordsDescription: "Primary queue records currently visible for operational review.",
      selectedRecord: "Selected Record",
      selectedRecordDescription: "Structured metadata for the currently highlighted queue record.",
      issueQueue: "Issue Queue",
      issueQueueDescription: "Issue and follow-up records linked to the current PSI workspace.",
      openPsiActions: "Open PSI Actions",
      openIssues: "Open Issues",
      openReports: "Open Reports",
      issueWatch: "Issue watch",
      selectedRecordTitle: "Selected record",
      supplier: "Supplier",
      action: "Action",
      operationalFollowUp: "Operational follow-up",
      queue: "Queue",
      openRecord: "Open record",
      title: "Title",
      owner: "Owner",
      branch: "Branch",
      lifecycle: "Lifecycle",
      createPurchaseRequest: "Create Purchase Request",
      recordReceiving: "Record Receiving",
      reportPurchaseIssue: "Report Purchase Issue",
      stats: {
        purchaseRequests: "Purchase Requests",
        pendingRequests: "Pending Requests",
        purchaseOrders: "Purchase Orders",
        issueOpen: "Issue Open",
      },
      columns: {
        record: "Record",
        status: "Status",
        priority: "Priority",
        lifecycle: "Lifecycle",
        issue: "Issue",
      },
    },
    issues: {
      eyebrow: "PSI Issues",
      title: "Issue and incident queue",
      description:
        "Cross-module issue queue for procurement, supplier, and inventory follow-up.",
      notice:
        "Issues remain metadata-only and route to detail/action placeholders. No workflow or notification is executed.",
      issues: "Issues",
      psiCoordination: "PSI coordination",
      coverage: "Coverage",
      coverageValue: "Procurement / Supplier / Inventory",
      openPsi: "Open PSI",
      openReports: "Open Reports",
      openActions: "Open Actions",
      issueQueue: "Issue Queue",
      issueQueueDescription:
        "Priority, status, module source, and linked detail access for active PSI issues.",
      issueActivity: "Issue Activity",
      columns: {
        issue: "Issue",
        module: "Module",
        priority: "Priority",
        status: "Status",
        lifecycle: "Lifecycle",
        detail: "Detail",
      },
    },
    actions: {
      title: "ME PSI Actions",
      description: "Action Draft / Form Placeholder Design",
      filters: "Filters",
      actionDrafts: "Action Drafts",
      noActionDraftFound: "No action draft found.",
      category: "Category",
      intent: "Intent",
      status: "Status",
      allCategories: "All categories",
      allIntents: "All intents",
      allStatuses: "All statuses",
      backToPsiActions: "Back to ME PSI Actions",
      notFoundTitle: "ME PSI Action Draft Not Found",
      openPsiIssues: "Open PSI Issues",
      lifecyclePlaceholders: "Lifecycle/timeline placeholders in PSI details",
      submitPreview: "Action Submit Preview",
      fields: "fields",
      required: "required",
      statsTitle: "Stats",
      total: "Total",
      placeholder: "Placeholder",
      requiredFields: "Required fields",
      module: "Module",
      notice:
        "Placeholder only. No real submit, no database/API, no write action, no approval engine, no stock posting, and no task/notification/workflow execution.",
      openDraftDetail: "Open draft detail",
      options: {
        all: "All",
        procurement: "Procurement",
        supplier: "Supplier",
        inventory: "Inventory",
        receiving: "Receiving",
        issue: "Issue",
        stock: "Stock",
        system: "System",
        create: "Create",
        updatePlaceholder: "Update placeholder",
        review: "Review",
        approvePlaceholder: "Approve placeholder",
        receive: "Receive",
        adjust: "Adjust",
        transfer: "Transfer",
        reportIssue: "Report issue",
        suggest: "Suggest",
        configure: "Configure",
        placeholder: "Placeholder",
        draft: "Draft",
        previewOnly: "Preview only",
        comingSoon: "Coming soon",
        blocked: "Blocked",
        disabled: "Disabled",
      },
    },
    detail: {
      psiRecord: "PSI Record",
      keyInformation: "Key Information",
      keyInformationDescription: "Core record fields for day-to-day operational review.",
      relatedRecordsDescription:
        "Connected PSI records used during review, coordination, and follow-up.",
      insights: "Insights",
      insightsDescription: "Operational indicators linked to the current record.",
      backToWorkspace: "Back to Workspace",
      relatedActionPlaceholders: "Related Action Placeholders",
      relatedActionDescription: "Actions route to draft previews and do not submit data.",
      recordContext: "Record Context",
      recordDetail: "Record detail",
      operationalWatch: "Operational Watch",
      noLinkedRecords: "No linked records in scope",
      queueReview: "Queue review",
      relatedActivity: "Related activity",
      crossModuleFollowUp: "Cross-module follow-up",
      reviewNotice: "Review the record summary, linked business records, operating timeline, and related actions from one detail workspace.",
      timeline: "Timeline",
      openRecord: "Open record",
      linkedInCurrentWorkspace: "Linked in current workspace",
      indicator: "Indicator",
      value: "Value",
      description: "Description",
      route: "Route",
      active: "Active",
      monitoring: "Monitoring",
      operationalReviewContext: "Operational review context",
      operationalUpdate: "Operational update",
      actionsCountPrefix: "Related actions",
    },
    standalone: {
      common: {
        backToPsi: "Back to PSI",
        branch: "Branch",
        storage: "Storage",
        owner: "Owner",
        risk: "Risk",
        category: "Category",
        coverage: "Coverage",
        leadTime: "Lead time",
        status: "Status",
        lastUpdated: "Last updated",
        activity: "Activity",
        overview: "Overview",
        issues: "Issues",
        nextSteps: "Next Steps",
        operatingNotes: "Operating Notes",
        currentRelease: "Current release",
        sourceNotice: "Source",
        catalogLayerNotice: "This workspace is currently published through the shared catalog layer.",
        connectedServiceNotice: "This workspace is currently published through the connected service layer.",
        addNote: "Add Note",
        viewHistory: "View History",
        exportProfile: "Export Profile",
        documents: "Documents",
        openProcurement: "Open Procurement",
        openSupplier: "Open Supplier",
        openInventory: "Open Inventory",
      },
      inventory: {
        eyebrow: "PSI Inventory",
        title: "Inventory stock detail",
        description: "Stock profile, movement context, expiry visibility, and linked procurement records using the shared detail pattern.",
        noticeSuffix: "Use it to review stock position, movement history, expiry watch, and replenishment linkage.",
        badgeDetail: "Inventory detail",
        badgeWarehouse: "Warehouse workspace",
        badgeControl: "Inventory control",
        reviewStock: "Review Stock",
        openRiskWatch: "Open risk watch",
        linkProcurement: "Link Procurement",
        exportStockCard: "Export Stock Card",
        viewMovement: "View Movement",
        stockMovement: "Stock Movement",
        expiry: "Expiry",
        stockOverviewDescription: "Stock profile and operating thresholds for the selected SKU.",
        item: "Item",
        currentStock: "Current stock",
        minStock: "Min stock",
        minimumStock: "Minimum stock",
        reorderSignal: "Reorder signal",
        linkedSupplier: "Linked supplier",
        stockNote: "Stock Note",
        stockNoteBody: "KCH freezer stock for coated fries is below threshold and is already linked to the active procurement queue. This is a planning view only and does not post movements or adjust stock.",
        movementDescription: "Recent movement rows and replenishment context.",
        date: "Date",
        movement: "Movement",
        qty: "Qty",
        reference: "Reference",
        expiryAndProcurement: "Expiry and Procurement",
        expiryAndProcurementDescription: "Operational watch items tied to stock quality and replenishment.",
        expiryWatch: "Expiry Watch",
        noImmediateExpiryRisk: "No immediate expiry risk",
        nearestExpiry: "Nearest tracked expiry window is 19 days out and remains outside escalation range.",
        eta: "ETA",
        lowStockRisk: "Low-stock Risk",
        watch: "Watch",
        relatedContext: "Related Context",
        workspaceNote: "Workspace Note",
        workspaceNoteDescription: "Inventory detail brings stock position, movement review, supplier linkage, and replenishment context into one operational record page.",
      },
      supplier: {
        eyebrow: "PSI Supplier",
        title: "Supplier operations detail",
        description: "Supplier profile, contact context, linked orders, and issue visibility inside the shared detail workspace pattern.",
        noticeSuffix: "Use it to review supplier performance, contacts, linked orders, and open follow-up items.",
        badgeDetail: "Supplier detail",
        badgeWorkspace: "Operations workspace",
        badgeOperations: "Supplier operations",
        reviewSupplier: "Review Supplier",
        openIssueQueue: "Open issue queue",
        assignFollowUp: "Assign Follow-up",
        contacts: "Contacts",
        orders: "Orders",
        supplierProfile: "Supplier profile",
        branchCoverage: "Branch coverage",
        serviceRegion: "Service region",
        contactStatus: "Contact status",
        currentRisk: "Current risk",
        supplierOverviewDescription: "Core supplier profile fields and commercial context.",
        supplierName: "Supplier name",
        supplierCode: "Supplier code",
        commercialStatus: "Commercial status",
        primaryEscalation: "Primary escalation",
        supplierNote: "Supplier Note",
        supplierNoteBody: "ABC Food Supply is an active food supplier used by KCH and BTU. Current follow-up is focused on price review and keeping delivery windows aligned with procurement demand.",
        contactsDescription: "Primary contacts and communication ownership.",
        contact: "Contact",
        role: "Role",
        phone: "Phone",
        email: "Email",
        ordersAndIssues: "Orders and Issues",
        ordersAndIssuesDescription: "Recent linked procurement records and current supplier issues.",
        order: "Order",
        value: "Value",
        openIssueSnapshot: "Open Issue Snapshot",
        openIssueSnapshotBody: "Two supplier issues remain open: one price confirmation gap and one delivery-slot coordination issue tied to KCH replenishment.",
        supplierHealth: "Supplier Health",
        review: "Review",
        openIssues: "Open Issues",
        linkedRecords: "Linked Records",
        workspaceNote: "Workspace Note",
        workspaceNoteDescription: "Supplier detail centralizes profile health, contacts, order history, and issue review for purchasing teams.",
      },
    },
    values: {
      object: "Object",
      tabs: "Tabs",
      noSupplier: "No Supplier",
      procurementSupplierInventory: "Procurement / Supplier / Inventory",
    },
  },
  zh: {
    shared: {
      psi: "PSI",
      procurement: "采购",
      supplier: "供应商",
      inventory: "库存",
      receiving: "收货",
      issues: "问题",
      actions: "动作",
      reports: "报表",
      overview: "概览",
      activity: "动态",
      attachments: "附件",
      linkedRecords: "关联记录",
      lifecycle: "生命周期",
      source: "来源",
      status: "状态",
      priority: "优先级",
      detail: "详情",
      module: "模块",
      record: "记录",
      action: "动作",
      relatedActions: "关联动作",
      relatedRecords: "关联记录",
      mockSource: "Mock 来源",
      serviceNoticePrefix: "PSI 服务提示：",
    },
    overview: {
      eyebrow: "PSI 工作区",
      title: "采购、供应商与库存营运",
      description: "用于复核队列、详情预览与关联上下文面板的 PSI 营运壳层。",
      notice: "使用 PSI 工作区协调采购请求、供应商跟进、库存风险与门店收货准备。",
      operationModules: "PSI 营运模块",
      operationModulesDescription: "每日 PSI 工作的主要入口。",
      procurementDescription: "请求队列、供应商交接与收货检查点。",
      supplierDescription: "供应商准备度、问题上下文与沟通状态。",
      inventoryDescription: "低库存、覆盖可见性与补货上下文。",
      procurementMetric: "12 项待复核",
      supplierMetric: "4 项供应商问题",
      inventoryMetric: "8 项观察库存",
      openProcurement: "打开采购",
      openSupplier: "打开供应商",
      openInventory: "打开库存",
      openPsiReports: "打开 PSI 报表",
      openIssues: "打开问题",
      createRequest: "创建请求",
      reviewSupplier: "复核供应商",
      linkInventory: "关联库存",
      currentFocus: "当前重点",
      procurementRequest: "采购请求",
      requestType: "请求类型",
      procurementNote: "采购备注",
      items: "项目",
      itemsDescription: "当前采购请求下的明细项目。",
      supplierAndReceiving: "供应商与收货",
      supplierAndReceivingDescription: "与供应商及门店收货准备相关的营运上下文。",
      linkedInventoryStatus: "关联库存状态",
      inventoryImpact: "库存影响",
      relatedContext: "关联上下文",
      serviceScope: "服务范围",
      workspaceNote: "工作区说明",
      workspaceNoteDescription:
        "PSI 沿用共享 ERP 详情模式，包含请求头、动作栏、明细项目、动态与门店上下文。",
    },
    rightRail: {
      psiStatus: "PSI 状态",
      procurementQueueVisible: "采购队列可见",
      supplierRisksSurfaced: "供应商风险已浮现",
      inventoryFollowUpCoordinated: "库存跟进仍通过工作区协调",
      todayFocus: "今日重点",
      workCoverage: "工作覆盖",
      procurementCoordination: "采购协同",
      supplierReview: "供应商复核",
      inventoryWatch: "库存观察",
      operationalFollowUp: "营运跟进",
      workspaceContext: "工作区上下文",
      serviceLayer: "服务层",
      issueWatch: "问题观察",
      issueContext: "问题上下文",
      currentQueue: "当前队列",
      procurementFollowUp: "采购跟进",
      supplierCoordination: "供应商协同",
      inventoryRiskReview: "库存风险复核",
      activeIssuesSuffix: "个有效问题",
      currentRelease: "当前版本",
      queueSize: "队列数量",
      openBranches: "打开门店",
      openDetail: "打开详情",
      currentWorkspace: "当前工作区",
      lifecycle: "生命周期",
      queue: "队列",
      queueReview: "队列复核",
      linkedIssueContext: "关联问题上下文",
      branchCoordination: "门店协同",
      catalogLayer: "通过共享目录层发布",
      connectedService: "通过已连接服务层发布",
      visibleRecordsSuffix: "条范围内有效记录",
      linkedIssueRecordsSuffix: "条关联问题记录",
      escalationReview: "升级复核",
      timelineFollowUp: "时间线跟进",
      operationalQueue: "营运队列",
      currentServiceScope: "当前服务范围",
      visibleRecords: "可见记录",
      issueWatchMeta: "问题观察",
      deliveryMode: "交付模式",
      catalogLayerShort: "目录层",
      connectedServiceShort: "已连接服务",
    },
    workspace: {
      eyebrow: "PSI 工作区",
      procurementTitle: "ME PSI 采购",
      procurementSubtitle: "采购请求、采购活动与问题复核工作区",
      supplierTitle: "ME PSI 供应商",
      supplierSubtitle: "供应商准备度、供应商问题与跟进工作区",
      inventoryTitle: "ME PSI 库存",
      inventorySubtitle: "库存风险、补货与库存观察工作区",
      mainRecords: "主要记录",
      mainRecordsDescription: "当前可见、用于营运复核的主要队列记录。",
      selectedRecord: "当前记录",
      selectedRecordDescription: "当前高亮队列记录的结构化元数据。",
      issueQueue: "问题队列",
      issueQueueDescription: "与当前 PSI 工作区关联的问题与跟进记录。",
      openPsiActions: "打开 PSI 动作",
      openIssues: "打开问题",
      openReports: "打开报表",
      issueWatch: "问题观察",
      selectedRecordTitle: "当前记录",
      supplier: "供应商",
      action: "动作",
      operationalFollowUp: "营运跟进",
      queue: "队列",
      openRecord: "打开记录",
      title: "标题",
      owner: "负责人",
      branch: "门店",
      lifecycle: "生命周期",
      createPurchaseRequest: "创建采购请求",
      recordReceiving: "记录收货",
      reportPurchaseIssue: "报告采购问题",
      stats: {
        purchaseRequests: "采购请求",
        pendingRequests: "待处理请求",
        purchaseOrders: "采购订单",
        issueOpen: "未关闭问题",
      },
      columns: {
        record: "记录",
        status: "状态",
        priority: "优先级",
        lifecycle: "生命周期",
        issue: "问题",
      },
    },
    issues: {
      eyebrow: "PSI 问题",
      title: "问题与事故队列",
      description: "用于采购、供应商与库存跟进的跨模块问题队列。",
      notice: "问题目前仅为元数据占位，并路由到详情/动作占位。不执行工作流或通知。",
      issues: "问题",
      psiCoordination: "PSI 协同",
      coverage: "覆盖范围",
      coverageValue: "采购 / 供应商 / 库存",
      openPsi: "打开 PSI",
      openReports: "打开报表",
      openActions: "打开动作",
      issueQueue: "问题队列",
      issueQueueDescription: "当前 PSI 问题的优先级、状态、模块来源与详情入口。",
      issueActivity: "问题动态",
      columns: {
        issue: "问题",
        module: "模块",
        priority: "优先级",
        status: "状态",
        lifecycle: "生命周期",
        detail: "详情",
      },
    },
    actions: {
      title: "ME PSI 动作",
      description: "动作草稿 / 表单占位设计",
      filters: "筛选",
      actionDrafts: "动作草稿",
      noActionDraftFound: "未找到动作草稿。",
      category: "分类",
      intent: "意图",
      status: "状态",
      allCategories: "全部分类",
      allIntents: "全部意图",
      allStatuses: "全部状态",
      backToPsiActions: "返回 ME PSI 动作",
      notFoundTitle: "找不到 ME PSI 动作草稿",
      openPsiIssues: "打开 PSI 问题",
      lifecyclePlaceholders: "PSI 详情中的生命周期 / 时间线占位",
      submitPreview: "动作可提交预览",
      fields: "字段",
      required: "必填",
      statsTitle: "统计",
      total: "总数",
      placeholder: "占位",
      requiredFields: "必填字段",
      module: "模块",
      notice:
        "仅为占位预览。不提交真实数据、不连接数据库/API、不执行写入动作、不执行审批引擎、不过账库存，也不触发任务/通知/工作流。",
      openDraftDetail: "打开草稿详情",
      options: {
        all: "全部",
        procurement: "采购",
        supplier: "供应商",
        inventory: "库存",
        receiving: "收货",
        issue: "问题",
        stock: "库存动作",
        system: "系统",
        create: "创建",
        updatePlaceholder: "更新占位",
        review: "复核",
        approvePlaceholder: "审批占位",
        receive: "收货",
        adjust: "调整",
        transfer: "调拨",
        reportIssue: "报告问题",
        suggest: "建议",
        configure: "配置",
        placeholder: "占位",
        draft: "草稿",
        previewOnly: "仅预览",
        comingSoon: "即将开放",
        blocked: "已阻挡",
        disabled: "停用",
      },
    },
    detail: {
      psiRecord: "PSI 记录",
      keyInformation: "关键信息",
      keyInformationDescription: "用于日常营运复核的核心记录字段。",
      relatedRecordsDescription: "复核、协同与跟进过程中使用的关联 PSI 记录。",
      insights: "洞察",
      insightsDescription: "与当前记录关联的营运指标。",
      backToWorkspace: "返回工作区",
      relatedActionPlaceholders: "关联动作占位",
      relatedActionDescription: "动作会路由到草稿预览，不会提交数据。",
      recordContext: "记录上下文",
      recordDetail: "记录详情",
      operationalWatch: "营运观察",
      noLinkedRecords: "当前范围没有关联记录",
      queueReview: "队列复核",
      relatedActivity: "关联动态",
      crossModuleFollowUp: "跨模块跟进",
      reviewNotice: "在同一个详情工作区复核记录摘要、关联业务记录、营运时间线与关联动作。",
      timeline: "时间线",
      openRecord: "打开记录",
      linkedInCurrentWorkspace: "已关联在当前工作区",
      indicator: "指标",
      value: "数值",
      description: "说明",
      route: "路线",
      active: "有效",
      monitoring: "观察中",
      operationalReviewContext: "营运复核上下文",
      operationalUpdate: "营运更新",
      actionsCountPrefix: "关联动作",
    },
    standalone: {
      common: {
        backToPsi: "返回 PSI",
        branch: "门店",
        storage: "储存",
        owner: "负责人",
        risk: "风险",
        category: "分类",
        coverage: "覆盖",
        leadTime: "交期",
        status: "状态",
        lastUpdated: "最后更新",
        activity: "动态",
        overview: "概览",
        issues: "问题",
        nextSteps: "下一步",
        operatingNotes: "营运备注",
        currentRelease: "当前版本",
        sourceNotice: "来源",
        catalogLayerNotice: "此工作区目前通过共享目录层发布。",
        connectedServiceNotice: "此工作区目前通过已连接服务层发布。",
        addNote: "添加备注",
        viewHistory: "查看历史",
        exportProfile: "导出资料",
        documents: "文件",
        openProcurement: "打开采购",
        openSupplier: "打开供应商",
        openInventory: "打开库存",
      },
      inventory: {
        eyebrow: "PSI 库存",
        title: "库存详情",
        description: "使用共享详情模式展示库存资料、出入库上下文、效期可见性与关联采购记录。",
        noticeSuffix: "用于复核库存位置、出入库历史、效期观察与补货关联。",
        badgeDetail: "库存详情",
        badgeWarehouse: "仓库工作区",
        badgeControl: "库存控制",
        reviewStock: "复核库存",
        openRiskWatch: "打开风险观察",
        linkProcurement: "关联采购",
        exportStockCard: "导出库存卡",
        viewMovement: "查看出入库",
        stockMovement: "库存出入库",
        expiry: "效期",
        stockOverviewDescription: "所选 SKU 的库存资料与营运阈值。",
        item: "项目",
        currentStock: "当前库存",
        minStock: "最低库存",
        minimumStock: "最低库存",
        reorderSignal: "补货信号",
        linkedSupplier: "关联供应商",
        stockNote: "库存备注",
        stockNoteBody: "KCH 冷冻库的 coated fries 库存低于阈值，并已关联到有效采购队列。此页面仅为规划视图，不会过账出入库或调整库存。",
        movementDescription: "近期出入库记录与补货上下文。",
        date: "日期",
        movement: "出入库",
        qty: "数量",
        reference: "参考",
        expiryAndProcurement: "效期与采购",
        expiryAndProcurementDescription: "与库存品质和补货相关的营运观察项。",
        expiryWatch: "效期观察",
        noImmediateExpiryRisk: "暂无即时效期风险",
        nearestExpiry: "最近追踪效期窗口为 19 天后，目前仍在升级范围之外。",
        eta: "预计到达",
        lowStockRisk: "低库存风险",
        watch: "观察",
        relatedContext: "关联上下文",
        workspaceNote: "工作区说明",
        workspaceNoteDescription: "库存详情把库存位置、出入库复核、供应商关联与补货上下文整合到一个营运记录页。",
      },
      supplier: {
        eyebrow: "PSI 供应商",
        title: "供应商营运详情",
        description: "在共享详情工作区模式中展示供应商资料、联系人上下文、关联订单与问题可见性。",
        noticeSuffix: "用于复核供应商表现、联系人、关联订单与未关闭跟进项。",
        badgeDetail: "供应商详情",
        badgeWorkspace: "营运工作区",
        badgeOperations: "供应商营运",
        reviewSupplier: "复核供应商",
        openIssueQueue: "打开问题队列",
        assignFollowUp: "分配跟进",
        contacts: "联系人",
        orders: "订单",
        supplierProfile: "供应商资料",
        branchCoverage: "门店覆盖",
        serviceRegion: "服务区域",
        contactStatus: "联系人状态",
        currentRisk: "当前风险",
        supplierOverviewDescription: "核心供应商资料与商业上下文。",
        supplierName: "供应商名称",
        supplierCode: "供应商编号",
        commercialStatus: "商业状态",
        primaryEscalation: "主要升级点",
        supplierNote: "供应商备注",
        supplierNoteBody: "ABC Food Supply 是 KCH 和 BTU 使用中的食品供应商。目前跟进重点是价格复核，并保持配送窗口与采购需求一致。",
        contactsDescription: "主要联系人与沟通归属。",
        contact: "联系人",
        role: "角色",
        phone: "电话",
        email: "Email",
        ordersAndIssues: "订单与问题",
        ordersAndIssuesDescription: "近期关联采购记录与当前供应商问题。",
        order: "订单",
        value: "金额",
        openIssueSnapshot: "未关闭问题快照",
        openIssueSnapshotBody: "仍有两个供应商问题未关闭：一个价格确认缺口，以及一个与 KCH 补货相关的配送时段协同问题。",
        supplierHealth: "供应商健康度",
        review: "复核",
        openIssues: "未关闭问题",
        linkedRecords: "关联记录",
        workspaceNote: "工作区说明",
        workspaceNoteDescription: "供应商详情为采购团队集中展示资料健康度、联系人、订单历史与问题复核。",
      },
    },
    values: {
      object: "对象",
      tabs: "标签页",
      noSupplier: "无供应商",
      procurementSupplierInventory: "采购 / 供应商 / 库存",
    },
  },
} as const;

export function getPsiCopy(locale: PsiLocale) {
  return psiLanguageCopy[locale] ?? psiLanguageCopy.en;
}
