export type PsiLocale = "en" | "zh";

export const psiLanguageCopy = {
  en: {
    shared: {
      psi: "PSI",
      procurement: "Procurement",
      supplier: "Supplier",
      inventory: "Inventory",
      receiving: "Receiving",
      issues: "Issues",
      actions: "Actions",
      reports: "Reports",
      overview: "Overview",
      activity: "Activity",
      attachments: "Attachments",
      linkedRecords: "Linked Records",
      lifecycle: "Lifecycle",
      source: "Source",
      status: "Status",
      priority: "Priority",
      detail: "Detail",
      module: "Module",
      record: "Record",
      action: "Action",
      relatedActions: "Related actions",
      relatedRecords: "Related Records",
      mockSource: "Mock source",
      serviceNoticePrefix: "PSI service notice:",
    },
    overview: {
      eyebrow: "PSI Workspace",
      title: "Procurement, supplier, and inventory operations",
      description:
        "Operational PSI shell with review queues, detail preview, and related context panels.",
      notice:
        "Use the PSI workspace to coordinate procurement requests, supplier follow-up, inventory risks, and branch receiving readiness.",
      operationModules: "PSI Operation Modules",
      operationModulesDescription: "Primary entry points for daily PSI work.",
      procurementDescription: "Request queues, supplier handoff, and receiving checkpoints.",
      supplierDescription: "Supplier readiness, issue context, and communication status.",
      inventoryDescription: "Low stock, coverage visibility, and replenishment context.",
      procurementMetric: "12 pending review",
      supplierMetric: "4 vendor issues",
      inventoryMetric: "8 watch items",
      openProcurement: "Open Procurement",
      openSupplier: "Open Supplier",
      openInventory: "Open Inventory",
      openPsiReports: "Open PSI Reports",
      openIssues: "Open Issues",
      createRequest: "Create Request",
      reviewSupplier: "Review Supplier",
      linkInventory: "Link Inventory",
      currentFocus: "Current Focus",
      procurementRequest: "Procurement request",
      requestType: "Request type",
      procurementNote: "Procurement Note",
      items: "Items",
      itemsDescription: "Line items under the current procurement request.",
      supplierAndReceiving: "Supplier and Receiving",
      supplierAndReceivingDescription:
        "Operational context tied to vendor and branch receiving readiness.",
      linkedInventoryStatus: "Linked Inventory Status",
      inventoryImpact: "Inventory Impact",
      relatedContext: "Related Context",
      serviceScope: "Service Scope",
      workspaceNote: "Workspace Note",
      workspaceNoteDescription:
        "PSI follows the shared ERP detail pattern with request header, action bar, line items, activity, and branch context.",
    },
    rightRail: {
      psiStatus: "PSI Status",
      procurementQueueVisible: "Procurement queue visible",
      supplierRisksSurfaced: "Supplier risks surfaced",
      inventoryFollowUpCoordinated:
        "Inventory follow-up remains coordinated through the workspace",
      todayFocus: "Today Focus",
      workCoverage: "Work Coverage",
      procurementCoordination: "Procurement coordination",
      supplierReview: "Supplier review",
      inventoryWatch: "Inventory watch",
      operationalFollowUp: "Operational follow-up",
      workspaceContext: "Workspace Context",
      serviceLayer: "Service Layer",
      issueWatch: "Issue Watch",
      issueContext: "Issue Context",
      queueReview: "Queue review",
      linkedIssueContext: "Linked issue context",
      branchCoordination: "Branch coordination",
      catalogLayer: "Published through the shared catalog layer",
      connectedService: "Published through the connected service layer",
      visibleRecordsSuffix: "active records in scope",
      linkedIssueRecordsSuffix: "linked issue records",
      escalationReview: "Escalation review",
      timelineFollowUp: "Timeline follow-up",
      operationalQueue: "Operational queue",
      currentServiceScope: "Current service scope",
      visibleRecords: "Visible records",
      issueWatchMeta: "Issue watch",
      deliveryMode: "Delivery mode",
      catalogLayerShort: "Catalog layer",
      connectedServiceShort: "Connected service",
    },
    workspace: {
      eyebrow: "PSI Workspace",
      procurementTitle: "ME PSI Procurement",
      procurementSubtitle: "Procurement requests, purchase activity, and issue review workspace",
      supplierTitle: "ME PSI Supplier",
      supplierSubtitle: "Supplier readiness, vendor issue, and follow-up workspace",
      inventoryTitle: "ME PSI Inventory",
      inventorySubtitle: "Inventory risk, replenishment, and stock watch workspace",
      mainRecords: "Main Records",
      mainRecordsDescription: "Primary queue records currently visible for operational review.",
      selectedRecord: "Selected Record",
      selectedRecordDescription: "Structured metadata for the currently highlighted queue record.",
      issueQueue: "Issue Queue",
      issueQueueDescription: "Issue and follow-up records linked to the current PSI workspace.",
      openPsiActions: "Open PSI Actions",
      openIssues: "Open Issues",
      openReports: "Open Reports",
      issueWatch: "Issue watch",
      selectedRecordTitle: "Selected record",
      supplier: "Supplier",
      action: "Action",
      operationalFollowUp: "Operational follow-up",
      queue: "Queue",
      openRecord: "Open record",
      title: "Title",
      owner: "Owner",
      branch: "Branch",
      lifecycle: "Lifecycle",
      createPurchaseRequest: "Create Purchase Request",
      recordReceiving: "Record Receiving",
      reportPurchaseIssue: "Report Purchase Issue",
      stats: {
        purchaseRequests: "Purchase Requests",
        pendingRequests: "Pending Requests",
        purchaseOrders: "Purchase Orders",
        issueOpen: "Issue Open",
      },
      columns: {
        record: "Record",
        status: "Status",
        priority: "Priority",
        lifecycle: "Lifecycle",
        issue: "Issue",
      },
    },
    issues: {
      eyebrow: "PSI Issues",
      title: "Issue and incident queue",
      description:
        "Cross-module issue queue for procurement, supplier, and inventory follow-up.",
      notice:
        "Issues remain metadata-only and route to detail/action placeholders. No workflow or notification is executed.",
      issues: "Issues",
      psiCoordination: "PSI coordination",
      coverage: "Coverage",
      coverageValue: "Procurement / Supplier / Inventory",
      openPsi: "Open PSI",
      openReports: "Open Reports",
      openActions: "Open Actions",
      issueQueue: "Issue Queue",
      issueQueueDescription:
        "Priority, status, module source, and linked detail access for active PSI issues.",
      issueActivity: "Issue Activity",
      columns: {
        issue: "Issue",
        module: "Module",
        priority: "Priority",
        status: "Status",
        lifecycle: "Lifecycle",
        detail: "Detail",
      },
    },
    actions: {
      title: "ME PSI Actions",
      description: "Action Draft / Form Placeholder Design",
      filters: "Filters",
      actionDrafts: "Action Drafts",
      noActionDraftFound: "No action draft found.",
      category: "Category",
      intent: "Intent",
      status: "Status",
      allCategories: "All categories",
      allIntents: "All intents",
      allStatuses: "All statuses",
      backToPsiActions: "Back to ME PSI Actions",
      notFoundTitle: "ME PSI Action Draft Not Found",
      openPsiIssues: "Open PSI Issues",
      lifecyclePlaceholders: "Lifecycle/timeline placeholders in PSI details",
      submitPreview: "Action Submit Preview",
      fields: "fields",
      required: "required",
    },
    detail: {
      psiRecord: "PSI Record",
      keyInformation: "Key Information",
      keyInformationDescription: "Core record fields for day-to-day operational review.",
      relatedRecordsDescription:
        "Connected PSI records used during review, coordination, and follow-up.",
      insights: "Insights",
      insightsDescription: "Operational indicators linked to the current record.",
      backToWorkspace: "Back to Workspace",
      relatedActionPlaceholders: "Related Action Placeholders",
      relatedActionDescription: "Actions route to draft previews and do not submit data.",
    },
    values: {
      object: "Object",
      tabs: "Tabs",
      noSupplier: "No Supplier",
      procurementSupplierInventory: "Procurement / Supplier / Inventory",
    },
  },
  zh: {
    shared: {
      psi: "PSI",
      procurement: "采购",
      supplier: "供应商",
      inventory: "库存",
      receiving: "收货",
      issues: "问题",
      actions: "动作",
      reports: "报表",
      overview: "概览",
      activity: "动态",
      attachments: "附件",
      linkedRecords: "关联记录",
      lifecycle: "生命周期",
      source: "来源",
      status: "状态",
      priority: "优先级",
      detail: "详情",
      module: "模块",
      record: "记录",
      action: "动作",
      relatedActions: "关联动作",
      relatedRecords: "关联记录",
      mockSource: "Mock 来源",
      serviceNoticePrefix: "PSI 服务提示：",
    },
    overview: {
      eyebrow: "PSI 工作区",
      title: "采购、供应商与库存营运",
      description: "用于复核队列、详情预览与关联上下文面板的 PSI 营运壳层。",
      notice: "使用 PSI 工作区协调采购请求、供应商跟进、库存风险与门店收货准备。",
      operationModules: "PSI 营运模块",
      operationModulesDescription: "每日 PSI 工作的主要入口。",
      procurementDescription: "请求队列、供应商交接与收货检查点。",
      supplierDescription: "供应商准备度、问题上下文与沟通状态。",
      inventoryDescription: "低库存、覆盖可见性与补货上下文。",
      procurementMetric: "12 项待复核",
      supplierMetric: "4 项供应商问题",
      inventoryMetric: "8 项观察库存",
      openProcurement: "打开采购",
      openSupplier: "打开供应商",
      openInventory: "打开库存",
      openPsiReports: "打开 PSI 报表",
      openIssues: "打开问题",
      createRequest: "创建请求",
      reviewSupplier: "复核供应商",
      linkInventory: "关联库存",
      currentFocus: "当前重点",
      procurementRequest: "采购请求",
      requestType: "请求类型",
      procurementNote: "采购备注",
      items: "项目",
      itemsDescription: "当前采购请求下的明细项目。",
      supplierAndReceiving: "供应商与收货",
      supplierAndReceivingDescription: "与供应商及门店收货准备相关的营运上下文。",
      linkedInventoryStatus: "关联库存状态",
      inventoryImpact: "库存影响",
      relatedContext: "关联上下文",
      serviceScope: "服务范围",
      workspaceNote: "工作区说明",
      workspaceNoteDescription:
        "PSI 沿用共享 ERP 详情模式，包含请求头、动作栏、明细项目、动态与门店上下文。",
    },
    rightRail: {
      psiStatus: "PSI 状态",
      procurementQueueVisible: "采购队列可见",
      supplierRisksSurfaced: "供应商风险已浮现",
      inventoryFollowUpCoordinated: "库存跟进仍通过工作区协调",
      todayFocus: "今日重点",
      workCoverage: "工作覆盖",
      procurementCoordination: "采购协同",
      supplierReview: "供应商复核",
      inventoryWatch: "库存观察",
      operationalFollowUp: "营运跟进",
      workspaceContext: "工作区上下文",
      serviceLayer: "服务层",
      issueWatch: "问题观察",
      issueContext: "问题上下文",
      queueReview: "队列复核",
      linkedIssueContext: "关联问题上下文",
      branchCoordination: "门店协同",
      catalogLayer: "通过共享目录层发布",
      connectedService: "通过已连接服务层发布",
      visibleRecordsSuffix: "条范围内有效记录",
      linkedIssueRecordsSuffix: "条关联问题记录",
      escalationReview: "升级复核",
      timelineFollowUp: "时间线跟进",
      operationalQueue: "营运队列",
      currentServiceScope: "当前服务范围",
      visibleRecords: "可见记录",
      issueWatchMeta: "问题观察",
      deliveryMode: "交付模式",
      catalogLayerShort: "目录层",
      connectedServiceShort: "已连接服务",
    },
    workspace: {
      eyebrow: "PSI 工作区",
      procurementTitle: "ME PSI 采购",
      procurementSubtitle: "采购请求、采购活动与问题复核工作区",
      supplierTitle: "ME PSI 供应商",
      supplierSubtitle: "供应商准备度、供应商问题与跟进工作区",
      inventoryTitle: "ME PSI 库存",
      inventorySubtitle: "库存风险、补货与库存观察工作区",
      mainRecords: "主要记录",
      mainRecordsDescription: "当前可见、用于营运复核的主要队列记录。",
      selectedRecord: "当前记录",
      selectedRecordDescription: "当前高亮队列记录的结构化元数据。",
      issueQueue: "问题队列",
      issueQueueDescription: "与当前 PSI 工作区关联的问题与跟进记录。",
      openPsiActions: "打开 PSI 动作",
      openIssues: "打开问题",
      openReports: "打开报表",
      issueWatch: "问题观察",
      selectedRecordTitle: "当前记录",
      supplier: "供应商",
      action: "动作",
      operationalFollowUp: "营运跟进",
      queue: "队列",
      openRecord: "打开记录",
      title: "标题",
      owner: "负责人",
      branch: "门店",
      lifecycle: "生命周期",
      createPurchaseRequest: "创建采购请求",
      recordReceiving: "记录收货",
      reportPurchaseIssue: "报告采购问题",
      stats: {
        purchaseRequests: "采购请求",
        pendingRequests: "待处理请求",
        purchaseOrders: "采购订单",
        issueOpen: "未关闭问题",
      },
      columns: {
        record: "记录",
        status: "状态",
        priority: "优先级",
        lifecycle: "生命周期",
        issue: "问题",
      },
    },
    issues: {
      eyebrow: "PSI 问题",
      title: "问题与事故队列",
      description: "用于采购、供应商与库存跟进的跨模块问题队列。",
      notice: "问题目前仅为元数据占位，并路由到详情/动作占位。不执行工作流或通知。",
      issues: "问题",
      psiCoordination: "PSI 协同",
      coverage: "覆盖范围",
      coverageValue: "采购 / 供应商 / 库存",
      openPsi: "打开 PSI",
      openReports: "打开报表",
      openActions: "打开动作",
      issueQueue: "问题队列",
      issueQueueDescription: "当前 PSI 问题的优先级、状态、模块来源与详情入口。",
      issueActivity: "问题动态",
      columns: {
        issue: "问题",
        module: "模块",
        priority: "优先级",
        status: "状态",
        lifecycle: "生命周期",
        detail: "详情",
      },
    },
    actions: {
      title: "ME PSI 动作",
      description: "动作草稿 / 表单占位设计",
      filters: "筛选",
      actionDrafts: "动作草稿",
      noActionDraftFound: "未找到动作草稿。",
      category: "分类",
      intent: "意图",
      status: "状态",
      allCategories: "全部分类",
      allIntents: "全部意图",
      allStatuses: "全部状态",
      backToPsiActions: "返回 ME PSI 动作",
      notFoundTitle: "找不到 ME PSI 动作草稿",
      openPsiIssues: "打开 PSI 问题",
      lifecyclePlaceholders: "PSI 详情中的生命周期 / 时间线占位",
      submitPreview: "动作可提交预览",
      fields: "字段",
      required: "必填",
    },
    detail: {
      psiRecord: "PSI 记录",
      keyInformation: "关键信息",
      keyInformationDescription: "用于日常营运复核的核心记录字段。",
      relatedRecordsDescription: "复核、协同与跟进过程中使用的关联 PSI 记录。",
      insights: "洞察",
      insightsDescription: "与当前记录关联的营运指标。",
      backToWorkspace: "返回工作区",
      relatedActionPlaceholders: "关联动作占位",
      relatedActionDescription: "动作会路由到草稿预览，不会提交数据。",
    },
    values: {
      object: "对象",
      tabs: "标签页",
      noSupplier: "无供应商",
      procurementSupplierInventory: "采购 / 供应商 / 库存",
    },
  },
} as const;

export function getPsiCopy(locale: PsiLocale) {
  return psiLanguageCopy[locale] ?? psiLanguageCopy.en;
}
