import type {
  MeApiBoundaryDraft,
  MeEntityMapping,
  MeLocalizedText,
  MeMigrationStep,
  MeRealDataMappingPageData,
  MeUiDataBlock,
  MeUiSurfaceKey,
} from "@/types/real-data-mapping";

function text(zh: string, en: string): MeLocalizedText {
  return { zh, en };
}

function block(input: MeUiDataBlock): MeUiDataBlock {
  return input;
}

function entity(input: MeEntityMapping): MeEntityMapping {
  return input;
}

function api(input: MeApiBoundaryDraft): MeApiBoundaryDraft {
  return input;
}

function step(input: MeMigrationStep): MeMigrationStep {
  return input;
}

const routeSets: Record<string, string[]> = {
  dashboard: ["/"],
  procurement: ["/psi", "/psi/procurement"],
  supplier: ["/psi", "/psi/supplier"],
  inventory: ["/psi", "/psi/inventory"],
  branches: ["/branches"],
  reports: ["/reports"],
  roles: ["/roles"],
};

export const realDataGuardrails = [
  "Planning-only. No database, API, auth, session, or write execution is connected.",
  "UI components must stay independent from repository, API, and schema implementation details.",
  "No direct database calls inside components or route files.",
  "No fetch, HTTP client helpers, Prisma client, credentials, or env-based connection logic in this layer.",
  "Read-only API boundaries should land before any workflow, approval, or stock posting writes.",
  "Repository/service/page-data boundaries remain the only approved mock-to-real migration path.",
];

export const realDataUiBlocks: MeUiDataBlock[] = [
  block({
    key: "dashboard-kpi-cards",
    surface: "dashboard",
    label: text("仪表盘 KPI 卡片", "Dashboard KPI Cards"),
    description: text("首页 KPI 指标卡片与趋势说明。", "Homepage KPI cards and trend annotations."),
    currentSource: "Static page-data helper metadata",
    futureSource: "Computed branch and operations summary view",
    sourceKind: "computed-view",
    readiness: "needs-schema",
    writeScope: "read-only",
    requiredEntities: ["branch", "inventory_stock", "procurement_request", "activity_event"],
    requiredFields: ["branch.id", "inventory_stock.on_hand_qty", "procurement_request.status", "activity_event.created_at"],
    relatedRoutes: routeSets.dashboard,
    guardrails: ["No live KPI calculation yet", "No direct SQL in components"],
  }),
  block({
    key: "dashboard-operational-alerts",
    surface: "dashboard",
    label: text("运营提醒", "Operational Alerts"),
    description: text("首页运营提醒与风险提示。", "Homepage operational alerts and risk notices."),
    currentSource: "Static alert card metadata",
    futureSource: "Issue and activity event aggregation",
    sourceKind: "computed-view",
    readiness: "needs-api",
    writeScope: "read-only",
    requiredEntities: ["issue", "activity_event", "inventory_stock"],
    requiredFields: ["issue.status", "issue.priority", "activity_event.related_entity", "inventory_stock.min_qty"],
    relatedRoutes: routeSets.dashboard,
    guardrails: ["No notification sending", "Read-only visibility first"],
  }),
  block({
    key: "dashboard-recent-activity",
    surface: "dashboard",
    label: text("最近活动", "Recent Activity"),
    description: text("首页最近活动与跨模块动态。", "Homepage recent activity and cross-module events."),
    currentSource: "Static timeline and alert copy",
    futureSource: "Activity event feed API",
    sourceKind: "api-endpoint",
    readiness: "needs-api",
    writeScope: "read-only",
    requiredEntities: ["activity_event", "user", "branch"],
    requiredFields: ["activity_event.id", "activity_event.created_at", "user.display_name", "branch.code"],
    relatedRoutes: routeSets.dashboard,
    guardrails: ["No audit write layer here", "No live subscriptions"],
  }),
  block({
    key: "dashboard-module-cards",
    surface: "dashboard",
    label: text("模块卡片", "Module Cards"),
    description: text("首页模块入口与状态摘要。", "Homepage module entry cards and status summary."),
    currentSource: "Config-driven module metadata plus static metrics",
    futureSource: "Computed module readiness summary",
    sourceKind: "computed-view",
    readiness: "needs-schema",
    writeScope: "read-only",
    requiredEntities: ["procurement_request", "supplier", "inventory_stock", "report_widget"],
    requiredFields: ["procurement_request.status", "supplier.status", "inventory_stock.risk_level", "report_widget.code"],
    relatedRoutes: routeSets.dashboard,
    guardrails: ["Navigation stays config-driven", "Do not hardcode live counts in components"],
  }),
  block({
    key: "dashboard-branch-context",
    surface: "dashboard",
    label: text("门店上下文", "Branch Context"),
    description: text("首页门店上下文与当前分店摘要。", "Homepage branch context and current branch summary."),
    currentSource: "Static branch preview metadata",
    futureSource: "Branch summary API",
    sourceKind: "api-endpoint",
    readiness: "needs-api",
    writeScope: "read-only",
    requiredEntities: ["branch", "activity_event", "issue"],
    requiredFields: ["branch.id", "branch.code", "branch.status", "issue.branch_id"],
    relatedRoutes: routeSets.dashboard,
    guardrails: ["No branch switching persistence", "No permission enforcement yet"],
  }),

  block({
    key: "procurement-request-summary",
    surface: "psi-procurement",
    label: text("采购申请摘要", "Procurement Request Summary"),
    description: text("采购详情页对象头与元数据摘要。", "Object header and metadata summary for procurement detail."),
    currentSource: "Static procurement detail page-data",
    futureSource: "Procurement request detail API",
    sourceKind: "api-endpoint",
    readiness: "ready-to-map",
    writeScope: "read-only",
    requiredEntities: ["procurement_request", "branch", "supplier", "user"],
    requiredFields: ["procurement_request.id", "procurement_request.status", "branch.code", "supplier.name", "user.display_name"],
    relatedRoutes: routeSets.procurement,
    guardrails: ["Header remains shell-driven", "No write actions from summary block"],
  }),
  block({
    key: "procurement-items-table",
    surface: "psi-procurement",
    label: text("采购明细表", "Procurement Items Table"),
    description: text("采购申请行项目与库存关联状态。", "Procurement line items and linked inventory status."),
    currentSource: "Static detail table rows",
    futureSource: "Procurement request items relation",
    sourceKind: "database-table",
    readiness: "needs-schema",
    writeScope: "read-only",
    requiredEntities: ["procurement_request_item", "inventory_item", "inventory_stock"],
    requiredFields: ["procurement_request_item.request_id", "procurement_request_item.qty", "inventory_item.sku", "inventory_stock.risk_level"],
    relatedRoutes: routeSets.procurement,
    guardrails: ["No stock posting", "No inline editing"],
  }),
  block({
    key: "procurement-timeline",
    surface: "psi-procurement",
    label: text("采购时间线", "Procurement Timeline"),
    description: text("采购申请生命周期与活动时间线。", "Lifecycle and activity timeline for the procurement request."),
    currentSource: "Static timeline items",
    futureSource: "Activity event stream scoped to procurement request",
    sourceKind: "api-endpoint",
    readiness: "needs-api",
    writeScope: "read-only",
    requiredEntities: ["activity_event", "procurement_request", "user"],
    requiredFields: ["activity_event.entity_id", "activity_event.event_type", "activity_event.created_at", "user.display_name"],
    relatedRoutes: routeSets.procurement,
    guardrails: ["No live event bus", "Read-only timeline first"],
  }),
  block({
    key: "procurement-action-bar",
    surface: "psi-procurement",
    label: text("采购动作栏", "Procurement Action Bar"),
    description: text("采购页面动作位与未来写入边界草稿。", "Procurement page action slots and future write boundary draft."),
    currentSource: "Static placeholder buttons",
    futureSource: "Action contract + permission mapping",
    sourceKind: "placeholder",
    readiness: "needs-permission",
    writeScope: "approval-write-future",
    requiredEntities: ["procurement_request", "task", "attachment", "audit_event"],
    requiredFields: ["procurement_request.id", "task.id", "attachment.id", "audit_event.id"],
    relatedRoutes: routeSets.procurement,
    guardrails: ["No approval execution", "No task creation", "No attachment upload yet"],
  }),
  block({
    key: "procurement-linked-inventory",
    surface: "psi-procurement",
    label: text("关联库存", "Linked Inventory"),
    description: text("采购申请右侧栏库存影响与补货上下文。", "Inventory impact and replenishment context in the procurement rail."),
    currentSource: "Static right-rail notes",
    futureSource: "Inventory risk view joined to procurement request",
    sourceKind: "computed-view",
    readiness: "needs-schema",
    writeScope: "read-only",
    requiredEntities: ["inventory_stock", "inventory_item", "procurement_request"],
    requiredFields: ["inventory_stock.item_id", "inventory_stock.on_hand_qty", "inventory_stock.min_qty"],
    relatedRoutes: routeSets.procurement,
    guardrails: ["No stock reservation logic", "No movement execution"],
  }),
  block({
    key: "procurement-linked-supplier",
    surface: "psi-procurement",
    label: text("关联供应商", "Linked Supplier"),
    description: text("采购申请关联供应商与履约上下文。", "Linked supplier and fulfillment context for procurement detail."),
    currentSource: "Static supplier note block",
    futureSource: "Supplier detail relation on procurement request",
    sourceKind: "database-table",
    readiness: "needs-schema",
    writeScope: "read-only",
    requiredEntities: ["supplier", "supplier_contact", "procurement_request"],
    requiredFields: ["supplier.id", "supplier.name", "supplier.lead_time_days", "supplier_contact.email"],
    relatedRoutes: routeSets.procurement,
    guardrails: ["No supplier portal", "No outbound messaging"],
  }),

  block({
    key: "supplier-profile",
    surface: "psi-supplier",
    label: text("供应商档案", "Supplier Profile"),
    description: text("供应商详情页对象头与档案字段。", "Object header and profile fields for supplier detail."),
    currentSource: "Static supplier page-data",
    futureSource: "Supplier detail API",
    sourceKind: "api-endpoint",
    readiness: "ready-to-map",
    writeScope: "read-only",
    requiredEntities: ["supplier", "branch", "user"],
    requiredFields: ["supplier.id", "supplier.name", "supplier.status", "supplier.category", "user.display_name"],
    relatedRoutes: routeSets.supplier,
    guardrails: ["No profile editing", "No workflow execution"],
  }),
  block({
    key: "supplier-contacts",
    surface: "psi-supplier",
    label: text("供应商联系人", "Supplier Contacts"),
    description: text("供应商联系人表与沟通角色。", "Supplier contact table and communication roles."),
    currentSource: "Static contact table rows",
    futureSource: "Supplier contact relation table",
    sourceKind: "database-table",
    readiness: "needs-schema",
    writeScope: "read-only",
    requiredEntities: ["supplier_contact", "supplier"],
    requiredFields: ["supplier_contact.supplier_id", "supplier_contact.name", "supplier_contact.phone", "supplier_contact.email"],
    relatedRoutes: routeSets.supplier,
    guardrails: ["No messaging integration", "No contact mutation"],
  }),
  block({
    key: "supplier-recent-orders",
    surface: "psi-supplier",
    label: text("最近采购记录", "Supplier Recent Orders"),
    description: text("供应商关联采购记录摘要。", "Linked procurement records summary for the supplier."),
    currentSource: "Static related order table",
    futureSource: "Procurement requests filtered by supplier",
    sourceKind: "api-endpoint",
    readiness: "needs-api",
    writeScope: "read-only",
    requiredEntities: ["supplier", "procurement_request", "branch"],
    requiredFields: ["procurement_request.supplier_id", "procurement_request.status", "branch.code", "procurement_request.total_estimated_amount"],
    relatedRoutes: routeSets.supplier,
    guardrails: ["No supplier-side actions", "No order mutation"],
  }),
  block({
    key: "supplier-issues",
    surface: "psi-supplier",
    label: text("供应商问题", "Supplier Issues"),
    description: text("供应商问题与风险上下文。", "Supplier issue and risk context."),
    currentSource: "Static issue note and rail items",
    futureSource: "Supplier issue list API",
    sourceKind: "api-endpoint",
    readiness: "needs-api",
    writeScope: "read-only",
    requiredEntities: ["issue", "supplier", "task"],
    requiredFields: ["issue.entity_id", "issue.priority", "issue.status", "task.status"],
    relatedRoutes: routeSets.supplier,
    guardrails: ["No issue close-loop actions", "No task creation yet"],
  }),
  block({
    key: "supplier-health",
    surface: "psi-supplier",
    label: text("供应商健康度", "Supplier Health"),
    description: text("供应商健康度与履约观察。", "Supplier health and fulfillment watch indicators."),
    currentSource: "Static rail summary",
    futureSource: "Computed supplier score view",
    sourceKind: "computed-view",
    readiness: "deferred",
    writeScope: "read-only",
    requiredEntities: ["supplier", "procurement_request", "issue", "activity_event"],
    requiredFields: ["supplier.status", "procurement_request.status", "issue.priority", "activity_event.created_at"],
    relatedRoutes: routeSets.supplier,
    guardrails: ["No scoring engine yet", "No predictive logic in UI"],
  }),
  block({
    key: "supplier-linked-procurement",
    surface: "psi-supplier",
    label: text("关联采购单", "Linked Procurement Records"),
    description: text("供应商详情侧栏关联采购记录。", "Linked procurement records in the supplier context rail."),
    currentSource: "Static rail record list",
    futureSource: "Procurement-by-supplier API",
    sourceKind: "api-endpoint",
    readiness: "needs-api",
    writeScope: "read-only",
    requiredEntities: ["supplier", "procurement_request"],
    requiredFields: ["procurement_request.id", "procurement_request.supplier_id", "procurement_request.status"],
    relatedRoutes: routeSets.supplier,
    guardrails: ["Read-only drill-down only", "No follow-up write flow"],
  }),

  block({
    key: "inventory-stock-profile",
    surface: "psi-inventory",
    label: text("库存档案", "Inventory Stock Profile"),
    description: text("库存详情页对象头与库存字段。", "Object header and stock profile fields for inventory detail."),
    currentSource: "Static inventory page-data",
    futureSource: "Inventory stock detail API",
    sourceKind: "api-endpoint",
    readiness: "ready-to-map",
    writeScope: "read-only",
    requiredEntities: ["inventory_item", "inventory_stock", "branch", "supplier"],
    requiredFields: ["inventory_item.sku", "inventory_stock.on_hand_qty", "inventory_stock.min_qty", "branch.code", "supplier.name"],
    relatedRoutes: routeSets.inventory,
    guardrails: ["No live stock adjustment", "No warehouse posting"],
  }),
  block({
    key: "inventory-stock-movement",
    surface: "psi-inventory",
    label: text("库存移动表", "Stock Movement Table"),
    description: text("库存流水与出入库上下文。", "Stock movement rows and inbound/outbound context."),
    currentSource: "Static stock movement table",
    futureSource: "Stock movement relation table",
    sourceKind: "database-table",
    readiness: "needs-schema",
    writeScope: "system-write-future",
    requiredEntities: ["stock_movement", "inventory_stock", "inventory_item"],
    requiredFields: ["stock_movement.inventory_stock_id", "stock_movement.qty_delta", "stock_movement.reference_code", "stock_movement.created_at"],
    relatedRoutes: routeSets.inventory,
    guardrails: ["Read view first", "No posting from UI"],
  }),
  block({
    key: "inventory-expiry-watch",
    surface: "psi-inventory",
    label: text("效期观察", "Expiry Watch"),
    description: text("库存效期观察与质量风险提示。", "Expiry watch and quality risk indicators."),
    currentSource: "Static expiry note",
    futureSource: "Inventory expiry computed view",
    sourceKind: "computed-view",
    readiness: "deferred",
    writeScope: "read-only",
    requiredEntities: ["inventory_stock", "inventory_item"],
    requiredFields: ["inventory_stock.expiry_date", "inventory_stock.batch_code", "inventory_item.name"],
    relatedRoutes: routeSets.inventory,
    guardrails: ["No batch transaction engine", "No wastage posting"],
  }),
  block({
    key: "inventory-low-stock-risk",
    surface: "psi-inventory",
    label: text("低库存风险", "Low-stock Risk"),
    description: text("库存侧栏低库存风险与补货观察。", "Low-stock risk and replenishment watch in the inventory rail."),
    currentSource: "Static rail risk summary",
    futureSource: "Inventory risk API",
    sourceKind: "computed-view",
    readiness: "needs-api",
    writeScope: "read-only",
    requiredEntities: ["inventory_stock", "procurement_request", "issue"],
    requiredFields: ["inventory_stock.on_hand_qty", "inventory_stock.min_qty", "procurement_request.status", "issue.priority"],
    relatedRoutes: routeSets.inventory,
    guardrails: ["No automatic reorder generation", "No stock rule engine"],
  }),
  block({
    key: "inventory-linked-supplier",
    surface: "psi-inventory",
    label: text("关联供应商", "Linked Supplier"),
    description: text("库存详情关联供应商上下文。", "Linked supplier context for inventory detail."),
    currentSource: "Static supplier context line",
    futureSource: "Inventory item preferred supplier relation",
    sourceKind: "database-table",
    readiness: "needs-schema",
    writeScope: "read-only",
    requiredEntities: ["inventory_item", "supplier"],
    requiredFields: ["inventory_item.preferred_supplier_id", "supplier.name", "supplier.status"],
    relatedRoutes: routeSets.inventory,
    guardrails: ["No supplier updates", "Read-only relation preview"],
  }),
  block({
    key: "inventory-linked-procurement",
    surface: "psi-inventory",
    label: text("关联采购", "Linked Procurement"),
    description: text("库存详情关联补货采购单。", "Linked replenishment procurement records for inventory detail."),
    currentSource: "Static linked procurement table",
    futureSource: "Procurement requests filtered by inventory item",
    sourceKind: "api-endpoint",
    readiness: "needs-api",
    writeScope: "read-only",
    requiredEntities: ["procurement_request", "procurement_request_item", "inventory_item"],
    requiredFields: ["procurement_request.id", "procurement_request.status", "procurement_request_item.inventory_item_id"],
    relatedRoutes: routeSets.inventory,
    guardrails: ["No procurement creation here", "No posting or receiving execution"],
  }),

  block({
    key: "branch-profile",
    surface: "branch-workspace",
    label: text("门店档案", "Branch Profile"),
    description: text("门店详情页对象头与门店档案字段。", "Object header and profile fields for branch detail."),
    currentSource: "Static branch preview metadata",
    futureSource: "Branch detail API",
    sourceKind: "api-endpoint",
    readiness: "ready-to-map",
    writeScope: "read-only",
    requiredEntities: ["branch", "user", "role"],
    requiredFields: ["branch.id", "branch.code", "branch.status", "user.display_name", "role.name"],
    relatedRoutes: routeSets.branches,
    guardrails: ["No tenant model yet", "No branch switch persistence"],
  }),
  block({
    key: "branch-operations-status",
    surface: "branch-workspace",
    label: text("门店运营状态", "Branch Operations Status"),
    description: text("门店运行状态行与负责人上下文。", "Branch operation rows and owner context."),
    currentSource: "Static operations table",
    futureSource: "Branch operations status view",
    sourceKind: "computed-view",
    readiness: "needs-schema",
    writeScope: "read-only",
    requiredEntities: ["branch", "inventory_stock", "procurement_request", "task"],
    requiredFields: ["branch.id", "inventory_stock.risk_level", "procurement_request.status", "task.status"],
    relatedRoutes: routeSets.branches,
    guardrails: ["No live SLA logic", "No action execution"],
  }),
  block({
    key: "branch-issue-activity-table",
    surface: "branch-workspace",
    label: text("门店问题与活动", "Branch Issue / Activity Table"),
    description: text("门店问题和活动列表。", "Branch issue and activity list."),
    currentSource: "Static issue table and timeline",
    futureSource: "Branch issue and activity APIs",
    sourceKind: "api-endpoint",
    readiness: "needs-api",
    writeScope: "read-only",
    requiredEntities: ["issue", "activity_event", "branch"],
    requiredFields: ["issue.branch_id", "issue.status", "activity_event.branch_id", "activity_event.created_at"],
    relatedRoutes: routeSets.branches,
    guardrails: ["No issue update workflow", "No branch notifications"],
  }),
  block({
    key: "branch-linked-modules",
    surface: "branch-workspace",
    label: text("门店关联模块", "Linked Modules"),
    description: text("门店关联 PSI / Reports / Roles 模块。", "Branch-linked PSI / Reports / Roles modules."),
    currentSource: "Static branch module cards",
    futureSource: "Computed branch module readiness view",
    sourceKind: "computed-view",
    readiness: "deferred",
    writeScope: "read-only",
    requiredEntities: ["branch", "report_widget", "role"],
    requiredFields: ["branch.code", "report_widget.code", "role.key"],
    relatedRoutes: routeSets.branches,
    guardrails: ["Navigation remains config-driven", "No tenant-aware feature toggles"],
  }),
  block({
    key: "branch-context-rail",
    surface: "branch-workspace",
    label: text("门店上下文侧栏", "Branch Context Rail"),
    description: text("门店详情右侧上下文与下一步建议。", "Context rail and next-step hints for branch detail."),
    currentSource: "Static rail cards",
    futureSource: "Branch context summary API",
    sourceKind: "api-endpoint",
    readiness: "needs-api",
    writeScope: "read-only",
    requiredEntities: ["branch", "activity_event", "issue", "task"],
    requiredFields: ["branch.code", "activity_event.summary", "issue.priority", "task.status"],
    relatedRoutes: routeSets.branches,
    guardrails: ["No branch permission logic", "No persistence in rail state"],
  }),

  block({
    key: "report-widgets",
    surface: "reports",
    label: text("报表小部件", "Report Widgets"),
    description: text("PSI 报表概览小部件。", "PSI report overview widgets."),
    currentSource: "Static report widget contract and page-data",
    futureSource: "Report snapshot and computed widget API",
    sourceKind: "computed-view",
    readiness: "needs-api",
    writeScope: "read-only",
    requiredEntities: ["report_widget", "report_snapshot", "branch"],
    requiredFields: ["report_widget.code", "report_snapshot.generated_at", "branch.code"],
    relatedRoutes: routeSets.reports,
    guardrails: ["No BI engine", "No chart query execution in UI"],
  }),
  block({
    key: "report-filters",
    surface: "reports",
    label: text("报表筛选器", "Report Filters"),
    description: text("报表筛选、时间范围与门店过滤。", "Report filters, date ranges, and branch scoping."),
    currentSource: "Static filter placeholders",
    futureSource: "Query parameter contract on report APIs",
    sourceKind: "placeholder",
    readiness: "needs-api",
    writeScope: "read-only",
    requiredEntities: ["branch", "report_snapshot"],
    requiredFields: ["branch.id", "report_snapshot.date_range_start", "report_snapshot.date_range_end"],
    relatedRoutes: routeSets.reports,
    guardrails: ["No client-side SQL", "No persisted filter state"],
  }),
  block({
    key: "report-export-placeholder",
    surface: "reports",
    label: text("报表导出占位", "Report Export Placeholder"),
    description: text("导出入口与未来文件边界。", "Export entry point and future file boundary."),
    currentSource: "Static export action placeholder",
    futureSource: "Report export API boundary draft",
    sourceKind: "placeholder",
    readiness: "deferred",
    writeScope: "external-sync-future",
    requiredEntities: ["report_snapshot", "attachment", "audit_event"],
    requiredFields: ["report_snapshot.id", "attachment.id", "audit_event.id"],
    relatedRoutes: routeSets.reports,
    guardrails: ["No export generation yet", "No file storage integration"],
  }),
  block({
    key: "report-computed-metrics",
    surface: "reports",
    label: text("报表计算指标", "Computed Metrics"),
    description: text("报表指标与趋势计算。", "Report metrics and trend computation."),
    currentSource: "Static metric metadata",
    futureSource: "Materialized report snapshots or metrics API",
    sourceKind: "computed-view",
    readiness: "needs-schema",
    writeScope: "read-only",
    requiredEntities: ["report_snapshot", "inventory_stock", "procurement_request", "supplier"],
    requiredFields: ["report_snapshot.metric_key", "report_snapshot.metric_value", "procurement_request.status"],
    relatedRoutes: routeSets.reports,
    guardrails: ["No runtime heavy aggregation in components", "No direct database access"],
  }),

  block({
    key: "role-profile",
    surface: "roles",
    label: text("角色档案", "Role Profile"),
    description: text("角色详情页档案与职责摘要。", "Role detail profile and responsibility summary."),
    currentSource: "Static role workspace metadata",
    futureSource: "Role detail API",
    sourceKind: "api-endpoint",
    readiness: "needs-schema",
    writeScope: "read-only",
    requiredEntities: ["role", "user"],
    requiredFields: ["role.id", "role.name", "user.display_name", "user.role_id"],
    relatedRoutes: routeSets.roles,
    guardrails: ["No auth/session coupling", "No runtime enforcement"],
  }),
  block({
    key: "role-user-mapping",
    surface: "roles",
    label: text("用户与员工映射", "User / Staff Mapping"),
    description: text("角色到员工的未来映射关系。", "Future mapping between roles and staff records."),
    currentSource: "Static placeholder rows",
    futureSource: "User-role relation API",
    sourceKind: "database-table",
    readiness: "needs-permission",
    writeScope: "read-only",
    requiredEntities: ["user", "role", "branch"],
    requiredFields: ["user.id", "user.role_id", "user.branch_id", "role.key"],
    relatedRoutes: routeSets.roles,
    guardrails: ["No user management yet", "No session or identity provider wiring"],
  }),
  block({
    key: "role-permission-preview",
    surface: "roles",
    label: text("权限预览", "Permission Preview"),
    description: text("角色权限预览与未来访问控制对接。", "Role permission preview and future access-control mapping."),
    currentSource: "Static access preview metadata",
    futureSource: "Access policy API or contract mapping",
    sourceKind: "placeholder",
    readiness: "needs-permission",
    writeScope: "not-planned",
    requiredEntities: ["role", "user", "audit_event"],
    requiredFields: ["role.key", "user.id", "audit_event.id"],
    relatedRoutes: routeSets.roles,
    guardrails: ["No middleware enforcement", "No runtime route hiding"],
  }),
];

export const realDataEntityMappings: MeEntityMapping[] = [
  entity({
    entity: "branch",
    label: text("门店", "Branch"),
    description: text("门店、区域与运营上下文主实体。", "Primary entity for branch, region, and operating context."),
    futureTableName: "branches",
    primaryKey: "id",
    requiredFields: ["id", "code", "name", "status", "scope"],
    optionalFields: ["manager_user_id", "region", "opened_at"],
    relationships: ["has many inventory_stock", "has many procurement_request", "has many issue", "has many activity_event"],
    usedBySurfaces: ["dashboard", "psi-procurement", "psi-supplier", "psi-inventory", "branch-workspace", "reports", "roles"],
    readiness: "needs-schema",
  }),
  entity({
    entity: "user",
    label: text("用户", "User"),
    description: text("未来员工、负责人和审计参与者实体。", "Future employee, owner, and audit actor entity."),
    futureTableName: "users",
    primaryKey: "id",
    requiredFields: ["id", "display_name", "status", "role_id"],
    optionalFields: ["branch_id", "email", "phone"],
    relationships: ["belongs to role", "belongs to branch", "has many activity_event"],
    usedBySurfaces: ["psi-procurement", "psi-supplier", "branch-workspace", "roles"],
    readiness: "needs-permission",
  }),
  entity({
    entity: "role",
    label: text("角色", "Role"),
    description: text("角色定义与未来权限映射实体。", "Role definition and future permission mapping entity."),
    futureTableName: "roles",
    primaryKey: "id",
    requiredFields: ["id", "key", "name", "status"],
    optionalFields: ["description", "branch_scope"],
    relationships: ["has many users", "maps to access policies"],
    usedBySurfaces: ["branch-workspace", "roles"],
    readiness: "needs-permission",
  }),
  entity({
    entity: "supplier",
    label: text("供应商", "Supplier"),
    description: text("供应商主档、履约与商业状态实体。", "Supplier master profile, fulfillment, and commercial status entity."),
    futureTableName: "suppliers",
    primaryKey: "id",
    requiredFields: ["id", "code", "name", "status", "category"],
    optionalFields: ["lead_time_days", "owner_user_id", "service_region"],
    relationships: ["has many supplier_contact", "has many procurement_request", "has many issue"],
    usedBySurfaces: ["psi-procurement", "psi-supplier", "psi-inventory"],
    readiness: "needs-schema",
  }),
  entity({
    entity: "supplier_contact",
    label: text("供应商联系人", "Supplier Contact"),
    description: text("供应商联系人与沟通角色。", "Supplier contacts and communication roles."),
    futureTableName: "supplier_contacts",
    primaryKey: "id",
    requiredFields: ["id", "supplier_id", "name", "email", "phone"],
    optionalFields: ["role_title", "status", "notes"],
    relationships: ["belongs to supplier"],
    usedBySurfaces: ["psi-supplier", "psi-procurement"],
    readiness: "needs-schema",
  }),
  entity({
    entity: "procurement_request",
    label: text("采购申请", "Procurement Request"),
    description: text("采购申请对象头与审批前读取实体。", "Procurement request object header and pre-approval read entity."),
    futureTableName: "procurement_requests",
    primaryKey: "id",
    requiredFields: ["id", "branch_id", "supplier_id", "status", "requested_by_user_id"],
    optionalFields: ["expected_delivery_at", "priority", "total_estimated_amount"],
    relationships: ["belongs to branch", "belongs to supplier", "has many procurement_request_item", "has many attachment"],
    usedBySurfaces: ["dashboard", "psi-procurement", "psi-supplier", "psi-inventory", "reports"],
    readiness: "needs-schema",
  }),
  entity({
    entity: "procurement_request_item",
    label: text("采购申请明细", "Procurement Request Item"),
    description: text("采购申请行项目实体。", "Procurement request line item entity."),
    futureTableName: "procurement_request_items",
    primaryKey: "id",
    requiredFields: ["id", "request_id", "inventory_item_id", "qty", "unit"],
    optionalFields: ["estimated_cost", "status", "notes"],
    relationships: ["belongs to procurement_request", "belongs to inventory_item"],
    usedBySurfaces: ["psi-procurement", "psi-inventory"],
    readiness: "needs-schema",
  }),
  entity({
    entity: "inventory_item",
    label: text("库存物料", "Inventory Item"),
    description: text("库存 SKU / 物料主档实体。", "Inventory SKU / item master entity."),
    futureTableName: "inventory_items",
    primaryKey: "id",
    requiredFields: ["id", "sku", "name", "status"],
    optionalFields: ["category", "preferred_supplier_id", "storage_type"],
    relationships: ["has many inventory_stock", "has many procurement_request_item", "belongs to supplier"],
    usedBySurfaces: ["psi-procurement", "psi-inventory"],
    readiness: "needs-schema",
  }),
  entity({
    entity: "inventory_stock",
    label: text("库存余额", "Inventory Stock"),
    description: text("门店库存余额与风险实体。", "Branch-level inventory stock balance and risk entity."),
    futureTableName: "inventory_stocks",
    primaryKey: "id",
    requiredFields: ["id", "inventory_item_id", "branch_id", "on_hand_qty", "min_qty"],
    optionalFields: ["coverage_days", "expiry_date", "risk_level"],
    relationships: ["belongs to inventory_item", "belongs to branch", "has many stock_movement"],
    usedBySurfaces: ["dashboard", "psi-procurement", "psi-inventory", "branch-workspace", "reports"],
    readiness: "needs-schema",
  }),
  entity({
    entity: "stock_movement",
    label: text("库存流水", "Stock Movement"),
    description: text("库存出入库流水实体。", "Inventory inbound/outbound movement entity."),
    futureTableName: "stock_movements",
    primaryKey: "id",
    requiredFields: ["id", "inventory_stock_id", "qty_delta", "movement_type", "created_at"],
    optionalFields: ["reference_code", "batch_code", "notes"],
    relationships: ["belongs to inventory_stock"],
    usedBySurfaces: ["psi-inventory"],
    readiness: "needs-schema",
  }),
  entity({
    entity: "issue",
    label: text("问题", "Issue"),
    description: text("跨模块问题、风险与跟进实体。", "Cross-module issue, risk, and follow-up entity."),
    futureTableName: "issues",
    primaryKey: "id",
    requiredFields: ["id", "entity_type", "entity_id", "status", "priority"],
    optionalFields: ["branch_id", "owner_user_id", "summary"],
    relationships: ["belongs to branch", "may link to supplier/procurement_request/inventory_stock"],
    usedBySurfaces: ["dashboard", "psi-supplier", "psi-inventory", "branch-workspace"],
    readiness: "needs-schema",
  }),
  entity({
    entity: "task",
    label: text("任务", "Task"),
    description: text("未来跨模块跟进任务实体。", "Future cross-module follow-up task entity."),
    futureTableName: "tasks",
    primaryKey: "id",
    requiredFields: ["id", "title", "status", "source_module"],
    optionalFields: ["owner_user_id", "branch_id", "due_at"],
    relationships: ["belongs to branch", "belongs to user", "may link to issue or procurement_request"],
    usedBySurfaces: ["psi-procurement", "psi-supplier", "psi-inventory", "branch-workspace", "tasks"],
    readiness: "deferred",
    notes: text("任务 UI 已存在，但真实任务写入仍延后。", "Task UI exists, but real task writes remain deferred."),
  }),
  entity({
    entity: "activity_event",
    label: text("活动事件", "Activity Event"),
    description: text("时间线、最近活动与审计前可视化事件实体。", "Timeline, recent activity, and pre-audit visual activity entity."),
    futureTableName: "activity_events",
    primaryKey: "id",
    requiredFields: ["id", "entity_type", "entity_id", "event_type", "created_at"],
    optionalFields: ["actor_user_id", "branch_id", "summary"],
    relationships: ["belongs to user", "belongs to branch", "may mirror audit_event later"],
    usedBySurfaces: ["dashboard", "psi-procurement", "psi-supplier", "psi-inventory", "branch-workspace"],
    readiness: "needs-schema",
  }),
  entity({
    entity: "report_widget",
    label: text("报表小部件", "Report Widget"),
    description: text("报表小部件注册与运行配置实体。", "Report widget registration and execution-config entity."),
    futureTableName: "report_widgets",
    primaryKey: "id",
    requiredFields: ["id", "code", "name", "status"],
    optionalFields: ["query_key", "default_filters", "module_scope"],
    relationships: ["has many report_snapshot"],
    usedBySurfaces: ["dashboard", "reports", "branch-workspace"],
    readiness: "needs-schema",
  }),
  entity({
    entity: "report_snapshot",
    label: text("报表快照", "Report Snapshot"),
    description: text("预计算报表输出与指标快照实体。", "Precomputed report output and metric snapshot entity."),
    futureTableName: "report_snapshots",
    primaryKey: "id",
    requiredFields: ["id", "widget_id", "metric_key", "metric_value", "generated_at"],
    optionalFields: ["branch_id", "date_range_start", "date_range_end"],
    relationships: ["belongs to report_widget", "may belong to branch"],
    usedBySurfaces: ["reports"],
    readiness: "needs-schema",
  }),
  entity({
    entity: "attachment",
    label: text("附件", "Attachment"),
    description: text("未来附件元数据实体。", "Future attachment metadata entity."),
    futureTableName: "attachments",
    primaryKey: "id",
    requiredFields: ["id", "entity_type", "entity_id", "file_name", "storage_key"],
    optionalFields: ["uploaded_by_user_id", "mime_type", "size_bytes"],
    relationships: ["belongs to procurement_request or supplier", "belongs to user"],
    usedBySurfaces: ["psi-procurement", "psi-supplier", "reports"],
    readiness: "deferred",
  }),
  entity({
    entity: "audit_event",
    label: text("审计事件", "Audit Event"),
    description: text("未来审计日志与动作溯源实体。", "Future audit log and action trace entity."),
    futureTableName: "audit_events",
    primaryKey: "id",
    requiredFields: ["id", "entity_type", "entity_id", "action_key", "created_at"],
    optionalFields: ["actor_user_id", "before_json", "after_json"],
    relationships: ["belongs to user", "may mirror activity_event"],
    usedBySurfaces: ["psi-procurement", "roles", "system-foundation"],
    readiness: "deferred",
  }),
];

export const realDataApiBoundaryDrafts: MeApiBoundaryDraft[] = [
  api({
    key: "get-branches",
    method: "GET",
    path: "/api/branches",
    purpose: text("读取门店列表与上下文摘要。", "Read branch list and context summary."),
    entities: ["branch"],
    readOrWrite: "read-only",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "draft-read-only",
    guardrails: ["Read-only first", "No branch switching persistence"],
  }),
  api({
    key: "get-branch-by-id",
    method: "GET",
    path: "/api/branches/:id",
    purpose: text("读取单个门店详情与运行上下文。", "Read a single branch detail and operating context."),
    entities: ["branch", "issue", "activity_event"],
    readOrWrite: "read-only",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "draft-read-only",
    guardrails: ["No tenant mutation", "No permission enforcement in UI layer"],
  }),
  api({
    key: "get-suppliers",
    method: "GET",
    path: "/api/suppliers",
    purpose: text("读取供应商列表与摘要。", "Read supplier list and summary."),
    entities: ["supplier"],
    readOrWrite: "read-only",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "draft-read-only",
    guardrails: ["Read-only first", "No supplier portal behavior"],
  }),
  api({
    key: "get-supplier-by-id",
    method: "GET",
    path: "/api/suppliers/:id",
    purpose: text("读取供应商详情、联系人与关联记录。", "Read supplier detail, contacts, and linked records."),
    entities: ["supplier", "supplier_contact", "procurement_request", "issue"],
    readOrWrite: "read-only",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "draft-read-only",
    guardrails: ["No contact writes", "No issue workflow execution"],
  }),
  api({
    key: "get-inventory",
    method: "GET",
    path: "/api/inventory",
    purpose: text("读取库存列表与风险摘要。", "Read inventory list and risk summary."),
    entities: ["inventory_item", "inventory_stock"],
    readOrWrite: "read-only",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "draft-read-only",
    guardrails: ["Read-only first", "No stock movement posting"],
  }),
  api({
    key: "get-inventory-by-id",
    method: "GET",
    path: "/api/inventory/:id",
    purpose: text("读取库存详情、流水、效期与关联采购。", "Read inventory detail, movement, expiry, and linked procurement."),
    entities: ["inventory_item", "inventory_stock", "stock_movement", "procurement_request"],
    readOrWrite: "read-only",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "draft-read-only",
    guardrails: ["No posting", "No quantity updates from UI"],
  }),
  api({
    key: "get-procurement-requests",
    method: "GET",
    path: "/api/procurement-requests",
    purpose: text("读取采购申请列表与状态摘要。", "Read procurement request list and status summary."),
    entities: ["procurement_request"],
    readOrWrite: "read-only",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "draft-read-only",
    guardrails: ["Read-only first", "No approval execution"],
  }),
  api({
    key: "get-procurement-request-by-id",
    method: "GET",
    path: "/api/procurement-requests/:id",
    purpose: text("读取采购申请详情、明细、时间线与关联上下文。", "Read procurement request detail, items, timeline, and linked context."),
    entities: ["procurement_request", "procurement_request_item", "supplier", "inventory_stock", "activity_event"],
    readOrWrite: "read-only",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "draft-read-only",
    guardrails: ["No draft mutation", "No task or approval creation"],
  }),
  api({
    key: "get-reports-psi-overview",
    method: "GET",
    path: "/api/reports/psi-overview",
    purpose: text("读取 PSI 报表概览与预计算指标。", "Read PSI overview report and precomputed metrics."),
    entities: ["report_widget", "report_snapshot", "branch"],
    readOrWrite: "read-only",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "draft-read-only",
    guardrails: ["No BI engine in UI", "Read-only computed output only"],
  }),
  api({
    key: "get-activity-events",
    method: "GET",
    path: "/api/activity-events",
    purpose: text("读取最近活动和详情时间线事件。", "Read recent activity and detail timeline events."),
    entities: ["activity_event", "user", "branch"],
    readOrWrite: "read-only",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "draft-read-only",
    guardrails: ["Read feed only", "No websocket or push requirement in first pass"],
  }),
  api({
    key: "post-procurement-requests",
    method: "POST",
    path: "/api/procurement-requests",
    purpose: text("未来创建采购申请草稿。", "Future creation of procurement request drafts."),
    entities: ["procurement_request", "procurement_request_item", "audit_event"],
    readOrWrite: "write-future",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "future-write-deferred",
    guardrails: ["Not implemented", "After read layer and permission model only"],
  }),
  api({
    key: "patch-procurement-request-by-id",
    method: "PATCH",
    path: "/api/procurement-requests/:id",
    purpose: text("未来更新采购申请草稿或审批前字段。", "Future update of procurement request draft or pre-approval fields."),
    entities: ["procurement_request", "audit_event"],
    readOrWrite: "write-future",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "future-write-deferred",
    guardrails: ["Not implemented", "Approval logic still deferred"],
  }),
  api({
    key: "post-tasks",
    method: "POST",
    path: "/api/tasks",
    purpose: text("未来创建跨模块跟进任务。", "Future creation of cross-module follow-up tasks."),
    entities: ["task", "user", "audit_event"],
    readOrWrite: "write-future",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "future-write-deferred",
    guardrails: ["Not implemented", "Task execution and workflow remain deferred"],
  }),
  api({
    key: "post-attachments",
    method: "POST",
    path: "/api/attachments",
    purpose: text("未来创建附件元数据与文件映射。", "Future creation of attachment metadata and file mapping."),
    entities: ["attachment", "user", "audit_event"],
    readOrWrite: "write-future",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "future-write-deferred",
    guardrails: ["Not implemented", "No file storage or upload flow yet"],
  }),
  api({
    key: "post-approval-actions",
    method: "POST",
    path: "/api/approval-actions",
    purpose: text("未来执行审批动作与审计记录。", "Future execution of approval actions and audit logging."),
    entities: ["procurement_request", "task", "audit_event"],
    readOrWrite: "write-future",
    authRequiredFuture: true,
    permissionRequiredFuture: true,
    status: "future-write-deferred",
    guardrails: ["Not implemented", "Approval workflow and notification remain deferred"],
  }),
];

export const realDataMigrationSteps: MeMigrationStep[] = [
  step({
    key: "freeze-shell",
    title: text("冻结 Shell 与详情模式", "Freeze Shell and Detail Pattern"),
    description: text("保持导航、布局与详情模式稳定，避免后续数据接入时重写 UI 外壳。", "Keep navigation, layouts, and detail patterns stable so data wiring does not force a shell rewrite."),
    status: "planned",
    guardrails: ["No route rewrites", "Keep shell independent from datasource choice"],
  }),
  step({
    key: "define-schema",
    title: text("定义数据库 Schema", "Define Database Schema"),
    description: text("先完成实体、字段、关系与命名约定，再考虑 API 或仓储实现。", "Complete entities, fields, relationships, and naming rules before any API or repository implementation."),
    status: "planned",
    guardrails: ["Schema first", "No direct component coupling to table names"],
  }),
  step({
    key: "read-only-api",
    title: text("先实现只读 API", "Implement Read-only API First"),
    description: text("优先上线 GET 边界，先让页面从统一读层取数。", "Ship GET boundaries first so pages move onto a unified read layer."),
    status: "planned",
    guardrails: ["No writes in first data milestone", "No approval execution"],
  }),
  step({
    key: "swap-page-data",
    title: text("替换 Page Data Helper", "Replace Page-data Helpers"),
    description: text("让现有 page-data helper 改为调用仓储/服务层，而不是直接返回静态 mock 字段。", "Move existing page-data helpers to repository/service-backed reads instead of static mock fields."),
    status: "planned",
    guardrails: ["Preserve current UI props", "Do not move fetch logic into components"],
  }),
  step({
    key: "auth-session",
    title: text("补充 Auth / Session", "Add Auth / Session"),
    description: text("在读层稳定后，再为未来身份上下文增加认证与会话。", "Add authentication and session context only after the read layer is stable."),
    status: "deferred",
    guardrails: ["No auth before data contracts settle", "No session assumptions in current UI"],
  }),
  step({
    key: "permissions",
    title: text("补充权限与角色控制", "Add Permissions and Role Controls"),
    description: text("基于已稳定的身份与读层，接入访问控制和权限过滤。", "Attach access control and permission filtering only after identity and read boundaries are stable."),
    status: "deferred",
    guardrails: ["No middleware rewrite in current milestone", "Keep navigation config-driven"],
  }),
  step({
    key: "writes-approvals",
    title: text("最后接入写入与审批", "Add Writes and Approvals Last"),
    description: text("写入、审批、库存过账和通知必须晚于只读层验证完成。", "Writes, approvals, stock posting, and notifications must come after the read layer has been validated."),
    status: "deferred",
    guardrails: ["No stock posting before audit and permission model", "No approval execution before workflow layer"],
  }),
];

export const realDataSurfaceOrder: MeUiSurfaceKey[] = [
  "dashboard",
  "psi-procurement",
  "psi-supplier",
  "psi-inventory",
  "branch-workspace",
  "reports",
  "roles",
];

export const realDataSurfaceLabels: Record<MeUiSurfaceKey, MeLocalizedText> = {
  dashboard: text("仪表盘", "Dashboard"),
  "psi-procurement": text("PSI 采购", "PSI Procurement"),
  "psi-supplier": text("PSI 供应商", "PSI Supplier"),
  "psi-inventory": text("PSI 库存", "PSI Inventory"),
  "branch-workspace": text("门店工作区", "Branch Workspace"),
  reports: text("报表", "Reports"),
  roles: text("角色", "Roles"),
  tasks: text("任务", "Tasks"),
  "demo-readiness": text("演示就绪", "Demo Readiness"),
  "stakeholder-summary": text("利益相关方总结", "Stakeholder Summary"),
  "system-foundation": text("系统基础层", "System Foundation"),
};

export const realDataMappingPageData: MeRealDataMappingPageData = {
  title: text("ME Real Data Mapping", "ME Real Data Mapping"),
  subtitle: text("Mock-to-real data preparation plan", "Mock-to-real data preparation plan"),
  uiBlocks: realDataUiBlocks,
  entities: realDataEntityMappings,
  apiBoundaries: realDataApiBoundaryDrafts,
  migrationSteps: realDataMigrationSteps,
  guardrails: realDataGuardrails,
  generatedAt: "2026-05-07T00:00:00.000Z",
};
