export type ReportLocale = "en" | "zh";

export const reportLanguageCopy = {
  en: {
    page: {
      eyebrow: "Reports Workspace",
      title: "Reporting and export readiness workspace",
      description:
        "Operational report shell with category tabs, widget catalog review, and layout previews.",
      notice:
        "Use this workspace to manage report catalogs, filter sets, layout templates, and export-readiness review.",
      serviceNoticePrefix: "Report service notice:",
    },
    badges: {
      reports: "Reports",
      reportCenter: "Report center",
      live: "Live",
      catalog: "Catalog",
    },
    actions: {
      openPosReports: "Open POS Reports",
      openWorkspace: "Open workspace",
      exportReview: "Export review",
      refreshPreview: "Refresh preview",
      viewLayout: "View layout",
      viewWidget: "View widget",
    },
    metrics: {
      totalWidgets: "Total widgets",
      activeWidgets: "Active widgets",
      placeholders: "Placeholders",
      exportable: "Exportable",
      refreshable: "Refreshable",
      drillDown: "Drill-down",
    },
    tabs: {
      reportOverview: "Report Overview",
      posReports: "POS Reports",
      salesAnalytics: "Sales Analytics",
      widgetCatalog: "Widget Catalog",
      dashboardLayouts: "Dashboard Layouts",
      computedMetrics: "Computed Metrics",
      psiPreview: "PSI Preview",
    },
    filters: {
      reportFilters: "Report Filters",
      widgetType: "Widget Type",
      sourceModule: "Source Module",
      status: "Status",
      severity: "Severity",
      all: "All",
      filterMode: "Filter mode",
      interactiveShell: "Interactive shell",
    },
    sections: {
      psiReportPreview: "PSI Report Preview",
      psiReportPreviewDescription: "PSI operational summary inside the shared reporting shell.",
      reportFilters: "Report Filters",
      reportFiltersDescription: "Operational filtering shell for the widget registry.",
      widgetCatalog: "Widget Catalog",
      widgetCatalogDescriptionSuffix: "widgets visible under the current filter set.",
      dashboardLayoutTemplates: "Dashboard Layout Templates",
      dashboardLayoutTemplatesDescription: "Reusable report layout references for future mapping.",
      computedMetrics: "Computed Metrics",
      computedMetricsDescription: "Operational metric framing for the current report workspace.",
      widgetMix: "Widget Mix",
      widgetMixDescription: "Current registry distribution.",
      selectedWidgetLayoutLinks: "Selected Widget Layout Links",
      selectedWidgetLayoutLinksDescription: "Layouts that currently reference the selected widget.",
      workspaceNote: "Workspace Note",
      workspaceNoteDescription:
        "The reports center aligns operational metrics, POS views, export readiness, and layout references in one reporting workspace.",
    },
    rightRail: {
      reportReadiness: "Report Readiness",
      reportCatalog: "Report catalog",
      operationalFilters: "Operational filters",
      exportReview: "Export review",
      scheduledDistributionSetup: "Scheduled distribution setup",
      currentFilter: "Current filter",
      currentStatus: "Current status",
      currentSeverity: "Current severity",
    },
    values: {
      overview: "Overview",
      psiReportWorkspace: "PSI report workspace",
      exportCenterWorkflow: "Export center remains part of the scheduled reporting workflow.",
      widgetRefreshVisualOnly: "Widget refresh is visual only and does not call an API.",
      of: "of",
    },
  },
  zh: {
    page: {
      eyebrow: "报表工作区",
      title: "报表与导出准备工作区",
      description: "用于分类标签、组件目录复核与版式预览的营运报表壳层。",
      notice: "使用此工作区管理报表目录、筛选集、版式模板与导出准备复核。",
      serviceNoticePrefix: "报表服务提示：",
    },
    badges: {
      reports: "报表",
      reportCenter: "报表中心",
      live: "实时",
      catalog: "目录",
    },
    actions: {
      openPosReports: "打开 POS 报表",
      openWorkspace: "打开工作区",
      exportReview: "导出复核",
      refreshPreview: "刷新预览",
      viewLayout: "查看版式",
      viewWidget: "查看组件",
    },
    metrics: {
      totalWidgets: "组件总数",
      activeWidgets: "启用组件",
      placeholders: "占位组件",
      exportable: "可导出",
      refreshable: "可刷新",
      drillDown: "可下钻",
    },
    tabs: {
      reportOverview: "报表概览",
      posReports: "POS 报表",
      salesAnalytics: "销售分析",
      widgetCatalog: "组件目录",
      dashboardLayouts: "看板版式",
      computedMetrics: "计算指标",
      psiPreview: "PSI 预览",
    },
    filters: {
      reportFilters: "报表筛选",
      widgetType: "组件类型",
      sourceModule: "来源模块",
      status: "状态",
      severity: "严重度",
      all: "全部",
      filterMode: "筛选模式",
      interactiveShell: "互动壳层",
    },
    sections: {
      psiReportPreview: "PSI 报表预览",
      psiReportPreviewDescription: "共享报表壳层中的 PSI 营运摘要。",
      reportFilters: "报表筛选",
      reportFiltersDescription: "用于组件注册表的营运筛选壳层。",
      widgetCatalog: "组件目录",
      widgetCatalogDescriptionSuffix: "个组件符合当前筛选条件。",
      dashboardLayoutTemplates: "看板版式模板",
      dashboardLayoutTemplatesDescription: "未来映射可复用的报表版式参考。",
      computedMetrics: "计算指标",
      computedMetricsDescription: "当前报表工作区的营运指标框架。",
      widgetMix: "组件分布",
      widgetMixDescription: "当前注册表分布。",
      selectedWidgetLayoutLinks: "所选组件版式链接",
      selectedWidgetLayoutLinksDescription: "当前引用所选组件的版式。",
      workspaceNote: "工作区说明",
      workspaceNoteDescription: "报表中心把营运指标、POS 视图、导出准备与版式参考集中在一个报表工作区。",
    },
    rightRail: {
      reportReadiness: "报表准备度",
      reportCatalog: "报表目录",
      operationalFilters: "营运筛选",
      exportReview: "导出复核",
      scheduledDistributionSetup: "定时报表分发设置",
      currentFilter: "当前筛选",
      currentStatus: "当前状态",
      currentSeverity: "当前严重度",
    },
    values: {
      overview: "概览",
      psiReportWorkspace: "PSI 报表工作区",
      exportCenterWorkflow: "导出中心仍属于定时报表流程的一部分。",
      widgetRefreshVisualOnly: "组件刷新仅为视觉预览，不会调用 API。",
      of: "/",
    },
  },
} as const;

export function getReportCopy(locale: ReportLocale) {
  return reportLanguageCopy[locale] ?? reportLanguageCopy.en;
}
