export interface RestaurantDataTableDefinition {
  key: string;
  label: { zh: string; en: string };
  moduleOwner: string;
  purpose: string;
  primaryDimensions: string[];
  exampleFields: string[];
  relatedTables: string[];
  futureSource: string;
  readinessStatus: "planning-only" | "future-real-data";
}

export const restaurantDataModel: RestaurantDataTableDefinition[] = [
  { key: "branches", label: { zh: "门店", en: "Branches" }, moduleOwner: "branches", purpose: "Store and branch master context for every operational workspace.", primaryDimensions: ["branch"], exampleFields: ["branch_id", "branch_code", "name", "region", "status"], relatedTables: ["staff", "schedules", "inventory_stock", "issues"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "staff", label: { zh: "员工", en: "Staff" }, moduleOwner: "staff", purpose: "People records used by staff, schedule, training, and task surfaces.", primaryDimensions: ["staff", "branch", "role"], exampleFields: ["staff_id", "name", "primary_branch_id", "employment_status", "role_key"], relatedTables: ["staff_roles", "staff_skills", "staff_availability", "training_records"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "staff_roles", label: { zh: "员工角色", en: "Staff Roles" }, moduleOwner: "roles", purpose: "Mapping between staff profiles, role contracts, and future permission scopes.", primaryDimensions: ["staff", "role"], exampleFields: ["staff_role_id", "staff_id", "role_key", "effective_from", "effective_to"], relatedTables: ["staff", "roles", "audit_events"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "staff_skills", label: { zh: "员工技能", en: "Staff Skills" }, moduleOwner: "training", purpose: "Skill matrix rows visible in staff and training workspaces.", primaryDimensions: ["staff", "skill"], exampleFields: ["staff_skill_id", "staff_id", "skill_key", "level", "verified_at"], relatedTables: ["staff", "training_records", "product_sops"], futureSource: "computed-view", readinessStatus: "planning-only" },
  { key: "staff_availability", label: { zh: "员工可用性", en: "Staff Availability" }, moduleOwner: "schedule", purpose: "Availability and off/unavailable rows for the schedule preview.", primaryDimensions: ["staff", "date", "branch"], exampleFields: ["availability_id", "staff_id", "date", "status", "note"], relatedTables: ["staff", "schedules", "shift_assignments"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "schedules", label: { zh: "排班", en: "Schedules" }, moduleOwner: "schedule", purpose: "Week-based roster plans by branch and operating window.", primaryDimensions: ["branch", "date", "shift"], exampleFields: ["schedule_id", "branch_id", "week_start", "coverage_status", "owner"], relatedTables: ["shift_assignments", "duty_stations", "staff_availability"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "shift_assignments", label: { zh: "班次分配", en: "Shift Assignments" }, moduleOwner: "schedule", purpose: "Individual shift rows bound to staff and duty stations.", primaryDimensions: ["staff", "shift", "branch", "date"], exampleFields: ["assignment_id", "schedule_id", "staff_id", "shift_start", "shift_end"], relatedTables: ["schedules", "staff", "duty_stations"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "duty_stations", label: { zh: "岗位站点", en: "Duty Stations" }, moduleOwner: "schedule", purpose: "Station coverage model for kitchen, service, receiving, and QA.", primaryDimensions: ["branch", "station", "shift"], exampleFields: ["station_id", "branch_id", "station_key", "shift_key", "required_headcount"], relatedTables: ["shift_assignments", "staff_skills"], futureSource: "computed-view", readinessStatus: "planning-only" },
  { key: "tasks", label: { zh: "任务", en: "Tasks" }, moduleOwner: "tasks", purpose: "Operational task queue with status, source linkage, and ownership.", primaryDimensions: ["branch", "task_status", "date"], exampleFields: ["task_id", "title", "source_module", "status", "priority"], relatedTables: ["task_links", "issues", "activity_events"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "task_links", label: { zh: "任务关联", en: "Task Links" }, moduleOwner: "tasks", purpose: "Links tasks to issues, procurement, inventory, inspections, and branches.", primaryDimensions: ["task", "linked_record"], exampleFields: ["task_link_id", "task_id", "record_type", "record_id", "link_status"], relatedTables: ["tasks", "issues", "procurement_requests", "inventory_items"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "training_courses", label: { zh: "培训课程", en: "Training Courses" }, moduleOwner: "training", purpose: "Course catalog metadata for role-based and SOP-linked training.", primaryDimensions: ["course", "role"], exampleFields: ["course_id", "title", "role_key", "category", "status"], relatedTables: ["training_records", "product_sops"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "training_records", label: { zh: "培训记录", en: "Training Records" }, moduleOwner: "training", purpose: "Staff progress, completion, and refresher records.", primaryDimensions: ["staff", "course", "branch"], exampleFields: ["record_id", "staff_id", "course_id", "progress_pct", "status"], relatedTables: ["training_courses", "staff", "staff_skills"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "inspections", label: { zh: "巡检", en: "Inspections" }, moduleOwner: "inspection", purpose: "Inspection and audit records used by branch and food-safety surfaces.", primaryDimensions: ["branch", "date", "inspection_type"], exampleFields: ["inspection_id", "branch_id", "inspection_type", "score", "status"], relatedTables: ["inspection_checklists", "inspection_findings", "issues"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "inspection_checklists", label: { zh: "巡检检查项", en: "Inspection Checklists" }, moduleOwner: "inspection", purpose: "Checklist line items and control points for inspection previews.", primaryDimensions: ["inspection", "check_item"], exampleFields: ["checklist_row_id", "inspection_id", "control_key", "result", "note"], relatedTables: ["inspections", "inspection_findings"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "inspection_findings", label: { zh: "巡检发现", en: "Inspection Findings" }, moduleOwner: "inspection", purpose: "Finding rows, severity, and suggested actions from inspections.", primaryDimensions: ["inspection", "issue_severity"], exampleFields: ["finding_id", "inspection_id", "severity", "finding_title", "suggested_action"], relatedTables: ["inspections", "issues", "tasks"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "issues", label: { zh: "问题", en: "Issues" }, moduleOwner: "issues", purpose: "Issue and incident records shared across modules.", primaryDimensions: ["branch", "issue_severity", "task_status"], exampleFields: ["issue_id", "title", "severity", "status", "source_module"], relatedTables: ["issue_links", "tasks", "activity_events"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "issue_links", label: { zh: "问题关联", en: "Issue Links" }, moduleOwner: "issues", purpose: "Links issues to labels, inspections, procurement, and stock records.", primaryDimensions: ["issue", "linked_record"], exampleFields: ["issue_link_id", "issue_id", "record_type", "record_id", "relationship"], relatedTables: ["issues", "inspection_findings", "expiry_labels", "procurement_requests"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "suppliers", label: { zh: "供应商", en: "Suppliers" }, moduleOwner: "supplier", purpose: "Supplier profile and readiness records.", primaryDimensions: ["supplier", "branch"], exampleFields: ["supplier_id", "name", "category", "status", "owner"], relatedTables: ["supplier_contacts", "procurement_requests", "finance_costs"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "supplier_contacts", label: { zh: "供应商联系人", en: "Supplier Contacts" }, moduleOwner: "supplier", purpose: "Supplier contact rows used by the supplier detail workspace.", primaryDimensions: ["supplier", "contact"], exampleFields: ["contact_id", "supplier_id", "name", "phone", "email"], relatedTables: ["suppliers"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "procurement_requests", label: { zh: "采购请求", en: "Procurement Requests" }, moduleOwner: "procurement", purpose: "Procurement request headers linked to branches, suppliers, and stock risks.", primaryDimensions: ["branch", "supplier", "date"], exampleFields: ["request_id", "branch_id", "supplier_id", "status", "requested_at"], relatedTables: ["procurement_request_items", "receiving_records", "inventory_stock"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "procurement_request_items", label: { zh: "采购请求明细", en: "Procurement Request Items" }, moduleOwner: "procurement", purpose: "Line items inside procurement requests.", primaryDimensions: ["procurement_request", "inventory_item"], exampleFields: ["request_item_id", "request_id", "inventory_item_id", "qty", "estimated_cost"], relatedTables: ["procurement_requests", "inventory_items"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "receiving_records", label: { zh: "收货记录", en: "Receiving Records" }, moduleOwner: "procurement", purpose: "Receiving checkpoints and inbound confirmations linked to procurement.", primaryDimensions: ["branch", "supplier", "date"], exampleFields: ["receiving_id", "request_id", "branch_id", "received_at", "status"], relatedTables: ["procurement_requests", "stock_movements"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "inventory_items", label: { zh: "库存品项", en: "Inventory Items" }, moduleOwner: "inventory", purpose: "Inventory item master used by stock, procurement, expiry, and SOP surfaces.", primaryDimensions: ["inventory_item", "product"], exampleFields: ["inventory_item_id", "sku", "name", "storage_type", "status"], relatedTables: ["inventory_stock", "stock_movements", "expiry_labels"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "inventory_stock", label: { zh: "库存余额", en: "Inventory Stock" }, moduleOwner: "inventory", purpose: "Per-branch stock balance and coverage context.", primaryDimensions: ["branch", "inventory_item", "date"], exampleFields: ["stock_id", "branch_id", "inventory_item_id", "on_hand_qty", "min_qty"], relatedTables: ["inventory_items", "stock_movements", "procurement_requests"], futureSource: "computed-view", readinessStatus: "planning-only" },
  { key: "stock_movements", label: { zh: "库存流水", en: "Stock Movements" }, moduleOwner: "inventory", purpose: "Movement history for receiving, issues, transfers, and adjustments.", primaryDimensions: ["branch", "inventory_item", "date"], exampleFields: ["movement_id", "inventory_item_id", "branch_id", "movement_type", "qty"], relatedTables: ["inventory_stock", "receiving_records", "stock_transfer", "stock_waste"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "stock_transfer", label: { zh: "库存调拨", en: "Stock Transfer" }, moduleOwner: "inventory", purpose: "Transfer headers between branches or storage locations.", primaryDimensions: ["branch", "inventory_item", "date"], exampleFields: ["transfer_id", "source_branch_id", "target_branch_id", "inventory_item_id", "status"], relatedTables: ["stock_movements", "inventory_stock"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "stock_waste", label: { zh: "库存报废", en: "Stock Waste" }, moduleOwner: "inventory", purpose: "Waste and loss records for cost, audit, and expiry review.", primaryDimensions: ["branch", "inventory_item", "date"], exampleFields: ["waste_id", "branch_id", "inventory_item_id", "qty", "reason"], relatedTables: ["stock_movements", "finance_costs", "audit_events"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "product_sops", label: { zh: "产品 SOP", en: "Product SOPs" }, moduleOwner: "sop", purpose: "Product-level SOP and recipe records.", primaryDimensions: ["product", "version"], exampleFields: ["sop_id", "product_key", "version", "status", "owner"], relatedTables: ["recipes", "product_standards", "training_courses"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "recipes", label: { zh: "配方", en: "Recipes" }, moduleOwner: "sop", purpose: "Recipe headers for standard products and menu items.", primaryDimensions: ["product", "version"], exampleFields: ["recipe_id", "product_key", "yield_qty", "status", "version"], relatedTables: ["recipe_ingredients", "product_sops", "finance_costs"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "recipe_ingredients", label: { zh: "配方原料", en: "Recipe Ingredients" }, moduleOwner: "sop", purpose: "Ingredient rows within recipes.", primaryDimensions: ["recipe", "inventory_item"], exampleFields: ["recipe_ingredient_id", "recipe_id", "inventory_item_id", "qty", "unit"], relatedTables: ["recipes", "inventory_items", "finance_costs"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "product_standards", label: { zh: "产品标准", en: "Product Standards" }, moduleOwner: "sop", purpose: "Operational standards for product quality and branch applicability.", primaryDimensions: ["product", "branch"], exampleFields: ["standard_id", "product_key", "branch_scope", "qc_target", "status"], relatedTables: ["product_sops", "recipes"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "expiry_labels", label: { zh: "保质期标签", en: "Expiry Labels" }, moduleOwner: "expiry", purpose: "Expiry label rows tied to stock and storage areas.", primaryDimensions: ["branch", "inventory_item", "date"], exampleFields: ["label_id", "branch_id", "inventory_item_id", "expiry_date", "status"], relatedTables: ["inventory_items", "label_logs", "issues"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "label_logs", label: { zh: "标签日志", en: "Label Logs" }, moduleOwner: "expiry", purpose: "Print/log activity and visibility state for label operations.", primaryDimensions: ["branch", "date", "inventory_item"], exampleFields: ["label_log_id", "label_id", "printed_at", "storage_zone", "status"], relatedTables: ["expiry_labels", "issues"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "pos_sales_daily", label: { zh: "POS 日销售", en: "POS Sales Daily" }, moduleOwner: "reports", purpose: "Daily branch-level sales snapshots for report and finance previews.", primaryDimensions: ["branch", "date", "report_period"], exampleFields: ["sales_daily_id", "branch_id", "sales_date", "gross_sales", "transaction_count"], relatedTables: ["pos_sales_items", "report_snapshots", "margin_snapshots"], futureSource: "api-endpoint", readinessStatus: "planning-only" },
  { key: "pos_sales_items", label: { zh: "POS 单品销售", en: "POS Sales Items" }, moduleOwner: "reports", purpose: "Item-level sales facts for item performance and margin review.", primaryDimensions: ["branch", "date", "product"], exampleFields: ["sales_item_id", "sales_daily_id", "product_key", "qty_sold", "gross_sales"], relatedTables: ["pos_sales_daily", "margin_snapshots"], futureSource: "api-endpoint", readinessStatus: "planning-only" },
  { key: "report_snapshots", label: { zh: "报表快照", en: "Report Snapshots" }, moduleOwner: "reports", purpose: "Rendered metric snapshots for dashboards and export placeholders.", primaryDimensions: ["report_period", "branch"], exampleFields: ["snapshot_id", "report_key", "period_key", "branch_scope", "generated_at"], relatedTables: ["pos_sales_daily", "margin_snapshots", "audit_events"], futureSource: "computed-view", readinessStatus: "planning-only" },
  { key: "finance_costs", label: { zh: "财务成本", en: "Finance Costs" }, moduleOwner: "finance", purpose: "Input cost and supplier cost comparison rows.", primaryDimensions: ["product", "supplier", "date"], exampleFields: ["finance_cost_id", "product_key", "supplier_id", "unit_cost", "effective_date"], relatedTables: ["suppliers", "recipes", "margin_snapshots"], futureSource: "computed-view", readinessStatus: "planning-only" },
  { key: "margin_snapshots", label: { zh: "毛利快照", en: "Margin Snapshots" }, moduleOwner: "finance", purpose: "Preview-only margin outputs by product and branch.", primaryDimensions: ["branch", "product", "report_period"], exampleFields: ["margin_snapshot_id", "product_key", "branch_id", "margin_pct", "status"], relatedTables: ["finance_costs", "pos_sales_daily", "report_snapshots"], futureSource: "computed-view", readinessStatus: "planning-only" },
  { key: "audit_events", label: { zh: "审计事件", en: "Audit Events" }, moduleOwner: "system", purpose: "Audit rows for route visibility, linked records, and future administrative review.", primaryDimensions: ["date", "branch", "staff"], exampleFields: ["audit_event_id", "event_type", "actor_key", "record_type", "occurred_at"], relatedTables: ["attachments", "issues", "tasks"], futureSource: "database-table", readinessStatus: "planning-only" },
  { key: "attachments", label: { zh: "附件", en: "Attachments" }, moduleOwner: "system", purpose: "Document, image, and file references linked to operational records.", primaryDimensions: ["record", "date"], exampleFields: ["attachment_id", "record_type", "record_id", "file_name", "status"], relatedTables: ["audit_events", "issues", "procurement_requests", "inspections"], futureSource: "file-import", readinessStatus: "planning-only" },
];
