export interface RestaurantFormulaDefinition {
  key: string;
  label: { zh: string; en: string };
  module: string;
  description: string;
  inputFields: string[];
  outputField: string;
  calculationNotes: string;
  executionStatus: "planning-only";
  futureEngine: "formula-layer" | "rules-engine" | "report-computation";
}

export const restaurantFormulas: RestaurantFormulaDefinition[] = [
  { key: "stock-risk-score", label: { zh: "库存风险分", en: "Stock Risk Score" }, module: "inventory", description: "Ranks low-stock risk for branch inventory previews.", inputFields: ["on_hand_qty", "min_qty", "coverage_days", "open_procurement_qty"], outputField: "stock_risk_score", calculationNotes: "Planned weighted score combining stock balance, days coverage, and inbound coverage.", executionStatus: "planning-only", futureEngine: "formula-layer" },
  { key: "expiry-days-remaining", label: { zh: "剩余保质天数", en: "Expiry Days Remaining" }, module: "expiry", description: "Converts expiry dates into watch windows for food-safety surfaces.", inputFields: ["expiry_date", "current_date"], outputField: "days_remaining", calculationNotes: "Simple date-diff planned for expiry watchlist grouping.", executionStatus: "planning-only", futureEngine: "formula-layer" },
  { key: "reorder-suggestion", label: { zh: "补货建议", en: "Reorder Suggestion" }, module: "procurement", description: "Suggests replenishment quantity from stock coverage and sales trend inputs.", inputFields: ["forecast_qty", "on_hand_qty", "min_qty", "lead_time_days"], outputField: "reorder_qty_suggestion", calculationNotes: "Planning-only replenishment formula; not executed in UI.", executionStatus: "planning-only", futureEngine: "formula-layer" },
  { key: "schedule-coverage-gap", label: { zh: "排班覆盖缺口", en: "Schedule Coverage Gap" }, module: "schedule", description: "Measures coverage gaps across duty stations and shifts.", inputFields: ["required_headcount", "assigned_headcount", "shift_key", "branch_id"], outputField: "coverage_gap", calculationNotes: "Future roster coverage formula used by schedule and staff previews.", executionStatus: "planning-only", futureEngine: "formula-layer" },
  { key: "training-completion-rate", label: { zh: "培训完成率", en: "Training Completion Rate" }, module: "training", description: "Calculates completion ratio for a course, branch, or role family.", inputFields: ["completed_records", "assigned_records"], outputField: "completion_rate", calculationNotes: "Simple progress ratio with branch/role slicing.", executionStatus: "planning-only", futureEngine: "formula-layer" },
  { key: "branch-inspection-score", label: { zh: "门店巡检分", en: "Branch Inspection Score" }, module: "inspection", description: "Aggregates inspection checklist results into a branch audit score.", inputFields: ["checklist_results", "finding_severity_weights"], outputField: "inspection_score", calculationNotes: "Weighted score future-planned for branch audit reporting.", executionStatus: "planning-only", futureEngine: "report-computation" },
  { key: "task-overdue-status", label: { zh: "任务逾期状态", en: "Task Overdue Status" }, module: "tasks", description: "Determines overdue state from due date and current status.", inputFields: ["due_at", "current_status", "current_date"], outputField: "overdue_flag", calculationNotes: "Boolean or grouped status planned for queue rendering.", executionStatus: "planning-only", futureEngine: "rules-engine" },
  { key: "product-cost-estimate", label: { zh: "产品成本估算", en: "Product Cost Estimate" }, module: "finance", description: "Estimates product input cost from recipe ingredients and supplier costs.", inputFields: ["recipe_ingredients", "unit_costs", "yield_qty"], outputField: "product_cost_estimate", calculationNotes: "Formula layer future source for finance preview and SOP-linked costing.", executionStatus: "planning-only", futureEngine: "formula-layer" },
  { key: "gross-margin-preview", label: { zh: "毛利预览", en: "Gross Margin Preview" }, module: "finance", description: "Computes margin preview from cost estimate and sell price.", inputFields: ["sell_price", "product_cost_estimate"], outputField: "gross_margin_pct_preview", calculationNotes: "Finance preview metric only, not final accounting output.", executionStatus: "planning-only", futureEngine: "report-computation" },
  { key: "sales-variance", label: { zh: "销售波动", en: "Sales Variance" }, module: "reports", description: "Compares branch sales against prior or target baseline.", inputFields: ["gross_sales", "baseline_sales"], outputField: "sales_variance_pct", calculationNotes: "Future report-computation metric for POS reports and branch performance.", executionStatus: "planning-only", futureEngine: "report-computation" },
  { key: "waste-rate", label: { zh: "报废率", en: "Waste Rate" }, module: "finance", description: "Measures waste against usage or sales base for operational review.", inputFields: ["waste_qty", "consumed_qty"], outputField: "waste_rate_pct", calculationNotes: "Future finance and food-safety metric.", executionStatus: "planning-only", futureEngine: "formula-layer" },
  { key: "labor-coverage-ratio", label: { zh: "人力覆盖比", en: "Labor Coverage Ratio" }, module: "schedule", description: "Compares assigned labor against required labor by shift.", inputFields: ["assigned_hours", "required_hours"], outputField: "labor_coverage_ratio", calculationNotes: "Future roster planning metric for schedule and branch review.", executionStatus: "planning-only", futureEngine: "report-computation" },
];
