import type { MeRoleProfile } from "@/types/role-workspace";

const previewOnlyNote = "Role preview metadata only. No real auth, session, permission enforcement, or route guard is connected.";

export const meRoleProfiles: MeRoleProfile[] = [
  {
    key: "owner",
    name: { zh: "经营者", en: "Owner" },
    description: {
      zh: "查看业务健康、收入占位、风险与决策摘要的管理角色。",
      en: "Leadership preview focused on business health, revenue placeholders, risk, and decision context.",
    },
    primaryGoal: { zh: "把握经营健康并做出关键决策", en: "Monitor business health and make key decisions" },
    tone: "success",
    status: "preview-only",
    defaultRoute: "/",
    suggestedModules: ["dashboard", "reports", "psi-workspace", "packages", "system-foundation"],
    visibleNavigationItemKeys: ["dashboard", "psi-workspace", "reports", "packages", "system-foundation"],
    foundationAccessLevel: "limited-preview",
    notes: previewOnlyNote,
  },
  {
    key: "store-manager",
    name: { zh: "门店经理", en: "Store Manager" },
    description: {
      zh: "面向日常运营、任务完成和问题跟进的门店管理视角。",
      en: "Daily operations view focused on task completion, execution follow-up, and issue handling.",
    },
    primaryGoal: { zh: "稳定门店执行并处理异常", en: "Keep daily store operations on track" },
    tone: "info",
    status: "preview-only",
    defaultRoute: "/",
    suggestedModules: ["dashboard", "psi-workspace", "tasks", "reports", "psi-issues"],
    visibleNavigationItemKeys: ["dashboard", "psi-workspace", "tasks", "reports", "psi-issues"],
    foundationAccessLevel: "hidden-preview",
    notes: previewOnlyNote,
  },
  {
    key: "purchasing",
    name: { zh: "采购", en: "Purchasing" },
    description: {
      zh: "围绕采购请求、供应商协同与收货占位的采购工作视角。",
      en: "Procurement workspace preview for purchase requests, supplier coordination, and receiving placeholders.",
    },
    primaryGoal: { zh: "推动采购与收货协同", en: "Coordinate purchase requests, suppliers, and receiving" },
    tone: "warning",
    status: "preview-only",
    defaultRoute: "/psi/procurement",
    suggestedModules: ["procurement", "supplier", "psi-actions", "reports"],
    visibleNavigationItemKeys: ["psi-workspace", "procurement", "supplier", "psi-actions", "reports"],
    foundationAccessLevel: "hidden-preview",
    notes: previewOnlyNote,
  },
  {
    key: "warehouse",
    name: { zh: "仓库", en: "Warehouse" },
    description: {
      zh: "关注库存、移动占位、补货与收货状态的仓储工作视角。",
      en: "Warehouse view centered on stock visibility, movement placeholders, replenishment, and receiving.",
    },
    primaryGoal: { zh: "控制库存风险并支持补货", en: "Manage stock risk and support replenishment" },
    tone: "warning",
    status: "preview-only",
    defaultRoute: "/psi/inventory",
    suggestedModules: ["inventory", "psi-issues", "psi-actions", "reports"],
    visibleNavigationItemKeys: ["psi-workspace", "inventory", "psi-issues", "reports"],
    foundationAccessLevel: "hidden-preview",
    notes: previewOnlyNote,
  },
  {
    key: "staff",
    name: { zh: "员工", en: "Staff" },
    description: {
      zh: "聚焦被分配任务、培训占位与有限问题上报入口的一线员工视角。",
      en: "Frontline preview focused on assigned work, training placeholders, and limited issue reporting.",
    },
    primaryGoal: { zh: "完成分配工作并跟进培训", en: "Complete assigned work and follow training guidance" },
    tone: "neutral",
    status: "preview-only",
    defaultRoute: "/tasks",
    suggestedModules: ["dashboard", "tasks", "education", "psi-issues"],
    visibleNavigationItemKeys: ["dashboard", "tasks", "education", "psi-issues"],
    foundationAccessLevel: "limited-preview",
    notes: previewOnlyNote,
  },
  {
    key: "system-admin",
    name: { zh: "系统管理员", en: "System Admin" },
    description: {
      zh: "面向平台配置、元数据治理与系统基础能力的管理角色。",
      en: "Platform setup preview for metadata management, governance, and system foundation oversight.",
    },
    primaryGoal: { zh: "维护平台基础配置与治理视图", en: "Oversee platform setup, metadata, and governance" },
    tone: "muted",
    status: "preview-only",
    defaultRoute: "/system-foundation",
    suggestedModules: ["system-foundation", "navigation-ia", "access-control", "audit-trail", "workflow"],
    visibleNavigationItemKeys: ["system-foundation", "navigation-ia", "access-control", "audit-trail", "workflow"],
    foundationAccessLevel: "full-preview",
    notes: previewOnlyNote,
  },
];
