export type TaskLocale = "en" | "zh";

export const taskLanguageCopy = {
  en: {
    page: {
      eyebrow: "Task Management",
      title: "Task operations workspace",
      description:
        "Daily execution queue for branch follow-up, issue handling, procurement coordination, and cross-module work orders.",
      notice:
        "Use this workspace to review assigned work, branch-linked tasks, comments, and operating timelines.",
      serviceNoticePrefix: "Task service notice:",
      emptyTitle: "Task record not available",
      emptyDescription: "The selected task could not be loaded into the current workspace.",
      emptyNotice: "Return to the task queue to continue reviewing operational work orders.",
    },
    badges: {
      taskQueue: "Task queue",
      branchFollowUp: "Branch follow-up",
      operationalReview: "Operational review",
      recordCheck: "Record check",
    },
    actions: {
      reviewQueue: "Review Queue",
      openBranches: "Open Branches",
      openInspection: "Open Inspection",
      openPsi: "Open PSI",
      exportQueue: "Export Queue",
      complete: "Complete",
      reassign: "Reassign",
      addComment: "Add Comment",
      escalate: "Escalate",
      backToQueue: "Back to Queue",
      openWorkspace: "Open workspace",
    },
    kpis: {
      openTasks: "Open tasks",
      inProgress: "In progress",
      waitingReview: "Waiting review",
      overdue: "Overdue",
      critical: "Critical",
    },
    tabs: {
      overview: "Overview",
      queue: "Queue",
      comments: "Comments",
      activity: "Activity",
      attachments: "Attachments",
      relatedRecords: "Related Records",
      evidence: "Evidence",
      audit: "Audit",
    },
    fields: {
      queueSize: "Queue size",
      branchScope: "Branch scope",
      priorityWatch: "Priority watch",
      workstream: "Workstream",
      task: "Task",
      taskId: "Task ID",
      title: "Title",
      taskTitle: "Task title",
      branch: "Branch",
      owner: "Owner",
      priority: "Priority",
      status: "Status",
      module: "Module",
      due: "Due",
      updated: "Updated",
      created: "Created",
      taskType: "Task type",
      sourceRecord: "Source record",
      sourceModule: "Source module",
      assignedTo: "Assigned to",
      currentBranch: "Current branch",
      currentStatus: "Current status",
      dueDate: "Due date",
      record: "Record",
      description: "Description",
      route: "Route",
      evidence: "Evidence",
      type: "Type",
      detail: "Detail",
      label: "Label",
      businessSummary: "Business Summary",
      taskNote: "Task Note",
      currentServiceScope: "Current service scope",
    },
    sections: {
      workQueue: "Work Queue",
      workQueueDescription:
        "Prioritized task records linked to branch operations, procurement, inventory, and incident handling.",
      selectedTask: "Selected Task",
      selectedTaskDescription:
        "Primary work order detail, assignment context, and linked business records.",
      taskOverview: "Task Overview",
      taskOverviewDescription:
        "Assignment context, branch impact, and linked operational summary for the selected work order.",
      relatedRecords: "Related Records",
      relatedRecordsDescription:
        "Business records referenced by this task across inventory, procurement, supplier, and reporting workspaces.",
      evidenceAndNotes: "Evidence and Notes",
      evidenceAndNotesDescription:
        "Supporting notes, documents, and operational evidence referenced during task follow-up.",
      activity: "Activity",
    },
    rightRail: {
      taskContext: "Task Context",
      operations: "Operations",
      branchFollowUp: "Branch follow-up",
      issueCoordination: "Issue coordination",
      inventoryProcurementLinkage: "Inventory and procurement linkage",
      currentFocus: "Current Focus",
      recordsWaitingForReview: "records waiting for review",
      overdueItems: "overdue items",
      criticalPriorityTasks: "critical-priority tasks",
      todaysPriorities: "Today’s Priorities",
      replenishmentReview: "Replenishment review",
      deliveryDelayEscalation: "Delivery-delay escalation",
      scheduleTrainingFollowUp: "Schedule and training follow-up",
      taskStatus: "Task Status",
      followUp: "Follow-up",
      commentTrail: "Comment trail",
      escalationReview: "Escalation review",
      relatedRecordCoordination: "Related record coordination",
      relatedModules: "Related Modules",
    },
    values: {
      allStoresScope: "All Stores / KCH / Central DC",
      dailyOperations: "Daily operations",
    },
  },
  zh: {
    page: {
      eyebrow: "任务管理",
      title: "任务营运工作区",
      description: "用于门店跟进、问题处理、采购协同与跨模块工单的每日执行队列。",
      notice: "使用此工作区复核已分派任务、门店关联任务、留言与营运时间线。",
      serviceNoticePrefix: "任务服务提示：",
      emptyTitle: "任务记录不可用",
      emptyDescription: "所选任务无法载入当前工作区。",
      emptyNotice: "返回任务队列继续复核营运工单。",
    },
    badges: {
      taskQueue: "任务队列",
      branchFollowUp: "门店跟进",
      operationalReview: "营运复核",
      recordCheck: "记录检查",
    },
    actions: {
      reviewQueue: "复核队列",
      openBranches: "打开门店",
      openInspection: "打开巡检",
      openPsi: "打开 PSI",
      exportQueue: "导出队列",
      complete: "完成",
      reassign: "重新分派",
      addComment: "添加备注",
      escalate: "升级处理",
      backToQueue: "返回队列",
      openWorkspace: "打开工作区",
    },
    kpis: {
      openTasks: "待办任务",
      inProgress: "处理中",
      waitingReview: "等待复核",
      overdue: "已逾期",
      critical: "紧急",
    },
    tabs: {
      overview: "概览",
      queue: "队列",
      comments: "留言",
      activity: "动态",
      attachments: "附件",
      relatedRecords: "关联记录",
      evidence: "证据",
      audit: "审计",
    },
    fields: {
      queueSize: "队列数量",
      branchScope: "门店范围",
      priorityWatch: "优先级关注",
      workstream: "工作流",
      task: "任务",
      taskId: "任务编号",
      title: "标题",
      taskTitle: "任务标题",
      branch: "门店",
      owner: "负责人",
      priority: "优先级",
      status: "状态",
      module: "模块",
      due: "截止",
      updated: "更新",
      created: "创建",
      taskType: "任务类型",
      sourceRecord: "来源记录",
      sourceModule: "来源模块",
      assignedTo: "分派给",
      currentBranch: "当前门店",
      currentStatus: "当前状态",
      dueDate: "截止日期",
      record: "记录",
      description: "说明",
      route: "入口",
      evidence: "证据",
      type: "类型",
      detail: "详情",
      label: "标签",
      businessSummary: "业务摘要",
      taskNote: "任务备注",
      currentServiceScope: "当前服务范围",
    },
    sections: {
      workQueue: "任务队列",
      workQueueDescription: "按优先级排列，并关联门店营运、采购、库存与问题处理的任务记录。",
      selectedTask: "当前任务",
      selectedTaskDescription: "主要工单详情、分派上下文与关联业务记录。",
      taskOverview: "任务概览",
      taskOverviewDescription: "所选工单的分派背景、门店影响与关联营运摘要。",
      relatedRecords: "关联记录",
      relatedRecordsDescription: "此任务引用的库存、采购、供应商与报表工作区业务记录。",
      evidenceAndNotes: "证据与备注",
      evidenceAndNotesDescription: "任务跟进过程中引用的备注、文件与营运证据。",
      activity: "动态",
    },
    rightRail: {
      taskContext: "任务上下文",
      operations: "营运",
      branchFollowUp: "门店跟进",
      issueCoordination: "问题协同",
      inventoryProcurementLinkage: "库存与采购关联",
      currentFocus: "当前重点",
      recordsWaitingForReview: "条记录等待复核",
      overdueItems: "项已逾期",
      criticalPriorityTasks: "项紧急任务",
      todaysPriorities: "今日优先事项",
      replenishmentReview: "补货复核",
      deliveryDelayEscalation: "延迟到货升级",
      scheduleTrainingFollowUp: "排班与培训跟进",
      taskStatus: "任务状态",
      followUp: "跟进",
      commentTrail: "留言记录",
      escalationReview: "升级复核",
      relatedRecordCoordination: "关联记录协同",
      relatedModules: "关联模块",
    },
    values: {
      allStoresScope: "全部门店 / KCH / Central DC",
      dailyOperations: "日常营运",
    },
  },
} as const;

export function getTaskCopy(locale: TaskLocale) {
  return taskLanguageCopy[locale] ?? taskLanguageCopy.en;
}
