import type { StoreOperationModule } from "@/types/store-operations";

export const storeOperationModules: StoreOperationModule[] = [
  {
    id: "branch-control",
    label: "Branch Control",
    shortLabel: "Branches",
    route: "/branches",
    description: "Branch master data, setup readiness, and daily outlet control.",
    primaryActionLabel: "Register Branch",
    searchPlaceholder: "Search branch, region, or setup status",
    filters: ["Active", "Setup Required", "Attention", "Suspended"],
    kpis: [
      { key: "totalBranches", label: "Total Branches", calculatorKey: "calculateBranchHealthScore" },
      { key: "openToday", label: "Open Today" },
      { key: "needAttention", label: "Need Attention" },
      { key: "missingSetup", label: "Missing Setup" },
      { key: "pendingBranchTasks", label: "Pending Branch Tasks" },
      { key: "todaySalesSignal", label: "Today Sales Signal" },
    ],
    recordLabel: "Branch",
    emptyStateTitle: "No Branches Registered",
    emptyStateDescription: "Register branches first so daily execution, inspection, and incident workflows have an outlet target.",
    detailTitle: "Branch Control Detail",
    statusFlow: ["Draft", "Setup Required", "Active", "Attention", "Suspended", "Closed"],
    masterDataDependencies: ["company", "region", "branch", "operatingHours", "role", "user"],
    linkedModules: ["outlet-execution", "store-inspection", "incident-center"],
  },
  {
    id: "outlet-execution",
    label: "Outlet Execution",
    shortLabel: "Execution",
    route: "/tasks",
    description: "Daily outlet work assignment, proof collection, and completion review.",
    primaryActionLabel: "Schedule Outlet Execution",
    searchPlaceholder: "Search task, outlet, trigger, or due date",
    filters: ["Due Today", "Overdue", "Pending Proof", "Pending Review", "Completed"],
    kpis: [
      { key: "dueToday", label: "Due Today", calculatorKey: "calculateTaskCompletionRate" },
      { key: "overdue", label: "Overdue" },
      { key: "photoProofPending", label: "Photo Proof Pending" },
      { key: "pendingReview", label: "Pending Review" },
      { key: "completed", label: "Completed" },
      { key: "branchCompletionRate", label: "Branch Completion Rate" },
    ],
    recordLabel: "Execution Task",
    emptyStateTitle: "No Outlet Execution Tasks",
    emptyStateDescription: "Create a scheduled execution task and assign target outlets with proof requirements.",
    detailTitle: "Outlet Execution Detail",
    statusFlow: ["Scheduled", "Due Today", "Submitted", "Pending Review", "Completed", "Overdue", "Escalated"],
    masterDataDependencies: ["branch", "taskType", "repeatRule", "completionStandard", "proofType", "shiftType"],
    linkedModules: ["store-inspection", "incident-center", "fefo-waste-control"],
  },
  {
    id: "store-inspection",
    label: "Store Inspection",
    shortLabel: "Inspection",
    route: "/inspection",
    description: "Checklist inspection, score review, failed item handling, and re-check workflow.",
    primaryActionLabel: "Schedule Inspection",
    searchPlaceholder: "Search inspection, checklist, branch, or failed item",
    filters: ["Scheduled", "In Progress", "Failed Items", "Pending Review", "Completed"],
    kpis: [
      { key: "scheduledToday", label: "Scheduled Today", calculatorKey: "calculateInspectionAverageScore" },
      { key: "completed", label: "Completed" },
      { key: "failedItems", label: "Failed Items" },
      { key: "averageScore", label: "Average Score" },
      { key: "pendingReview", label: "Pending Review" },
      { key: "autoIssuesCreated", label: "Auto Issues Created" },
    ],
    recordLabel: "Inspection",
    emptyStateTitle: "No Inspections Scheduled",
    emptyStateDescription: "Create inspections from checklist templates or run a temporary branch spot check.",
    detailTitle: "Inspection Review Detail",
    statusFlow: ["Scheduled", "In Progress", "Failed Items", "Pending Review", "Completed", "Issue Created"],
    masterDataDependencies: ["checklistTemplate", "checklistItem", "scoringRule", "failureRule", "photoRequirement"],
    linkedModules: ["outlet-execution", "incident-center", "sop-training"],
  },
  {
    id: "incident-center",
    label: "Incident Center",
    shortLabel: "Incidents",
    route: "/issues",
    description: "Containment, escalation, corrective action, and SLA review for store incidents.",
    primaryActionLabel: "Report Incident",
    searchPlaceholder: "Search incident, severity, branch, or SLA status",
    filters: ["Open", "Critical", "Overdue", "Contained", "Pending Review", "Resolved"],
    kpis: [
      { key: "openIssues", label: "Open Issues", calculatorKey: "calculateIncidentSlaStatus" },
      { key: "critical", label: "Critical" },
      { key: "overdue", label: "Overdue" },
      { key: "contained", label: "Contained" },
      { key: "pendingReview", label: "Pending Review" },
      { key: "resolvedToday", label: "Resolved Today" },
    ],
    recordLabel: "Incident",
    emptyStateTitle: "No Open Incidents",
    emptyStateDescription: "Incidents are created from branch reports or failed inspections and then escalated to corrective action.",
    detailTitle: "Incident Handling Detail",
    statusFlow: ["New", "Contained", "Assigned", "In Progress", "Pending Review", "Resolved", "Reopened"],
    masterDataDependencies: ["issueCategory", "severity", "impactArea", "escalationRule", "slaRule", "rootCauseType"],
    linkedModules: ["outlet-execution", "store-inspection", "branch-control"],
  },
  {
    id: "fefo-waste-control",
    label: "FEFO / Waste Control",
    shortLabel: "FEFO",
    route: "/expiry",
    description: "Batch ageing, FEFO action, disposal tracking, and waste cost control.",
    primaryActionLabel: "Register Batch",
    searchPlaceholder: "Search batch, product, storage, or expiry state",
    filters: ["Expiring Today", "Expiring 3 Days", "Use First", "Expired", "Disposed"],
    kpis: [
      { key: "expiringToday", label: "Expiring Today", calculatorKey: "calculateExpiryRiskScore" },
      { key: "expiringThreeDays", label: "Expiring 3 Days" },
      { key: "useFirst", label: "Use First" },
      { key: "expired", label: "Expired" },
      { key: "disposedQty", label: "Disposed Qty" },
      { key: "wasteCost", label: "Waste Cost", calculatorKey: "calculateWasteCost" },
    ],
    recordLabel: "Batch",
    emptyStateTitle: "No FEFO Batches Registered",
    emptyStateDescription: "Register outlet batches so the system can identify use-first, expiry, and disposal actions.",
    detailTitle: "FEFO Control Detail",
    statusFlow: ["Fresh", "Expiring Soon", "Use First", "Hold", "Expired", "Disposed"],
    masterDataDependencies: ["product", "storageLocation", "shelfLifeRule", "fefoRule", "wasteReason", "supplier", "batchLot"],
    linkedModules: ["outlet-execution", "incident-center", "branch-control"],
  },
  {
    id: "sop-training",
    label: "SOP & Training",
    shortLabel: "SOP",
    route: "/sop",
    description: "Controlled SOP documents, training acknowledgement, and checklist linkage.",
    primaryActionLabel: "Create Controlled SOP",
    searchPlaceholder: "Search SOP, version, training status, or review cycle",
    filters: ["Effective", "Need Review", "Draft / Review", "Training Pending", "Acknowledged"],
    kpis: [
      { key: "effectiveSops", label: "Effective SOPs", calculatorKey: "calculateSopTrainingCompletion" },
      { key: "needReview", label: "Need Review" },
      { key: "draftReview", label: "Draft / Review" },
      { key: "trainingPending", label: "Training Pending" },
      { key: "acknowledged", label: "Acknowledged" },
      { key: "checklistLinked", label: "Checklist Linked" },
    ],
    recordLabel: "SOP Document",
    emptyStateTitle: "No Controlled SOPs",
    emptyStateDescription: "Create a controlled SOP, define approval flow, and link training or checklist usage.",
    detailTitle: "SOP Governance Detail",
    statusFlow: ["Draft", "Review", "Approved", "Effective", "Need Review", "Superseded", "Obsolete"],
    masterDataDependencies: ["sopCategory", "processArea", "documentCode", "approvalFlow", "trainingRule", "reviewCycle"],
    linkedModules: ["store-inspection", "outlet-execution", "branch-control"],
  },
];

export function getStoreOperationModuleByRoute(route: string) {
  return storeOperationModules.find((module) => module.route === route);
}

export function getStoreOperationModuleByLegacyKey(key: string) {
  const map: Record<string, StoreOperationModule["id"]> = {
    branches: "branch-control",
    tasks: "outlet-execution",
    inspection: "store-inspection",
    issues: "incident-center",
    expiry: "fefo-waste-control",
    sop: "sop-training",
  };
  const id = map[key];
  return storeOperationModules.find((module) => module.id === id);
}
